// Thin platform seam for the standalone font capability exports of
// `@tiqian/ffi` (ADR 0053 cutover, stage 1 JS seats).
//
// The engine logic itself lives in the Haxe module org.tiqian.font and arrives
// through the generated tree under ../engine-gen (copied from
// engine-haxe/out/ts/gen, generated by the engine `ts` bundle). This adapter
// owns only the wire seam that used to live in
// `ffi/js/src/jsMain/kotlin/org/tiqian/ffi/js/FontExports.kt` plus the JSON
// decode helpers of `WireJson.kt` (parseFontMetricsRequestJson /
// parseFontRequestJson): requests enter as JSON strings, responses leave as
// JSON strings, and the emission order of every field matches the Kotlin
// builder byte for byte on the f64 reading (TCN-45: the Kotlin/JS values were
// f32-grid artifacts, the numbers here are the exact f64 results of the same
// formulas).
//
// Note kept for the protocol single-sourcing lane: the FontMetricsRequest /
// FontRequest JSON parsing below is still a hand-written shell. The request
// models have not joined a protocol bundle yet; when they do, this shell is
// replaced by the generated wire model.

import { TextRange } from "../engine-gen/org/tiqian/core/TextRange.ts";
import {
  FontMetricsRequest,
  StubFontMetricsResolver,
} from "../engine-gen/org/tiqian/font/FontMetrics.ts";
import { FontRole } from "../engine-gen/org/tiqian/font/FontRole.ts";
import { FontRequest } from "../engine-gen/org/tiqian/font/FontPolicy.ts";
import { PreferCjkForAmbiguousPunctuationResolver } from "../engine-gen/org/tiqian/font/PreferCjkForAmbiguousPunctuationResolver.ts";

/** Mirrors the identity of Kotlin's IllegalArgumentException on this wire. */
export class IllegalArgumentException extends Error {
  constructor(message: string) {
    super(message);
    this.name = "IllegalArgumentException";
  }
}

/** Reads one dynamically present string member; absent and mistyped are empty. */
function stringMember(raw: Record<string, unknown> | null, name: string): string {
  if (raw === null) return "";
  const value = raw[name];
  return typeof value === "string" ? value : "";
}

/** Reads one dynamically present number member; absent and mistyped are NaN. */
function numberMember(raw: Record<string, unknown> | null, name: string): number {
  if (raw === null) return Number.NaN;
  const value = raw[name];
  return typeof value === "number" ? value : Number.NaN;
}

/** Reads one dynamically present boolean member; absent and mistyped are false. */
function booleanMember(raw: Record<string, unknown> | null, name: string): boolean {
  if (raw === null) return false;
  const value = raw[name];
  return typeof value === "boolean" ? value : false;
}

/** Reads a JSON string array the way WireJson.kt parseDynamicStringList does. */
function stringListMember(raw: Record<string, unknown> | null, name: string): string[] {
  if (raw === null) return [];
  const value = raw[name];
  if (!Array.isArray(value)) return [];
  return value.map((item) => (typeof item === "string" ? item : ""));
}

/**
 * Decodes a font role name the way WireJson.kt does: a present string goes
 * through the enum name lookup, and an unknown name raises the same failure
 * identity as Kotlin's FontRole.valueOf; anything else is FontRole.Unknown.
 */
function fontRoleMember(raw: Record<string, unknown> | null, name: string): FontRole {
  const value = raw === null ? undefined : raw[name];
  if (typeof value !== "string") return FontRole.Unknown;
  const role = (FontRole as Record<string, FontRole | undefined>)[value];
  if (role === undefined) {
    throw new IllegalArgumentException(
      "Failed to create enum FontRole entry " + value,
    );
  }
  return role;
}

/** Parses a FontMetricsRequest JSON the way WireJson.kt parseFontMetricsRequestJson does. */
function parseFontMetricsRequestJson(json: string): FontMetricsRequest {
  let raw: Record<string, unknown> | null;
  try {
    raw = JSON.parse(json) as Record<string, unknown> | null;
  } catch {
    throw new SyntaxError("Unexpected token in JSON");
  }
  if (raw === null || typeof raw !== "object") raw = null;
  const fontWeight = numberMember(raw, "fontWeight");
  return new FontMetricsRequest(
    stringMember(raw, "fontKey"),
    numberMember(raw, "fontSize"),
    fontRoleMember(raw, "role"),
    stringMember(raw, "locale"),
    stringListMember(raw, "fontFamilies"),
    Number.isNaN(fontWeight) ? null : Math.trunc(fontWeight),
    booleanMember(raw, "italic"),
    stringMember(raw, "faceSelectionText"),
  );
}

/** Parses a FontRequest JSON the way WireJson.kt parseFontRequestJson does. */
function parseFontRequestJson(json: string): FontRequest {
  let raw: Record<string, unknown> | null;
  try {
    raw = JSON.parse(json) as Record<string, unknown> | null;
  } catch {
    throw new SyntaxError("Unexpected token in JSON");
  }
  if (raw === null || typeof raw !== "object") raw = null;
  return new FontRequest(
    stringListMember(raw, "preferredFamilies"),
    stringMember(raw, "locale"),
    fontRoleMember(raw, "role"),
  );
}

/**
 * Renders one wire number exactly like the Kotlin builder: the ECMA shortest
 * round-trip form, with NaN/Infinity spelled out and negative zero folded to
 * `0`. The values themselves are full-precision f64 (TCN-45).
 */
function appendJsonNumber(out: string[], value: number): void {
  if (Number.isNaN(value)) {
    out.push("NaN");
  } else if (value === Number.POSITIVE_INFINITY) {
    out.push("Infinity");
  } else if (value === Number.NEGATIVE_INFINITY) {
    out.push("-Infinity");
  } else if (value === 0) {
    out.push("0");
  } else {
    out.push(String(value));
  }
}

/** Renders one wire string exactly like WireJson.kt appendJsonString. */
function appendJsonString(out: string[], value: string): void {
  out.push(JSON.stringify(value));
}

/**
 * Resolves the engine's data-free font metrics for a JSON FontMetricsRequest
 * and returns the RawFontMetrics as JSON (ascent/descent/leading/source, plus
 * typoAscent/typoDescent when the face carries a declared typographic box).
 * Replaces the Kotlin @JsExport fontMetricsResolve.
 */
export function fontMetricsResolve(requestJson: string): string {
  const request = parseFontMetricsRequestJson(requestJson);
  const metrics = new StubFontMetricsResolver().resolve(request);
  const out: string[] = [];
  out.push('{"ascent":');
  appendJsonNumber(out, metrics.ascent);
  out.push(',"descent":');
  appendJsonNumber(out, metrics.descent);
  out.push(',"leading":');
  appendJsonNumber(out, metrics.leading);
  out.push(',"source":');
  appendJsonString(out, metrics.source.kind);
  if (metrics.typoAscent !== null && metrics.typoAscent !== undefined) {
    out.push(',"typoAscent":');
    appendJsonNumber(out, metrics.typoAscent);
  }
  if (metrics.typoDescent !== null && metrics.typoDescent !== undefined) {
    out.push(',"typoDescent":');
    appendJsonNumber(out, metrics.typoDescent);
  }
  out.push("}");
  return out.join("");
}

/**
 * Resolves the engine's LatinVsCjkFaceSelection fallback decision for the
 * source text substring in start..<end given a JSON FontRequest
 * (preferredFamilies/locale/role). Replaces the Kotlin @JsExport
 * fontFallbackResolve; the emission order matches FontExports.kt.
 */
export function fontFallbackResolve(
  text: string,
  start: number,
  end: number,
  requestJson: string,
): string {
  const request = parseFontRequestJson(requestJson);
  const decision = new PreferCjkForAmbiguousPunctuationResolver().resolve(
    text,
    new TextRange(start, end),
    request,
  );
  const out: string[] = [];
  out.push('{"range":{"start":');
  appendJsonNumber(out, decision.range.start);
  out.push(',"end":');
  appendJsonNumber(out, decision.range.end);
  out.push("}");
  out.push(',"candidate":{"key":');
  appendJsonString(out, decision.candidate.key);
  out.push(',"family":');
  appendJsonString(out, decision.candidate.family);
  out.push(',"role":');
  appendJsonString(out, decision.candidate.role.kind);
  out.push("},\"role\":");
  appendJsonString(out, decision.role.kind);
  out.push(",\"reason\":");
  appendJsonString(out, decision.reason);
  out.push("}");
  return out.join("");
}
