package org.tiqian.font;
import org.tiqian.core.TextRange;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;
class CjkFontRoleClassifierTest {
 static function c(t:String,s:Int,e:Int):FontRole return new CjkFontRoleClassifier().classify(t,new TextRange(s,e));
 @:test public static function classifiesCjkText():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCjkText"); TracedAssertions.assertEqualsRendered("CjkText",Std.string(c("提",0,1))); }
 @:test public static function classifiesCjkPunctuation():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCjkPunctuation"); var a=["……","⋯⋯","——","⸺","。","・","‧","～","／"];var i=0;while(i<a.length){var x=a[i];TracedAssertions.assertEqualsRendered("CjkPunctuation",Std.string(c(x,0,1)));i++;} }
 @:test public static function classifiesLatinText():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesLatinText"); TracedAssertions.assertEqualsRendered("LatinText",Std.string(c("English",0,1))); }
 @:test public static function classifiesUnicodeEmojiPresentationWithoutReclassifyingPlainKeycapBases():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesUnicodeEmojiPresentationWithoutReclassifyingPlainKeycapBases"); var xs=["⌚","🀄","🫪"];var xi=0;while(xi<xs.length){var x=xs[xi];TracedAssertions.assertEqualsRendered("Emoji",Std.string(c(x,0,x.length)));xi++;} TracedAssertions.assertEqualsRendered("LatinText",Std.string(c("1",0,1))); TracedAssertions.assertEqualsRendered("Symbol",Std.string(c("❤",0,1))); }
 @:test public static function classifiesAsciiSymbolsAndPunctuationAsLatin():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesAsciiSymbolsAndPunctuationAsLatin"); var xs=["%",".","#","@","&","(","_"];var xi=0;while(xi<xs.length){var x=xs[xi];TracedAssertions.assertEqualsRendered("LatinText",Std.string(c(x,0,1)));xi++;} }
 @:test public static function classifiesAsciiHyphenSlashTildeAsLatinRegardlessOfContext():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesAsciiHyphenSlashTildeAsLatinRegardlessOfContext"); var xs=["well-known","https://example","中文/TERFism","中文-中文"];var xi=0;while(xi<xs.length){var x=xs[xi];var p=x.indexOf("-");if(p<0)p=x.indexOf("/");TracedAssertions.assertEqualsRendered("LatinText",Std.string(c(x,p,p+1)));xi++;} }
 @:test public static function classifiesCurlyQuotesAsCjkWhenSurroundedByCjk():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCurlyQuotesAsCjkWhenSurroundedByCjk"); TracedAssertions.assertEqualsRendered("CjkPunctuation",Std.string(c("他说“你好”",2,3))); }
 @:test public static function classifiesCurlyQuotesAsLatinWhenSurroundedByLatin():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCurlyQuotesAsLatinWhenSurroundedByLatin"); TracedAssertions.assertEqualsRendered("LatinText",Std.string(c("said “hello” end",5,6))); TracedAssertions.assertEqualsRendered("LatinText",Std.string(c("it’s",2,3))); }
 @:test public static function classifiesCurlyQuotesAsCjkInMixedContext():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCurlyQuotesAsCjkInMixedContext"); TracedAssertions.assertEqualsRendered("CjkPunctuation",Std.string(c("他说“hello”",2,3))); }
 @:test public static function classifiesAsciiBracketsAsLatin():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesAsciiBracketsAsLatin"); var xs=["(",")","[","]","{"];var xi=0;while(xi<xs.length){var x=xs[xi];TracedAssertions.assertEqualsRendered("LatinText",Std.string(c(x,0,1)));xi++;} }
 @:test public static function classifiesCurlyQuotesAsCjkAtTextBoundary():Void { new TestTraceRecorder("CjkFontRoleClassifierTest").section("classifiesCurlyQuotesAsCjkAtTextBoundary"); TracedAssertions.assertEqualsRendered("CjkPunctuation",Std.string(c("“你好”",0,1))); }
}
