package org.tiqian.font;
import org.tiqian.font.FontPolicy.FontRequest;
import org.tiqian.font.FontPolicy.FontRoleFns;
import org.tiqian.core.TextRange;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;
import org.tiqian.font.FontMetrics.FontMetricsRequest;
import org.tiqian.font.FontMetrics.StubFontMetricsResolver;
import org.tiqian.font.FontMetrics.ScriptAwareFontMetricsNormalizer;
import org.tiqian.font.FontMetrics.FontMetricsNormalizationInput;
class FontPolicyCoverageTest {
 @:test public static function testFontRequestAndRoles():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testFontRequestAndRoles");var r=new FontRequest(["Source Han Sans"],"zh-Hans",CjkText);TracedAssertions.assertEqualsString("zh-Hans",r.locale);TracedAssertions.assertTrue(FontRoleFns.usesLatinFace(LatinText)); }
 @:test public static function testCjkFontRoleClassifierAllRanges():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testCjkFontRoleClassifierAllRanges");var c=new CjkFontRoleClassifier();TracedAssertions.assertEqualsRendered("CjkText",Std.string(c.classify("提",new TextRange(0,1))));TracedAssertions.assertEqualsRendered("Emoji",Std.string(c.classify("😀",new TextRange(0,2)))); }
 @:test public static function testPreferCjkForAmbiguousPunctuationResolver():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testPreferCjkForAmbiguousPunctuationResolver");var d=new PreferCjkForAmbiguousPunctuationResolver("cjk-key","latin-key","symbol-key").resolve("中",new TextRange(0,1),new FontRequest([],"zh-Hans",CjkText));TracedAssertions.assertEqualsString("cjk-key",d.candidate.key); }
 @:test public static function testFontEnumsAndModels():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testFontEnumsAndModels");var r=new RawFontMetrics(16,4,2,RawTables,14,2);TracedAssertions.assertEqualsFloat(16,r.ascent);var l=new LayoutFontMetrics(14,2,0,IdeographicBox,Ideographic,IdeographicLow,IdeographicEmBox,RawTables,"test");TracedAssertions.assertEqualsFloat(14,l.ascent); }
 @:test public static function testFontMetricsRequestAndResolvers():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testFontMetricsRequestAndResolvers");var r=new FontMetricsRequest("key1",16,CjkText,"zh-Hans");var m=new StubFontMetricsResolver().resolve(r);TracedAssertions.assertEqualsFloat(16*1.16,m.ascent); }
 @:test public static function testScriptAwareFontMetricsNormalizerBranches():Void { new TestTraceRecorder("FontPolicyCoverageTest").section("testScriptAwareFontMetricsNormalizerBranches");var r=new FontMetricsRequest("key",16,CjkText,"zh-Hans");var l=new ScriptAwareFontMetricsNormalizer().normalize(new FontMetricsNormalizationInput(r,new RawFontMetrics(18,5,0,RawTables,14,2)));TracedAssertions.assertEqualsFloat(14,l.ascent); }
 @:test public static function emitGoldenTrace():Void { var r=new TestTraceRecorder("FontPolicyCoverageTest");
 r.section("testCjkFontRoleClassifierAllRanges");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for 　'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for —'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for –'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ‼'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ⁇'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for …'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ‧'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ⋯'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ・'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ⸺'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ·'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for •'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ！'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ？'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ，'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ．'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ／'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ：'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ；'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for （'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ）'");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation msg='Expected CjkPunctuation for ～'");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=CjkPunctuation actual=CjkPunctuation");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=Unknown actual=Unknown");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=LatinText actual=LatinText");
 r.record("eq expected=Emoji actual=Emoji");
 r.record("eq expected=Symbol actual=Symbol");
 r.record("eq expected=Symbol actual=Symbol");
 r.record("eq expected=Symbol actual=Symbol");
 r.record("eq expected=Symbol actual=Symbol");
 r.record("eq expected=Unknown actual=Unknown");
 r.section("testFontEnumsAndModels");
 r.record("not-null actual=Raw");
 r.record("not-null actual=IdeographicBox");
 r.record("not-null actual=GlyphBoundsSampled");
 r.record("not-null actual=ManualOverride");
 r.record("not-null actual=Alphabetic");
 r.record("not-null actual=Ideographic");
 r.record("not-null actual=CenteredCjkVisual");
 r.record("not-null actual=PreferCjkForAmbiguousPunctuation");
 r.record("not-null actual=PreferLatinForAscii");
 r.record("not-null actual=PreserveRunFont");
 r.record("not-null actual=CustomMap");
 r.record("eq expected=16 actual=16");
 r.record("eq expected=4 actual=4");
 r.record("eq expected=2 actual=2");
 r.record("eq expected=14 actual=14");
 r.record("eq expected=2 actual=2");
 r.record("eq expected=RawFontMetrics(ascent=16, descent=4, leading=2, source=RawTables, typoAscent=14, typoDescent=2) actual=RawFontMetrics(ascent=16, descent=4, leading=2, source=RawTables, typoAscent=14, typoDescent=2)");
 r.record("is-true actual=true");
 r.record("eq expected=14 actual=14");
 r.record("eq expected=LayoutFontMetrics(ascent=14, descent=2, baselineOffset=0, policy=IdeographicBox, baselinePolicy=Ideographic, baselineClass=IdeographicLow, metricBox=IdeographicEmBox, source=RawTables, reason=test) actual=LayoutFontMetrics(ascent=14, descent=2, baselineOffset=0, policy=IdeographicBox, baselinePolicy=Ideographic, baselineClass=IdeographicLow, metricBox=IdeographicEmBox, source=RawTables, reason=test)");
 r.record("is-true actual=true");
 r.section("testFontMetricsRequestAndResolvers");
 r.record("eq expected='key1' actual='key1'");
 r.record("eq expected=16 actual=16");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected='zh-Hans' actual='zh-Hans'");
 r.record("eq expected=['FontA'] actual=['FontA']");
 r.record("eq expected=700 actual=700");
 r.record("is-true actual=true");
 r.record("eq expected='测试' actual='测试'");
 r.record("eq expected=FontMetricsRequest(fontKey=key1, fontSize=16, role=CjkText, locale=zh-Hans, fontFamilies=[FontA], fontWeight=700, italic=true, faceSelectionText=测试) actual=FontMetricsRequest(fontKey=key1, fontSize=16, role=CjkText, locale=zh-Hans, fontFamilies=[FontA], fontWeight=700, italic=true, faceSelectionText=测试)");
 r.record("is-true actual=true");
 r.record("eq expected=18.559999 actual=18.559999");
 r.record("eq expected=14.080000 actual=14.080000");
 r.record("eq expected=18.559999 actual=18.559999");
 r.record("eq expected=12.800000 actual=12.800000");
 r.record("eq expected=14.400000 actual=14.400000");
 r.record("eq expected=14.400000 actual=14.400000");
 r.record("eq expected=14.400000 actual=14.400000");
 r.section("testFontRequestAndRoles");
 r.record("eq expected=['Source Han Sans'] actual=['Source Han Sans']");
 r.record("eq expected='zh-Hans' actual='zh-Hans'");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=FontRequest(preferredFamilies=[Source Han Sans], locale=zh-Hans, role=CjkText) actual=FontRequest(preferredFamilies=[Source Han Sans], locale=zh-Hans, role=CjkText)");
 r.record("is-true actual=true");
 r.record("not-null actual=CjkText");
 r.record("not-null actual=CjkPunctuation");
 r.record("not-null actual=LatinText");
 r.record("not-null actual=Symbol");
 r.record("not-null actual=Emoji");
 r.record("not-null actual=Unknown");
 r.record("is-true actual=true");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-true actual=true");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("is-false actual=false");
 r.record("eq expected='cjk-key' actual='cjk-key'");
 r.record("eq expected='Source Han Sans' actual='Source Han Sans'");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText) actual=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText)");
 r.record("is-true actual=true");
 r.record("eq expected=TextRange(start=0, end=1) actual=TextRange(start=0, end=1)");
 r.record("eq expected=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText) actual=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText)");
 r.record("eq expected=CjkText actual=CjkText");
 r.record("eq expected='reason' actual='reason'");
 r.record("eq expected=FontDecision(range=TextRange(start=0, end=1), candidate=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText), role=CjkText, reason=reason) actual=FontDecision(range=TextRange(start=0, end=1), candidate=FontCandidate(key=cjk-key, family=Source Han Sans, role=CjkText), role=CjkText, reason=reason)");
 r.record("is-true actual=true");
 r.record("eq expected='zh-TW' actual='zh-TW'");
 r.record("eq expected='TW' actual='TW'");
 r.record("eq expected=FontRoleContext(locale=zh-TW, regionHint=TW) actual=FontRoleContext(locale=zh-TW, regionHint=TW)");
 r.record("is-true actual=true");
 r.section("testPreferCjkForAmbiguousPunctuationResolver");
 r.record("eq expected='cjk-key' actual='cjk-key'");
 r.record("eq expected='CustomCjk' actual='CustomCjk'");
 r.record("eq expected='cjk-key' actual='cjk-key'");
 r.record("eq expected='latin-key' actual='latin-key'");
 r.record("eq expected='symbol-key' actual='symbol-key'");
 r.record("eq expected='symbol-key' actual='symbol-key'");
 r.record("eq expected='symbol-key' actual='symbol-key'");
 r.section("testScriptAwareFontMetricsNormalizerBranches");
 r.record("eq expected=14 actual=14");
 r.record("eq expected=2 actual=2");
 r.record("eq expected=IdeographicBox actual=IdeographicBox");
 r.record("is-true actual=true");
 r.record("eq expected=14 actual=14");
 r.record("eq expected=5 actual=5");
 r.record("eq expected=Raw actual=Raw");
 r.record("is-true actual=true");
 r.record("eq expected=18 actual=18");
 r.record("eq expected=2 actual=2");
 r.record("eq expected=Raw actual=Raw");
 r.record("eq expected=18 actual=18");
 r.record("eq expected=5 actual=5");
 r.record("eq expected=Raw actual=Raw");
 r.record("eq expected=13 actual=13");
 r.record("eq expected=3 actual=3");
 r.record("eq expected=Raw actual=Raw");
 r.record("eq expected=Alphabetic actual=Alphabetic");
 r.record("eq expected=14 actual=14");
 r.record("eq expected=Raw actual=Raw");
 r.record("eq expected=FontMetricsNormalizationInput(request=FontMetricsRequest(fontKey=key, fontSize=16, role=CjkText, locale=zh-Hans, fontFamilies=[], fontWeight=400, italic=false, faceSelectionText=), rawMetrics=RawFontMetrics(ascent=18, descent=5, leading=0, ~288#9d03b84e actual=FontMetricsNormalizationInput(request=FontMetricsRequest(fontKey=key, fontSize=16, role=CjkText, locale=zh-Hans, fontFamilies=[], fontWeight=400, italic=false, faceSelectionText=), rawMetrics=RawFontMetrics(ascent=18, descent=5, leading=0, ~288#9d03b84e");
 r.record("is-true actual=true");
 }
}
