package org.tiqian.protocol

sealed class ParagraphRequestException(override val message: String) : RuntimeException(message) {
    data object EmptyParagraph : ParagraphRequestException("EmptyParagraph")
    data object InvalidMaximumMeasure : ParagraphRequestException("InvalidMaximumMeasure")
    data object InvalidFontSize : ParagraphRequestException("InvalidFontSize")
    data object InvalidLineHeight : ParagraphRequestException("InvalidLineHeight")
    data object InvalidFirstLineIndent : ParagraphRequestException("InvalidFirstLineIndent")
    data object InvalidFontWeight : ParagraphRequestException("InvalidFontWeight")
    data object InvalidEmphasisDotGapEm : ParagraphRequestException("InvalidEmphasisDotGapEm")
    data object MissingExplicitFontFamilies : ParagraphRequestException("MissingExplicitFontFamilies")
    data object InvalidTextSpanRange : ParagraphRequestException("InvalidTextSpanRange")
    data object MissingTextSpanFontFamilies : ParagraphRequestException("MissingTextSpanFontFamilies")
    data object InvalidTextSpanFontSize : ParagraphRequestException("InvalidTextSpanFontSize")
    data object InvalidTextSpanFontWeight : ParagraphRequestException("InvalidTextSpanFontWeight")
    data object InvalidTextSpanBaselineShift : ParagraphRequestException("InvalidTextSpanBaselineShift")
    data object InvalidSourceBoundary : ParagraphRequestException("InvalidSourceBoundary")
    data object InvalidLineBreakSpanRange : ParagraphRequestException("InvalidLineBreakSpanRange")
    data object InvalidInlineBoxRange : ParagraphRequestException("InvalidInlineBoxRange")
    data object InvalidInlineBoxGeometry : ParagraphRequestException("InvalidInlineBoxGeometry")
    data object InvalidInlineObjectRange : ParagraphRequestException("InvalidInlineObjectRange")
    data object InvalidInlineObjectAdvance : ParagraphRequestException("InvalidInlineObjectAdvance")
    data object InvalidInlineObjectVerticalGeometry : ParagraphRequestException("InvalidInlineObjectVerticalGeometry")
    data object InvalidDecorationRange : ParagraphRequestException("InvalidDecorationRange")
}
