// Generated by the reflaxe TypeScript target. Do not edit.

import { WireField } from "./WireField.ts";
import { WireValue } from "./WireValue.ts";
import { formatFloatRuntime, readUnit } from "../../../runtime.ts";

export class JsCoerce {
  public static toNumber(value: WireValue): number {
    switch (value.kind) {
      case "WNull":
        return 0.0;
      case "WBool":
      {
        return (value.value ? 1.0 : 0.0);
      }
      case "WNum":
      {
        return value.value;
      }
      case "WStr":
      {
        return JsCoerce.toNumberFromString(value.value);
      }
      case "WArr":
        return JsCoerce.toNumberFromString(JsCoerce.toString(value));
      case "WObj":
        return JsCoerce.toNumberFromString(JsCoerce.toString(value));
    }
  }

  public static toString(value: WireValue): string {
    switch (value.kind) {
      case "WNull":
        return "null";
      case "WBool":
      {
        return (value.value ? "true" : "false");
      }
      case "WNum":
      {
        return JsCoerce.numberToString(value.value);
      }
      case "WStr":
      {
        return value.value;
      }
      case "WArr":
      {
        return JsCoerce.joinItems(value.items);
      }
      case "WObj":
        return "[object Object]";
    }
  }

  private static joinItems(items: WireValue[]): string {
    const parts = new Array<string>();
    let itemIndexIdx = 0;
    while (itemIndexIdx < items.length) {
      const item = items[itemIndexIdx]!;
      parts.push(JsCoerce.itemText(item));
      itemIndexIdx++;
    }
    return parts.join(",");
  }

  private static itemText(item: WireValue): string {
    switch (item.kind) {
      case "WNull":
        return "";
      case "WBool":
        return JsCoerce.toString(item);
      case "WNum":
        return JsCoerce.toString(item);
      case "WStr":
        return JsCoerce.toString(item);
      case "WArr":
        return JsCoerce.toString(item);
      case "WObj":
        return JsCoerce.toString(item);
    }
  }

  public static numberToString(value: number): string {
    if (Number.isNaN(value)) {
      return "NaN";
    }
    if (value === Infinity) {
      return "Infinity";
    }
    if (value === -Infinity) {
      return "-Infinity";
    }
    if (value === 0.0) {
      return "0";
    }
    if (value === Math.floor(value) && Math.abs(value) < 1e21) {
      let rest = Math.abs(value);
      let digits = "";
      while (rest >= 10) {
        const digit = Math.floor(rest % 10);
        digits = String.fromCodePoint(48 + digit) + digits;
        rest = Math.floor(rest / 10);
      }
      digits = String.fromCodePoint(48 + Math.floor(rest)) + digits;
      return (value < 0 ? `-${digits}` : digits);
    }
    return formatFloatRuntime(value);
  }

  public static toNumberFromString(text: string): number {
    const trimmed = JsCoerce.jsTrim(text);
    if (trimmed.length === 0) {
      return 0.0;
    }
    let negative = false;
    let body = trimmed;
    const first = body.charAt(0);
    if (first === "-") {
      negative = true;
      body = body.substr(1);
    } else {
      if (first === "+") {
        body = body.substr(1);
      }
    }
    if (body === "Infinity") {
      return (negative ? -Infinity : Infinity);
    }
    if (body === "NaN") {
      return Number.NaN;
    }
    const radix = JsCoerce.radixPrefix(body);
    if (radix > 0) {
      const digits = body.substr(2);
      let value = 0.0;
      let indexIdx = 0;
      while (indexIdx < digits.length) {
        const digit = JsCoerce.hexDigit((Number.isNaN(digits.charCodeAt(indexIdx)) ? null : digits.charCodeAt(indexIdx))!);
        if (digit < 0) {
          return Number.NaN;
        }
        value = value * radix + digit;
        indexIdx++;
      }
      return (negative ? -value : value);
    }
    if (!JsCoerce.isStrictDecimal(body)) {
      return Number.NaN;
    }
    const parsed = ((s) => { let a = 0, z = s.length; while (a < z) { const c = s.charCodeAt(a); if (c === 32 || (c >= 9 && c <= 13)) { a++; } else { break; } } while (z > a) { const c = s.charCodeAt(z - 1); if (c === 32 || (c >= 9 && c <= 13)) { z--; } else { break; } } let i = a; const c0 = s.charCodeAt(i); if (c0 === 43 || c0 === 45) { i++; } let before = 0; while (i < z) { const c = s.charCodeAt(i); if (c >= 48 && c <= 57) { i++; before++; } else { break; } } let after = 0; if (i < z && s.charCodeAt(i) === 46) { i++; while (i < z) { const c = s.charCodeAt(i); if (c >= 48 && c <= 57) { i++; after++; } else { break; } } } let ok = before > 0 || after > 0; if (ok && i < z) { const e = s.charCodeAt(i); if (e === 101 || e === 69) { i++; const c1 = s.charCodeAt(i); if (c1 === 43 || c1 === 45) { i++; } let m = 0; while (i < z) { const c = s.charCodeAt(i); if (c >= 48 && c <= 57) { i++; m++; } else { break; } } ok = m > 0; } else { ok = false; } } return ok && i === z ? Number.parseFloat(s.substring(a, z)) : Number.NaN; })(body);
    return (negative ? -parsed : parsed);
  }

  private static radixPrefix(body: string): number {
    if (body.length < 3) {
      return 0;
    }
    const marker = body.substr(0, 2);
    if (marker === "0x" || marker === "0X") {
      return 16;
    }
    if (marker === "0o" || marker === "0O") {
      return 8;
    }
    if (marker === "0b" || marker === "0B") {
      return 2;
    }
    return 0;
  }

  private static hexDigit(code: number): number {
    if (code >= 48 && code <= 57) {
      return code - 48;
    }
    if (code >= 65 && code <= 70) {
      return code - 55;
    }
    if (code >= 97 && code <= 102) {
      return code - 87;
    }
    return -1;
  }

  private static isStrictDecimal(body: string): boolean {
    let index = 0;
    let seenDigit = false;
    while (index < body.length && JsCoerce.isDecimalDigit((Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))!)) {
      index++;
      seenDigit = true;
    }
    if (index < body.length && (Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))! === 46) {
      index++;
      while (index < body.length && JsCoerce.isDecimalDigit((Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))!)) {
        index++;
        seenDigit = true;
      }
    }
    if (!seenDigit) {
      return false;
    }
    if (index < body.length && ((Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))! === 101 || (Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))! === 69)) {
      index++;
      if (index < body.length && ((Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))! === 43 || (Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))! === 45)) {
        index++;
      }
      let exponentDigits = false;
      while (index < body.length && JsCoerce.isDecimalDigit((Number.isNaN(body.charCodeAt(index)) ? null : body.charCodeAt(index))!)) {
        index++;
        exponentDigits = true;
      }
      if (!exponentDigits) {
        return false;
      }
    }
    return index === body.length;
  }

  private static isDecimalDigit(code: number): boolean {
    return code >= 48 && code <= 57;
  }

  private static jsTrim(text: string): string {
    let start = 0;
    let end = text.length;
    while (start < end && JsCoerce.isJsWhitespace((Number.isNaN(text.charCodeAt(start)) ? null : text.charCodeAt(start))!)) {
      start++;
    }
    while (end > start && JsCoerce.isJsWhitespace(readUnit(text, end - 1)!)) {
      end--;
    }
    return (start === 0 && end === text.length ? text : text.substr(start, end - start));
  }

  private static isJsWhitespace(code: number): boolean {
    return code === 32 || code === 9 || code === 10 || code === 13 || code === 12 || code === 11 || code === 160;
  }

  public static renderJson(value: WireValue): string {
    switch (value.kind) {
      case "WNull":
        return "null";
      case "WBool":
      {
        return (value.value ? "true" : "false");
      }
      case "WNum":
      {
        return JsCoerce.numberToString(value.value);
      }
      case "WStr":
      {
        return JsCoerce.quoteJson(value.value);
      }
      case "WArr":
      {
        return JsCoerce.renderArray(value.items);
      }
      case "WObj":
      {
        return JsCoerce.renderObject(value.fields);
      }
    }
  }

  private static renderArray(items: WireValue[]): string {
    const parts = new Array<string>();
    let itemIndexIdx = 0;
    while (itemIndexIdx < items.length) {
      const item = items[itemIndexIdx]!;
      parts.push(JsCoerce.renderJson(item));
      itemIndexIdx++;
    }
    return `[${parts.join(",")}]`;
  }

  private static renderObject(fields: WireField[]): string {
    const parts = new Array<string>();
    let fieldIndexIdx = 0;
    while (fieldIndexIdx < fields.length) {
      const field = fields[fieldIndexIdx]!;
      parts.push(JsCoerce.quoteJson(field.name) + ":" + JsCoerce.renderJson(field.value));
      fieldIndexIdx++;
    }
    return `{${parts.join(",")}}`;
  }

  private static quoteJson(text: string): string {
    let out_b = "";
    out_b += "\"";
    let indexIdx = 0;
    while (indexIdx < text.length) {
      const code = (Number.isNaN(text.charCodeAt(indexIdx)) ? null : text.charCodeAt(indexIdx))!;
      if (code === 34) {
        out_b += "\\\"";
      } else {
        if (code === 92) {
          out_b += "\\\\";
        } else {
          if (code === 8) {
            out_b += "\\b";
          } else {
            if (code === 12) {
              out_b += "\\f";
            } else {
              if (code === 10) {
                out_b += "\\n";
              } else {
                if (code === 13) {
                  out_b += "\\r";
                } else {
                  if (code === 9) {
                    out_b += "\\t";
                  } else {
                    if (code < 32) {
                      out_b += "\\u00";
                      {
                        const x = "0123456789abcdef".charAt((code >> 4) & 15);
                        out_b += x;
                      }
                      {
                        const x2 = "0123456789abcdef".charAt(code & 15);
                        out_b += x2;
                      }
                    } else {
                      const c = code!;
                      out_b += String.fromCodePoint(c);
                    }
                  }
                }
              }
            }
          }
        }
      }
      indexIdx++;
    }
    out_b += "\"";
    return out_b;
  }
}
