// Generated by the reflaxe TypeScript target. Do not edit.

export class PlanSchema {
  public static readonly PLAN_SCHEMA: number = 1;
  public static readonly PLAN_LAYOUT_REVISION: string = "tiqian-layout-v2";
}
