// Generated by the reflaxe TypeScript target. Do not edit.

export interface AutoWrap {
  readonly kind: "AutoWrap"
}

export interface MandatoryBreak {
  readonly kind: "MandatoryBreak"
}

export interface ParagraphEnd {
  readonly kind: "ParagraphEnd"
}

export type PlanEndReason =
  | AutoWrap
  | MandatoryBreak
  | ParagraphEnd;

export const PlanEndReason = Object.freeze({
  AutoWrap: Object.freeze({ kind: "AutoWrap" } as AutoWrap),
  MandatoryBreak: Object.freeze({ kind: "MandatoryBreak" } as MandatoryBreak),
  ParagraphEnd: Object.freeze({ kind: "ParagraphEnd" } as ParagraphEnd)
});

export function comparePlanEndReason(a: PlanEndReason, b: PlanEndReason): number {
  if (a === b) return 0;
  if (a.kind === "AutoWrap") return 0 - (b.kind === "AutoWrap" ? 0 : 0);
  if (a.kind === "MandatoryBreak") return 1 - (b.kind === "MandatoryBreak" ? 1 : 0);
  if (a.kind === "ParagraphEnd") return 2 - (b.kind === "ParagraphEnd" ? 2 : 0);
  return 0;
}
