// Generated by the reflaxe TypeScript target. Do not edit.

export interface TextSpanInput {
  start: number;
  end: number;
  families: string[];
  fontSizePx: number;
  fontWeight: number;
  italic: boolean;
  baselineShift: number;
}
