// Generated by the reflaxe TypeScript target. Do not edit.

import { Sha256 } from "./../../../haxe/crypto/Sha256.js";
import { EncodeResult } from "./EncodeResult.js";
import { JsCoerce } from "./JsCoerce.js";
import { WireField } from "./WireField.js";
import { WireValue } from "./WireValue.js";
import { BytesBuffer, doubleToI64 } from "../../../runtime.js";

export class Canonical {
  public static digest(data: Uint8Array): Uint8Array {
    return Sha256.make(data);
  }

  public static encode(input: WireValue, kind: number): EncodeResult {
    const writer = new Writer(kind);
    const text = Canonical.member(input, "text");
    let textValue = "";
    if (!Canonical.isWireNull(text)) {
      textValue = JsCoerce.toString(text);
    }
    writer.str(textValue);
    if (kind === 0) {
      Canonical.numberField(writer, Canonical.numberMember(input, "maxWidthPx"));
    }
    const semantics = Canonical.encodeSemantics(writer, Canonical.member(input, "semantics"));
    if (semantics !== null) {
      return ({ kind: "CErr", issue: semantics } as EncodeResult);
    }
    const spans = Canonical.encodeTextSpans(writer, Canonical.member(input, "textSpans"));
    if (spans !== null) {
      return ({ kind: "CErr", issue: spans } as EncodeResult);
    }
    const boxes = Canonical.encodeInlineBoxes(writer, Canonical.member(input, "inlineBoxes"));
    if (boxes !== null) {
      return ({ kind: "CErr", issue: boxes } as EncodeResult);
    }
    const boundaries = Canonical.arrOfNullable(Canonical.member(input, "sourceBoundaries"));
    writer.u32(boundaries.length);
    let boundaryIndexIdx = 0;
    while (boundaryIndexIdx < boundaries.length) {
      const boundary = boundaries[boundaryIndexIdx]!;
      const value = Canonical.canonicalF64(JsCoerce.toNumber(boundary));
      writer.f64((value === null ? 0.0 : value));
      boundaryIndexIdx++;
    }
    return ({ kind: "COk", bytes: writer.finish() } as EncodeResult);
  }

  public static member(input: WireValue, name: string): WireValue {
    if (Canonical.isWireObj(input)) {
      return Canonical.memberOfFields(Canonical.objFields(input), name);
    }
    return { kind: "WNull" };
  }

  private static memberOfFields(fields: WireField[], name: string): WireValue {
    let fieldIndexIdx = 0;
    while (fieldIndexIdx < fields.length) {
      const field = fields[fieldIndexIdx]!;
      if (field.name === name) {
        return field.value;
      }
      fieldIndexIdx++;
    }
    return { kind: "WNull" };
  }

  private static canonicalF64(value: number): number | null {
    if (!Number.isFinite(value)) {
      return null;
    }
    return (value === 0.0 ? 0.0 : value);
  }

  private static numberMember(input: WireValue, name: string): number | null {
    const resolved = Canonical.member(input, name);
    return (resolved.kind === "WNull" ? null : Canonical.canonicalF64(JsCoerce.toNumber(resolved)));
  }

  private static numberField(writer: Writer, value: number | null): void {
    if (value === null) {
      writer.u8(0);
    } else {
      writer.u8(1);
      writer.f64(value);
    }
  }

  private static listMember(value: WireValue): ListShape {
    if (Canonical.isWireNull(value)) {
      return { kind: "LAbsent" };
    }
    if (Canonical.isWireArr(value)) {
      return ({ kind: "LArr", items: Canonical.arrOf(value) } as ListShape);
    }
    return { kind: "LBad" };
  }

  private static isWireNull(value: WireValue): boolean {
    switch (value.kind) {
      case "WNull":
        return true;
      case "WBool":
        return false;
      case "WNum":
        return false;
      case "WStr":
        return false;
      case "WArr":
        return false;
      case "WObj":
        return false;
    }
  }

  private static isWireArr(value: WireValue): boolean {
    switch (value.kind) {
      case "WNull":
        return false;
      case "WBool":
        return false;
      case "WNum":
        return false;
      case "WStr":
        return false;
      case "WArr":
        return true;
      case "WObj":
        return false;
    }
  }

  private static isWireObj(value: WireValue): boolean {
    switch (value.kind) {
      case "WNull":
        return false;
      case "WBool":
        return false;
      case "WNum":
        return false;
      case "WStr":
        return false;
      case "WArr":
        return false;
      case "WObj":
        return true;
    }
  }

  private static arrOf(value: WireValue): WireValue[] {
    switch (value.kind) {
      case "WNull":
        return new Array<WireValue>();
      case "WBool":
        return new Array<WireValue>();
      case "WNum":
        return new Array<WireValue>();
      case "WStr":
        return new Array<WireValue>();
      case "WArr":
      {
        return value.items;
      }
      case "WObj":
        return new Array<WireValue>();
    }
  }

  private static arrOfNullable(value: WireValue): WireValue[] {
    switch (value.kind) {
      case "WNull":
        return new Array<WireValue>();
      case "WBool":
        return new Array<WireValue>();
      case "WNum":
        return new Array<WireValue>();
      case "WStr":
        return new Array<WireValue>();
      case "WArr":
      {
        return value.items;
      }
      case "WObj":
        return new Array<WireValue>();
    }
  }

  private static objFields(value: WireValue): WireField[] {
    switch (value.kind) {
      case "WNull":
        return new Array<WireField>();
      case "WBool":
        return new Array<WireField>();
      case "WNum":
        return new Array<WireField>();
      case "WStr":
        return new Array<WireField>();
      case "WArr":
        return new Array<WireField>();
      case "WObj":
      {
        return value.fields;
      }
    }
  }

  private static isBadShape(shape: ListShape): boolean {
    switch (shape.kind) {
      case "LAbsent":
        return false;
      case "LArr":
        return false;
      case "LBad":
        return true;
    }
  }

  private static shapeItems(shape: ListShape): WireValue[] {
    switch (shape.kind) {
      case "LAbsent":
        return new Array<WireValue>();
      case "LArr":
      {
        return shape.items;
      }
      case "LBad":
        return new Array<WireValue>();
    }
  }

  private static encodeSemantics(writer: Writer, value: WireValue): string {
    const shape = Canonical.listMember(value);
    if (Canonical.isBadShape(shape)) {
      return "InvalidSnapshotSemantics";
    }
    const items = Canonical.shapeItems(shape);
    writer.u32(items.length);
    let spanIndexIdx = 0;
    while (spanIndexIdx < items.length) {
      const span = items[spanIndexIdx]!;
      const attributes = Canonical.member(span, "attributes");
      const order = Canonical.numberMember(span, "order");
      const tagName = Canonical.member(span, "tagName");
      let flags = 0;
      if (attributes.kind !== "WNull") {
        flags |= 1;
      }
      if (order !== null) {
        flags |= 2;
      }
      if (tagName.kind !== "WNull") {
        flags |= 4;
      }
      writer.u8(flags);
      Canonical.numberField(writer, Canonical.numberMember(span, "start"));
      Canonical.numberField(writer, Canonical.numberMember(span, "end"));
      if (tagName.kind !== "WNull") {
        writer.str(JsCoerce.toString(tagName));
      }
      if (order !== null) {
        writer.f64(order);
      }
      if (attributes.kind !== "WNull") {
        Canonical.encodeAttributes(writer, attributes);
      }
      spanIndexIdx++;
    }
    return null;
  }

  private static encodeTextSpans(writer: Writer, value: WireValue): string {
    const shape = Canonical.listMember(value);
    if (Canonical.isBadShape(shape)) {
      return "InvalidSnapshotTextSpans";
    }
    const items = Canonical.shapeItems(shape);
    writer.u32(items.length);
    let spanIndexIdx = 0;
    while (spanIndexIdx < items.length) {
      const span = items[spanIndexIdx]!;
      const families = Canonical.familiesOf(span);
      const fontSizePx = Canonical.numberMember(span, "fontSizePx");
      const fontWeight = Canonical.numberMember(span, "fontWeight");
      const italic = Canonical.italicOf(span);
      const baselineShiftPx = Canonical.numberMember(span, "baselineShiftPx");
      let flags = 0;
      if (families !== null) {
        flags |= 1;
      }
      if (fontSizePx !== null) {
        flags |= 2;
      }
      if (fontWeight !== null) {
        flags |= 4;
      }
      if (italic !== null) {
        flags |= 8;
      }
      if (baselineShiftPx !== null) {
        flags |= 16;
      }
      writer.u8(flags);
      Canonical.numberField(writer, Canonical.numberMember(span, "start"));
      Canonical.numberField(writer, Canonical.numberMember(span, "end"));
      if (families !== null) {
        writer.u32(families.length);
        let nameIndexIdx = 0;
        while (nameIndexIdx < families.length) {
          writer.str(families[nameIndexIdx]!);
          nameIndexIdx++;
        }
      }
      if (fontSizePx !== null) {
        writer.f64(fontSizePx);
      }
      if (fontWeight !== null) {
        writer.f64(fontWeight);
      }
      if (italic !== null) {
        writer.u8((italic ? 1 : 0));
      }
      if (baselineShiftPx !== null) {
        writer.f64(baselineShiftPx);
      }
      spanIndexIdx++;
    }
    return null;
  }

  private static encodeInlineBoxes(writer: Writer, value: WireValue): string {
    const shape = Canonical.listMember(value);
    if (Canonical.isBadShape(shape)) {
      return "InvalidSnapshotInlineBoxes";
    }
    const items = Canonical.shapeItems(shape);
    writer.u32(items.length);
    let itemIndexIdx = 0;
    while (itemIndexIdx < items.length) {
      const item = items[itemIndexIdx]!;
      const inlineStartPx = Canonical.numberMember(item, "inlineStartPx");
      const inlineEndPx = Canonical.numberMember(item, "inlineEndPx");
      const outerSpacing = Canonical.member(item, "outerSpacing");
      let flags = 0;
      if (inlineStartPx !== null) {
        flags |= 1;
      }
      if (inlineEndPx !== null) {
        flags |= 2;
      }
      if (outerSpacing.kind !== "WNull") {
        flags |= 4;
      }
      writer.u8(flags);
      Canonical.numberField(writer, Canonical.numberMember(item, "start"));
      Canonical.numberField(writer, Canonical.numberMember(item, "end"));
      if (inlineStartPx !== null) {
        writer.f64(inlineStartPx);
      }
      if (inlineEndPx !== null) {
        writer.f64(inlineEndPx);
      }
      if (outerSpacing.kind !== "WNull") {
        writer.str(JsCoerce.toString(outerSpacing));
      }
      itemIndexIdx++;
    }
    return null;
  }

  private static familiesOf(span: WireValue): string[] | null {
    const raw = Canonical.member(span, "fontFamilies");
    if (Canonical.isWireArr(raw)) {
      return Canonical.familiesFromList(Canonical.arrOf(raw));
    }
    return null;
  }

  private static familiesFromList(list: WireValue[]): string[] {
    const names = new Array<string>();
    let itemIndexIdx = 0;
    while (itemIndexIdx < list.length) {
      names.push(JsCoerce.toString(list[itemIndexIdx]!));
      itemIndexIdx++;
    }
    return names;
  }

  private static italicOf(span: WireValue): boolean | null {
    const raw = Canonical.member(span, "italic");
    if (Canonical.isWireBool(raw)) {
      return Canonical.boolOf(raw);
    }
    return null;
  }

  private static isWireBool(value: WireValue): boolean {
    switch (value.kind) {
      case "WNull":
        return false;
      case "WBool":
        return true;
      case "WNum":
        return false;
      case "WStr":
        return false;
      case "WArr":
        return false;
      case "WObj":
        return false;
    }
  }

  private static boolOf(value: WireValue): boolean {
    switch (value.kind) {
      case "WNull":
        return false;
      case "WBool":
      {
        return value.value;
      }
      case "WNum":
        return false;
      case "WStr":
        return false;
      case "WArr":
        return false;
      case "WObj":
        return false;
    }
  }

  private static encodeAttributes(writer: Writer, value: WireValue): void {
    if (Canonical.isWireObj(value)) {
      Canonical.encodeObjectAttributes(writer, Canonical.objFields(value));
      return;
    }
    if (Canonical.isWireArr(value)) {
      writer.u8(2);
      writer.bytes(new TextEncoder().encode(JsCoerce.renderJson(value)));
      return;
    }
    writer.u8(0);
  }

  private static encodeObjectAttributes(writer: Writer, fields: WireField[]): void {
    writer.u8(1);
    writer.u32(fields.length);
    let fieldIndexIdx = 0;
    while (fieldIndexIdx < fields.length) {
      const field = fields[fieldIndexIdx]!;
      writer.str(field.name);
      writer.str(JsCoerce.toString(field.value));
      fieldIndexIdx++;
    }
  }
}

export class Writer {
  private readonly buf: BytesBuffer;

  constructor(kind: number) {
    this.buf = new BytesBuffer();
    this.buf.add(new TextEncoder().encode("TQCS"));
    this.u8(1);
    this.u8(kind);
  }

  public u8(value: number): void {
    this.buf.addByte(value & 255);
  }

  public u32(value: number): void {
    this.emitBits(value);
  }

  public f64(value: number): void {
    const bits = doubleToI64(value);
    this.emitBits(bits.low);
    this.emitBits(bits.high);
  }

  private emitBits(value: number): void {
    this.buf.addByte(value & 255);
    this.buf.addByte((value >>> 8) & 255);
    this.buf.addByte((value >>> 16) & 255);
    this.buf.addByte((value >>> 24) & 255);
  }

  public str(value: string): void {
    this.bytes(new TextEncoder().encode(value));
  }

  public bytes(value: Uint8Array): void {
    this.u32(value.length);
    this.buf.add(value);
  }

  public finish(): Uint8Array {
    return this.buf.getBytes();
  }
}

export interface LAbsent {
  readonly kind: "LAbsent"
}

export interface LArr {
  readonly kind: "LArr"
  readonly items: WireValue[]
}

export interface LBad {
  readonly kind: "LBad"
}

export type ListShape =
  | LAbsent
  | LArr
  | LBad;
