// Generated by the reflaxe TypeScript target. Do not edit.

export interface DecorationInput {
  start: number;
  end: number;
  kind: string;
}

export function compareDecorationInput(a: DecorationInput, b: DecorationInput): number {
  if (a === b) return 0;
  if (a.start !== b.start) return a.start - b.start;
  if (a.end !== b.end) return a.end - b.end;
  if (a.kind !== b.kind) return a.kind < b.kind ? -1 : 1;
  return 0;
}
