// Generated by the reflaxe TypeScript target. Do not edit.

import { ParagraphRequestError } from "./ParagraphRequestError.js";

export class ParagraphRequestException extends Error {
  public readonly error: ParagraphRequestError;

  constructor(error: ParagraphRequestError) {
    super(ParagraphRequestException.describe(error));
    this.name = "ParagraphRequestException";
    this.error = error;
  }

  public static describe(error: ParagraphRequestError): string {
    switch (error.kind) {
      case "EmptyParagraph":
        return "EmptyParagraph";
      case "InvalidMaximumMeasure":
        return "InvalidMaximumMeasure";
      case "InvalidFontSize":
        return "InvalidFontSize";
      case "InvalidLineHeight":
        return "InvalidLineHeight";
      case "InvalidFirstLineIndent":
        return "InvalidFirstLineIndent";
      case "InvalidFontWeight":
        return "InvalidFontWeight";
      case "InvalidEmphasisDotGapEm":
        return "InvalidEmphasisDotGapEm";
      case "MissingExplicitFontFamilies":
        return "MissingExplicitFontFamilies";
      case "InvalidTextSpanRange":
        return "InvalidTextSpanRange";
      case "MissingTextSpanFontFamilies":
        return "MissingTextSpanFontFamilies";
      case "InvalidTextSpanFontSize":
        return "InvalidTextSpanFontSize";
      case "InvalidTextSpanFontWeight":
        return "InvalidTextSpanFontWeight";
      case "InvalidTextSpanBaselineShift":
        return "InvalidTextSpanBaselineShift";
      case "InvalidSourceBoundary":
        return "InvalidSourceBoundary";
      case "InvalidLineBreakSpanRange":
        return "InvalidLineBreakSpanRange";
      case "InvalidInlineBoxRange":
        return "InvalidInlineBoxRange";
      case "InvalidInlineBoxGeometry":
        return "InvalidInlineBoxGeometry";
      case "InvalidInlineObjectRange":
        return "InvalidInlineObjectRange";
      case "InvalidInlineObjectAdvance":
        return "InvalidInlineObjectAdvance";
      case "InvalidInlineObjectVerticalGeometry":
        return "InvalidInlineObjectVerticalGeometry";
      case "InvalidDecorationRange":
        return "InvalidDecorationRange";
    }
  }
}
