// Generated by the reflaxe TypeScript target. Do not edit.

import { DecorationInput } from "./DecorationInput.js";
import { InlineBoxInput } from "./InlineBoxInput.js";
import { InlineObjectInput } from "./InlineObjectInput.js";
import { LineBreakSpanInput } from "./LineBreakSpanInput.js";
import { TextSpanInput } from "./TextSpanInput.js";

export interface ParagraphRequest {
  fontSessionId: string;
  text: string;
  maxWidthPx: number;
  fontFamilies: string[];
  fontSizePx: number;
  lineHeightPx: number;
  locale: string;
  fontWeight: number;
  italic: boolean;
  firstLineIndentIc: number;
  lineLengthGridEnabled: boolean;
  emphasisDotGapEm: number | null;
  sourceBoundaries: number[];
  textSpans: TextSpanInput[];
  lineBreakSpans: LineBreakSpanInput[];
  inlineBoxes: InlineBoxInput[];
  inlineObjects: InlineObjectInput[];
  decorations: DecorationInput[];
}
