// Generated by the reflaxe TypeScript target. Do not edit.

import { ParagraphRequest } from "./ParagraphRequest.js";
import { ParagraphRequestChecks } from "./ParagraphRequestChecks.js";
import { ParagraphRequestException } from "./ParagraphRequestException.js";

export class ParagraphRequestTestSupport {
  public static request(): ParagraphRequest {
    return { fontSessionId: "tq-font-test-1", text: "正文一段", maxWidthPx: 80.0, fontFamilies: ["Fake CJK"], fontSizePx: 16.0, lineHeightPx: 24.0, locale: "zh-Hans", fontWeight: 400, italic: false, firstLineIndentIc: 0.0, lineLengthGridEnabled: false, emphasisDotGapEm: null, sourceBoundaries: [], textSpans: [], lineBreakSpans: [], inlineBoxes: [], inlineObjects: [], decorations: [] };
  }

  public static issueOf(request: ParagraphRequest): string {
    let name = "";
    try {
      ParagraphRequestChecks.validate(request);
    } catch (error) {
      if (error instanceof ParagraphRequestException) {
        name = ParagraphRequestException.describe(error.error);
      } else {
        throw error;
      }
    }
    return name;
  }

  public static withText(text: string): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.text = text;
    return copy;
  }

  public static withMaxWidth(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.maxWidthPx = value;
    return copy;
  }

  public static withFontSize(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.fontSizePx = value;
    return copy;
  }

  public static withLineHeight(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.lineHeightPx = value;
    return copy;
  }

  public static withIndent(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.firstLineIndentIc = value;
    return copy;
  }

  public static withWeight(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.fontWeight = value;
    return copy;
  }

  public static withGap(value: number): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.emphasisDotGapEm = value;
    return copy;
  }

  public static withFamilies(families: string[]): ParagraphRequest {
    const copy = ParagraphRequestTestSupport.request();
    copy.fontFamilies = families;
    return copy;
  }
}
