// Generated by the reflaxe TypeScript target. Do not edit.

import { UStringFault } from "./UStringFault.ts";

export class UStringException extends Error {
  public readonly fault: UStringFault;

  constructor(fault: UStringFault) {
    super(UStringException.describe(fault));
    this.name = "UStringException";
    this.fault = fault;
  }

  public static describe(fault: UStringFault): string {
    switch (fault.kind) {
      case "InvalidCodePoint":
      {
        return `invalid code point: ${fault.code}`;
      }
      case "UnpairedSurrogate":
      {
        return `unpaired surrogate: ${fault.unit}`;
      }
    }
  }
}
