// Generated by the reflaxe TypeScript target. Do not edit.

import { LineAdjustmentStrategy } from "./LineAdjustmentStrategy.ts";
import { LineEndPunctuationStyle } from "./LineEndPunctuationStyle.ts";

export class AdjustmentStylePolicy {
  public readonly lineEndPunctuation: LineEndPunctuationStyle;
  public readonly allowInlineStopCompression: boolean;
  public readonly allowSinoWesternGapAdjustment: boolean;
  public readonly lineAdjustment: LineAdjustmentStrategy;

  constructor(lineEndPunctuation: LineEndPunctuationStyle | null = null, allowInlineStopCompression: boolean | null = null, allowSinoWesternGapAdjustment: boolean | null = null, lineAdjustment: LineAdjustmentStrategy | null = null) {
    this.lineEndPunctuation = lineEndPunctuation ?? (LineEndPunctuationStyle.ForceHalfWidth as LineEndPunctuationStyle);
    this.allowInlineStopCompression = allowInlineStopCompression ?? true;
    this.allowSinoWesternGapAdjustment = allowSinoWesternGapAdjustment ?? true;
    this.lineAdjustment = lineAdjustment ?? (LineAdjustmentStrategy.PushInFirst as LineAdjustmentStrategy);
  }

  public toString(): string {
    return `AdjustmentStylePolicy(lineEndPunctuation=${this.lineEndPunctuation.kind}, allowInlineStopCompression=${this.allowInlineStopCompression}, allowSinoWesternGapAdjustment=${this.allowSinoWesternGapAdjustment}, lineAdjustment=${this.lineAdjustment.kind})`;
  }

  public static samePolicy(a: AdjustmentStylePolicy, b: AdjustmentStylePolicy): boolean {
    return a.lineEndPunctuation === b.lineEndPunctuation && a.allowInlineStopCompression === b.allowInlineStopCompression && a.allowSinoWesternGapAdjustment === b.allowSinoWesternGapAdjustment && a.lineAdjustment === b.lineAdjustment;
  }
}
