// Generated by the reflaxe TypeScript target. Do not edit.

export interface Disabled {
  readonly kind: "Disabled"
}

export interface Replace {
  readonly kind: "Replace"
}

export interface Insert {
  readonly kind: "Insert"
}

export type AutoSpaceMode =
  | Disabled
  | Replace
  | Insert;

export const AutoSpaceMode = Object.freeze({
  Disabled: Object.freeze({ kind: "Disabled" } as Disabled),
  Replace: Object.freeze({ kind: "Replace" } as Replace),
  Insert: Object.freeze({ kind: "Insert" } as Insert)
});

export function compareAutoSpaceMode(a: AutoSpaceMode, b: AutoSpaceMode): number {
  if (a === b) return 0;
  if (a.kind === "Disabled") return 0 - (b.kind === "Disabled" ? 0 : 0);
  if (a.kind === "Replace") return 1 - (b.kind === "Replace" ? 1 : 0);
  if (a.kind === "Insert") return 2 - (b.kind === "Insert" ? 2 : 0);
  return 0;
}
