// Generated by the reflaxe TypeScript target. Do not edit.

import { KinsokuLevel } from "./KinsokuLevel.ts";
import { PunctuationClass } from "./PunctuationClass.ts";
import { PunctuationPolicy } from "./PunctuationPolicy.ts";
import { PunctuationWidthPolicy } from "./PunctuationWidthPolicy.ts";

export class ClreqPunctuationPolicies {
  private static readonly OPENING_UNITS: readonly number[] = [8220, 8216, 65288, 12298, 12296, 12300, 12302, 12304, 12308, 12310, 12312, 12314];
  private static readonly CLOSING_UNITS: readonly number[] = [8221, 8217, 65289, 12299, 12297, 12301, 12303, 12305, 12309, 12311, 12313, 12315];
  private static readonly PAUSE_OR_STOP_UNITS: readonly number[] = [65292, 12289, 12290, 65307, 65306, 65281, 65311];
  private static readonly INTERPUNCT_UNITS: readonly number[] = [12539, 8231, 8226];
  private static readonly CONNECTOR_UNITS: readonly number[] = [65374, 126, 45, 8211];
  private static readonly SOLIDUS_UNITS: readonly number[] = [47, 65295];
  private static readonly ELLIPSIS_UNITS: readonly number[] = [8230, 8943];
  private static readonly DASH_UNITS: readonly number[] = [8212, 11834];
  private static readonly SHORT_HYPHEN_CONNECTORS: readonly number[] = [45, 8211];
  private static readonly SENTENCE_END_STOPS: readonly number[] = [12290, 65281, 65311, 65294];
  private static readonly ASCII_POINT_MARKS: readonly number[] = [44, 46, 58, 59, 33, 63];

  public static isAsciiPointMark(char: string): boolean {
    return ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.ASCII_POINT_MARKS, (Number.isNaN(char.charCodeAt(0)) ? null : char.charCodeAt(0))!);
  }

  public static classify(char: string): PunctuationClass {
    const unit = (Number.isNaN(char.charCodeAt(0)) ? null : char.charCodeAt(0))!;
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.OPENING_UNITS, unit)) {
      return PunctuationClass.Opening;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.CLOSING_UNITS, unit)) {
      return PunctuationClass.Closing;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.PAUSE_OR_STOP_UNITS, unit)) {
      return PunctuationClass.PauseOrStop;
    }
    if (unit === 183) {
      return PunctuationClass.MiddleDot;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.INTERPUNCT_UNITS, unit)) {
      return PunctuationClass.Interpunct;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.CONNECTOR_UNITS, unit)) {
      return PunctuationClass.Connector;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.SOLIDUS_UNITS, unit)) {
      return PunctuationClass.Solidus;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.ELLIPSIS_UNITS, unit)) {
      return PunctuationClass.Ellipsis;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.DASH_UNITS, unit)) {
      return PunctuationClass.Dash;
    }
    return PunctuationClass.Other;
  }

  public static forcedHalfWidth(char: string, policy: PunctuationWidthPolicy): boolean {
    const unit = (Number.isNaN(char.charCodeAt(0)) ? null : char.charCodeAt(0))!;
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.SHORT_HYPHEN_CONNECTORS, unit)) {
      return true;
    }
    const cls = ClreqPunctuationPolicies.classify(char);
    if (policy.gbFixedSeparators && (cls.kind === "Connector" || cls.kind === "MiddleDot" || cls.kind === "Interpunct" || cls.kind === "Solidus")) {
      return true;
    }
    if (policy.interior.kind === "Kaiming") {
      if (cls.kind === "Opening" || cls.kind === "Closing") {
        return true;
      }
      if (cls.kind === "PauseOrStop" && !ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.SENTENCE_END_STOPS, unit)) {
        return true;
      }
    }
    return false;
  }

  public static policyFor(char: string): PunctuationPolicy {
    const punctuationClass = ClreqPunctuationPolicies.classify(char);
    return new PunctuationPolicy(punctuationClass, !ClreqPunctuationPolicies.forbiddenAtLineStart(char, KinsokuLevel.Basic), !ClreqPunctuationPolicies.forbiddenAtLineEnd(char, KinsokuLevel.Basic), ClreqPunctuationPolicies.defaultPunctuationBodyEm((Number.isNaN(char.charCodeAt(0)) ? null : char.charCodeAt(0))!, punctuationClass), ClreqPunctuationPolicies.defaultPunctuationAdvanceEm((Number.isNaN(char.charCodeAt(0)) ? null : char.charCodeAt(0))!, punctuationClass));
  }

  public static forbiddenAtLineStart(char: string, level: KinsokuLevel): boolean {
    if (level.kind === "None") {
      return false;
    }
    const cls = ClreqPunctuationPolicies.classify(char);
    if (cls.kind === "PauseOrStop" || cls.kind === "Closing" || cls.kind === "Connector" || cls.kind === "MiddleDot" || cls.kind === "Interpunct" || cls.kind === "Solidus") {
      return true;
    }
    if (cls.kind === "Dash" || cls.kind === "Ellipsis") {
      return level.kind === "Strict";
    }
    return false;
  }

  public static forbiddenAtLineEnd(char: string, level: KinsokuLevel): boolean {
    if (level.kind === "None") {
      return false;
    }
    const cls = ClreqPunctuationPolicies.classify(char);
    if (cls.kind === "Opening") {
      return true;
    }
    if (cls.kind === "Solidus") {
      return level.kind !== "Basic";
    }
    return false;
  }

  private static defaultPunctuationBodyEm(unit: number | null, punctuationClass: PunctuationClass): number {
    if (unit === 11834) {
      return 2.0;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.SHORT_HYPHEN_CONNECTORS, unit)) {
      return 0.5;
    }
    if (punctuationClass.kind === "PauseOrStop") {
      return 0.5;
    }
    if (punctuationClass.kind === "Closing") {
      return 0.5;
    }
    if (punctuationClass.kind === "Opening") {
      return 0.5;
    }
    return 1.0;
  }

  private static defaultPunctuationAdvanceEm(unit: number | null, punctuationClass: PunctuationClass): number {
    if (unit === 11834) {
      return 2.0;
    }
    if (ClreqPunctuationPolicies.containsUnit(ClreqPunctuationPolicies.SHORT_HYPHEN_CONNECTORS, unit)) {
      return 0.5;
    }
    return 1.0;
  }

  private static containsUnit(units: readonly number[], unit: number | null): boolean {
    let index = 0;
    while (index < units.length) {
      if (units[index]! === unit) {
        return true;
      }
      index += 1;
    }
    return false;
  }
}
