// Generated by the reflaxe TypeScript target. Do not edit.

import { CjkPunctuationGlyphPolicy } from "./CjkPunctuationGlyphPolicy.ts";
import { CjkPunctuationGlyphSubstitution } from "./CjkPunctuationGlyphSubstitution.ts";
import { UStringException } from "./../../../std/UStringException.ts";

export class ClreqPunctuationGlyphSubstitutor {
  private readonly policy: CjkPunctuationGlyphPolicy;
  private static readonly MIDLINE_ELLIPSIS: string = "⋯";
  private static readonly TWO_EM_DASH_SOURCE: string = "——";
  private static readonly TWO_EM_DASH: string = "⸺";
  private static readonly KATAKANA_MIDDLE_DOT: string = "・";
  private static readonly HYPHENATION_POINT: string = "‧";
  private static readonly BULLET: string = "•";
  private static readonly MIDDLE_DOT: string = "·";
  private static readonly HEX_UPPER: string = "0123456789ABCDEF";

  constructor(policy: CjkPunctuationGlyphPolicy | null = null) {
    this.policy = policy ?? (CjkPunctuationGlyphPolicy.PreferClreqRecommendedCodepoints as CjkPunctuationGlyphPolicy);
  }

  public substitute(sourceText: string): CjkPunctuationGlyphSubstitution {
    const displayText = (this.policy.kind === "PreserveInput" ? sourceText : ClreqPunctuationGlyphSubstitutor.toClreqRecommendedDisplayText(sourceText));
    const reason = (displayText === sourceText ? `CjkPunctuationGlyphPolicy:${this.policy.kind}:preserve` : `CjkPunctuationGlyphPolicy:${this.policy.kind}:${ClreqPunctuationGlyphSubstitutor.toCodePointLabels(sourceText)}->${ClreqPunctuationGlyphSubstitutor.toCodePointLabels(displayText)}`);
    return new CjkPunctuationGlyphSubstitution(sourceText, displayText, reason);
  }

  public toString(): string {
    return `ClreqPunctuationGlyphSubstitutor(policy=${this.policy.kind})`;
  }

  private static toClreqRecommendedDisplayText(text: string): string {
    let output = "";
    let index = 0;
    let allEllipsis = true;
    while (index < text.length) {
      if ((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))! !== 8230) {
        allEllipsis = false;
        break;
      }
      const tail = output.charCodeAt(output.length - 1);
      if (tail >= 55296 && tail <= 56319 && ClreqPunctuationGlyphSubstitutor.MIDLINE_ELLIPSIS.length > 0 && !(ClreqPunctuationGlyphSubstitutor.MIDLINE_ELLIPSIS.charCodeAt(0) >= 56320 && ClreqPunctuationGlyphSubstitutor.MIDLINE_ELLIPSIS.charCodeAt(0) <= 57343)) {
        throw new UStringException({ kind: "UnpairedSurrogate", unit: tail });
      }
      output += ClreqPunctuationGlyphSubstitutor.MIDLINE_ELLIPSIS;
      index += 1;
    }
    if (allEllipsis) {
      const tail2 = output.charCodeAt(output.length - 1);
      if (tail2 >= 55296 && tail2 <= 56319) {
        throw new UStringException({ kind: "UnpairedSurrogate", unit: tail2 });
      }
      return output;
    }
    if (text === ClreqPunctuationGlyphSubstitutor.TWO_EM_DASH_SOURCE) {
      return ClreqPunctuationGlyphSubstitutor.TWO_EM_DASH;
    }
    if (text === ClreqPunctuationGlyphSubstitutor.KATAKANA_MIDDLE_DOT || text === ClreqPunctuationGlyphSubstitutor.HYPHENATION_POINT || text === ClreqPunctuationGlyphSubstitutor.BULLET) {
      return ClreqPunctuationGlyphSubstitutor.MIDDLE_DOT;
    }
    return text;
  }

  private static toCodePointLabels(text: string): string {
    let output = "";
    let index = 0;
    while (index < text.length) {
      if (index > 0) {
        const tail3 = output.charCodeAt(output.length - 1);
        if (tail3 >= 55296 && tail3 <= 56319 && "+".length > 0 && !("+".charCodeAt(0) >= 56320 && "+".charCodeAt(0) <= 57343)) {
          throw new UStringException({ kind: "UnpairedSurrogate", unit: tail3 });
        }
        output += "+";
      }
      const tail4 = output.charCodeAt(output.length - 1);
      if (tail4 >= 55296 && tail4 <= 56319 && "U+".length > 0 && !("U+".charCodeAt(0) >= 56320 && "U+".charCodeAt(0) <= 57343)) {
        throw new UStringException({ kind: "UnpairedSurrogate", unit: tail4 });
      }
      output += "U+";
      const tail5 = output.charCodeAt(output.length - 1);
      if (tail5 >= 55296 && tail5 <= 56319 && ClreqPunctuationGlyphSubstitutor.hexLabel((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!).length > 0 && !(ClreqPunctuationGlyphSubstitutor.hexLabel((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!).charCodeAt(0) >= 56320 && ClreqPunctuationGlyphSubstitutor.hexLabel((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!).charCodeAt(0) <= 57343)) {
        throw new UStringException({ kind: "UnpairedSurrogate", unit: tail5 });
      }
      output += ClreqPunctuationGlyphSubstitutor.hexLabel((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!);
      index += 1;
    }
    const tail6 = output.charCodeAt(output.length - 1);
    if (tail6 >= 55296 && tail6 <= 56319) {
      throw new UStringException({ kind: "UnpairedSurrogate", unit: tail6 });
    }
    return output;
  }

  private static hexLabel(unit: number): string {
    return ClreqPunctuationGlyphSubstitutor.HEX_UPPER.substring((unit >>> 12) & 15, ((unit >>> 12) & 15) + 1) + ClreqPunctuationGlyphSubstitutor.HEX_UPPER.substring((unit >>> 8) & 15, ((unit >>> 8) & 15) + 1) + ClreqPunctuationGlyphSubstitutor.HEX_UPPER.substring((unit >>> 4) & 15, ((unit >>> 4) & 15) + 1) + ClreqPunctuationGlyphSubstitutor.HEX_UPPER.substring(unit & 15, (unit & 15) + 1);
  }
}
