// Generated by the reflaxe TypeScript target. Do not edit.

export interface FullWidth {
  readonly kind: "FullWidth"
}

export interface Kaiming {
  readonly kind: "Kaiming"
}

export type InteriorPunctuationStyle =
  | FullWidth
  | Kaiming;

export const InteriorPunctuationStyle = Object.freeze({
  FullWidth: Object.freeze({ kind: "FullWidth" } as FullWidth),
  Kaiming: Object.freeze({ kind: "Kaiming" } as Kaiming)
});

export function compareInteriorPunctuationStyle(a: InteriorPunctuationStyle, b: InteriorPunctuationStyle): number {
  if (a === b) return 0;
  if (a.kind === "FullWidth") return 0 - (b.kind === "FullWidth" ? 0 : 0);
  if (a.kind === "Kaiming") return 1 - (b.kind === "Kaiming" ? 1 : 0);
  return 0;
}
