// Generated by the reflaxe TypeScript target. Do not edit.

import { HangingPunctuationStyle } from "./HangingPunctuationStyle.ts";
import { KinsokuLevel } from "./KinsokuLevel.ts";
import { KinsokuMode } from "./KinsokuMode.ts";
import { ResolvedKinsoku } from "./ResolvedKinsoku.ts";

export class KinsokuModes {
  public static resolve(mode: KinsokuMode, measureEm: number): ResolvedKinsoku {
    switch (mode.kind) {
      case "Fixed":
      {
        return KinsokuModes.resolveFixed(mode.level, mode.hanging);
      }
      case "MeasureAdaptive":
      {
        return KinsokuModes.resolveMeasureAdaptive(measureEm, mode.hangBelowEm, mode.gbAboveEm, mode.strictAboveEm);
      }
    }
  }

  public static render(mode: KinsokuMode): string {
    switch (mode.kind) {
      case "Fixed":
      {
        return `Fixed(level=${mode.level.kind}, hanging=${mode.hanging.kind})`;
      }
      case "MeasureAdaptive":
      {
        return `MeasureAdaptive(hangBelowEm=${mode.hangBelowEm}, gbAboveEm=${mode.gbAboveEm}, strictAboveEm=${mode.strictAboveEm})`;
      }
    }
  }

  public static sameMode(a: KinsokuMode, b: KinsokuMode): boolean {
    switch (a.kind) {
      case "Fixed":
      {
        return KinsokuModes.sameFixed(a.level, a.hanging, b);
      }
      case "MeasureAdaptive":
      {
        return KinsokuModes.sameMeasureAdaptive(a.hangBelowEm, a.gbAboveEm, a.strictAboveEm, b);
      }
    }
  }

  private static resolveFixed(level: KinsokuLevel, hanging: HangingPunctuationStyle): ResolvedKinsoku {
    return new ResolvedKinsoku(level, hanging, `Fixed:${level.kind}${(hanging.kind !== "Disabled" ? "+Hang" : "")}`);
  }

  private static resolveMeasureAdaptive(measureEm: number, hangBelowEm: number, gbAboveEm: number, strictAboveEm: number): ResolvedKinsoku {
    const level = (measureEm > strictAboveEm ? KinsokuLevel.Strict : (measureEm > gbAboveEm ? KinsokuLevel.GbStyle : KinsokuLevel.Basic));
    const hanging = (measureEm < hangBelowEm ? HangingPunctuationStyle.PauseStops : HangingPunctuationStyle.Disabled);
    const tag = `MeasureAdaptiveKinsoku:${Math.trunc(measureEm)}字→${level.kind}${(hanging.kind !== "Disabled" ? "+Hang" : "")}`;
    return new ResolvedKinsoku(level, hanging, tag);
  }

  private static sameFixed(level: KinsokuLevel, hanging: HangingPunctuationStyle, b: KinsokuMode): boolean {
    switch (b.kind) {
      case "Fixed":
      {
        return level === b.level && hanging === b.hanging;
      }
      case "MeasureAdaptive":
        return false;
    }
  }

  private static sameMeasureAdaptive(hangBelowEm: number, gbAboveEm: number, strictAboveEm: number, b: KinsokuMode): boolean {
    switch (b.kind) {
      case "Fixed":
        return false;
      case "MeasureAdaptive":
      {
        return hangBelowEm === b.hangBelowEm && gbAboveEm === b.gbAboveEm && strictAboveEm === b.strictAboveEm;
      }
    }
  }
}
