// Generated by the reflaxe TypeScript target. Do not edit.

export interface None {
  readonly kind: "None"
}

export interface Basic {
  readonly kind: "Basic"
}

export interface GbStyle {
  readonly kind: "GbStyle"
}

export interface Strict {
  readonly kind: "Strict"
}

export type KinsokuLevel =
  | None
  | Basic
  | GbStyle
  | Strict;

export const KinsokuLevel = Object.freeze({
  None: Object.freeze({ kind: "None" } as None),
  Basic: Object.freeze({ kind: "Basic" } as Basic),
  GbStyle: Object.freeze({ kind: "GbStyle" } as GbStyle),
  Strict: Object.freeze({ kind: "Strict" } as Strict)
});

export function compareKinsokuLevel(a: KinsokuLevel, b: KinsokuLevel): number {
  if (a === b) return 0;
  if (a.kind === "None") return 0 - (b.kind === "None" ? 0 : 0);
  if (a.kind === "Basic") return 1 - (b.kind === "Basic" ? 1 : 0);
  if (a.kind === "GbStyle") return 2 - (b.kind === "GbStyle" ? 2 : 0);
  if (a.kind === "Strict") return 3 - (b.kind === "Strict" ? 3 : 0);
  return 0;
}
