// Generated by the reflaxe TypeScript target. Do not edit.

export interface PushInFirst {
  readonly kind: "PushInFirst"
}

export interface PushOutFirst {
  readonly kind: "PushOutFirst"
}

export interface PushOutOnly {
  readonly kind: "PushOutOnly"
}

export type LineAdjustmentStrategy =
  | PushInFirst
  | PushOutFirst
  | PushOutOnly;

export const LineAdjustmentStrategy = Object.freeze({
  PushInFirst: Object.freeze({ kind: "PushInFirst" } as PushInFirst),
  PushOutFirst: Object.freeze({ kind: "PushOutFirst" } as PushOutFirst),
  PushOutOnly: Object.freeze({ kind: "PushOutOnly" } as PushOutOnly)
});

export function compareLineAdjustmentStrategy(a: LineAdjustmentStrategy, b: LineAdjustmentStrategy): number {
  if (a === b) return 0;
  if (a.kind === "PushInFirst") return 0 - (b.kind === "PushInFirst" ? 0 : 0);
  if (a.kind === "PushOutFirst") return 1 - (b.kind === "PushOutFirst" ? 1 : 0);
  if (a.kind === "PushOutOnly") return 2 - (b.kind === "PushOutOnly" ? 2 : 0);
  return 0;
}
