// Generated by the reflaxe TypeScript target. Do not edit.

import { IntRange } from "./../core/IntRange.ts";
import { UnicodeNumberData } from "./../core/UnicodeNumberData.ts";
import { readUnit } from "../../../runtime.ts";

export class NumberSymbolCohesion {
  public static unbreakableRanges(text: string): IntRange[] {
    const result: IntRange[] = [];
    let i = 0;
    while (i < text.length) {
      if (!UnicodeNumberData.contains((Number.isNaN(text.charCodeAt(i)) ? null : text.charCodeAt(i))!)) {
        i += 1;
        continue;
      }
      let end = i;
      while (end + 1 < text.length) {
        const unit = readUnit(text, end + 1)!!;
        if (UnicodeNumberData.contains(unit)) {
          end += 1;
        } else {
          if ((unit === 46 || unit === 44) && end + 2 < text.length && UnicodeNumberData.contains(readUnit(text, end + 2)!)) {
            end += 2;
          } else {
            break;
          }
        }
      }
      let start = i;
      if (start > 0 && (NumberSymbolCohesion.isPrefixSign(readUnit(text, start - 1)!) || NumberSymbolCohesion.isFrontCurrency(readUnit(text, start - 1)!))) {
        start -= 1;
      }
      while (end + 1 < text.length && NumberSymbolCohesion.isSuffixUnit(readUnit(text, end + 1)!)) {
        end += 1;
      }
      if (end + 1 < text.length && NumberSymbolCohesion.isBackCurrency(readUnit(text, end + 1)!)) {
        end += 1;
      }
      result.push(new IntRange(start, end));
      i = end + 1;
    }
    return result;
  }

  private static isPrefixSign(unit: number): boolean {
    return unit === 43 || unit === 45 || unit === 177;
  }

  private static isSuffixUnit(unit: number): boolean {
    return unit === 37 || unit === 8240 || unit === 176 || unit === 8451 || unit === 8457 || unit === 8242 || unit === 8243;
  }

  private static isFrontCurrency(unit: number): boolean {
    return unit === 165 || unit === 65509 || unit === 36 || unit === 65284 || unit === 8364 || unit === 163 || unit === 8361 || unit === 8381 || unit === 8377 || unit === 3647;
  }

  private static isBackCurrency(unit: number): boolean {
    return unit === 8363;
  }
}
