// Generated by the reflaxe TypeScript target. Do not edit.

export interface Opening {
  readonly kind: "Opening"
}

export interface Closing {
  readonly kind: "Closing"
}

export interface PauseOrStop {
  readonly kind: "PauseOrStop"
}

export interface MiddleDot {
  readonly kind: "MiddleDot"
}

export interface Interpunct {
  readonly kind: "Interpunct"
}

export interface Connector {
  readonly kind: "Connector"
}

export interface Solidus {
  readonly kind: "Solidus"
}

export interface Ellipsis {
  readonly kind: "Ellipsis"
}

export interface Dash {
  readonly kind: "Dash"
}

export interface Other {
  readonly kind: "Other"
}

export type PunctuationClass =
  | Opening
  | Closing
  | PauseOrStop
  | MiddleDot
  | Interpunct
  | Connector
  | Solidus
  | Ellipsis
  | Dash
  | Other;

export const PunctuationClass = Object.freeze({
  Opening: Object.freeze({ kind: "Opening" } as Opening),
  Closing: Object.freeze({ kind: "Closing" } as Closing),
  PauseOrStop: Object.freeze({ kind: "PauseOrStop" } as PauseOrStop),
  MiddleDot: Object.freeze({ kind: "MiddleDot" } as MiddleDot),
  Interpunct: Object.freeze({ kind: "Interpunct" } as Interpunct),
  Connector: Object.freeze({ kind: "Connector" } as Connector),
  Solidus: Object.freeze({ kind: "Solidus" } as Solidus),
  Ellipsis: Object.freeze({ kind: "Ellipsis" } as Ellipsis),
  Dash: Object.freeze({ kind: "Dash" } as Dash),
  Other: Object.freeze({ kind: "Other" } as Other)
});

export function comparePunctuationClass(a: PunctuationClass, b: PunctuationClass): number {
  if (a === b) return 0;
  if (a.kind === "Opening") return 0 - (b.kind === "Opening" ? 0 : 0);
  if (a.kind === "Closing") return 1 - (b.kind === "Closing" ? 1 : 0);
  if (a.kind === "PauseOrStop") return 2 - (b.kind === "PauseOrStop" ? 2 : 0);
  if (a.kind === "MiddleDot") return 3 - (b.kind === "MiddleDot" ? 3 : 0);
  if (a.kind === "Interpunct") return 4 - (b.kind === "Interpunct" ? 4 : 0);
  if (a.kind === "Connector") return 5 - (b.kind === "Connector" ? 5 : 0);
  if (a.kind === "Solidus") return 6 - (b.kind === "Solidus" ? 6 : 0);
  if (a.kind === "Ellipsis") return 7 - (b.kind === "Ellipsis" ? 7 : 0);
  if (a.kind === "Dash") return 8 - (b.kind === "Dash" ? 8 : 0);
  if (a.kind === "Other") return 9 - (b.kind === "Other" ? 9 : 0);
  return 0;
}
