// Generated by the reflaxe TypeScript target. Do not edit.

export interface RawTables {
  readonly kind: "RawTables"
}

export interface OpenTypeBase {
  readonly kind: "OpenTypeBase"
}

export interface GlyphSampling {
  readonly kind: "GlyphSampling"
}

export interface ManualOverride {
  readonly kind: "ManualOverride"
}

export interface SynthesizedIdeographicBox {
  readonly kind: "SynthesizedIdeographicBox"
}

export type FontMetricSource =
  | RawTables
  | OpenTypeBase
  | GlyphSampling
  | ManualOverride
  | SynthesizedIdeographicBox;

export const FontMetricSource = Object.freeze({
  RawTables: Object.freeze({ kind: "RawTables" } as RawTables),
  OpenTypeBase: Object.freeze({ kind: "OpenTypeBase" } as OpenTypeBase),
  GlyphSampling: Object.freeze({ kind: "GlyphSampling" } as GlyphSampling),
  ManualOverride: Object.freeze({ kind: "ManualOverride" } as ManualOverride),
  SynthesizedIdeographicBox: Object.freeze({ kind: "SynthesizedIdeographicBox" } as SynthesizedIdeographicBox)
});

export function compareFontMetricSource(a: FontMetricSource, b: FontMetricSource): number {
  if (a === b) return 0;
  if (a.kind === "RawTables") return 0 - (b.kind === "RawTables" ? 0 : 0);
  if (a.kind === "OpenTypeBase") return 1 - (b.kind === "OpenTypeBase" ? 1 : 0);
  if (a.kind === "GlyphSampling") return 2 - (b.kind === "GlyphSampling" ? 2 : 0);
  if (a.kind === "ManualOverride") return 3 - (b.kind === "ManualOverride" ? 3 : 0);
  if (a.kind === "SynthesizedIdeographicBox") return 4 - (b.kind === "SynthesizedIdeographicBox" ? 4 : 0);
  return 0;
}
