// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./../core/TextRange.ts";
import { FontRole } from "./FontRole.ts";

export class FontRoleContext {
  public readonly locale: string;
  public readonly regionHint: string | null;

  constructor(locale: string | null = null, regionHint?: string | null) {
    this.locale = locale ?? "zh-Hans";
    this.regionHint = regionHint;
  }

  public toString(): string {
    return `FontRoleContext(locale=${this.locale}, regionHint=${this.regionHint})`;
  }
}

export function compareFontRoleContext(a: FontRoleContext, b: FontRoleContext): number {
  if (a === b) return 0;
  if (a.locale !== b.locale) return a.locale < b.locale ? -1 : 1;
  if (a.regionHint === null && b.regionHint !== null) return -1;
  if (a.regionHint !== null && b.regionHint === null) return 1;
  if (a.regionHint !== null && b.regionHint !== null && a.regionHint !== b.regionHint) return a.regionHint < b.regionHint ? -1 : 1;
  return 0;
}

export type FontRoleClassifierClassifyFn = (text: string, range: TextRange, context?: FontRoleContext | null) => FontRole;

export interface FontRoleClassifier {
  readonly classify: FontRoleClassifierClassifyFn;
}
