// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./../core/TextRange.ts";
import type { FallbackResolver } from "./FontPolicy.ts";
import { FontCandidate, FontDecision, FontRequest } from "./FontPolicy.ts";

export class PreferCjkForAmbiguousPunctuationResolver implements FallbackResolver {
  private readonly cjkFontKey: string;
  private readonly latinFontKey: string;
  private readonly symbolFontKey: string;

  constructor(cjkFontKey: string | null = null, latinFontKey: string | null = null, symbolFontKey: string | null = null) {
    this.cjkFontKey = cjkFontKey ?? "cjk-primary";
    this.latinFontKey = latinFontKey ?? "latin-primary";
    this.symbolFontKey = symbolFontKey ?? "symbol-fallback";
  }

  public resolve(text: string, range: TextRange, request: FontRequest): FontDecision {
    const c = PreferCjkForAmbiguousPunctuationResolver.candidateFor(request, this.cjkFontKey, this.latinFontKey, this.symbolFontKey);
    return new FontDecision(range, c, request.role, `PreferCjkForAmbiguousPunctuationResolver:${request.role.kind}`);
  }

  private static candidateFor(request: FontRequest, cjkFontKey: string, latinFontKey: string, symbolFontKey: string): FontCandidate {
    const role = request.role;
    switch (role.kind) {
      case "CjkText":
      case "CjkPunctuation":
        return new FontCandidate(cjkFontKey, (request.preferredFamilies.length === 0 ? cjkFontKey : request.preferredFamilies[0]!), request.role);
      case "LatinText":
        return new FontCandidate(latinFontKey, latinFontKey, request.role);
      case "Symbol":
      case "Emoji":
      case "Unknown":
        return new FontCandidate(symbolFontKey, symbolFontKey, request.role);
    }
  }
}
