// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class AutoSpaceDecisionInfo {
  public readonly clusterRange: TextRange;
  public readonly side: string;
  public readonly boundaryRole: string;
  public readonly mode: string;
  public readonly charactersAffected: number;
  public readonly reductionPerChar: number;
  public readonly totalReduction: number;
  public readonly reason: string;

  constructor(clusterRange: TextRange, side: string, boundaryRole: string, mode: string, charactersAffected: number, reductionPerChar: number, totalReduction: number, reason: string) {
    this.clusterRange = clusterRange;
    this.side = side;
    this.boundaryRole = boundaryRole;
    this.mode = mode;
    this.charactersAffected = charactersAffected;
    this.reductionPerChar = reductionPerChar;
    this.totalReduction = totalReduction;
    this.reason = reason;
  }

  public toString(): string {
    return `AutoSpaceDecisionInfo(clusterRange=${this.clusterRange.toString()}, side=${this.side}, boundaryRole=${this.boundaryRole}, mode=${this.mode}, charactersAffected=${this.charactersAffected}, reductionPerChar=${this.reductionPerChar}, totalReduction=${this.totalReduction}, reason=${this.reason})`;
  }
}
