// Generated by the reflaxe TypeScript target. Do not edit.

import { BopomofoGlyphRole } from "./BopomofoGlyphRole.ts";
import { Glyph } from "./Glyph.ts";

export class BopomofoGlyphPlacement {
  public readonly text: string;
  public readonly left: number;
  public readonly top: number;
  public readonly width: number;
  public readonly height: number;
  public readonly role: BopomofoGlyphRole;
  public readonly glyphs: readonly Glyph[];
  public readonly drawX: number;
  public readonly baselineY: number;
  public readonly fontSize: number;

  constructor(text: string, left: number, top: number, width: number, height: number, role: BopomofoGlyphRole, glyphs: Glyph[] | null = null, drawX: number, baselineY: number, fontSize: number) {
    this.text = text;
    this.left = left;
    this.top = top;
    this.width = width;
    this.height = height;
    this.role = role;
    this.glyphs = glyphs ?? [];
    this.drawX = drawX;
    this.baselineY = baselineY;
    this.fontSize = fontSize;
  }

  public toString(): string {
    return `BopomofoGlyphPlacement(text=${this.text}, left=${this.left}, top=${this.top}, width=${this.width}, height=${this.height}, role=${this.role.kind}, glyphs=${(() => { let out = "["; const n = this.glyphs.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.glyphs[i]!.toString(); } out += "]"; return out; })()}, drawX=${this.drawX}, baselineY=${this.baselineY}, fontSize=${this.fontSize})`;
  }
}
