// Generated by the reflaxe TypeScript target. Do not edit.

import { BopomofoGlyphPlacement } from "./BopomofoGlyphPlacement.ts";
import { TextRange } from "./TextRange.ts";

export class BopomofoDecisionInfo {
  public readonly baseRange: TextRange;
  public readonly text: string;
  public readonly lineIndex: number;
  public readonly placements: readonly BopomofoGlyphPlacement[];
  public readonly fontFamilies: readonly string[];
  public readonly fontWeight: number;
  public readonly locale: string;

  constructor(baseRange: TextRange, text: string, lineIndex: number, placements: BopomofoGlyphPlacement[], fontFamilies: string[] | null = null, fontWeight: number | null = null, locale: string | null = null) {
    this.baseRange = baseRange;
    this.text = text;
    this.lineIndex = lineIndex;
    this.placements = placements;
    this.fontFamilies = fontFamilies ?? [];
    this.fontWeight = fontWeight ?? 400;
    this.locale = locale ?? "zh-Hans";
  }

  public toString(): string {
    return `BopomofoDecisionInfo(baseRange=${this.baseRange.toString()}, text=${this.text}, lineIndex=${this.lineIndex}, placements=${(() => { let out = "["; const n = this.placements.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.placements[i]!.toString(); } out += "]"; return out; })()}, fontFamilies=${(() => { let out = "["; const n = this.fontFamilies.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.fontFamilies[i]!; } out += "]"; return out; })()}, fontWeight=${this.fontWeight}, locale=${this.locale})`;
  }
}
