// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class Cluster {
  public readonly range: TextRange;
  public readonly text: string;
  public readonly displayText: string;
  public readonly fontKey: string;
  public readonly advance: number;
  public readonly baselineShift: number;
  public readonly leadingLayoutAdvance: number;
  public readonly glyphInlineShift: number;

  constructor(range: TextRange, text: string, fontKey: string, advance: number, displayText: string | null = null, baselineShift: number | null = null, leadingLayoutAdvance: number | null = null, glyphInlineShift: number | null = null) {
    this.range = range;
    this.text = text;
    this.displayText = displayText ?? text;
    this.fontKey = fontKey;
    this.advance = advance;
    this.baselineShift = baselineShift ?? 0.0;
    this.leadingLayoutAdvance = leadingLayoutAdvance ?? 0.0;
    this.glyphInlineShift = glyphInlineShift ?? 0.0;
  }

  public toString(): string {
    return `Cluster(range=${this.range.toString()}, text=${this.text}, displayText=${this.displayText}, fontKey=${this.fontKey}, advance=${this.advance}, baselineShift=${this.baselineShift}, leadingLayoutAdvance=${this.leadingLayoutAdvance}, glyphInlineShift=${this.glyphInlineShift})`;
  }
}
