// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange, compareTextRange } from "./TextRange.ts";

export class ContextualKinsokuDecisionInfo {
  public readonly range: TextRange;
  public readonly sourceText: string;
  public readonly clusterIndex: number;
  public readonly forbiddenPosition: string;
  public readonly reason: string;
  public readonly impossibleMeasureFallback: string | null;

  constructor(range: TextRange, sourceText: string, clusterIndex: number, forbiddenPosition: string, reason: string, impossibleMeasureFallback: string | null = null) {
    this.range = range;
    this.sourceText = sourceText;
    this.clusterIndex = clusterIndex;
    this.forbiddenPosition = forbiddenPosition;
    this.reason = reason;
    this.impossibleMeasureFallback = impossibleMeasureFallback ?? null;
  }

  public toString(): string {
    return `ContextualKinsokuDecisionInfo(range=${this.range.toString()}, sourceText=${this.sourceText}, clusterIndex=${this.clusterIndex}, forbiddenPosition=${this.forbiddenPosition}, reason=${this.reason}, impossibleMeasureFallback=${this.impossibleMeasureFallback})`;
  }
}

export function compareContextualKinsokuDecisionInfo(a: ContextualKinsokuDecisionInfo, b: ContextualKinsokuDecisionInfo): number {
  if (a === b) return 0;
  { const cmp = compareTextRange(a.range, b.range); if (cmp !== 0) return cmp; }
  if (a.sourceText !== b.sourceText) return a.sourceText < b.sourceText ? -1 : 1;
  if (a.clusterIndex !== b.clusterIndex) return a.clusterIndex - b.clusterIndex;
  if (a.forbiddenPosition !== b.forbiddenPosition) return a.forbiddenPosition < b.forbiddenPosition ? -1 : 1;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  if (a.impossibleMeasureFallback === null && b.impossibleMeasureFallback !== null) return -1;
  if (a.impossibleMeasureFallback !== null && b.impossibleMeasureFallback === null) return 1;
  if (a.impossibleMeasureFallback !== null && b.impossibleMeasureFallback !== null && a.impossibleMeasureFallback !== b.impossibleMeasureFallback) return a.impossibleMeasureFallback < b.impossibleMeasureFallback ? -1 : 1;
  return 0;
}
