// Generated by the reflaxe TypeScript target. Do not edit.

import { DecorationKind } from "./DecorationKind.ts";
import { TextRange, compareTextRange } from "./TextRange.ts";

export class DecorationSpan {
  public readonly range: TextRange;
  public readonly kind: DecorationKind;

  constructor(range: TextRange, kind: DecorationKind) {
    this.range = range;
    this.kind = kind;
  }

  public toString(): string {
    return `DecorationSpan(range=${this.range.toString()}, kind=${this.kind.kind})`;
  }
}

export function DecorationSpankindOrder(v: DecorationKind): number {
  if (v.kind === "ProperNoun") return 2;
  if (v.kind === "Mourning") return 1;
  if (v.kind === "Emphasis") return 0;
  if (v.kind === "BookTitle") return 3;
  return 0;
}

export function compareDecorationSpan(a: DecorationSpan, b: DecorationSpan): number {
  if (a === b) return 0;
  { const cmp = compareTextRange(a.range, b.range); if (cmp !== 0) return cmp; }
  if (DecorationSpankindOrder(a.kind) !== DecorationSpankindOrder(b.kind)) return DecorationSpankindOrder(a.kind) - DecorationSpankindOrder(b.kind);
  return 0;
}
