// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange, compareTextRange } from "./TextRange.ts";

export class EmergencyTrackingEligibilityDecisionInfo {
  public readonly range: TextRange;
  public readonly sourceText: string;
  public readonly reason: string;

  constructor(range: TextRange, sourceText: string, reason: string) {
    this.range = range;
    this.sourceText = sourceText;
    this.reason = reason;
  }

  public toString(): string {
    return `EmergencyTrackingEligibilityDecisionInfo(range=${this.range.toString()}, sourceText=${this.sourceText}, reason=${this.reason})`;
  }
}

export function compareEmergencyTrackingEligibilityDecisionInfo(a: EmergencyTrackingEligibilityDecisionInfo, b: EmergencyTrackingEligibilityDecisionInfo): number {
  if (a === b) return 0;
  { const cmp = compareTextRange(a.range, b.range); if (cmp !== 0) return cmp; }
  if (a.sourceText !== b.sourceText) return a.sourceText < b.sourceText ? -1 : 1;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  return 0;
}
