// Generated by the reflaxe TypeScript target. Do not edit.

export class FirstLineIndentDecisionInfo {
  public readonly source: string;
  public readonly measureEm: number;
  public readonly thresholdEm: number;
  public readonly resolvedEm: number;

  constructor(source: string, measureEm: number, thresholdEm: number, resolvedEm: number) {
    this.source = source;
    this.measureEm = measureEm;
    this.thresholdEm = thresholdEm;
    this.resolvedEm = resolvedEm;
  }

  public toString(): string {
    return `FirstLineIndentDecisionInfo(source=${this.source}, measureEm=${this.measureEm}, thresholdEm=${this.thresholdEm}, resolvedEm=${this.resolvedEm})`;
  }
}
