// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange, compareTextRange } from "./TextRange.ts";

export class FontDecisionInfo {
  public readonly range: TextRange;
  public readonly sourceText: string;
  public readonly displayText: string;
  public readonly role: string;
  public readonly fontKey: string;
  public readonly reason: string;
  public readonly substitutionReason: string;

  constructor(range: TextRange, sourceText: string, displayText: string, role: string, fontKey: string, reason: string, substitutionReason: string) {
    this.range = range;
    this.sourceText = sourceText;
    this.displayText = displayText;
    this.role = role;
    this.fontKey = fontKey;
    this.reason = reason;
    this.substitutionReason = substitutionReason;
  }

  public toString(): string {
    return `FontDecisionInfo(range=${this.range.toString()}, sourceText=${this.sourceText}, displayText=${this.displayText}, role=${this.role}, fontKey=${this.fontKey}, reason=${this.reason}, substitutionReason=${this.substitutionReason})`;
  }
}

export function compareFontDecisionInfo(a: FontDecisionInfo, b: FontDecisionInfo): number {
  if (a === b) return 0;
  { const cmp = compareTextRange(a.range, b.range); if (cmp !== 0) return cmp; }
  if (a.sourceText !== b.sourceText) return a.sourceText < b.sourceText ? -1 : 1;
  if (a.displayText !== b.displayText) return a.displayText < b.displayText ? -1 : 1;
  if (a.role !== b.role) return a.role < b.role ? -1 : 1;
  if (a.fontKey !== b.fontKey) return a.fontKey < b.fontKey ? -1 : 1;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  if (a.substitutionReason !== b.substitutionReason) return a.substitutionReason < b.substitutionReason ? -1 : 1;
  return 0;
}
