// Generated by the reflaxe TypeScript target. Do not edit.

import { Glyph } from "./Glyph.ts";
import { TextRange } from "./TextRange.ts";

export class GlyphRun {
  public readonly range: TextRange;
  public readonly fontKey: string;
  public readonly glyphs: readonly Glyph[];
  public readonly advance: number;
  public readonly openTypeFeatures: readonly string[];

  constructor(range: TextRange, fontKey: string, glyphs: Glyph[], advance: number, openTypeFeatures: string[] | null = null) {
    this.range = range;
    this.fontKey = fontKey;
    this.glyphs = glyphs;
    this.advance = advance;
    this.openTypeFeatures = openTypeFeatures ?? [];
  }

  public toString(): string {
    return `GlyphRun(range=${this.range.toString()}, fontKey=${this.fontKey}, glyphs=${(() => { let out = "["; const n = this.glyphs.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.glyphs[i]!.toString(); } out += "]"; return out; })()}, advance=${this.advance}, openTypeFeatures=${(() => { let out = "["; const n = this.openTypeFeatures.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.openTypeFeatures[i]!; } out += "]"; return out; })()})`;
  }
}
