// Generated by the reflaxe TypeScript target. Do not edit.

import { InlineObjectBoundaryAdjustment } from "./InlineObjectBoundaryAdjustment.ts";
import { TextRange } from "./TextRange.ts";

export class InlineObjectSpan {
  public readonly range: TextRange;
  public readonly advance: number;
  public readonly ascent: number;
  public readonly descent: number;
  public readonly leadingBoundary: InlineObjectBoundaryAdjustment;
  public readonly trailingBoundary: InlineObjectBoundaryAdjustment;
  public static readonly INLINE_OBJECT_REPLACEMENT_CHAR: string = "￼";

  constructor(range: TextRange, advance: number, ascent: number, descent: number, leadingBoundary: InlineObjectBoundaryAdjustment | null = null, trailingBoundary: InlineObjectBoundaryAdjustment | null = null) {
    this.range = range;
    this.advance = advance;
    this.ascent = ascent;
    this.descent = descent;
    this.leadingBoundary = leadingBoundary ?? InlineObjectBoundaryAdjustment.fixed();
    this.trailingBoundary = trailingBoundary ?? InlineObjectBoundaryAdjustment.fixed();
  }

  public toString(): string {
    return `InlineObjectSpan(range=${this.range.toString()}, advance=${this.advance}, ascent=${this.ascent}, descent=${this.descent}, leadingBoundary=${this.leadingBoundary.toString()}, trailingBoundary=${this.trailingBoundary.toString()})`;
  }
}
