// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class InlineBoxDecisionInfo {
  public readonly range: TextRange;
  public readonly inlineStart: number;
  public readonly inlineEnd: number;
  public readonly outerSpacing: string;
  public readonly firstClusterIndex: number;
  public readonly lastClusterIndex: number;
  public readonly reason: string;

  constructor(range: TextRange, inlineStart: number, inlineEnd: number, outerSpacing: string, firstClusterIndex: number, lastClusterIndex: number, reason: string | null = null) {
    this.range = range;
    this.inlineStart = inlineStart;
    this.inlineEnd = inlineEnd;
    this.outerSpacing = outerSpacing;
    this.firstClusterIndex = firstClusterIndex;
    this.lastClusterIndex = lastClusterIndex;
    this.reason = reason ?? "InlineBoxBoundaryAdvance";
  }

  public toString(): string {
    return `InlineBoxDecisionInfo(range=${this.range.toString()}, inlineStart=${this.inlineStart}, inlineEnd=${this.inlineEnd}, outerSpacing=${this.outerSpacing}, firstClusterIndex=${this.firstClusterIndex}, lastClusterIndex=${this.lastClusterIndex}, reason=${this.reason})`;
  }
}
