// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class InlineObjectDecisionInfo {
  public readonly range: TextRange;
  public readonly advance: number;
  public readonly ascent: number;
  public readonly descent: number;
  public readonly clusterIndex: number;
  public readonly lineIndex: number;
  public readonly leadingUniformStretch: boolean;
  public readonly leadingPreferredStretchKind: string | null;
  public readonly leadingPreferredStretchNaturalWidth: number;
  public readonly leadingPreferredStretchTargetWidth: number;
  public readonly leadingPreferredStretchCapacity: number;
  public readonly leadingPreventsLineBreak: boolean;
  public readonly leadingShrinkCapacity: number;
  public readonly leadingLineEndDiscardableAdvance: number;
  public readonly trailingUniformStretch: boolean;
  public readonly trailingPreferredStretchKind: string | null;
  public readonly trailingPreferredStretchNaturalWidth: number;
  public readonly trailingPreferredStretchTargetWidth: number;
  public readonly trailingPreferredStretchCapacity: number;
  public readonly trailingPreventsLineBreak: boolean;
  public readonly trailingShrinkCapacity: number;
  public readonly trailingLineEndDiscardableAdvance: number;
  public readonly reason: string;

  constructor(range: TextRange, advance: number, ascent: number, descent: number, clusterIndex: number, lineIndex: number, leadingUniformStretch: boolean | null = null, leadingPreferredStretchKind: string | null = null, leadingPreferredStretchNaturalWidth: number | null = null, leadingPreferredStretchTargetWidth: number | null = null, leadingPreferredStretchCapacity: number | null = null, leadingPreventsLineBreak: boolean | null = null, leadingShrinkCapacity: number | null = null, leadingLineEndDiscardableAdvance: number | null = null, trailingUniformStretch: boolean | null = null, trailingPreferredStretchKind: string | null = null, trailingPreferredStretchNaturalWidth: number | null = null, trailingPreferredStretchTargetWidth: number | null = null, trailingPreferredStretchCapacity: number | null = null, trailingPreventsLineBreak: boolean | null = null, trailingShrinkCapacity: number | null = null, trailingLineEndDiscardableAdvance: number | null = null, reason: string | null = null) {
    this.range = range;
    this.advance = advance;
    this.ascent = ascent;
    this.descent = descent;
    this.clusterIndex = clusterIndex;
    this.lineIndex = lineIndex;
    this.leadingUniformStretch = leadingUniformStretch ?? false;
    this.leadingPreferredStretchKind = leadingPreferredStretchKind ?? null;
    this.leadingPreferredStretchNaturalWidth = leadingPreferredStretchNaturalWidth ?? 0.0;
    this.leadingPreferredStretchTargetWidth = leadingPreferredStretchTargetWidth ?? 0.0;
    this.leadingPreferredStretchCapacity = leadingPreferredStretchCapacity ?? 0.0;
    this.leadingPreventsLineBreak = leadingPreventsLineBreak ?? false;
    this.leadingShrinkCapacity = leadingShrinkCapacity ?? 0.0;
    this.leadingLineEndDiscardableAdvance = leadingLineEndDiscardableAdvance ?? 0.0;
    this.trailingUniformStretch = trailingUniformStretch ?? false;
    this.trailingPreferredStretchKind = trailingPreferredStretchKind ?? null;
    this.trailingPreferredStretchNaturalWidth = trailingPreferredStretchNaturalWidth ?? 0.0;
    this.trailingPreferredStretchTargetWidth = trailingPreferredStretchTargetWidth ?? 0.0;
    this.trailingPreferredStretchCapacity = trailingPreferredStretchCapacity ?? 0.0;
    this.trailingPreventsLineBreak = trailingPreventsLineBreak ?? false;
    this.trailingShrinkCapacity = trailingShrinkCapacity ?? 0.0;
    this.trailingLineEndDiscardableAdvance = trailingLineEndDiscardableAdvance ?? 0.0;
    this.reason = reason ?? "MeasurableOpaqueInlineObject";
  }

  public toString(): string {
    return `InlineObjectDecisionInfo(range=${this.range.toString()}, advance=${this.advance}, ascent=${this.ascent}, descent=${this.descent}, clusterIndex=${this.clusterIndex}, lineIndex=${this.lineIndex}, leadingUniformStretch=${this.leadingUniformStretch}, leadingPreferredStretchKind=${this.leadingPreferredStretchKind}, leadingPreferredStretchNaturalWidth=${this.leadingPreferredStretchNaturalWidth}, leadingPreferredStretchTargetWidth=${this.leadingPreferredStretchTargetWidth}, leadingPreferredStretchCapacity=${this.leadingPreferredStretchCapacity}, leadingPreventsLineBreak=${this.leadingPreventsLineBreak}, leadingShrinkCapacity=${this.leadingShrinkCapacity}, leadingLineEndDiscardableAdvance=${this.leadingLineEndDiscardableAdvance}, trailingUniformStretch=${this.trailingUniformStretch}, trailingPreferredStretchKind=${this.trailingPreferredStretchKind}, trailingPreferredStretchNaturalWidth=${this.trailingPreferredStretchNaturalWidth}, trailingPreferredStretchTargetWidth=${this.trailingPreferredStretchTargetWidth}, trailingPreferredStretchCapacity=${this.trailingPreferredStretchCapacity}, trailingPreventsLineBreak=${this.trailingPreventsLineBreak}, trailingShrinkCapacity=${this.trailingShrinkCapacity}, trailingLineEndDiscardableAdvance=${this.trailingLineEndDiscardableAdvance}, reason=${this.reason})`;
  }
}
