// Generated by the reflaxe TypeScript target. Do not edit.

import { InlineObjectPreferredStretchKind } from "./InlineObjectPreferredStretchKind.ts";
import { TextRangeError } from "./TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";

export class InlineObjectPreferredStretch {
  public readonly kind: InlineObjectPreferredStretchKind;
  public readonly naturalWidth: number;
  public readonly targetWidth: number;

  constructor(kind: InlineObjectPreferredStretchKind, naturalWidth: number, targetWidth: number) {
    if (!InlineObjectPreferredStretch.isFinite(naturalWidth) || naturalWidth < 0.0) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Inline-object preferred stretch natural width must be finite and non-negative" } as TextRangeError));
    }
    if (!InlineObjectPreferredStretch.isFinite(targetWidth) || targetWidth <= naturalWidth) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Inline-object preferred stretch target must be finite and exceed its natural width" } as TextRangeError));
    }
    this.kind = kind;
    this.naturalWidth = naturalWidth;
    this.targetWidth = targetWidth;
  }

  public get capacity(): number {
    return this.get_capacity();
  }
  public get_capacity(): number {
    return this.targetWidth - this.naturalWidth;
  }

  public toString(): string {
    return `InlineObjectPreferredStretch(kind=${this.kind.kind}, naturalWidth=${this.naturalWidth}, targetWidth=${this.targetWidth})`;
  }

  private static isFinite(value: number): boolean {
    return value === value && value !== Infinity && value !== -Infinity;
  }
}
