// Generated by the reflaxe TypeScript target. Do not edit.

import { formatFloatRuntime } from "../../../runtime.ts";

export class InlineObjectLineHeightDecisionInfo {
  public readonly baseLineHeight: number;
  public readonly baseFaceAscent: number;
  public readonly baseFaceDescent: number;
  public readonly availableInterlineSpace: number;
  public readonly minimumClearance: number;
  public readonly lineAscents: readonly number[];
  public readonly lineDescents: readonly number[];
  public readonly lineExtras: readonly number[];
  public readonly boundaryShiftsAfter: readonly number[];
  public readonly trailingExtra: number;
  public readonly expandedLineIndices: readonly number[];
  public readonly reason: string;

  constructor(baseLineHeight: number, baseFaceAscent: number, baseFaceDescent: number, availableInterlineSpace: number, minimumClearance: number, lineAscents: number[], lineDescents: number[], lineExtras: number[], boundaryShiftsAfter: number[], trailingExtra: number, expandedLineIndices: number[], reason: string) {
    this.baseLineHeight = baseLineHeight;
    this.baseFaceAscent = baseFaceAscent;
    this.baseFaceDescent = baseFaceDescent;
    this.availableInterlineSpace = availableInterlineSpace;
    this.minimumClearance = minimumClearance;
    this.lineAscents = lineAscents;
    this.lineDescents = lineDescents;
    this.lineExtras = lineExtras;
    this.boundaryShiftsAfter = boundaryShiftsAfter;
    this.trailingExtra = trailingExtra;
    this.expandedLineIndices = expandedLineIndices;
    this.reason = reason;
  }

  public toString(): string {
    return `InlineObjectLineHeightDecisionInfo(baseLineHeight=${this.baseLineHeight}, baseFaceAscent=${this.baseFaceAscent}, baseFaceDescent=${this.baseFaceDescent}, availableInterlineSpace=${this.availableInterlineSpace}, minimumClearance=${this.minimumClearance}, lineAscents=${(() => { let out = "["; const n = this.lineAscents.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.lineAscents[i]!; } out += "]"; return out; })()}, lineDescents=${(() => { let out = "["; const n = this.lineDescents.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.lineDescents[i]!; } out += "]"; return out; })()}, lineExtras=${(() => { let out = "["; const n = this.lineExtras.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.lineExtras[i]!; } out += "]"; return out; })()}, boundaryShiftsAfter=${(() => { let out = "["; const n = this.boundaryShiftsAfter.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.boundaryShiftsAfter[i]!; } out += "]"; return out; })()}, trailingExtra=${this.trailingExtra}, expandedLineIndices=${(() => { let out = "["; const n = this.expandedLineIndices.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.expandedLineIndices[i]!; } out += "]"; return out; })()}, reason=${this.reason})`;
  }
}
