// Generated by the reflaxe TypeScript target. Do not edit.

export interface PunctuationTrailing {
  readonly kind: "PunctuationTrailing"
}

export interface Relation {
  readonly kind: "Relation"
}

export interface BinaryOperator {
  readonly kind: "BinaryOperator"
}

export type InlineObjectPreferredStretchKind =
  | PunctuationTrailing
  | Relation
  | BinaryOperator;

export const InlineObjectPreferredStretchKind = Object.freeze({
  PunctuationTrailing: Object.freeze({ kind: "PunctuationTrailing" } as PunctuationTrailing),
  Relation: Object.freeze({ kind: "Relation" } as Relation),
  BinaryOperator: Object.freeze({ kind: "BinaryOperator" } as BinaryOperator)
});

export function compareInlineObjectPreferredStretchKind(a: InlineObjectPreferredStretchKind, b: InlineObjectPreferredStretchKind): number {
  if (a === b) return 0;
  if (a.kind === "PunctuationTrailing") return 0 - (b.kind === "PunctuationTrailing" ? 0 : 0);
  if (a.kind === "Relation") return 1 - (b.kind === "Relation" ? 1 : 0);
  if (a.kind === "BinaryOperator") return 2 - (b.kind === "BinaryOperator" ? 2 : 0);
  return 0;
}
