// Generated by the reflaxe TypeScript target. Do not edit.

export interface None {
  readonly kind: "None"
}

export interface Previous {
  readonly kind: "Previous"
}

export type InlineAttachment =
  | None
  | Previous;

export const InlineAttachment = Object.freeze({
  None: Object.freeze({ kind: "None" } as None),
  Previous: Object.freeze({ kind: "Previous" } as Previous)
});

export function compareInlineAttachment(a: InlineAttachment, b: InlineAttachment): number {
  if (a === b) return 0;
  if (a.kind === "None") return 0 - (b.kind === "None" ? 0 : 0);
  if (a.kind === "Previous") return 1 - (b.kind === "Previous" ? 1 : 0);
  return 0;
}
