// Generated by the reflaxe TypeScript target. Do not edit.

import { InlineBoxOuterSpacing } from "./InlineBoxOuterSpacing.ts";
import { TextRange } from "./TextRange.ts";

export class InlineBoxSpan {
  public readonly range: TextRange;
  public readonly inlineStart: number;
  public readonly inlineEnd: number;
  public readonly outerSpacing: InlineBoxOuterSpacing;

  constructor(range: TextRange, inlineStart: number | null = null, inlineEnd: number | null = null, outerSpacing: InlineBoxOuterSpacing | null = null) {
    this.range = range;
    this.inlineStart = inlineStart ?? 0.0;
    this.inlineEnd = inlineEnd ?? 0.0;
    this.outerSpacing = outerSpacing ?? (InlineBoxOuterSpacing.Narrow as InlineBoxOuterSpacing);
  }

  public toString(): string {
    return `InlineBoxSpan(range=${this.range.toString()}, inlineStart=${this.inlineStart}, inlineEnd=${this.inlineEnd}, outerSpacing=${this.outerSpacing.kind})`;
  }
}
