// Generated by the reflaxe TypeScript target. Do not edit.

export interface Start {
  readonly kind: "Start"
}

export interface Center {
  readonly kind: "Center"
}

export interface End {
  readonly kind: "End"
}

export type LastLineAlignment =
  | Start
  | Center
  | End;

export const LastLineAlignment = Object.freeze({
  Start: Object.freeze({ kind: "Start" } as Start),
  Center: Object.freeze({ kind: "Center" } as Center),
  End: Object.freeze({ kind: "End" } as End)
});

export function compareLastLineAlignment(a: LastLineAlignment, b: LastLineAlignment): number {
  if (a === b) return 0;
  if (a.kind === "Start") return 0 - (b.kind === "Start" ? 0 : 0);
  if (a.kind === "Center") return 1 - (b.kind === "Center" ? 1 : 0);
  if (a.kind === "End") return 2 - (b.kind === "End" ? 2 : 0);
  return 0;
}
