// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRangeError } from "./TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";

export class LayoutConstraints {
  public readonly maxWidth: number;
  public readonly maxHeight: number;
  public readonly maxLines: number;

  constructor(maxWidth: number, maxHeight: number | null = null, maxLines: number | null = null) {
    this.maxWidth = maxWidth;
    this.maxHeight = maxHeight ?? Infinity;
    this.maxLines = maxLines ?? 2147483647;
    if (!(this.maxWidth > 0.0)) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "maxWidth must be positive." } as TextRangeError));
    }
    if (!(this.maxHeight > 0.0)) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "maxHeight must be positive." } as TextRangeError));
    }
    if (this.maxLines <= 0) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "maxLines must be positive." } as TextRangeError));
    }
  }

  public toString(): string {
    return `LayoutConstraints(maxWidth=${this.maxWidth}, maxHeight=${this.maxHeight}, maxLines=${this.maxLines})`;
  }
}
