// Generated by the reflaxe TypeScript target. Do not edit.

import { Cluster } from "./Cluster.ts";
import { GlyphRun } from "./GlyphRun.ts";
import { LayoutDebugInfo } from "./LayoutDebugInfo.ts";
import { LayoutInput } from "./LayoutInput.ts";
import { LineBox } from "./LineBox.ts";
import { Size } from "./Size.ts";

export class LayoutResult {
  public readonly input: LayoutInput;
  public readonly size: Size;
  public readonly clusters: readonly Cluster[];
  public readonly glyphRuns: readonly GlyphRun[];
  public readonly lines: readonly LineBox[];
  public readonly debug: LayoutDebugInfo;

  constructor(input: LayoutInput, size: Size, clusters: readonly Cluster[], glyphRuns: readonly GlyphRun[], lines: readonly LineBox[], debug: LayoutDebugInfo) {
    this.input = input;
    this.size = size;
    this.clusters = clusters;
    this.glyphRuns = glyphRuns;
    this.lines = lines;
    this.debug = debug;
  }

  public toString(): string {
    return `LayoutResult(input=${this.input.toString()}, size=${this.size.toString()}, clusters=${(() => { let out = "["; const n = this.clusters.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.clusters[i]!.toString(); } out += "]"; return out; })()}, glyphRuns=${(() => { let out = "["; const n = this.glyphRuns.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.glyphRuns[i]!.toString(); } out += "]"; return out; })()}, lines=${(() => { let out = "["; const n = this.lines.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.lines[i]!.toString(); } out += "]"; return out; })()}, debug=${this.debug.toString()})`;
  }
}
