// Generated by the reflaxe TypeScript target. Do not edit.

export class LineDebugInfo {
  public readonly repair: string | null;
  public readonly notes: string[];

  constructor(repair: string | null, notes: string[] | null = null) {
    this.repair = repair;
    this.notes = notes ?? [];
  }

  public toString(): string {
    return `LineDebugInfo(repair=${this.repair}, notes=${(() => { let out = "["; const n = this.notes.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.notes[i]!; } out += "]"; return out; })()})`;
  }
}
