// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class LineEdgeTrimDecisionInfo {
  public readonly lineRange: TextRange;
  public readonly clusterRange: TextRange;
  public readonly side: string;
  public readonly trimAmount: number;
  public readonly consumedBefore: number;
  public readonly naturalGlue: number;
  public readonly reason: string;

  constructor(lineRange: TextRange, clusterRange: TextRange, side: string, trimAmount: number, consumedBefore: number, naturalGlue: number, reason: string) {
    this.lineRange = lineRange;
    this.clusterRange = clusterRange;
    this.side = side;
    this.trimAmount = trimAmount;
    this.consumedBefore = consumedBefore;
    this.naturalGlue = naturalGlue;
    this.reason = reason;
  }

  public toString(): string {
    return `LineEdgeTrimDecisionInfo(lineRange=${this.lineRange.toString()}, clusterRange=${this.clusterRange.toString()}, side=${this.side}, trimAmount=${this.trimAmount}, consumedBefore=${this.consumedBefore}, naturalGlue=${this.naturalGlue}, reason=${this.reason})`;
  }
}
