// Generated by the reflaxe TypeScript target. Do not edit.

export interface ProgressiveTechnical {
  readonly kind: "ProgressiveTechnical"
}

export type LineBreakPolicy =
  | ProgressiveTechnical;

export const LineBreakPolicy = Object.freeze({
  ProgressiveTechnical: Object.freeze({ kind: "ProgressiveTechnical" } as ProgressiveTechnical)
});

export function compareLineBreakPolicy(a: LineBreakPolicy, b: LineBreakPolicy): number {
  if (a === b) return 0;
  if (a.kind === "ProgressiveTechnical") return 0 - (b.kind === "ProgressiveTechnical" ? 0 : 0);
  return 0;
}
