// Generated by the reflaxe TypeScript target. Do not edit.

export class MaxLinesDecisionInfo {
  public readonly laidOutLines: number;
  public readonly visibleLines: number;
  public readonly reason: string;

  constructor(laidOutLines: number, visibleLines: number, reason: string | null = null) {
    this.laidOutLines = laidOutLines;
    this.visibleLines = visibleLines;
    this.reason = reason ?? "MaxLinesLineTruncation";
  }

  public toString(): string {
    return `MaxLinesDecisionInfo(laidOutLines=${this.laidOutLines}, visibleLines=${this.visibleLines}, reason=${this.reason})`;
  }
}

export function compareMaxLinesDecisionInfo(a: MaxLinesDecisionInfo, b: MaxLinesDecisionInfo): number {
  if (a === b) return 0;
  if (a.laidOutLines !== b.laidOutLines) return a.laidOutLines - b.laidOutLines;
  if (a.visibleLines !== b.visibleLines) return a.visibleLines - b.visibleLines;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  return 0;
}
