// Generated by the reflaxe TypeScript target. Do not edit.

import { Ic, Zero, toString } from "./Ic.ts";
import { LastLineAlignment } from "./LastLineAlignment.ts";
import { LineLengthGrid } from "./LineLengthGrid.ts";
import { MeasureAdaptiveFirstLineIndent } from "./MeasureAdaptiveFirstLineIndent.ts";
import { RubyLineHeightMode } from "./RubyLineHeightMode.ts";
import { WritingMode } from "./WritingMode.ts";

export class ParagraphStyle {
  public readonly lastLineAlignment: LastLineAlignment;
  public readonly writingMode: WritingMode;
  public readonly lineHeight: number | null;
  public readonly firstLineIndent: Ic | null;
  public readonly blockIndent: Ic;
  public readonly firstLineIndentPolicy: MeasureAdaptiveFirstLineIndent;
  public readonly lineLengthGrid: LineLengthGrid;
  public readonly rubyLineHeightMode: RubyLineHeightMode;
  public readonly inlineObjectMinimumClearanceEm: number;
  public readonly emphasisDotGapEm: number;
  public static readonly DEFAULT_EMPHASIS_DOT_GAP_EM: number = 0.1;
  public static readonly DEFAULT_INLINE_OBJECT_MINIMUM_CLEARANCE_EM: number = 0.1;

  constructor(lastLineAlignment: LastLineAlignment | null = null, writingMode: WritingMode | null = null, lineHeight: number | null = null, firstLineIndent: Ic | null = null, blockIndent: Ic | null = null, firstLineIndentPolicy: MeasureAdaptiveFirstLineIndent | null = null, lineLengthGrid: LineLengthGrid | null = null, rubyLineHeightMode: RubyLineHeightMode | null = null, inlineObjectMinimumClearanceEm: number | null = null, emphasisDotGapEm: number | null = null) {
    this.lastLineAlignment = lastLineAlignment ?? (LastLineAlignment.Start as LastLineAlignment);
    this.writingMode = writingMode ?? (WritingMode.HorizontalTb as WritingMode);
    this.lineHeight = lineHeight ?? null;
    this.firstLineIndent = firstLineIndent ?? null;
    this.blockIndent = blockIndent ?? Zero;
    this.firstLineIndentPolicy = firstLineIndentPolicy ?? new MeasureAdaptiveFirstLineIndent(14.0, 1.0, 2.0);
    this.lineLengthGrid = lineLengthGrid ?? new LineLengthGrid(true, null);
    this.rubyLineHeightMode = rubyLineHeightMode ?? (RubyLineHeightMode.PerLine as RubyLineHeightMode);
    this.inlineObjectMinimumClearanceEm = inlineObjectMinimumClearanceEm ?? ParagraphStyle.DEFAULT_INLINE_OBJECT_MINIMUM_CLEARANCE_EM;
    this.emphasisDotGapEm = emphasisDotGapEm ?? ParagraphStyle.DEFAULT_EMPHASIS_DOT_GAP_EM;
  }

  public toString(): string {
    return `ParagraphStyle(lastLineAlignment=${this.lastLineAlignment.kind}, writingMode=${this.writingMode.kind}, lineHeight=${this.lineHeight}, firstLineIndent=${(this.firstLineIndent === null ? "null" : toString(this.firstLineIndent))}, blockIndent=${toString(this.blockIndent)}, firstLineIndentPolicy=${this.firstLineIndentPolicy.toString()}, lineLengthGrid=${this.lineLengthGrid.toString()}, rubyLineHeightMode=${this.rubyLineHeightMode.kind}, inlineObjectMinimumClearanceEm=${this.inlineObjectMinimumClearanceEm}, emphasisDotGapEm=${this.emphasisDotGapEm})`;
  }
}
