// Generated by the reflaxe TypeScript target. Do not edit.

import { Border, Fill, RichTextBackgroundDrawStyle } from "./RichTextBackgroundDrawStyle.ts";
import { RichTextBackgroundMetricPolicy } from "./RichTextBackgroundMetricPolicy.ts";
import { TextRangeError } from "./TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";

export class RichTextBackgroundPaint {
  public readonly horizontalPadding: number;
  public readonly verticalPadding: number;
  public readonly cornerRadius: number;
  public readonly continuationCornerRadius: number;
  public readonly metricPolicy: RichTextBackgroundMetricPolicy;
  public readonly drawStyle: RichTextBackgroundDrawStyle;

  constructor(horizontalPadding: number | null = null, verticalPadding: number | null = null, cornerRadius: number | null = null, continuationCornerRadius: number | null = null, metricPolicy: RichTextBackgroundMetricPolicy | null = null, drawStyle: RichTextBackgroundDrawStyle | null = null) {
    this.horizontalPadding = horizontalPadding ?? 0.0;
    this.verticalPadding = verticalPadding ?? 0.0;
    this.cornerRadius = cornerRadius ?? 0.0;
    this.continuationCornerRadius = continuationCornerRadius ?? (cornerRadius ?? 0.0);
    this.metricPolicy = metricPolicy ?? (RichTextBackgroundMetricPolicy.MarkedFaces as RichTextBackgroundMetricPolicy);
    this.drawStyle = drawStyle ?? Fill.instance;
    if (!RichTextBackgroundPaint.isFinite(this.horizontalPadding) || this.horizontalPadding < 0.0 || !RichTextBackgroundPaint.isFinite(this.verticalPadding) || this.verticalPadding < 0.0 || !RichTextBackgroundPaint.isFinite(this.cornerRadius) || this.cornerRadius < 0.0 || !RichTextBackgroundPaint.isFinite(this.continuationCornerRadius) || this.continuationCornerRadius < 0.0) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Failed requirement." } as TextRangeError));
    }
  }

  public toString(): string {
    return `RichTextBackgroundPaint(horizontalPadding=${this.horizontalPadding}, verticalPadding=${this.verticalPadding}, cornerRadius=${this.cornerRadius}, continuationCornerRadius=${this.continuationCornerRadius}, metricPolicy=${this.metricPolicy.kind}, drawStyle=${this.drawStyle.toString()})`;
  }

  public static withHorizontalPadding(value: number): RichTextBackgroundPaint {
    return new RichTextBackgroundPaint(value, 0.0, 0.0, 0.0, RichTextBackgroundMetricPolicy.MarkedFaces, Fill.instance);
  }

  public static withMetricPolicy(value: RichTextBackgroundMetricPolicy): RichTextBackgroundPaint {
    return new RichTextBackgroundPaint(0.0, 0.0, 0.0, 0.0, value, Fill.instance);
  }

  public static withCornerRadius(corner: number, continuation: number | null): RichTextBackgroundPaint {
    return new RichTextBackgroundPaint(0.0, 0.0, corner, continuation, RichTextBackgroundMetricPolicy.MarkedFaces, Fill.instance);
  }

   static sameValues(a: RichTextBackgroundPaint, b: RichTextBackgroundPaint): boolean {
    return a.horizontalPadding === b.horizontalPadding && a.verticalPadding === b.verticalPadding && a.cornerRadius === b.cornerRadius && a.continuationCornerRadius === b.continuationCornerRadius && a.metricPolicy === b.metricPolicy && RichTextBackgroundPaint.sameDrawStyle(a.drawStyle, b.drawStyle);
  }

  private static sameDrawStyle(a: RichTextBackgroundDrawStyle, b: RichTextBackgroundDrawStyle): boolean {
    if (a instanceof Fill || b instanceof Fill) {
      return a instanceof Fill && b instanceof Fill && Fill.instance === a && Fill.instance === b;
    }
    if (a instanceof Border && b instanceof Border) {
      return a.strokeWidth === b.strokeWidth;
    }
    return false;
  }

  private static isFinite(value: number): boolean {
    return value === value && value !== Infinity && value !== -Infinity;
  }
}
