// Generated by the reflaxe TypeScript target. Do not edit.

import { Glyph } from "./Glyph.ts";
import { TextRange } from "./TextRange.ts";

export class RubyDecisionInfo {
  public readonly baseRange: TextRange;
  public readonly text: string;
  public readonly lineIndex: number;
  public readonly centerX: number;
  public readonly baselineY: number;
  public readonly fontSize: number;
  public readonly ascent: number;
  public readonly descent: number;
  public readonly width: number;
  public readonly overhang: number;
  public readonly fontFamilies: readonly string[];
  public readonly fontWeight: number;
  public readonly locale: string;
  public readonly glyphs: readonly Glyph[];

  constructor(baseRange: TextRange, text: string, lineIndex: number, centerX: number, baselineY: number, fontSize: number, overhang: number, ascent: number | null = null, descent: number | null = null, width: number | null = null, fontFamilies: string[] | null = null, fontWeight: number | null = null, locale: string | null = null, glyphs: Glyph[] | null = null) {
    this.baseRange = baseRange;
    this.text = text;
    this.lineIndex = lineIndex;
    this.centerX = centerX;
    this.baselineY = baselineY;
    this.fontSize = fontSize;
    this.overhang = overhang;
    this.ascent = ascent ?? 0.0;
    this.descent = descent ?? 0.0;
    this.width = width ?? 0.0;
    this.fontFamilies = fontFamilies ?? [];
    this.fontWeight = fontWeight ?? 400;
    this.locale = locale ?? "zh-Hans";
    this.glyphs = glyphs ?? [];
  }

  public toString(): string {
    return `RubyDecisionInfo(baseRange=${this.baseRange.toString()}, text=${this.text}, lineIndex=${this.lineIndex}, centerX=${this.centerX}, baselineY=${this.baselineY}, fontSize=${this.fontSize}, ascent=${this.ascent}, descent=${this.descent}, width=${this.width}, overhang=${this.overhang}, fontFamilies=${(() => { let out = "["; const n = this.fontFamilies.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.fontFamilies[i]!; } out += "]"; return out; })()}, fontWeight=${this.fontWeight}, locale=${this.locale}, glyphs=${(() => { let out = "["; const n = this.glyphs.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.glyphs[i]!.toString(); } out += "]"; return out; })()})`;
  }
}
