// Generated by the reflaxe TypeScript target. Do not edit.

export interface PerLine {
  readonly kind: "PerLine"
}

export interface UniformParagraph {
  readonly kind: "UniformParagraph"
}

export type RubyLineHeightMode =
  | PerLine
  | UniformParagraph;

export const RubyLineHeightMode = Object.freeze({
  PerLine: Object.freeze({ kind: "PerLine" } as PerLine),
  UniformParagraph: Object.freeze({ kind: "UniformParagraph" } as UniformParagraph)
});

export function compareRubyLineHeightMode(a: RubyLineHeightMode, b: RubyLineHeightMode): number {
  if (a === b) return 0;
  if (a.kind === "PerLine") return 0 - (b.kind === "PerLine" ? 0 : 0);
  if (a.kind === "UniformParagraph") return 1 - (b.kind === "UniformParagraph" ? 1 : 0);
  return 0;
}
