// Generated by the reflaxe TypeScript target. Do not edit.

export interface Backward {
  readonly kind: "Backward"
}

export interface Forward {
  readonly kind: "Forward"
}

export interface Nearest {
  readonly kind: "Nearest"
}

export type SourceBoundaryBias =
  | Backward
  | Forward
  | Nearest;

export const SourceBoundaryBias = Object.freeze({
  Backward: Object.freeze({ kind: "Backward" } as Backward),
  Forward: Object.freeze({ kind: "Forward" } as Forward),
  Nearest: Object.freeze({ kind: "Nearest" } as Nearest)
});

export function compareSourceBoundaryBias(a: SourceBoundaryBias, b: SourceBoundaryBias): number {
  if (a === b) return 0;
  if (a.kind === "Backward") return 0 - (b.kind === "Backward" ? 0 : 0);
  if (a.kind === "Forward") return 1 - (b.kind === "Forward" ? 1 : 0);
  if (a.kind === "Nearest") return 2 - (b.kind === "Nearest" ? 2 : 0);
  return 0;
}
