// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./TextRange.ts";

export class SpacingDecisionInfo {
  public readonly range: TextRange;
  public readonly leftChar: string;
  public readonly rightChar: string;
  public readonly naturalInnerGlue: number;
  public readonly adjustedInnerGlue: number;
  public readonly reduction: number;
  public readonly reductionTargetRange: TextRange;
  public readonly reason: string;

  constructor(range: TextRange, leftChar: string, rightChar: string, naturalInnerGlue: number, adjustedInnerGlue: number, reduction: number, reductionTargetRange: TextRange, reason: string) {
    this.range = range;
    this.leftChar = leftChar;
    this.rightChar = rightChar;
    this.naturalInnerGlue = naturalInnerGlue;
    this.adjustedInnerGlue = adjustedInnerGlue;
    this.reduction = reduction;
    this.reductionTargetRange = reductionTargetRange;
    this.reason = reason;
  }

  public toString(): string {
    return `SpacingDecisionInfo(range=${this.range.toString()}, leftChar=${this.leftChar}, rightChar=${this.rightChar}, naturalInnerGlue=${this.naturalInnerGlue}, adjustedInnerGlue=${this.adjustedInnerGlue}, reduction=${this.reduction}, reductionTargetRange=${this.reductionTargetRange.toString()}, reason=${this.reason})`;
  }
}
