// Generated by the reflaxe TypeScript target. Do not edit.

import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";

export class TextRange {
  public readonly start: number;
  public readonly end: number;

  constructor(start: number, end: number) {
    if (start > end) {
      throw new TiqianIllegalArgumentException({ kind: "StartGreaterThanEnd" });
    }
    if (start < 0) {
      throw new TiqianIllegalArgumentException({ kind: "NegativeStart" });
    }
    this.start = start;
    this.end = end;
  }

  public get length(): number {
    return this.get_length();
  }
  public get_length(): number {
    return this.end - this.start;
  }

  public get isEmpty(): boolean {
    return this.get_isEmpty();
  }
  public get_isEmpty(): boolean {
    return this.length === 0;
  }

  public toString(): string {
    return `TextRange(start=${this.start}, end=${this.end})`;
  }
}

export function compareTextRange(a: TextRange, b: TextRange): number {
  if (a === b) return 0;
  if (a.start !== b.start) return a.start - b.start;
  if (a.end !== b.end) return a.end - b.end;
  return 0;
}
