// Generated by the reflaxe TypeScript target. Do not edit.

export interface StartGreaterThanEnd {
  readonly kind: "StartGreaterThanEnd"
}

export interface NegativeStart {
  readonly kind: "NegativeStart"
}

export interface Message {
  readonly kind: "Message"
  readonly text: string
}

export type TextRangeError =
  | StartGreaterThanEnd
  | NegativeStart
  | Message;
