// Generated by the reflaxe TypeScript target. Do not edit.

export class TiqianNoSuchElementException extends Error {
  public readonly error: NoSuchElementError;

  constructor(error: NoSuchElementError) {
    super(TiqianNoSuchElementException.describe(error));
    this.name = "TiqianNoSuchElementException";
    this.error = error;
  }

  public static describe(error: NoSuchElementError): string {
    return (() => {
  const _g = error.text;
  const text = _g;
  return text;
})();
  }
}

export interface Message {
  readonly kind: "Message"
  readonly text: string
}

export type NoSuchElementError =
  | Message;
