// Generated by the reflaxe TypeScript target. Do not edit.

import { LineBreakSpan } from "./LineBreakSpan.ts";
import { TextRange } from "./TextRange.ts";
import { TextSpan } from "./TextSpan.ts";

export class TiqianTextContent {
  public readonly text: string;
  public readonly spans: readonly TextSpan[];
  public readonly sourceBoundaries: readonly number[];
  public readonly lineBreakSpans: readonly LineBreakSpan[];
  public readonly autoSpaceSuppressedRanges: readonly TextRange[];

  constructor(text: string, spans: TextSpan[] | null = null, sourceBoundaries: number[] | null = null, lineBreakSpans: LineBreakSpan[] | null = null, autoSpaceSuppressedRanges: TextRange[] | null = null) {
    this.text = text;
    this.spans = spans ?? [];
    this.sourceBoundaries = sourceBoundaries ?? [];
    this.lineBreakSpans = lineBreakSpans ?? [];
    this.autoSpaceSuppressedRanges = autoSpaceSuppressedRanges ?? [];
  }

  public toString(): string {
    return `TiqianTextContent(text=${this.text}, spans=${(() => { let out = "["; const n = this.spans.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.spans[i]!.toString(); } out += "]"; return out; })()}, sourceBoundaries=${(() => { let out = "["; const n = this.sourceBoundaries.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.sourceBoundaries[i]!; } out += "]"; return out; })()}, lineBreakSpans=${(() => { let out = "["; const n = this.lineBreakSpans.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.lineBreakSpans[i]!.toString(); } out += "]"; return out; })()}, autoSpaceSuppressedRanges=${(() => { let out = "["; const n = this.autoSpaceSuppressedRanges.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.autoSpaceSuppressedRanges[i]!.toString(); } out += "]"; return out; })()})`;
  }
}
