// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRangeError } from "./TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";
import { UnicodeWordCharacterData } from "./UnicodeWordCharacterData.ts";

export class UnicodeWordCharacter {
  public static readonly DATA_REVISION: string = "17.0.0";
  public static readonly DATA_SOURCE: string = "https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedGeneralCategory.txt";
  public static readonly DATA_SHA256: string = "d62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e";

  public static contains(codePoint: number): boolean {
    if (codePoint < 0 || codePoint > 1114111) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    if (codePoint >= 55296 && codePoint <= 57343) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Surrogate is not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    return UnicodeWordCharacterData.contains(codePoint);
  }
}
