// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRangeError } from "./TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./TiqianIllegalArgumentException.ts";
import { UnicodeNumberData } from "./UnicodeNumberData.ts";

export class UnicodeNumber {
  public static contains(codePoint: number): boolean {
    if (codePoint < 0 || codePoint > 1114111) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    if (codePoint >= 55296 && codePoint <= 57343) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Surrogate is not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    return UnicodeNumberData.contains(codePoint);
  }
}
