// Generated by the reflaxe TypeScript target. Do not edit.

import { TableData } from "./TableData.js";

export interface TOk {
  readonly kind: "TOk"
  readonly data: TableData
}

export interface TErr {
  readonly kind: "TErr"
  readonly issue: string
}

export type DecodeResult =
  | TOk
  | TErr;
