// Generated by the reflaxe TypeScript target. Do not edit.

export class MetricEntry {
  public familiesRef: number;
  public weight: number;
  public italic: number;
  public roleRef: number;
  public faceSelectionRef: number;
  public valuePoolRef: number;
  public valuesEm: (number | null)[];
  public stored: boolean;

  constructor(familiesRef: number, weight: number, italic: number, roleRef: number, faceSelectionRef: number, valuePoolRef: number) {
    this.familiesRef = familiesRef;
    this.weight = weight;
    this.italic = italic;
    this.roleRef = roleRef;
    this.faceSelectionRef = faceSelectionRef;
    this.valuePoolRef = valuePoolRef;
    this.valuesEm = [];
    this.stored = false;
  }
}
