// Generated by the reflaxe TypeScript target. Do not edit.

import type { DecodeResult } from "./DecodeResult.js";
import { MetricEntry } from "./MetricEntry.js";
import { StyleRow } from "./StyleRow.js";
import { TableData } from "./TableData.js";
import { TableInput } from "./TableInput.js";
import { TableProbe } from "./TableProbe.js";
import { ValueRow } from "./ValueRow.js";
import { BytesBuffer, doubleToI64, i64ToDouble } from "../../../runtime.js";

export class SnapshotTableBinary {
  public static encode(table: TableInput): Uint8Array {
    return SnapshotTableBinary.encodeData(SnapshotTableBinary.lower(table));
  }

  public static encodeData(data: TableData): Uint8Array {
    const writer = new TableWriter();
    writer.raw(new TextEncoder().encode("TIQTBL03"));
    writer.u32(data.replayStringCount);
    writer.u32(data.strings.length);
    writer.u32(data.metricRows.length);
    writer.u32(data.valuePool.length);
    writer.u32(data.probeTextRefs.length);
    writer.u32(data.advancePool.length);
    writer.u32(data.styleFontSize.length);
    writer.u32(data.featuresPool.length);
    writer.u32(data.faceTexts.length);
    writer.u32(data.typographyTexts.length);
    writer.u32(data.valueStyleTexts.length);
    writer.u32(data.fontPreloadTexts.length);
    SnapshotTableBinary.writeTextRegion(writer, data.strings);
    let indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.u32(data.metricRows[indexIdx]!.familiesRef);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.f64(data.metricRows[indexIdx]!.weight);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.u8(data.metricRows[indexIdx]!.italic);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.u32(data.metricRows[indexIdx]!.roleRef);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.u32(data.metricRows[indexIdx]!.faceSelectionRef);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.metricRows.length) {
      writer.u32(data.metricRows[indexIdx]!.valuePoolRef);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.valuePool.length) {
      SnapshotTableBinary.writeValueRow(writer, data.valuePool[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.probeTextRefs.length) {
      writer.u32(data.probeTextRefs[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.probeAdvanceRefs.length) {
      writer.u16(data.probeAdvanceRefs[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.probeStyleRefs.length) {
      writer.u16(data.probeStyleRefs[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.probeFeatureRefs.length) {
      writer.u16(data.probeFeatureRefs[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.advancePool.length) {
      writer.f64(data.advancePool[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.styleFontSize.length) {
      writer.f64(data.styleFontSize[indexIdx]!);
      writer.f64(data.styleFontWeight[indexIdx]!);
      writer.u8(data.styleItalic[indexIdx]!);
      writer.u32(data.styleScriptRefs[indexIdx]!);
      writer.u32(data.styleLanguageRefs[indexIdx]!);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.featuresPool.length) {
      writer.u32(SnapshotTableBinary.featureRowBytes(data.featuresPool[indexIdx]!).length);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < data.featuresPool.length) {
      writer.raw(SnapshotTableBinary.featureRowBytes(data.featuresPool[indexIdx]!));
      indexIdx++;
    }
    SnapshotTableBinary.writeTextRegion(writer, data.faceTexts);
    SnapshotTableBinary.writeTextRegion(writer, data.typographyTexts);
    SnapshotTableBinary.writeTextRegion(writer, data.valueStyleTexts);
    SnapshotTableBinary.writeTextRegion(writer, data.fontPreloadTexts);
    writer.raw(new TextEncoder().encode(data.revisionText));
    return writer.finish();
  }

  public static decode(bytes: Uint8Array): DecodeResult {
    const reader = new TableReader(bytes);
    const magic = reader.takeRaw(8);
    if (reader.failed) {
      return ({ kind: "TErr", issue: reader.issue } as DecodeResult);
    }
    if (!SnapshotTableBinary.magicEquals(magic)) {
      return ({ kind: "TErr", issue: "SnapshotTablesInvalid" } as DecodeResult);
    }
    const data = new TableData();
    data.replayStringCount = reader.u32();
    const stringCount = reader.u32();
    const metricCount = reader.u32();
    const valuePoolCount = reader.u32();
    const probeCount = reader.u32();
    const advancePoolCount = reader.u32();
    const stylePoolCount = reader.u32();
    const featuresPoolCount = reader.u32();
    const faceCount = reader.u32();
    const typographyCount = reader.u32();
    const valueStyleCount = reader.u32();
    const fontPreloadCount = reader.u32();
    data.strings = reader.textRegion(stringCount);
    let indexIdx = 0;
    while (indexIdx < metricCount) {
      const row = new MetricEntry(reader.u32(), 0, 0, 0, 0, 0);
      row.stored = true;
      data.metricRows.push(row);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < metricCount) {
      data.metricRows[indexIdx]!.weight = reader.f64();
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < metricCount) {
      data.metricRows[indexIdx]!.italic = reader.u8();
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < metricCount) {
      data.metricRows[indexIdx]!.roleRef = reader.u32();
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < metricCount) {
      data.metricRows[indexIdx]!.faceSelectionRef = reader.u32();
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < metricCount) {
      data.metricRows[indexIdx]!.valuePoolRef = reader.u32();
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < valuePoolCount) {
      data.valuePool.push(SnapshotTableBinary.readValueRow(reader));
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < probeCount) {
      data.probeTextRefs.push(reader.u32());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < probeCount) {
      data.probeAdvanceRefs.push(reader.u16());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < probeCount) {
      data.probeStyleRefs.push(reader.u16());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < probeCount) {
      data.probeFeatureRefs.push(reader.u16());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < advancePoolCount) {
      data.advancePool.push(reader.f64());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < stylePoolCount) {
      data.styleFontSize.push(reader.f64());
      data.styleFontWeight.push(reader.f64());
      data.styleItalic.push(reader.u8());
      data.styleScriptRefs.push(reader.u32());
      data.styleLanguageRefs.push(reader.u32());
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < featuresPoolCount) {
      reader.u32();
      indexIdx++;
    }
    for (let indexIdx = 0; indexIdx < featuresPoolCount; indexIdx += 1) {
      data.featuresPool.push(reader.featureRow());
    }
    data.faceTexts = reader.textRegion(faceCount);
    data.typographyTexts = reader.textRegion(typographyCount);
    data.valueStyleTexts = reader.textRegion(valueStyleCount);
    data.fontPreloadTexts = reader.textRegion(fontPreloadCount);
    if (reader.failed) {
      return ({ kind: "TErr", issue: reader.issue } as DecodeResult);
    }
    data.revisionText = reader.restText();
    if (reader.failed) {
      return ({ kind: "TErr", issue: reader.issue } as DecodeResult);
    }
    return ({ kind: "TOk", data } as DecodeResult);
  }

  public static sortMetricRows(rows: MetricEntry[]): MetricEntry[] {
    let writeIdx = 1;
    while (writeIdx < rows.length) {
      const record = rows[writeIdx]!;
      let readIdx = writeIdx - 1;
      while (readIdx >= 0 && SnapshotTableBinary.metricBefore(record, rows[readIdx]!)) {
        rows[readIdx + 1] = rows[readIdx]!;
        readIdx--;
      }
      rows[readIdx + 1] = record;
      writeIdx++;
    }
    return rows;
  }

  private static metricBefore(a: MetricEntry, b: MetricEntry): boolean {
    if (a.familiesRef !== b.familiesRef) {
      return a.familiesRef < b.familiesRef;
    }
    if (a.weight < b.weight) {
      return true;
    }
    if (b.weight < a.weight) {
      return false;
    }
    if (a.italic !== b.italic) {
      return a.italic < b.italic;
    }
    if (a.roleRef !== b.roleRef) {
      return a.roleRef < b.roleRef;
    }
    return a.faceSelectionRef < b.faceSelectionRef;
  }

  private static magicEquals(magic: Uint8Array): boolean {
    const expected = new TextEncoder().encode("TIQTBL03");
    if (magic.length !== expected.length) {
      return false;
    }
    let indexIdx = 0;
    while (indexIdx < expected.length) {
      if (magic[indexIdx]! !== expected[indexIdx]!) {
        return false;
      }
      indexIdx++;
    }
    return true;
  }

  private static lower(table: TableInput): TableData {
    const data = new TableData();
    data.replayStringCount = table.replayStrings.length;
    const interner = new StringInterner(table.replayStrings);
    let indexIdx = 0;
    const metricEntries = new Array<MetricEntry>();
    while (indexIdx < table.metrics.length) {
      const row = table.metrics[indexIdx]!;
      const entry = new MetricEntry(interner.intern(row.serializedFamilies), row.fontWeight, (row.italic ? 1 : 0), interner.intern(row.role), interner.intern(row.faceSelectionText), 0);
      metricEntries.push(entry);
      indexIdx++;
    }
    SnapshotTableBinary.sortMetricRows(metricEntries);
    const valuePool = new Array<ValueRow>();
    indexIdx = 0;
    while (indexIdx < metricEntries.length) {
      const values = table.metrics[indexIdx]!.valuesEm;
      metricEntries[indexIdx]!.valuePoolRef = SnapshotTableBinary.poolRefOf(valuePool, values);
      indexIdx++;
    }
    data.metricRows = metricEntries;
    data.valuePool = valuePool;
    const advancePool = new Array<number>();
    const stylePool = new Array<StyleRow>();
    const featuresPool = new Array<number[]>();
    indexIdx = 0;
    while (indexIdx < table.probes.length) {
      const probe = table.probes[indexIdx]!;
      const textRef = interner.intern(probe.text);
      const scriptRef = interner.intern(probe.script);
      const languageRef = interner.intern(probe.language);
      const featureRefs = new Array<number>();
      let featureIdx = 0;
      while (featureIdx < probe.features.length) {
        featureRefs.push(interner.intern(probe.features[featureIdx]!));
        featureIdx++;
      }
      data.probeTextRefs.push(textRef);
      data.probeAdvanceRefs.push(SnapshotTableBinary.pooledFloat(advancePool, probe.advancePx));
      data.probeStyleRefs.push(SnapshotTableBinary.pooledStyle(stylePool, probe, scriptRef, languageRef));
      data.probeFeatureRefs.push(SnapshotTableBinary.pooledFeatures(featuresPool, featureRefs));
      indexIdx++;
    }
    data.advancePool = advancePool;
    data.featuresPool = featuresPool;
    data.styleFontSize = new Array<number>();
    data.styleFontWeight = new Array<number>();
    data.styleItalic = new Array<number>();
    data.styleScriptRefs = new Array<number>();
    data.styleLanguageRefs = new Array<number>();
    let styleIdx = 0;
    while (styleIdx < stylePool.length) {
      data.styleFontSize.push(stylePool[styleIdx]!.fontSizePx);
      data.styleFontWeight.push(stylePool[styleIdx]!.fontWeight);
      data.styleItalic.push(stylePool[styleIdx]!.italic);
      data.styleScriptRefs.push(stylePool[styleIdx]!.scriptRef);
      data.styleLanguageRefs.push(stylePool[styleIdx]!.languageRef);
      styleIdx++;
    }
    data.strings = interner.strings;
    data.faceTexts = SnapshotTableBinary.copyTexts(table.faces);
    data.typographyTexts = SnapshotTableBinary.copyTexts(table.typographies);
    data.valueStyleTexts = SnapshotTableBinary.copyTexts(table.valueStyles);
    data.fontPreloadTexts = SnapshotTableBinary.copyTexts(table.fontPreloads);
    data.revisionText = table.revisionsText;
    return data;
  }

  private static copyTexts(texts: string[]): string[] {
    const out = new Array<string>();
    let indexIdx = 0;
    while (indexIdx < texts.length) {
      out.push(texts[indexIdx]!);
      indexIdx++;
    }
    return out;
  }

  private static poolRefOf(pool: ValueRow[], values: (number | null)[]): number {
    let indexIdx = 0;
    while (indexIdx < pool.length) {
      if (SnapshotTableBinary.sameValues(pool[indexIdx]!.values, values)) {
        return indexIdx;
      }
      indexIdx++;
    }
    pool.push(new ValueRow(values));
    return pool.length - 1;
  }

  private static sameValues(a: (number | null)[], b: (number | null)[]): boolean {
    if (a.length !== b.length) {
      return false;
    }
    let indexIdx = 0;
    while (indexIdx < a.length) {
      const left = a[indexIdx]!;
      const right = b[indexIdx]!;
      if (left === null && right === null) {
        indexIdx++;
        continue;
      }
      if (left === null || right === null) {
        return false;
      }
      if (!SnapshotTableBinary.f64BitsEqual(left, right)) {
        return false;
      }
      indexIdx++;
    }
    return true;
  }

  private static f64BitsEqual(a: number, b: number): boolean {
    const ab = doubleToI64(a);
    const bb = doubleToI64(b);
    return ab.high === bb.high && ab.low === bb.low;
  }

  private static pooledFloat(pool: number[], value: number): number {
    let indexIdx = 0;
    while (indexIdx < pool.length) {
      if (SnapshotTableBinary.f64BitsEqual(pool[indexIdx]!, value)) {
        return indexIdx;
      }
      indexIdx++;
    }
    pool.push(value);
    return pool.length - 1;
  }

  private static pooledStyle(pool: StyleRow[], probe: TableProbe, scriptRef: number, languageRef: number): number {
    let indexIdx = 0;
    while (indexIdx < pool.length) {
      const row = pool[indexIdx]!;
      if (SnapshotTableBinary.f64BitsEqual(row.fontSizePx, probe.fontSizePx) && SnapshotTableBinary.f64BitsEqual(row.fontWeight, probe.fontWeight) && row.italic === (probe.italic ? 1 : 0) && row.scriptRef === scriptRef && row.languageRef === languageRef) {
        return indexIdx;
      }
      indexIdx++;
    }
    pool.push(new StyleRow(probe.fontSizePx, probe.fontWeight, (probe.italic ? 1 : 0), scriptRef, languageRef));
    return pool.length - 1;
  }

  private static pooledFeatures(pool: number[][], refs: number[]): number {
    let indexIdx = 0;
    while (indexIdx < pool.length) {
      if (SnapshotTableBinary.sameRefs(pool[indexIdx]!, refs)) {
        return indexIdx;
      }
      indexIdx++;
    }
    pool.push(refs);
    return pool.length - 1;
  }

  private static sameRefs(a: number[], b: number[]): boolean {
    if (a.length !== b.length) {
      return false;
    }
    let indexIdx = 0;
    while (indexIdx < a.length) {
      if (a[indexIdx]! !== b[indexIdx]!) {
        return false;
      }
      indexIdx++;
    }
    return true;
  }

  private static writeTextRegion(writer: TableWriter, texts: string[]): void {
    let totalIdx = 0;
    while (totalIdx < texts.length) {
      writer.u32(new TextEncoder().encode(texts[totalIdx]!).length);
      totalIdx++;
    }
    totalIdx = 0;
    while (totalIdx < texts.length) {
      writer.raw(new TextEncoder().encode(texts[totalIdx]!));
      totalIdx++;
    }
  }

  private static writeValueRow(writer: TableWriter, row: ValueRow): void {
    let slotIdx = 0;
    while (slotIdx < row.values.length) {
      const value = row.values[slotIdx]!;
      if (value === null) {
        writer.absentF64();
      } else {
        writer.f64(value);
      }
      slotIdx++;
    }
  }

  private static featureRowBytes(refs: number[]): Uint8Array {
    const row = new TableWriter();
    row.u16(refs.length);
    let indexIdx = 0;
    while (indexIdx < refs.length) {
      row.u32(refs[indexIdx]!);
      indexIdx++;
    }
    return row.finish();
  }

  private static readValueRow(reader: TableReader): ValueRow {
    const values = new Array<number | null>();
    for (let slotIdx = 0; slotIdx < 5; slotIdx += 1) {
      const low = reader.u32();
      const high = reader.u32();
      if (high === 2146959360 && low === 0) {
        values.push(null);
      } else {
        values.push(i64ToDouble(low, high));
      }
    }
    return new ValueRow(values);
  }
}

export class StringInterner {
  public readonly strings: string[];

  constructor(replayStrings: string[]) {
    this.strings = new Array<string>();
    let indexIdx = 0;
    while (indexIdx < replayStrings.length) {
      this.strings.push(replayStrings[indexIdx]!);
      indexIdx++;
    }
  }

  public intern(text: string): number {
    let indexIdx = 0;
    while (indexIdx < this.strings.length) {
      if (this.strings[indexIdx]! === text) {
        return indexIdx;
      }
      indexIdx++;
    }
    this.strings.push(text);
    return this.strings.length - 1;
  }
}

export class TableWriter {
  private readonly buf: BytesBuffer;

  constructor() {
    this.buf = new BytesBuffer();
  }

  public raw(bytes: Uint8Array): void {
    this.buf.add(bytes);
  }

  public u8(value: number): void {
    this.buf.addByte(value & 255);
  }

  public u16(value: number): void {
    this.buf.addByte(value & 255);
    this.buf.addByte((value >>> 8) & 255);
  }

  public u32(value: number): void {
    this.buf.addByte(value & 255);
    this.buf.addByte((value >>> 8) & 255);
    this.buf.addByte((value >>> 16) & 255);
    this.buf.addByte((value >>> 24) & 255);
  }

  public f64(value: number): void {
    const bits = doubleToI64(value);
    this.u32(bits.low);
    this.u32(bits.high);
  }

  public absentF64(): void {
    this.u32(0);
    this.u32(2146959360);
  }

  public finish(): Uint8Array {
    return this.buf.getBytes();
  }
}

export class TableReader {
  private readonly bytes: Uint8Array;
  private pos: number;
  public failed: boolean;
  public issue: string;

  constructor(bytes: Uint8Array) {
    this.bytes = bytes;
    this.pos = 0;
    this.failed = false;
    this.issue = "";
  }

  public u8(): number {
    if (!this.need(1)) {
      return 0;
    }
    const value = this.bytes[this.pos]!;
    this.pos += 1;
    return value;
  }

  public u16(): number {
    if (!this.need(2)) {
      return 0;
    }
    const value = this.bytes[this.pos]! | (this.bytes[this.pos + 1]! << 8);
    this.pos += 2;
    return value;
  }

  public u32(): number {
    if (!this.need(4)) {
      return 0;
    }
    const value = (this.bytes[this.pos]! | (this.bytes[this.pos + 1]! << 8) | (this.bytes[this.pos + 2]! << 16)) + this.bytes[this.pos + 3]! * 16777216;
    this.pos += 4;
    return value;
  }

  public f64(): number {
    const low = this.u32();
    const high = this.u32();
    if (this.failed) {
      return 0.0;
    }
    return i64ToDouble(low, high);
  }

  public takeRaw(length: number): Uint8Array {
    if (!this.need(length)) {
      return new Uint8Array(0);
    }
    const value = this.bytes.slice(this.pos, this.pos + length);
    this.pos += length;
    return value;
  }

  public featureRow(): number[] {
    const refs = new Array<number>();
    const count = this.u16();
    if (this.failed) {
      return refs;
    }
    for (let indexIdx = 0; indexIdx < count; indexIdx += 1) {
      refs.push(this.u32());
    }
    return refs;
  }

  public textRegion(count: number): string[] {
    const texts = new Array<string>();
    if (this.failed) {
      return texts;
    }
    const lengths = new Array<number>();
    let running = 0;
    let indexIdx = 0;
    while (indexIdx < count) {
      const delta = this.u32();
      if (this.failed) {
        return texts;
      }
      running += delta;
      if (running < 0 || this.pos + running > this.bytes.length) {
        this.failed = true;
        this.issue = "SnapshotTablesInvalid";
        return texts;
      }
      lengths.push(delta);
      indexIdx++;
    }
    indexIdx = 0;
    while (indexIdx < lengths.length) {
      texts.push(new TextDecoder().decode(this.bytes.subarray(this.pos, this.pos + lengths[indexIdx]!)));
      this.pos += lengths[indexIdx]!;
      indexIdx++;
    }
    return texts;
  }

  public restText(): string {
    if (!this.need(0)) {
      return "";
    }
    const value = new TextDecoder().decode(this.bytes.subarray(this.pos, this.pos + this.bytes.length - this.pos));
    this.pos = this.bytes.length;
    return value;
  }

  private need(length: number): boolean {
    if (this.failed) {
      return false;
    }
    if (length < 0 || this.pos + length > this.bytes.length) {
      this.failed = true;
      this.issue = "SnapshotTablesInvalid";
      return false;
    }
    return true;
  }
}
