package org.tiqian.layout;

import org.tiqian.core.Cluster;
import org.tiqian.core.IntRange;
import org.tiqian.core.EastAsianSpacingEdges;
import org.tiqian.core.EastAsianSpacingValue;
import org.tiqian.core.InlineObjectPreferredStretch;
import org.tiqian.core.InlineObjectPreferredStretchKind;
import org.tiqian.font.FontRole;
import org.tiqian.layout.ProgressiveBreakDecisions.ProgressiveBreakTier;
import org.tiqian.layout.ProgressiveBreakDecisions.ShrinkChannel;
import org.tiqian.layout.LineOptimization.PushInAllocation;
import org.tiqian.layout.LineOptimization.RepairOption;
import std.SortedSet;

@:dataClass class JustificationOpportunity { public final targetClusterIndex:Int; public final kind:GlueKind; public final priority:Int; public final capacity:Float; public final reason:Null<String>; public function new(targetClusterIndex:Int,kind:GlueKind,priority:Int,capacity:Float,?reason:Null<String>){this.targetClusterIndex=targetClusterIndex;this.kind=kind;this.priority=priority;this.capacity=capacity;this.reason=reason;} }
@:dataClass class JustificationAllocation { public final targetClusterIndex:Int; public final kind:GlueKind; public final priority:Int; public final delta:Float; public final reason:String; public function new(targetClusterIndex:Int,kind:GlueKind,priority:Int,delta:Float,reason:String){this.targetClusterIndex=targetClusterIndex;this.kind=kind;this.priority=priority;this.delta=delta;this.reason=reason;} }
@:dataClass class JustificationPlan { public final lineClusterRange:IntRange; public final allocations:Array<JustificationAllocation>; public final deficitBefore:Float; public final unfilledDeficit:Float; public final fallbackReason:Null<String>; public function new(lineClusterRange:IntRange,allocations:Array<JustificationAllocation>,deficitBefore:Float,unfilledDeficit:Float,?fallbackReason:Null<String>){this.lineClusterRange=lineClusterRange;this.allocations=allocations;this.deficitBefore=deficitBefore;this.unfilledDeficit=unfilledDeficit;this.fallbackReason=fallbackReason;} }
@:dataClass class CompressionPlan { public final allocations:Array<PushInAllocation>; public final surplusBefore:Float; public final unfilledSurplus:Float; public function new(allocations:Array<PushInAllocation>,surplusBefore:Float,unfilledSurplus:Float){this.allocations=allocations;this.surplusBefore=surplusBefore;this.unfilledSurplus=unfilledSurplus;} }

@:dataClass class ShrinkOpportunity { public final clusterIndex:Int; public final tier:Int; public final capacity:Float; public final channel:ShrinkChannel; public function new(clusterIndex:Int,tier:Int,capacity:Float,channel:ShrinkChannel){this.clusterIndex=clusterIndex;this.tier=tier;this.capacity=capacity;this.channel=channel;} }

class Justifier {
 public var wordSpaceMaxEm:Float; public var progressiveTechnicalWhitespaceStretchMaxEm:Float;
 public function new(?wordSpaceMaxEm:Null<Float>,?progressiveTechnicalWhitespaceStretchMaxEm:Null<Float>){this.wordSpaceMaxEm=wordSpaceMaxEm==null?0.5:wordSpaceMaxEm;this.progressiveTechnicalWhitespaceStretchMaxEm=progressiveTechnicalWhitespaceStretchMaxEm==null?0.25:progressiveTechnicalWhitespaceStretchMaxEm;}
 public function progressiveTechnicalWhitespaceStretchCapacity(fontSize:Float):Float return progressiveTechnicalWhitespaceStretchMaxEm*fontSize;
 public function justify(adjustedClusters:Array<Cluster>,clusterRoles:Array<FontRole>,eastAsianSpacingEdges:Array<EastAsianSpacingEdges>,lineClusterRange:IntRange,maxWidth:Float,fontSize:Float,skip:Bool,?skipReason:Null<String>,?allowSinoWesternGapStretch:Bool=true, cjkLatinSpaceBaseEm:Float, cjkLatinSpaceMaxEm:Float,?noStretchBoundaryClusters:Null<SortedSet<Int>>,?noStretchBoundaryAfterClusters:Null<SortedSet<Int>>,?westernBracketCjkInterCharBoundaryAfterClusters:Null<SortedSet<Int>>,?attachedInlinePhysicalBoundaryAfterClusters:Null<SortedSet<Int>>,?attachedInlineVirtualBoundaryAfterClusters:Null<SortedMap<Int,Int>>,?attachedInlineVirtualSinoWesternBoundaryAfterClusters:Null<SortedSet<Int>>,?uniformInlineObjectBoundaryAfterClusters:Null<SortedSet<Int>>,?preferredInlineObjectBoundaryAfterClusters:Null<SortedMap<Int,InlineObjectPreferredStretch>>,?technicalBoundaryAfterClusters:Null<SortedMap<Int,ProgressiveBreakTier>>,?emergencyTrackingBoundaryAfterClusters:Null<SortedMap<Int,String>>,?preferredEmergencyTrackingBoundaryAfterClusters:Null<SortedMap<Int,String>>):JustificationPlan {
  final closed=noStretchBoundaryClusters==null?SortedSet.builder().build():noStretchBoundaryClusters; final closedAfter=noStretchBoundaryAfterClusters==null?SortedSet.builder().build():noStretchBoundaryAfterClusters;
  final bracket=westernBracketCjkInterCharBoundaryAfterClusters==null?SortedSet.builder().build():westernBracketCjkInterCharBoundaryAfterClusters; final physical=attachedInlinePhysicalBoundaryAfterClusters==null?SortedSet.builder().build():attachedInlinePhysicalBoundaryAfterClusters; final virtual=attachedInlineVirtualBoundaryAfterClusters==null?SortedMap.builder().build():attachedInlineVirtualBoundaryAfterClusters; final virtualSino=attachedInlineVirtualSinoWesternBoundaryAfterClusters==null?SortedSet.builder().build():attachedInlineVirtualSinoWesternBoundaryAfterClusters; final uniform=uniformInlineObjectBoundaryAfterClusters==null?SortedSet.builder().build():uniformInlineObjectBoundaryAfterClusters;
  if(clusterRoles.length!=adjustedClusters.length) throw new org.tiqian.core.TiqianIllegalArgumentException(org.tiqian.core.TextRangeError.Message("clusterRoles must align with adjustedClusters.")); if(eastAsianSpacingEdges.length!=adjustedClusters.length) throw new org.tiqian.core.TiqianIllegalArgumentException(org.tiqian.core.TextRangeError.Message("East_Asian_Spacing values must align with adjustedClusters."));
  var width=0.0; var i=lineClusterRange.start; while(i<=lineClusterRange.end){if(i>=0&&i<adjustedClusters.length)width+=adjustedClusters[i].advance;i++;} final deficit=Math.max(maxWidth-width,0); if(skip||deficit<=0)return new JustificationPlan(lineClusterRange,[],deficit,deficit,skip?skipReason:null);
  var rem=deficit; final out:Array<JustificationAllocation>=[];
  function isClosed(left:Int,right:Int):Bool return closedAfter.has(left)||closed.has(left)||closed.has(right);
  function preferredGlue(k:InlineObjectPreferredStretchKind):GlueKind return switch(k){case PunctuationTrailing:GlueKind.InlineObjectPunctuationTrailing;case Relation:GlueKind.InlineObjectRelation;case BinaryOperator:GlueKind.InlineObjectBinaryOperator;};
  function preferredReason(k:InlineObjectPreferredStretchKind):String return switch(k){case PunctuationTrailing:"InlineObjectPunctuationTrailing";case Relation:"InlineObjectRelation";case BinaryOperator:"InlineObjectBinaryOperator";};
  function addTier(kind:GlueKind,priority:Int,capacity:Float,reason:String,pred:Int->Bool):Void { if(rem<=0||capacity<=0)return; final opp:Array<JustificationOpportunity>=[]; var j=lineClusterRange.start; while(j<lineClusterRange.end){if(pred(j)&&!isClosed(j,j+1))opp.push(new JustificationOpportunity(j,kind,priority,capacity,reason));j++;} allocate(opp,reason,capacity); }
  function allocate(opp:Array<JustificationOpportunity>,reason:String,cap:Float):Void {if(opp.length==0)return; var total=0.0; var oi=0; while(oi<opp.length){total+=opp[oi].capacity;oi++;} if(total<=0)return;final f=Math.min(1,rem/total);oi=0;while(oi<opp.length){final o=opp[oi];final d=o.capacity*f;if(d>0)out.push(new JustificationAllocation(o.targetClusterIndex,o.kind,o.priority,d,o.reason==null?reason:o.reason));oi++;}rem-=total*f;}
  final tech=technicalBoundaryAfterClusters; addTier(GlueKind.ProgressiveTechnical,0,progressiveTechnicalWhitespaceStretchCapacity(fontSize),"ProgressiveTechnicalWhitespaceStretch",function(j){return tech!=null&&tech.get(j)==ProgressiveBreakTier.Whitespace&&StringTools.trim(adjustedClusters[j].text)=="";});
  addTier(GlueKind.WordSpace,0,Math.max(wordSpaceMaxEm*fontSize,0),"WordSpace",function(j){return j>0&&j<adjustedClusters.length-1&&adjustedClusters[j].text!=""&&StringTools.trim(adjustedClusters[j].text)==""&&eastAsianSpacingEdges[j-1].trailing==EastAsianSpacingValue.Narrow&&eastAsianSpacingEdges[j+1].leading==EastAsianSpacingValue.Narrow&&adjustedClusters[j].advance>0;});
  if(allowSinoWesternGapStretch){addTier(GlueKind.CjkLatinSpace,1,Math.max((cjkLatinSpaceMaxEm-cjkLatinSpaceBaseEm)*fontSize,0),"CjkLatinSpace",function(j){return j+1<eastAsianSpacingEdges.length&&eastAsianSpacingEdges[j].trailing!=eastAsianSpacingValue(eastAsianSpacingEdges[j+1].leading)&&isWideNarrow(eastAsianSpacingEdges[j].trailing,eastAsianSpacingEdges[j+1].leading)&&adjustedClusters[j].text.indexOf(" ")<0;});}
  var pref=preferredInlineObjectBoundaryAfterClusters; if(pref!=null){var keys=pref.keys(); var ki=0; while(ki<keys.length){var key=keys[ki];var p=pref.get(key);if(p!=null&&key>=lineClusterRange.start&&key<lineClusterRange.end&&!isClosed(key,key+1))allocate([new JustificationOpportunity(key,preferredGlue(p.kind),2,p.capacity,preferredReason(p.kind))],preferredReason(p.kind),0);ki++;}}
  var hasCjk=false; i=lineClusterRange.start;while(i<=lineClusterRange.end){if(i>=0&&i<eastAsianSpacingEdges.length&&eastAsianSpacingEdges[i].containsWide)hasCjk=true;i++;}
  if(rem>0&&(hasCjk||uniform.size()>0)){addTier(GlueKind.CjkInterChar,3,rem,"CjkInterChar",function(j){return (clusterRoles[j]==FontRole.CjkText||clusterRoles[j]==FontRole.CjkPunctuation)&&(clusterRoles[j+1]==FontRole.CjkText||clusterRoles[j+1]==FontRole.CjkPunctuation)||isWideNarrow(eastAsianSpacingEdges[j].trailing,eastAsianSpacingEdges[j+1].leading)||bracket.has(j)||virtual.exists(j)&&!uniform.has(j);});}
  return new JustificationPlan(lineClusterRange,out,deficit,Math.max(rem,0),rem>0&&!hasCjk?"WesternDominantLineNaturalSpacing":null);
 }
 public function compress(surplus:Float,shrinkOpportunities:Array<ShrinkOpportunity>):CompressionPlan {if(surplus<=0)return new CompressionPlan([],surplus,0);var rem=surplus;final out:Array<PushInAllocation>=[];var a=shrinkOpportunities.filter(function(x)return x.capacity>0);var tier=-1;var group:Array<ShrinkOpportunity>=[];function flush():Void{if(group.length==0)return;var total=0.0;var gi=0;while(gi<group.length){total+=group[gi].capacity;gi++;}var f=Math.min(1,rem/total);gi=0;while(gi<group.length){var o=group[gi];var d=o.capacity*f;if(d>0)out.push(new PushInAllocation(o.clusterIndex,d,o.capacity,o.channel));gi++;}rem-=total*f;group=[];}var ai=0;while(ai<a.length){var o=a[ai];if(tier>=0&&o.tier!=tier){flush();if(rem<=0)break;}tier=o.tier;group.push(o);ai++;}flush();return new CompressionPlan(out,surplus,Math.max(rem,0));}
}
function eastAsianSpacingValue(x:EastAsianSpacingValue):EastAsianSpacingValue return x;
function isWideNarrow(a:EastAsianSpacingValue,b:EastAsianSpacingValue):Bool return (a==EastAsianSpacingValue.Wide&&b==EastAsianSpacingValue.Narrow)||(a==EastAsianSpacingValue.Narrow&&b==EastAsianSpacingValue.Wide);
