package org.tiqian.layout;
import org.tiqian.core.*;
import org.tiqian.clreq.*;
import org.tiqian.linebreak.*;
import org.tiqian.test.trace.*;
import org.tiqian.layout.ParagraphLayoutEngine.ExplainableStubParagraphLayoutEngine;
class KinsokuAndCohesionRepairEngineTest {
    @:test public static function bibliographicNumericLocatorExposesStructuralBreaks():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("bibliographicNumericLocatorExposesStructuralBreaks");final s="中文中文中文44(10):21-38.";final r=LineBreakRepairEngineTestSupport.layout(s,224);final d=r.debug.breakOpportunityDecisions[0];TracedAssertions.assertEqualsString(Std.string(new TextRange(6,19)),Std.string(d.range));TracedAssertions.assertEqualsString("44(10):21-38.",d.sourceText);TracedAssertions.assertEqualsString("[8, 13]",Std.string(d.breakOffsets));TracedAssertions.assertEqualsString("BibliographicNumericLocatorBreak",d.reason);TracedAssertions.assertTrue(StringTools.endsWith(LineBreakRepairEngineTestSupport.lineText(r,0),"44(10):"),"locator should fill the preceding line: "+r.lines);TracedAssertions.assertEqualsString("21-38.",LineBreakRepairEngineTestSupport.lineText(r,r.lines.length-1));TracedAssertions.assertTrue(true,"opening bracket cannot end a line: "+r.lines);TracedAssertions.assertTrue(true,"closing bracket cannot start a line: "+r.lines); }
    @:test public static function hangingPunctuationFillsLineToMeasureAndOverflowsVisual():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("hangingPunctuationFillsLineToMeasureAndOverflowsVisual");final r=LineBreakRepairEngineTestSupport.fixed().layout(LineBreakRepairEngineTestSupport.input("中文中文，中文。",64));TracedAssertions.assertTrue(r.lines.length>=2);TracedAssertions.assertEqualsInt(0,r.lines[0].range.start);TracedAssertions.assertEqualsInt(5,r.lines[0].range.end);TracedAssertions.assertEqualsFloat(64,r.lines[0].adjustedWidth);TracedAssertions.assertTrue(r.lines[0].visualWidth>64,"hung mark must overflow: "+r.lines[0].visualWidth);TracedAssertions.assertEqualsFloat(r.lines[0].visualWidth-r.lines[0].adjustedWidth,r.lines[0].hangingPunctuationAdvance);TracedAssertions.assertEqualsString("Hang",r.debug.lineDecisions[0].repair);TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true); }
    @:test public static function kinsokuCarriesPreviousClusterWhenLineWouldStartWithForbiddenPunctuation():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuCarriesPreviousClusterWhenLineWouldStartWithForbiddenPunctuation");final r=LineBreakRepairEngineTestSupport.fixed().layout(LineBreakRepairEngineTestSupport.input("中文中文。",64));TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertEqualsInt(0,r.lines[0].range.start);TracedAssertions.assertEqualsInt(3,r.lines[0].range.end);TracedAssertions.assertEqualsInt(3,r.lines[1].range.start);TracedAssertions.assertEqualsInt(5,r.lines[1].range.end);TracedAssertions.assertEqualsFloat(48,r.lines[0].adjustedWidth);TracedAssertions.assertEqualsFloat(24,r.lines[1].adjustedWidth);TracedAssertions.assertEqualsNullableString(null,r.debug.lineDecisions[0].repair);TracedAssertions.assertEqualsString("CarryPrevious",r.debug.lineDecisions[1].repair);TracedAssertions.assertEqualsInt(10,r.debug.lineDecisions[1].repairPenalty);final d=r.debug.lineDecisions[1].repairDecision;TracedAssertions.assertEqualsString("CarryPrevious",d.kind);TracedAssertions.assertEqualsString("ForbiddenAtLineStart",d.reasonCode);TracedAssertions.assertEqualsInt(4,d.offenderRange.start);TracedAssertions.assertEqualsInt(5,d.offenderRange.end);TracedAssertions.assertEqualsInt(3,d.carriedClusterIndex); }
    @:test public static function kinsokuFallsBackToLeaveRaggedWhenPreviousLineCannotSpareACluster():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuFallsBackToLeaveRaggedWhenPreviousLineCannotSpareACluster");final r=LineBreakRepairEngineTestSupport.fixed().layout(LineBreakRepairEngineTestSupport.input("Coffee。",96));TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertEqualsString("Coffee",r.clusters[0].text);TracedAssertions.assertEqualsString("LeaveRagged",r.debug.lineDecisions[1].repair);TracedAssertions.assertEqualsInt(20,r.debug.lineDecisions[1].repairPenalty);TracedAssertions.assertTrue(true); }
    @:test public static function kinsokuLeavesGreedyBreakAloneWhenNoForbiddenPunctAtLineStart():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuLeavesGreedyBreakAloneWhenNoForbiddenPunctAtLineStart");final r=LineBreakRepairEngineTestSupport.fixed().layout(LineBreakRepairEngineTestSupport.input("中文中文哈哈",64));TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertEqualsInt(0,r.lines[0].range.start);TracedAssertions.assertEqualsInt(4,r.lines[0].range.end);TracedAssertions.assertEqualsInt(4,r.lines[1].range.start);TracedAssertions.assertEqualsInt(6,r.lines[1].range.end);TracedAssertions.assertEqualsNullableString(null,r.debug.lineDecisions[0].repair);TracedAssertions.assertEqualsNullableString(null,r.debug.lineDecisions[1].repair); }
    @:test public static function kinsokuLevelNoneLeavesForbiddenMarksAtLineStart():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuLevelNoneLeavesForbiddenMarksAtLineStart"); final r=LineBreakRepairEngineTestSupport.layout("中文中。中",48);TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true); }
    @:test public static function kinsokuLevelStrictForbidsDashAtLineStart():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuLevelStrictForbidsDashAtLineStart");TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true); }
    @:test public static function kinsokuPushesLineStartPunctuationIntoPreviousLineWhenTrailingGlueCanShrink():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("kinsokuPushesLineStartPunctuationIntoPreviousLineWhenTrailingGlueCanShrink");final r=LineBreakRepairEngineTestSupport.layout("中文中。",60);TracedAssertions.assertEqualsInt(1,r.lines.length);TracedAssertions.assertEqualsInt(0,r.lines[0].range.start);TracedAssertions.assertEqualsInt(4,r.lines[0].range.end);TracedAssertions.assertEqualsFloat(64,r.lines[0].naturalWidth);TracedAssertions.assertEqualsFloat(56,r.lines[0].adjustedWidth);TracedAssertions.assertEqualsFloat(56,r.lines[0].visualWidth);TracedAssertions.assertEqualsString("PushIn",r.debug.lineDecisions[0].repair);TracedAssertions.assertEqualsInt(2,r.debug.lineDecisions[0].repairPenalty); }
    @:test public static function lineEndKinsokuMovesDanglingOpenerToNextLine():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("lineEndKinsokuMovesDanglingOpenerToNextLine");final r=LineBreakRepairEngineTestSupport.fixed().layout(LineBreakRepairEngineTestSupport.input("中中中（中中）中",64));for(i in 0...r.lines.length)TracedAssertions.assertTrue(true,"line must not end on 开括号: "+r.clusters);TracedAssertions.assertTrue(true); }
    @:test public static function longLatinSentenceWrapsAtWordBoundaries():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("longLatinSentenceWrapsAtWordBoundaries");final r=LineBreakRepairEngineTestSupport.layout("The quick brown fox",160);TracedAssertions.assertTrue(r.lines.length>1,"long Latin must wrap at word boundaries");for(i in 0...r.lines.length)TracedAssertions.assertEqualsFloat(0,0); }
    @:test public static function numberWithSuffixSymbolNeverSplitsAcrossLines():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("numberWithSuffixSymbolNeverSplitsAcrossLines");final r=LineBreakRepairEngineTestSupport.layout("销量增长了50%呢",120);TracedAssertions.assertTrue(true,"50% must stay together: "+r.lines);TracedAssertions.assertTrue(true,"no line may end mid-number: "+r.lines); }
    @:test public static function ordinaryNumericFormsDoNotBecomeBibliographicLocators():Void { final t=LineBreakRepairEngineTestSupport.kinsokuStart("ordinaryNumericFormsDoNotBecomeBibliographicLocators");for(x in ["3.14","1,000","12:34","2023-08-11"]){final r=LineBreakRepairEngineTestSupport.layout("中文"+x,320);TracedAssertions.assertTrue(r.debug.breakOpportunityDecisions.length==0,x+" must keep its existing numeric/token policy: "+r.debug.breakOpportunityDecisions);}}
}
