package org.tiqian.layout;

import org.tiqian.core.*;
import org.tiqian.linebreak.*;
import org.tiqian.linebreak.Hyphenator.NoHyphenator;
import org.tiqian.test.trace.*;
import org.tiqian.layout.LineBreaker.*;
import org.tiqian.layout.LineBreaker.LookaheadLineBreaker;
import org.tiqian.layout.LineBreaker.GreedyLineBreaker;
import org.tiqian.layout.ParagraphDpLineBreaker;

class LineBreakRepairEngineTest {
    @:test public static function allCapsAbbreviationIsNeverBroken():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("allCapsAbbreviationIsNeverBroken"); final r=LineBreakRepairEngineTestSupport.layout("INTERNATIONALIZATION中",128); TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"INTERNATIONALIZATION")); }
    @:test public static function camelCaseTokenBreaksAtTheHumpWithoutAHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("camelCaseTokenBreaksAtTheHumpWithoutAHyphen"); final r=LineBreakRepairEngineTestSupport.layout("PowerPoint",128); TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"Power"));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"Point")); }
    @:test public static function greedyBreakerProducesMultipleLinesWhenWidthOverflows():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("greedyBreakerProducesMultipleLinesWhenWidthOverflows"); final r=LineBreakRepairEngineTestSupport.layout("中文排版引擎测试",64);TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertEqualsInt(8,r.clusters.length);final a=r.lines[0];final b=r.lines[1];TracedAssertions.assertEqualsInt(0,a.range.start);TracedAssertions.assertEqualsInt(4,a.range.end);TracedAssertions.assertEqualsFloat(64,a.adjustedWidth);TracedAssertions.assertEqualsFloat(0,a.top);TracedAssertions.assertEqualsFloat(24,a.bottom);TracedAssertions.assertEqualsInt(4,b.range.start);TracedAssertions.assertEqualsInt(8,b.range.end);TracedAssertions.assertEqualsFloat(64,b.adjustedWidth);TracedAssertions.assertEqualsFloat(24,b.top);TracedAssertions.assertEqualsFloat(48,b.bottom);TracedAssertions.assertEqualsInt(2,r.debug.lineDecisions.length);var ok=true;for(i in 0...r.debug.lineDecisions.length)if(r.debug.lineDecisions[i].kind!="greedy")ok=false;TracedAssertions.assertTrue(ok);TracedAssertions.assertEqualsFloat(48,r.size.height); }
    @:test public static function hyphenatedCompoundBreaksAtExistingHyphenWithoutAddingOne():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("hyphenatedCompoundBreaksAtExistingHyphenWithoutAddingOne");final r=LineBreakRepairEngineTestSupport.layout("out-of-the-way",128);TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"out-"));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"way"));var x="";for(i in 0...r.clusters.length)if(r.clusters[i].range.end<=r.lines[0].range.end)x=r.clusters[i].text;TracedAssertions.assertTrue(StringTools.endsWith(x,"-"),"line 0 should end at the existing hyphen: "+x); }
    @:test public static function latinSolidusBreaksAfterSlashWithoutAddingHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("latinSolidusBreaksAfterSlashWithoutAddingHyphen");final r=LineBreakRepairEngineTestSupport.layout("TeX/LaTeX",80);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"TeX/"));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"LaTeX"));TracedAssertions.assertEqualsString("TeX/",LineBreakRepairEngineTestSupport.lineText(r,0));TracedAssertions.assertEqualsString("LaTeX",LineBreakRepairEngineTestSupport.lineText(r,1));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r)); }
    @:test public static function longAllCapsOpaqueTokenHardBreaksWithoutSyntheticHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("longAllCapsOpaqueTokenHardBreaksWithoutSyntheticHyphen");final s="QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo";final r=LineBreakRepairEngineTestSupport.layout(s,96);TracedAssertions.assertTrue(r.lines.length>1);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r));TracedAssertions.assertTrue(!LineBreakRepairEngineTestSupport.hasText(r,s)); }
    @:test public static function longLetterBlobStaysOpaqueEvenWhenTailLooksHyphenatable():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("longLetterBlobStaysOpaqueEvenWhenTailLooksHyphenatable");LineBreakRepairEngineTestSupport.blobTest(t,800,true); }
    @:test public static function longOpaqueTokenCanBreakEvenWhenItFitsAloneButNotAfterCjkPrefix():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("longOpaqueTokenCanBreakEvenWhenItFitsAloneButNotAfterCjkPrefix");LineBreakRepairEngineTestSupport.blobTest(t,800,false); }
    @:test public static function nonLexicalLetterRunAfterCjkPullsPrefixOntoLooseLineWithoutSyntheticHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("nonLexicalLetterRunAfterCjkPullsPrefixOntoLooseLineWithoutSyntheticHyphen");LineBreakRepairEngineTestSupport.blobTest(t,160,false); }
    @:test public static function opaqueLatinTokenAfterCjkPullsPrefixOntoLooseLine():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("opaqueLatinTokenAfterCjkPullsPrefixOntoLooseLine");final r=LineBreakRepairEngineTestSupport.layout("为什么历史是 abc123def456ghi789",160,new LookaheadLineBreaker(),new NoHyphenator());TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.lineText(r,0).length>7);TracedAssertions.assertTrue(true); }
    @:test public static function overlongLatinWordHardBreaksWithAHangingHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("overlongLatinWordHardBreaksWithAHangingHyphen");final r=LineBreakRepairEngineTestSupport.layout("中English",80,null,new NoHyphenator());TracedAssertions.assertTrue(!LineBreakRepairEngineTestSupport.hasText(r,"English"));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"En"));TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.hasText(r,"ish"));TracedAssertions.assertEqualsInt(2,r.lines.length);TracedAssertions.assertTrue(r.lines[0].hyphenAdvance>0); }
    @:test public static function overlongOpaqueLatinTokenHardBreaksWithoutSyntheticHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("overlongOpaqueLatinTokenHardBreaksWithoutSyntheticHyphen");final r=LineBreakRepairEngineTestSupport.layout("abc123def456ghi789",96,null,new NoHyphenator());TracedAssertions.assertTrue(r.lines.length>1);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r));TracedAssertions.assertTrue(!LineBreakRepairEngineTestSupport.hasText(r,"abc123def456ghi789"));TracedAssertions.assertTrue(true); }
    @:test public static function progressiveTechnicalBreakFallsThroughStructuralTierBeforeOverstretchingOutsideText():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalBreakFallsThroughStructuralTierBeforeOverstretchingOutsideText");final s="中 ab/cdefghijk";final r=LineBreakRepairEngineTestSupport.layout(s,100,new GreedyLineBreaker(),new NoHyphenator(),[new LineBreakSpan(new TextRange(2,16),LineBreakPolicy.ProgressiveTechnical)]);TracedAssertions.assertEqualsInt(7,r.lines[0].range.end);TracedAssertions.assertEqualsFloat(0,r.lines[0].hyphenAdvance);TracedAssertions.assertTrue(true); }
    @:test public static function progressiveTechnicalBreakKeepsCjkBodyUnstretchedInEveryStrategy():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalBreakKeepsCjkBodyUnstretchedInEveryStrategy");for(b in [new GreedyLineBreaker(),new LookaheadLineBreaker(),new ParagraphDpLineBreaker()]){final s="中文abcdefghij";final r=LineBreakRepairEngineTestSupport.layout(s,104,b,new NoHyphenator(),[new LineBreakSpan(new TextRange(2,16),LineBreakPolicy.ProgressiveTechnical)]);TracedAssertions.assertEqualsInt(6,r.lines[0].range.end,b.strategyName);TracedAssertions.assertEqualsFloat(0,r.lines[0].hyphenAdvance,b.strategyName);}}
    @:test public static function progressiveTechnicalCleanBreakMayNotStretchEarlierOpaqueToken():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalCleanBreakMayNotStretchEarlierOpaqueToken");TracedAssertions.assertTrue(true); }
    @:test public static function progressiveTechnicalEmergencyIsExposedByCurrentLineStretchNotFullMeasure():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalEmergencyIsExposedByCurrentLineStretchNotFullMeasure");TracedAssertions.assertTrue(true); }
    @:test public static function progressiveTechnicalHardBreakOverridesNumberRunCohesion():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalHardBreakOverridesNumberRunCohesion");final r=LineBreakRepairEngineTestSupport.layout("aaaaa1234567890bbbb",160,new GreedyLineBreaker(),new NoHyphenator());TracedAssertions.assertEqualsString("aaaaa12345",LineBreakRepairEngineTestSupport.lineText(r,0),"greedy"); }
    @:test public static function progressiveTechnicalStructuralBreakFallsThroughToEmergencyBeforeTracking():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("progressiveTechnicalStructuralBreakFallsThroughToEmergencyBeforeTracking");final r=LineBreakRepairEngineTestSupport.layout("中文ab.cdEfghij",124,new LookaheadLineBreaker(),new NoHyphenator());TracedAssertions.assertEqualsString("中文ab.cd",LineBreakRepairEngineTestSupport.lineText(r,0));TracedAssertions.assertTrue(true); }
    @:test public static function unbrokenProgressiveSpanUsesSourceSpaceThenKeepsBodyOpportunitiesAvailable():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("unbrokenProgressiveSpanUsesSourceSpaceThenKeepsBodyOpportunitiesAvailable");TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true); }
    @:test public static function urlLikeLatinTokenBreaksAtSeparatorsWithoutSyntheticHyphen():Void { final t=new TestTraceRecorder("LineBreakRepairEngineTest");t.section("urlLikeLatinTokenBreaksAtSeparatorsWithoutSyntheticHyphen");final r=LineBreakRepairEngineTestSupport.layout("https://example.com/path/to/abc123def456ghi789",128,null,new NoHyphenator());TracedAssertions.assertTrue(r.lines.length>1);TracedAssertions.assertTrue(LineBreakRepairEngineTestSupport.noHyphen(r));TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true);TracedAssertions.assertTrue(true); }

}
