package org.tiqian.layout;
import org.tiqian.core.*;
import org.tiqian.test.trace.*;
import org.tiqian.layout.LineOptimization.RepairOption;
import org.tiqian.layout.ProgressiveBreakDecisions.ShrinkOpportunity;
import org.tiqian.layout.ProgressiveBreakDecisions.ShrinkChannel;
import org.tiqian.layout.ProgressiveBreakDecisions.UnbreakableRanges;
import org.tiqian.layout.ProgressiveBreakDecisions.ProgressiveBreakTier;
class ParagraphDpLineBreakerTest {
 static function rec(n:String):Void new TestTraceRecorder("ParagraphDpLineBreakerTest").section(n);
 static function c(i:Int,t:String,a:Float):Cluster return ParagraphDpLineBreakerTestSupport.cluster(i,t,a);
 public static function compressedSameTierBoundaryIsNotReportedAsPromotion():Void { rec("compressedSameTierBoundaryIsNotReportedAsPromotion"); var cs=[c(0,"a",30),c(1,"/",30),c(2,"b",25),c(3,"c",30),c(4,"d",30)]; var s=ParagraphDpLineBreakerTestSupport.solve(cs,80,[new ShrinkOpportunity(2,2,5,ShrinkChannel.RawAdvance)],null,true,null,ParagraphDpLineBreakerTestSupport.opportunities([2,3],[new TextRange(0,5),new TextRange(0,5)],[ProgressiveBreakTier.Emergency,ProgressiveBreakTier.Emergency])); ParagraphDpLineBreakerTestSupport.tiles(s,5); TracedAssertions.assertEqualsInt(0,s.lines[0].clusterRange.start); TracedAssertions.assertEqualsInt(2,s.lines[0].clusterRange.end); TracedAssertions.assertTrue(s.lines[0].repair!=null); }
 public static function tilesAllClustersInOrder():Void { rec("tilesAllClustersInOrder"); var s=ParagraphDpLineBreakerTestSupport.solve(ParagraphDpLineBreakerTestSupport.han(23),100); ParagraphDpLineBreakerTestSupport.tiles(s,23); TracedAssertions.assertEqualsString("ParagraphEnd",Type.enumConstructor(s.lines[s.lines.length-1].endReason)); }
 public static function singleLineWhenEverythingFits():Void { rec("singleLineWhenEverythingFits"); var s=ParagraphDpLineBreakerTestSupport.solve(ParagraphDpLineBreakerTestSupport.han(4),400); TracedAssertions.assertEqualsInt(1,s.lines.length); TracedAssertions.assertEqualsString("ParagraphEnd",Type.enumConstructor(s.lines[0].endReason)); }
 public static function mandatoryBreakBindsControlToPreviousLine():Void { rec("mandatoryBreakBindsControlToPreviousLine"); var cs=[c(0,"中",16),c(1,"中",16),c(2,"\n",0),c(3,"中",16),c(4,"中",16)]; var s=ParagraphDpLineBreakerTestSupport.solve(cs,200,null,[2]); ParagraphDpLineBreakerTestSupport.tiles(s,5); TracedAssertions.assertEqualsInt(2,s.lines.length); TracedAssertions.assertEqualsString("MandatoryBreak",Type.enumConstructor(s.lines[0].endReason)); TracedAssertions.assertEqualsInt(0,s.lines[0].clusterRange.start); TracedAssertions.assertEqualsInt(2,s.lines[0].clusterRange.end); TracedAssertions.assertEqualsString("ParagraphEnd",Type.enumConstructor(s.lines[1].endReason)); }
 public static function trailingMandatoryBreakEmitsParagraphEndLine():Void { rec("trailingMandatoryBreakEmitsParagraphEndLine"); var s=ParagraphDpLineBreakerTestSupport.solve([c(0,"中",16),c(1,"\n",0)],200,null,[1]); TracedAssertions.assertEqualsString("MandatoryBreak",Type.enumConstructor(s.lines[0].endReason)); TracedAssertions.assertEqualsString("ParagraphEnd",Type.enumConstructor(s.lines[s.lines.length-1].endReason)); TracedAssertions.assertTrue(s.lines[s.lines.length-1].clusterRange.start>s.lines[s.lines.length-1].clusterRange.end); }
 public static function neverBreaksInsideUnbreakableRange():Void { rec("neverBreaksInsideUnbreakableRange"); var s=ParagraphDpLineBreakerTestSupport.solve(ParagraphDpLineBreakerTestSupport.han(10),64,null,null,null,new UnbreakableRanges([new IntRange(3,6)])); ParagraphDpLineBreakerTestSupport.tiles(s,10); for(l in s.lines) if(l.clusterRange.start<=l.clusterRange.end) TracedAssertions.assertTrue(!(l.clusterRange.start>=4&&l.clusterRange.start<=6)); }
 public static function kinsokuAvoidanceRoutesAroundForbiddenLineStart():Void { rec("kinsokuAvoidanceRoutesAroundForbiddenLineStart"); var cs=ParagraphDpLineBreakerTestSupport.han(7); cs[6]=c(6,"。",16); var s=ParagraphDpLineBreakerTestSupport.solve(cs,48); ParagraphDpLineBreakerTestSupport.tiles(s,7); for(l in s.lines) if(l.clusterRange.start<=l.clusterRange.end) TracedAssertions.assertTrue(l.clusterRange.start!=6||l.repair!=null); }
 public static function compressionEdgeRecordsPushInRepair():Void { rec("compressionEdgeRecordsPushInRepair"); var cs=ParagraphDpLineBreakerTestSupport.han(7); cs[3]=c(3,"，",16); var s=ParagraphDpLineBreakerTestSupport.solve(cs,56,[new ShrinkOpportunity(3,5,8,ShrinkChannel.TrailingGlue)],null,true); ParagraphDpLineBreakerTestSupport.tiles(s,7); TracedAssertions.assertTrue(s.lines.length>0); }
 public static function compressionDisabledWithoutPushInFlag():Void { rec("compressionDisabledWithoutPushInFlag"); var cs=ParagraphDpLineBreakerTestSupport.han(5); cs[3]=c(3,"，",16); var s=ParagraphDpLineBreakerTestSupport.solve(cs,56,[new ShrinkOpportunity(3,5,8,ShrinkChannel.TrailingGlue)],null,false); ParagraphDpLineBreakerTestSupport.tiles(s,5); TracedAssertions.assertTrue(s.lines.length>0); }
 public static function overWideSingleClusterStillProgresses():Void { rec("overWideSingleClusterStillProgresses"); var s=ParagraphDpLineBreakerTestSupport.solve([c(0,"中",16),c(1,"Ｗ",300),c(2,"中",16)],48); ParagraphDpLineBreakerTestSupport.tiles(s,3); }
}
