package org.tiqian.layout;
import org.tiqian.core.Cluster;
import org.tiqian.core.TextRange;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;
class ProgressiveBreakDecisionsCoverageTest {
 static var span=new TextRange(0,5);
 static function c(i:Int,?text:Null<String>,?a:Null<Float>):Cluster return new Cluster(new TextRange(i,i+1),text==null?"中":text,"test",a==null?16:a,text==null?"中":text);
 static function op(t:ProgressiveBreakTier,s:TextRange,?cap:Null<Float>):ProgressiveBreakOpportunity return new ProgressiveBreakOpportunity(t,s,cap);
 static function m(a:Array<Int>):Map<Int,Bool>{var x=new Map<Int,Bool>();for(i in a)x.set(i,true);return x;}
 static function run(n:String,f:Void->Void):Void{new TestTraceRecorder("ProgressiveBreakDecisionsCoverageTest").section(n);f();}
 public static function defaultsAdmitTheCleanTierWithoutGeometryInputs():Void run("defaultsAdmitTheCleanTierWithoutGeometryInputs",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(1,op(Whitespace,span));o.set(2,op(Emergency,span));TracedAssertions.assertEqualsInt(1,ProgressiveBreakDecisions.decideProgressiveBreak(0,2,o));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,2,3,o));});
 public static function lineStartAtTheOverflowBoundaryScansAnEmptyRange():Void run("lineStartAtTheOverflowBoundaryScansAnEmptyRange",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(2,op(Emergency,span));TracedAssertions.assertEqualsInt(2,ProgressiveBreakDecisions.decideProgressiveBreak(2,2,o));});
 public static function twoSameTierBoundariesPickTheRightmost():Void run("twoSameTierBoundariesPickTheRightmost",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(2,op(Whitespace,span));o.set(4,op(Whitespace,span));TracedAssertions.assertEqualsInt(4,ProgressiveBreakDecisions.decideProgressiveBreak(0,4,o,[for(i in 0...5)c(i)],64, null,8));});
 public static function visiblyLooseCleanTiersFallThroughToEmergency():Void run("visiblyLooseCleanTiersFallThroughToEmergency",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(2,op(Whitespace,span));o.set(4,op(Emergency,span));TracedAssertions.assertEqualsInt(4,ProgressiveBreakDecisions.decideProgressiveBreak(0,4,o,[for(i in 0...5)c(i)],200,null,8));});
 public static function aLeftwardEmergencyBoundaryKeepsTheBestCleanTier():Void run("aLeftwardEmergencyBoundaryKeepsTheBestCleanTier",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(2,op(Emergency,span));o.set(4,op(Whitespace,span));TracedAssertions.assertEqualsInt(4,ProgressiveBreakDecisions.decideProgressiveBreak(0,4,o,[for(i in 0...5)c(i)],200,null,8));});
 public static function spanEdgeAndWhitespaceClustersDoNotCountAsTechnicalUnits():Void run("spanEdgeAndWhitespaceClustersDoNotCountAsTechnicalUnits",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();var s=new TextRange(1,4);o.set(2,op(Whitespace,s));o.set(3,op(Emergency,s));TracedAssertions.assertEqualsInt(3,ProgressiveBreakDecisions.decideProgressiveBreak(0,3,o,[c(0),c(1," "),c(2,"a"),c(3,"b")],200,null,8));});
 public static function singleTechnicalUnitFallsBackToTheCjkGapDensity():Void run("singleTechnicalUnitFallsBackToTheCjkGapDensity",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();var s=new TextRange(0,1);o.set(1,op(Whitespace,s));o.set(2,op(Emergency,s));TracedAssertions.assertEqualsInt(2,ProgressiveBreakDecisions.decideProgressiveBreak(0,2,o,[c(0,"a"),c(1,"b"),c(2,"c")],200,m([1]),8));});
 public static function candidateOutsideTheClusterListIsAllowed():Void run("candidateOutsideTheClusterListIsAllowed",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(1,op(Emergency,span));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,1,5,o,[c(0)]));});
 public static function candidatesOutsideTheActiveSpanAreAllowed():Void run("candidatesOutsideTheActiveSpanAreAllowed",function(){var cs=[for(i in 0...4)c(i)];var a=new TextRange(5,10);var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(1,op(Emergency,a));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,1,2,o,cs));var t=new Map<Int,ProgressiveBreakOpportunity>();t.set(1,op(Emergency,new TextRange(0,2)));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,1,2,t,cs));var z=new Map<Int,ProgressiveBreakOpportunity>();z.set(1,op(Emergency,new TextRange(0,4)));TracedAssertions.assertFalse(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,1,2,z,cs));});
 public static function candidatesOfADifferentSpanAreAllowed():Void run("candidatesOfADifferentSpanAreAllowed",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(1,op(Emergency,new TextRange(0,2)));o.set(3,op(Whitespace,new TextRange(2,6)));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,1,3,o));});
 public static function sameTierPastTheRawGreedyIsAllowedAndWorseTiersAreNot():Void run("sameTierPastTheRawGreedyIsAllowedAndWorseTiersAreNot",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(2,op(Whitespace,span));o.set(3,op(Whitespace,span));o.set(4,op(Emergency,span));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,2,3,o));TracedAssertions.assertFalse(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,2,4,o));});
 public static function candidatesBeforeTheRawGreedyMustMatchTheSelectedBoundary():Void run("candidatesBeforeTheRawGreedyMustMatchTheSelectedBoundary",function(){var o=new Map<Int,ProgressiveBreakOpportunity>();o.set(1,op(Whitespace,span));o.set(2,op(Whitespace,span));o.set(3,op(Emergency,span));TracedAssertions.assertTrue(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,3,2,o));TracedAssertions.assertFalse(ProgressiveBreakDecisions.progressiveCandidateAllowed(0,3,1,o));});
 static function hy(n:String,limit:Float,g:Map<Int,Bool>,?s:Null<Map<Int,Bool>>,?cap:Null<Float>):Int{var cs=[for(i in 0...4)c(i)];return ProgressiveBreakDecisions.decideHyphenBreak(0,3,cs,limit,m([3]),g,8,s,cap);}
 public static function hyphenBreakReturnsOverflowAtPlainWordBoundaries():Void run("hyphenBreakReturnsOverflowAtPlainWordBoundaries",function(){TracedAssertions.assertEqualsInt(1,ProgressiveBreakDecisions.decideHyphenBreak(0,1,[c(0),c(1),c(2)],16,m([]),m([]),8));});
 public static function overLongWordsMustHyphenateFromTheLineStart():Void run("overLongWordsMustHyphenateFromTheLineStart",function(){TracedAssertions.assertEqualsInt(2,ProgressiveBreakDecisions.decideHyphenBreak(0,2,[c(0),c(1),c(2)],48,m([0,1,2]),m([]),8));});
 public static function aFittingWholeWordBreaksThere():Void run("aFittingWholeWordBreaksThere",function(){TracedAssertions.assertEqualsInt(1,ProgressiveBreakDecisions.decideHyphenBreak(0,2,[c(0),c(1),c(2)],16,m([2]),m([]),8));});
 public static function sinoWesternGapsAbsorbingTheDeficitKeepTheWholeWord():Void run("sinoWesternGapsAbsorbingTheDeficitKeepTheWholeWord",function(){TracedAssertions.assertEqualsInt(2,hy("x",40,m([1]),m([1]),8));});
 public static function gaplessOrTooLooseLinesHyphenateInstead():Void run("gaplessOrTooLooseLinesHyphenateInstead",function(){TracedAssertions.assertEqualsInt(3,hy("x",60,m([2])));TracedAssertions.assertEqualsInt(3,hy("x",100,m([1])));TracedAssertions.assertEqualsInt(2,ProgressiveBreakDecisions.decideHyphenBreak(0,3,[c(0),c(1),c(2),c(3)],36,m([3]),m([1]),8));});
 public static function flush():Void {new TestTraceRecorder("ProgressiveBreakDecisionsCoverageTest").flush();}
}
