package org.tiqian.layout;

import org.tiqian.core.Cluster;
import org.tiqian.core.ClusterGeometryDecisionInfo;
import org.tiqian.core.InlineAttachment;
import org.tiqian.core.IntRange;
import org.tiqian.core.LineEdgeTrimDecisionInfo;
import org.tiqian.core.SpacingDecisionInfo;
import org.tiqian.core.TextRange;
import org.tiqian.layout.LineOptimization.LineCandidate;
import org.tiqian.layout.PunctuationModel.PunctuationAnchor;
import org.tiqian.layout.PunctuationModel.PunctuationAtom;
import org.tiqian.layout.PunctuationModel.PunctuationSpacingCompressionResult;
import org.tiqian.clreq.PunctuationClass;
import std.SortedMap;

class PunctuationGeometryLedger {
 public final naturalClusters:Array<Cluster>; public final geometries:SortedMap<Int,PunctuationClusterGeometry>; public final budgets:SortedMap<Int,GlueBudget>;
 public final justificationDeltaByCluster:SortedMap<Int,Float>; public final rawEdgeTrimByCluster:SortedMap<Int,Float>; public final rubySpreadByCluster:SortedMap<Int,Float>; public final inlineBoxAdvanceByCluster:SortedMap<Int,Float>; public final attachedInlineTrailingGlueByCluster:SortedMap<Int,Float>;
 public function new(n:Array<Cluster>,g:SortedMap<Int,PunctuationClusterGeometry>,b:SortedMap<Int,GlueBudget>,?d:SortedMap<Int,Float>,?r:SortedMap<Int,Float>,?s:SortedMap<Int,Float>,?i:SortedMap<Int,Float>,?a:SortedMap<Int,Float>){naturalClusters=n;geometries=g;budgets=b;justificationDeltaByCluster=d==null?emptyF():d;rawEdgeTrimByCluster=r==null?emptyF():r;rubySpreadByCluster=s==null?emptyF():s;inlineBoxAdvanceByCluster=i==null?emptyF():i;attachedInlineTrailingGlueByCluster=a==null?emptyF():a;}
 static function emptyF():SortedMap<Int,Float> return SortedMap.builder().build();
 static function cloneF(x:SortedMap<Int,Float>):SortedMap<Int,Float>{final b=SortedMap.builder();for(k in x.keys())b.put(k,x.get(k));return b.build();}
 static function cloneB(x:SortedMap<Int,GlueBudget>):SortedMap<Int,GlueBudget>{final b=SortedMap.builder();for(k in x.keys())b.put(k,x.get(k));return b.build();}
 static function replace(x:PunctuationGeometryLedger,?d:SortedMap<Int,Float>,?r:SortedMap<Int,Float>,?s:SortedMap<Int,Float>,?i:SortedMap<Int,Float>,?a:SortedMap<Int,Float>,?b:SortedMap<Int,GlueBudget>):PunctuationGeometryLedger return new PunctuationGeometryLedger(x.naturalClusters,x.geometries,b==null?x.budgets:b,d==null?x.justificationDeltaByCluster:d,r==null?x.rawEdgeTrimByCluster:r,s==null?x.rubySpreadByCluster:s,i==null?x.inlineBoxAdvanceByCluster:i,a==null?x.attachedInlineTrailingGlueByCluster:a);
 public static function from(cs:Array<Cluster>,atoms:Array<PunctuationAtom>,plan:PunctuationSpacingCompressionResult):PunctuationGeometryLedger {final g=SortedMap.builder();for(i in 0...cs.length){final aa=atoms.filter(x->isInside(x.range,cs[i].range));if(aa.length>0){final body=aa.map(x->x.bodyWidth).sumOfFloat(x->x);g.put(i,new PunctuationClusterGeometry(cs[i].range,cs[i].text,cs[i].displayText,cs[i].advance,body,aa[0].leadingGlue.natural,aa[aa.length-1].trailingGlue.natural,aa[0].leadingGlueInitiallyConsumed,aa[aa.length-1].trailingGlueInitiallyConsumed,aa.length==1?aa[0].glyphInlineShift:0,aa.length==1?aa[0].glyphPlacementReason:null,aa.length==1?aa[0].anchor:null,aa[0].geometrySource));}}final bb=SortedMap.builder();for(k in g.keys()){final z=g.get(k);bb.put(k,new GlueBudget(z.leadingGlueNatural,z.leadingGlueInitiallyConsumed,z.trailingGlueNatural,z.trailingGlueInitiallyConsumed));}return new PunctuationGeometryLedger(cs,g,bb).consumeSpacing(plan);}
 public function resolveClusters():Array<Cluster>{return naturalClusters.map((c,i)->{final v=resolvedAdvance(i,c);final sh=geometries.has(i)?geometries.get(i).glyphInlineShift:0;return v==c.advance&&sh==0?c:new Cluster(c.range,c.text,c.fontKey,v,c.displayText,c.glyphInlineShift+sh);});}
 function resolvedAdvance(i:Int,c:Cluster):Float{final raw=rawEdgeTrimByCluster.has(i)?rawEdgeTrimByCluster.get(i):0,sp=rubySpreadByCluster.has(i)?rubySpreadByCluster.get(i):0,d=justificationDeltaByCluster.has(i)?justificationDeltaByCluster.get(i):0,att=attachedInlineTrailingGlueByCluster.has(i)?attachedInlineTrailingGlueByCluster.get(i):0,box=inlineBoxAdvanceByCluster.has(i)?inlineBoxAdvanceByCluster.get(i):0;if(!geometries.has(i))return Math.max(0,c.advance+d+sp+att-raw);final g=geometries.get(i);if(!budgets.has(i))return Math.max(0,g.bodyWidth+box+d+sp-raw);final b=budgets.get(i);return Math.max(0,g.bodyWidth+box+b.leadingRemaining+b.trailingRemaining+d+sp+att-raw);}
 public function withInlineBoxAdvances(m:SortedMap<Int,Float>):PunctuationGeometryLedger return m.size()==0?this:replace(this,null,null,null,m);
 public function withRubySpread(m:SortedMap<Int,Float>):PunctuationGeometryLedger return m.size()==0?this:replace(this,null,null,m);
 public function withRawEdgeTrims(m:SortedMap<Int,Float>):PunctuationGeometryLedger{if(m.size()==0)return this;final n=cloneF(rawEdgeTrimByCluster);for(k in m.keys())n.put(k,(n.has(k)?n.get(k):0)+m.get(k));return replace(this,null,n);}
 public function addJustificationDeltas(m:SortedMap<Int,Float>):PunctuationGeometryLedger return replace(this,m);
 function consumeSide(m:SortedMap<Int,Float>,lead:Bool):PunctuationGeometryLedger{final n=cloneB(budgets);for(k in m.keys())if(n.has(k)&&m.get(k)>0){final q=n.get(k);if(lead)n.put(k,new GlueBudget(q.leadingNatural,Math.min(q.leadingNatural,q.leadingConsumed+m.get(k)),q.trailingNatural,q.trailingConsumed));else n.put(k,new GlueBudget(q.leadingNatural,q.leadingConsumed,q.trailingNatural,Math.min(q.trailingNatural,q.trailingConsumed+m.get(k))));}return replace(this,null,null,null,null,null,n);}
 public function consumeLeadingByCluster(m:SortedMap<Int,Float>):PunctuationGeometryLedger return consumeSide(m,true); public function consumeTrailingByCluster(m:SortedMap<Int,Float>):PunctuationGeometryLedger return consumeSide(m,false);
 public function glueCapacities():SortedMap<Int,GlueCapacity>{final b=SortedMap.builder();for(k in budgets.keys()){final q=budgets.get(k);if(q.leadingRemaining>0||q.trailingRemaining>0)b.put(k,new GlueCapacity(q.leadingRemaining,q.trailingRemaining,geometries.has(k)&&geometries.get(k).anchor==PunctuationAnchor.Center));}return b.build();}
 public function toDecisionInfo():Array<ClusterGeometryDecisionInfo>{final r:Array<ClusterGeometryDecisionInfo>=[];for(k in geometries.keys()){final g=geometries.get(k),b=budgets.get(k);r.push(new ClusterGeometryDecisionInfo(g.range,g.sourceText,g.displayText,g.baseAdvance,g.bodyWidth,b.leadingNatural,b.leadingConsumed,b.trailingNatural,b.trailingConsumed,justificationDeltaByCluster.has(k)?justificationDeltaByCluster.get(k):0,resolvedAdvance(k,naturalClusters[k]),"PunctuationGeometryLedger",g.reason,rubySpreadByCluster.has(k)?rubySpreadByCluster.get(k):0,g.glyphInlineShift,g.glyphPlacementReason));}return r;}
 function consumeSpacing(p:PunctuationSpacingCompressionResult):PunctuationGeometryLedger{final n=cloneB(budgets);for(a in p.adjustments){var idx=-1;for(i in 0...naturalClusters.length)if(isInside(a.reductionTargetRange,naturalClusters[i].range)){idx=i;break;}if(idx>=0&&n.has(idx)){final q=n.get(idx);if(geometries.get(idx).anchor==PunctuationAnchor.Center){final x=Math.min(a.reduction/2,q.leadingRemaining,q.trailingRemaining);n.put(idx,new GlueBudget(q.leadingNatural,q.leadingConsumed+x,q.trailingNatural,q.trailingConsumed+x));}else if(q.trailingRemaining>=q.leadingRemaining)n.put(idx,new GlueBudget(q.leadingNatural,q.leadingConsumed,q.trailingNatural,Math.min(q.trailingNatural,q.trailingConsumed+a.reduction)));else n.put(idx,new GlueBudget(q.leadingNatural,Math.min(q.leadingNatural,q.leadingConsumed+a.reduction),q.trailingNatural,q.trailingConsumed));}}return replace(this,null,null,null,null,null,n);}
 public function consumeLineEdgeGlue(lines:Array<LineCandidate>,?force:Null<Bool>):LineEdgeTrimResult{if(lines.length==0||budgets.size()==0)return new LineEdgeTrimResult(this,[]);final lead=SortedMap.builder();final trail=SortedMap.builder();final ds:Array<LineEdgeTrimDecisionInfo>=[];final forceEnd=force==null?true:force;for(line in lines){if(line.clusterRange.start>line.clusterRange.end)continue;final idx=line.clusterRange.end;if(forceEnd&&budgets.has(idx)){final q=budgets.get(idx);if(q.trailingRemaining>0){trail.put(idx,q.trailingRemaining);ds.push(new LineEdgeTrimDecisionInfo(line.sourceRange,naturalClusters[idx].range,"trailing",q.trailingRemaining,q.trailingConsumed,q.trailingNatural,"LineEndHalfWidthPunctuation"));}}final st=line.clusterRange.start;if(budgets.has(st)){final q=budgets.get(st);if(q.leadingRemaining>0){lead.put(st,q.leadingRemaining);ds.push(new LineEdgeTrimDecisionInfo(line.sourceRange,naturalClusters[st].range,"leading",q.leadingRemaining,q.leadingConsumed,q.leadingNatural,"LineStartHalfWidthPunctuation"));}}}return new LineEdgeTrimResult(consumeLeadingByCluster(lead).consumeTrailingByCluster(trail),ds);}
 public function resolveAttachedInlinePunctuationBoundaries(a:Array<InlineAttachment>,atoms:Array<PunctuationAtom>,em:Float):AttachedInlinePunctuationBoundaryResult{if(a.length!=naturalClusters.length)throw "Inline attachments must align with punctuation geometry clusters.";return new AttachedInlinePunctuationBoundaryResult(this,emptyF(),[]);}
 public static function isInside(self:TextRange,other:TextRange):Bool return self.start>=other.start&&self.end<=other.end;
 public static function clusterIndexRangeFor(self:Array<Cluster>,r:TextRange):Null<IntRange>{var f=-1,l=-1;for(i in 0...self.length)if(self[i].range.start>=r.start&&self[i].range.end<=r.end){if(f<0)f=i;l=i;}return f<0?null:new IntRange(f,l);}
}
class AttachedInlinePunctuationBoundaryResult {public final geometry:PunctuationGeometryLedger;public final trailingGlueByCluster:SortedMap<Int,Float>;public final decisions:Array<SpacingDecisionInfo>;public function new(g:PunctuationGeometryLedger,t:SortedMap<Int,Float>,d:Array<SpacingDecisionInfo>){geometry=g;trailingGlueByCluster=t;decisions=d;}}
class PunctuationClusterGeometry {public final range:TextRange;public final sourceText:String;public final displayText:String;public final baseAdvance:Float;public final bodyWidth:Float;public final leadingGlueNatural:Float;public final trailingGlueNatural:Float;public final leadingGlueInitiallyConsumed:Float;public final trailingGlueInitiallyConsumed:Float;public final glyphInlineShift:Float;public final glyphPlacementReason:Null<String>;public final anchor:Null<PunctuationAnchor>;public final reason:String;public function new(r:TextRange,s:String,d:String,b:Float,w:Float,ln:Float,tn:Float,lc:Float,tc:Float,sh:Float,pr:Null<String>,a:Null<PunctuationAnchor>,reason:String){range=r;sourceText=s;displayText=d;baseAdvance=b;bodyWidth=w;leadingGlueNatural=ln;trailingGlueNatural=tn;leadingGlueInitiallyConsumed=lc;trailingGlueInitiallyConsumed=tc;glyphInlineShift=sh;glyphPlacementReason=pr;anchor=a;this.reason=reason;}}
class GlueBudget {public final leadingNatural:Float;public final leadingConsumed:Float;public final trailingNatural:Float;public final trailingConsumed:Float;public function new(a:Float,b:Float,c:Float,d:Float){leadingNatural=a;leadingConsumed=b;trailingNatural=c;trailingConsumed=d;}public var leadingRemaining(get,never):Float;function get_leadingRemaining():Float return Math.max(0,leadingNatural-leadingConsumed);public var trailingRemaining(get,never):Float;function get_trailingRemaining():Float return Math.max(0,trailingNatural-trailingConsumed);}
class LineEdgeTrimResult {public final geometry:PunctuationGeometryLedger;public final decisions:Array<LineEdgeTrimDecisionInfo>;public function new(g:PunctuationGeometryLedger,d:Array<LineEdgeTrimDecisionInfo>){geometry=g;decisions=d;}}
class GlueCapacity {public final leading:Float;public final trailing:Float;public final paired:Bool;public function new(l:Float,t:Float,p:Bool){leading=l;trailing=t;paired=p;}}
