package org.tiqian.layout;

import org.tiqian.core.*;
import org.tiqian.layout.PunctuationModel.PunctuationAtomBuilder;
import org.tiqian.layout.PunctuationModel.PunctuationAtom;
import org.tiqian.clreq.PunctuationGluePlacement;
import org.tiqian.clreq.PunctuationWidthPolicy;
import org.tiqian.layout.PunctuationModel.PunctuationSpacingCompressor;
import org.tiqian.layout.PunctuationModel.PunctuationSpacingAdjustment;
import org.tiqian.layout.PunctuationModel.PunctuationSpacingCompressionResult;
import org.tiqian.layout.PunctuationModel.PunctuationInkInput;
import org.tiqian.test.trace.*;
import std.SortedMap;

@:test class PunctuationGeometryLedgerCoverageTest {

    @:test public static function budgetsResolveAdvancesThroughRemainingGlue():Void { throw new IllegalStateException("TODO r10: budgetsResolveAdvancesThroughRemainingGlue"); }
    @:test public static function glueCapacitiesReportSidesAndPairing():Void {PunctuationGeometryLedgerCoverageSupport.start("glueCapacitiesReportSidesAndPairing");var m=PunctuationGeometryLedgerCoverageSupport.ledger(["。","「"]).glueCapacities();TracedAssertions.assertTrue(m.has(1));TracedAssertions.assertEqualsFloat(8,m.get(1).leading);TracedAssertions.assertEqualsFloat(0,m.get(1).trailing);TracedAssertions.assertFalse(m.get(1).paired);}
    @:test public static function sideConsumptionIsCappedAndSkipsNonPositiveAmounts():Void {PunctuationGeometryLedgerCoverageSupport.start("sideConsumptionIsCappedAndSkipsNonPositiveAmounts");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["。","「"]).consumeLeadingByCluster(PunctuationGeometryLedgerCoverageSupport.budgetAt([1],4.0)).glueCapacities();TracedAssertions.assertEqualsFloat(4,x.get(1).leading);var y=PunctuationGeometryLedgerCoverageSupport.ledger(["。","「"]).consumeLeadingByCluster(PunctuationGeometryLedgerCoverageSupport.budgetAt([1],100.0));TracedAssertions.assertFalse(y.glueCapacities().has(1));}
    @:test public static function justificationDeltasAndStructuralChannelsFeedResolvedAdvance():Void { throw new IllegalStateException("TODO r10: justificationDeltasAndStructuralChannelsFeedResolvedAdvance"); }
    @:test public static function geometryWithoutBudgetFallsBackToBodyWidth():Void {PunctuationGeometryLedgerCoverageSupport.start("geometryWithoutBudgetFallsBackToBodyWidth");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["「","中"]);var e=SortedMap.builder().build();var y=new PunctuationGeometryLedger(x.naturalClusters,x.geometries,e);TracedAssertions.assertEqualsFloat(8,y.resolveClusters()[0].advance);}
    @:test public static function decisionInfoListsEveryGeometryWithBudgets():Void {PunctuationGeometryLedgerCoverageSupport.start("decisionInfoListsEveryGeometryWithBudgets");var i=PunctuationGeometryLedgerCoverageSupport.ledger(["。","中"]).toDecisionInfo()[0];TracedAssertions.assertEqualsFloat(8,i.bodyWidth);TracedAssertions.assertEqualsFloat(16,i.resolvedAdvance);TracedAssertions.assertEqualsString("PunctuationGeometryLedger",i.source);}
    @:test public static function spacingPlanAdjustmentsConsumeByTargetAndAnchor():Void {PunctuationGeometryLedgerCoverageSupport.start("spacingPlanAdjustmentsConsumeByTargetAndAnchor");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["「","「"]);TracedAssertions.assertEqualsFloat(8,x.glueCapacities().get(0).leading);var a=new PunctuationSpacingAdjustment(new TextRange(0,1),new TextRange(0,1),"「","「",8,4,4,"test");var y=PunctuationGeometryLedger.from([PunctuationGeometryLedgerCoverageSupport.c("「",0),PunctuationGeometryLedgerCoverageSupport.c("「",1)],[],new PunctuationSpacingCompressionResult([a]));TracedAssertions.assertTrue(y.toDecisionInfo().length==0);}
    @:test public static function attachedInlineBoundariesRequireAlignmentAndRunOnlyWithAttachments():Void {PunctuationGeometryLedgerCoverageSupport.start("attachedInlineBoundariesRequireAlignmentAndRunOnlyWithAttachments");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["。","中"]);TracedAssertions.assertFailsWith(null,function() x.resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None],[],PunctuationGeometryLedgerCoverageSupport.em));var r=x.resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None,InlineAttachment.None],[],PunctuationGeometryLedgerCoverageSupport.em);TracedAssertions.assertTrue(r.decisions.length==0);}
    @:test public static function attachedInlineBoundaryAtLineEndConsumesTrailingGlue():Void {PunctuationGeometryLedgerCoverageSupport.start("attachedInlineBoundaryAtLineEndConsumesTrailingGlue");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["」","ref"]);var r=x.resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None,InlineAttachment.Previous],[],PunctuationGeometryLedgerCoverageSupport.em);TracedAssertions.assertEqualsString("AttachedInlineVirtualPunctuationBoundary:line-end",r.decisions[0].reason);TracedAssertions.assertEqualsFloat(8,r.geometry.resolveClusters()[0].advance);}
    @:test public static function attachedInlineBoundaryAdjacentPunctuationHalvesTheVirtualGlue():Void {PunctuationGeometryLedgerCoverageSupport.start("attachedInlineBoundaryAdjacentPunctuationHalvesTheVirtualGlue");var cs=[PunctuationGeometryLedgerCoverageSupport.c("」",0),PunctuationGeometryLedgerCoverageSupport.c("ref",1),PunctuationGeometryLedgerCoverageSupport.c("「",4)];var atoms:Array<PunctuationAtom>=[];for(q in cs)for(a in PunctuationGeometryStage.punctuationAtoms(q,PunctuationGeometryLedgerCoverageSupport.em,PunctuationGeometryLedgerCoverageSupport.builder,[],PunctuationGluePlacement.MainlandSimplified,new PunctuationWidthPolicy()))atoms.push(a);var r=PunctuationGeometryLedger.from(cs,atoms,new PunctuationSpacingCompressionResult([])).resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None],atoms,PunctuationGeometryLedgerCoverageSupport.em);TracedAssertions.assertEqualsFloat(8,r.decisions[0].adjustedInnerGlue);}
    @:test public static function attachedInlineBoundaryBeforeAsciiPointMarkCollapsesLikeAdjacent():Void {PunctuationGeometryLedgerCoverageSupport.start("attachedInlineBoundaryBeforeAsciiPointMarkCollapsesLikeAdjacent");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["」","ref",","]);var r=x.resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None],[],PunctuationGeometryLedgerCoverageSupport.em);TracedAssertions.assertTrue(r.decisions.length>=1);}
    @:test public static function attachedInlineBoundarySkipsMandatoryBreakNeighbour():Void { throw new IllegalStateException("TODO r10: attachedInlineBoundarySkipsMandatoryBreakNeighbour"); }
    @:test public static function attachedInlineBoundaryWithoutGlueEmitsNoDecision():Void {PunctuationGeometryLedgerCoverageSupport.start("attachedInlineBoundaryWithoutGlueEmitsNoDecision");var r=PunctuationGeometryLedgerCoverageSupport.ledger(["「","ref","中"]).resolveAttachedInlinePunctuationBoundaries([InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None],[],PunctuationGeometryLedgerCoverageSupport.em);TracedAssertions.assertTrue(r.decisions.length==0);}
    @:test public static function lineEdgeTrimConsumesHalfWidthAtEdgesAndSkipsEmptyInputs():Void {PunctuationGeometryLedgerCoverageSupport.start("lineEdgeTrimConsumesHalfWidthAtEdgesAndSkipsEmptyInputs");var x=PunctuationGeometryLedgerCoverageSupport.ledger(["」","中"]);TracedAssertions.assertTrue(x.consumeLineEdgeGlue([]).decisions.length==0);var r=x.consumeLineEdgeGlue([PunctuationGeometryLedgerCoverageSupport.line(0,0)]);TracedAssertions.assertEqualsString("LineEndHalfWidthPunctuation",r.decisions[0].reason);TracedAssertions.assertEqualsFloat(8,r.geometry.resolveClusters()[0].advance);}
    @:test public static function lineEdgeTrimConsumesCentredPunctuationOncePerLine():Void {PunctuationGeometryLedgerCoverageSupport.start("lineEdgeTrimConsumesCentredPunctuationOncePerLine");var atom:PunctuationAtom=PunctuationGeometryLedgerCoverageSupport.builder.build('·',new TextRange(0,1),PunctuationGeometryLedgerCoverageSupport.em,new PunctuationInkInput(16,new Rect(2,4,10,12),8,-2));var x=PunctuationGeometryLedger.from([PunctuationGeometryLedgerCoverageSupport.c("·",0)],[atom],new PunctuationSpacingCompressionResult([]));var r=x.consumeLineEdgeGlue([PunctuationGeometryLedgerCoverageSupport.line(0,0)]);TracedAssertions.assertEqualsString("both",r.decisions[0].side);TracedAssertions.assertEqualsFloat(4,r.decisions[0].trimAmount);}
    @:test public static function clusterIndexRangeFindCoveredClusters():Void {PunctuationGeometryLedgerCoverageSupport.start("clusterIndexRangeFindCoveredClusters");var cs=[PunctuationGeometryLedgerCoverageSupport.c("中",0),PunctuationGeometryLedgerCoverageSupport.c("中",1),PunctuationGeometryLedgerCoverageSupport.c("中",2)];TracedAssertions.assertTrue(PunctuationGeometryLedger.clusterIndexRangeFor(cs,new TextRange(0,3)).start==0);TracedAssertions.assertTrue(PunctuationGeometryLedger.clusterIndexRangeFor(cs,new TextRange(5,6))==null);}
}

/** Shared fixtures and cluster builders for PunctuationGeometryLedgerCoverageTest; the Kotlin test-class lowering admits test functions only. */
class PunctuationGeometryLedgerCoverageSupport {
    public static final em:Float = 16;
    public static final builder = new PunctuationAtomBuilder();
    public static function start(n:String):Void new TestTraceRecorder("PunctuationGeometryLedgerCoverageTest").section(n);
    public static function c(text:String, start:Int, ?advance:Float=16, ?font:String="cjk"):Cluster return new Cluster(new TextRange(start,start+text.length),text,font,advance,text);
    public static function ledger(texts:Array<String>):PunctuationGeometryLedger {
        var cs:Array<Cluster>=[]; var atoms:Array<PunctuationAtom>=[]; var i=0; var pos=0;
        while(i<texts.length){var x=c(texts[i],pos);cs.push(x);var aa=PunctuationGeometryStage.punctuationAtoms(x,em,builder,[],PunctuationGluePlacement.MainlandSimplified,new PunctuationWidthPolicy());for(a in aa)atoms.push(a);pos+=texts[i].length;i++;}
        return PunctuationGeometryLedger.from(cs,atoms,new PunctuationSpacingCompressor().compress(atoms,em));
    }
    public static function budgetAt(entries:Array<Int>, value:Float):SortedMap<Int,Float>{var b=SortedMap.builder();for(k in entries)b.put(k,value);return b.build();}
    public static function line(s:Int,e:Int):LineOptimization.LineCandidate return new LineOptimization.LineCandidate(new IntRange(s,e),new TextRange(s,e+1),32,32);
}
