package org.tiqian.layout;

import org.tiqian.core.IntRange;
import org.tiqian.core.Cluster;
import org.tiqian.core.TextRange;
import org.tiqian.layout.LineOptimization.RepairOption;
import org.tiqian.layout.LineOptimization.RepairOptions;
import org.tiqian.layout.LineOptimization.RepairCandidate;
import org.tiqian.layout.LineBreaker.GreedyLineBreaker;
import org.tiqian.layout.ProgressiveBreakDecisions.ShrinkOpportunity;
import org.tiqian.layout.ProgressiveBreakDecisions.ShrinkChannel;
import org.tiqian.layout.ProgressiveBreakDecisions.UnbreakableRanges;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;

class PushInLineWideCapacityTest {
    @:test public static function pushInAggregatesShrinkFromMultiplePrecedingClusters():Void {
        final t=new TestTraceRecorder("PushInLineWideCapacityTest");t.section("pushInAggregatesShrinkFromMultiplePrecedingClusters"); final c:Array<Cluster>=[];
        for(i in 0...5)c.push(PushInLineWideCapacityTestSupport.cluster(i,i+1,"中",16)); c.push(PushInLineWideCapacityTestSupport.cluster(5,6,"、",16)); for(i in 0...4)c.push(PushInLineWideCapacityTestSupport.cluster(6+i,7+i,"文",16)); c.push(PushInLineWideCapacityTestSupport.cluster(10,11,"。",16));
        final s=new GreedyLineBreaker().breakLines(c,c,160,[new ShrinkOpportunity(5,6,8,ShrinkChannel.TrailingGlue),new ShrinkOpportunity(10,6,8,ShrinkChannel.TrailingGlue)]); final l=s.lines[0];
        TracedAssertions.assertEqualsInt(1,s.lines.length);TracedAssertions.assertEqualsIntRange(new IntRange(0,10),l.clusterRange);TracedAssertions.assertEqualsFloat(160,l.adjustedWidth);TracedAssertions.assertTrue(l.repair!=null);
        switch(l.repair){case PushIn(_,_,off,alloc,shrink,cap): TracedAssertions.assertEqualsInt(10,off);TracedAssertions.assertEqualsFloat(16,shrink);TracedAssertions.assertEqualsFloat(16,cap);TracedAssertions.assertEqualsInt(2,alloc.length); TracedAssertions.assertEqualsInt(10,alloc[0].clusterIndex); TracedAssertions.assertEqualsFloat(8,alloc[0].shrink); TracedAssertions.assertEqualsInt(5,alloc[1].clusterIndex); TracedAssertions.assertEqualsFloat(8,alloc[1].shrink); default: TracedAssertions.fail("expected PushIn");}
    }
    @:test public static function pushInRejectsWhenLineWideCapacityStillInsufficient():Void {
        final t=new TestTraceRecorder("PushInLineWideCapacityTest");t.section("pushInRejectsWhenLineWideCapacityStillInsufficient"); final c=[for(i in 0...11) PushInLineWideCapacityTestSupport.cluster(i,i+1,i==5?"、":i==10?"。":"文",16)]; final s=new GreedyLineBreaker().breakLines(c,c,160,[new ShrinkOpportunity(5,6,4,ShrinkChannel.TrailingGlue)]);
        TracedAssertions.assertEqualsInt(2,s.lines.length);TracedAssertions.assertEqualsIntRange(new IntRange(0,8),s.lines[0].clusterRange);TracedAssertions.assertEqualsIntRange(new IntRange(9,10),s.lines[1].clusterRange);
        switch(s.lines[1].repair){case CarryPrevious(_): TracedAssertions.assertTrue(true); default: TracedAssertions.fail("expected CarryPrevious");}
        var p:Null<RepairCandidate>=null; for(cand in s.lines[1].repairCandidates) if(cand.kind=="PushIn"){p=cand;break;}
        TracedAssertions.assertNotNullRendered(p!=null,"PushIn candidate"); TracedAssertions.assertFalse(p.accepted); TracedAssertions.assertEqualsString("insufficient-capacity",p.rejectionReason); TracedAssertions.assertEqualsFloat(4,p.availableCapacity); TracedAssertions.assertEqualsFloat(16,p.requiredShrink);
    }
    @:test public static function pushInOffenderOnlyCapacityStillWorksBackCompat():Void { final t=new TestTraceRecorder("PushInLineWideCapacityTest");t.section("pushInOffenderOnlyCapacityStillWorksBackCompat"); final c=[PushInLineWideCapacityTestSupport.cluster(0,1,"中",16),PushInLineWideCapacityTestSupport.cluster(1,2,"文",16),PushInLineWideCapacityTestSupport.cluster(2,3,"中",16),PushInLineWideCapacityTestSupport.cluster(3,4,"。",16)]; final s=new GreedyLineBreaker().breakLines(c,c,60,[new ShrinkOpportunity(3,6,4,ShrinkChannel.TrailingGlue)]); TracedAssertions.assertEqualsInt(1,s.lines.length); switch(s.lines[0].repair){case PushIn(_,_,_,alloc,shrink,_): TracedAssertions.assertEqualsInt(1,alloc.length);TracedAssertions.assertEqualsInt(3,alloc[0].clusterIndex);TracedAssertions.assertEqualsFloat(4,shrink); default: TracedAssertions.fail("expected PushIn");} }
    @:test public static function pushInMergesOffenderThatFitsAfterChainedRepairs():Void { final t=new TestTraceRecorder("PushInLineWideCapacityTest");t.section("pushInMergesOffenderThatFitsAfterChainedRepairs"); final c=[for(i in 0...10) PushInLineWideCapacityTestSupport.cluster(i,i+1,i==3?"」":i==4?"。":i==8?"、":"中",16)]; final s=new GreedyLineBreaker().breakLines(c,c,64,[new ShrinkOpportunity(3,6,8,ShrinkChannel.TrailingGlue),new ShrinkOpportunity(4,6,8,ShrinkChannel.TrailingGlue),new ShrinkOpportunity(8,6,8,ShrinkChannel.TrailingGlue)]); TracedAssertions.assertEqualsInt(3,s.lines.length); TracedAssertions.assertEqualsIntRange(new IntRange(0,4),s.lines[0].clusterRange);TracedAssertions.assertEqualsIntRange(new IntRange(5,8),s.lines[1].clusterRange);TracedAssertions.assertEqualsIntRange(new IntRange(9,9),s.lines[2].clusterRange); for(line in s.lines) TracedAssertions.assertEqualsString("中",c[line.clusterRange.start].text); switch(s.lines[1].repair){case PushIn(_,_,_,_,shrink,_): TracedAssertions.assertEqualsFloat(0,shrink); default: TracedAssertions.fail("expected PushIn");} TracedAssertions.assertTrue(RepairOptions.reason(s.lines[1].repair).indexOf("fits-no-shrink")>=0);TracedAssertions.assertEqualsFloat(64,s.lines[1].adjustedWidth); }
    @:test public static function carryPreviousRefusesToSplitUnbreakableSpan():Void { final t=new TestTraceRecorder("PushInLineWideCapacityTest");t.section("carryPreviousRefusesToSplitUnbreakableSpan"); final c=[PushInLineWideCapacityTestSupport.cluster(0,1,"中",16),PushInLineWideCapacityTestSupport.cluster(1,2,"中",16),PushInLineWideCapacityTestSupport.cluster(2,3,"王",16),PushInLineWideCapacityTestSupport.cluster(3,4,"小",16),PushInLineWideCapacityTestSupport.cluster(4,5,"明",16),PushInLineWideCapacityTestSupport.cluster(5,6,"。",16)]; final s=new GreedyLineBreaker().breakLines(c,c,80,[new ShrinkOpportunity(5,6,8,ShrinkChannel.TrailingGlue)],new UnbreakableRanges([new IntRange(2,4)])); TracedAssertions.assertEqualsInt(2,s.lines.length); switch(s.lines[1].repair){case LeaveRagged(_): TracedAssertions.assertTrue(true); default: TracedAssertions.fail("expected LeaveRagged");} final reason=RepairOptions.reason(s.lines[1].repair);TracedAssertions.assertTrue(reason.substr(reason.length-"carry-would-split-mourning-span".length)=="carry-would-split-mourning-span");var carry:Null<RepairCandidate>=null;for(cand in s.lines[1].repairCandidates)if(cand.kind=="CarryPrevious"){carry=cand;break;}TracedAssertions.assertNotNullRendered(carry!=null,"CarryPrevious candidate");TracedAssertions.assertEqualsString("carry-would-split-mourning-span",carry.rejectionReason); }
}
