package org.tiqian.layout;

import org.tiqian.core.*;
import org.tiqian.font.FontRole;
import org.tiqian.test.trace.*;
import org.tiqian.layout.ParagraphLayoutEngine.ExplainableStubParagraphLayoutEngine;
import org.tiqian.layout.LineBreaker.LookaheadLineBreaker;
import org.tiqian.linebreak.Hyphenator.NoHyphenator;
import std.SortedMap;
import std.UString;
import org.tiqian.core.RoleOverrideInfo;
import org.tiqian.core.PunctuationDecisionInfo;
import org.tiqian.layout.QuoteClassificationEngineTestSupport.ProportionalQuoteTextShaper;

class QuoteClassificationEngineTest {
    static function t(n:String):TestTraceRecorder return QuoteClassificationEngineTestSupport.begin(n);
    static function s(expected:Array<Int>, actual:Array<Int>, ?m:String):Void TracedAssertions.assertEqualsIntArray(expected,actual,m);
    static function q(result:LayoutResult, role:String):Void { var a:Array<Int>=[]; for(i in 0...result.debug.roleOverrides.length) if(result.debug.roleOverrides[i].overriddenRole==role) a.push(result.debug.roleOverrides[i].range.start); }

    @:test public static function keepsLatinTechnicalPunctuationInLatinRun():Void { var z=t("keepsLatinTechnicalPunctuationInLatinRun"); var r=QuoteClassificationEngineTestSupport.layout("well-known/path",320); var x=""; var all=true; var any=false; for(ci in 0...r.clusters.length){var c=r.clusters[ci];x+=c.text;all=all&&c.fontKey=="latin-primary";any=any||c.text=="well-";} TracedAssertions.assertEqualsString("well-known/path",x); TracedAssertions.assertTrue(all); TracedAssertions.assertTrue(any); }
    @:test public static function classifiesAsciiBracketsAsLatinRegardlessOfSurroundingContext():Void { var z=t("classifiesAsciiBracketsAsLatinRegardlessOfSurroundingContext"); var r=QuoteClassificationEngineTestSupport.layout("中文(English)中文",320); var c:Cluster=null; for(ci in 0...r.clusters.length){var x=r.clusters[ci]; if(x.text=="(English)") c=x; TracedAssertions.assertEqualsString("latin-primary",c.fontKey); var d=null; for(di in 0...r.debug.fontDecisions.length){var x=r.debug.fontDecisions[di]; if(x.sourceText=="(English)") d=x; TracedAssertions.assertEqualsString("LatinText",d.role); }}}
    @:test public static function classifiesAsciiBracketsAsLatinInsidePureCjkContent():Void { var z=t("classifiesAsciiBracketsAsLatinInsidePureCjkContent"); var r=QuoteClassificationEngineTestSupport.layout("中文(中文)",320); for(ci in 0...r.clusters.length) {var c=r.clusters[ci]; if(c.text=="("||c.text==")") TracedAssertions.assertEqualsString("latin-primary",c.fontKey); }}
    @:test public static function asciiClosingBracketWithCjkInteriorIsForbiddenAtLineStart():Void { var z=t("asciiClosingBracketWithCjkInteriorIsForbiddenAtLineStart"); var text="如今已占据超七成份额(国产品牌)，互联网大厂排队抢购？"; var r=new ExplainableStubParagraphLayoutEngine(null,null,null,null,null,null,null,null,new LookaheadLineBreaker()).layout(QuoteClassificationEngineTestSupport.input(text,232)); var m=""; for(i in 0...r.lines.length){var l=r.lines[i];m+=Std.string(l.clusterRange)+" "+Std.string(l.range)+" "+Std.string(l.endReason)+" \""+UString.slice(text,l.range.start,l.range.end)+"\"\n";} var ok=true; for(li in 0...r.lines.length){var l=r.lines[li]; if(UString.slice(text,l.range.start,l.range.end).indexOf(")")==0)ok=false; TracedAssertions.assertTrue(ok,m); for(i in 0...r.clusters.length) { var c=r.clusters[i]; if(c.text==")")TracedAssertions.assertEqualsString("latin-primary",c.fontKey); } }}
    @:test public static function asciiOpeningBracketWithCjkInteriorIsForbiddenAtLineEnd():Void { var z=t("asciiOpeningBracketWithCjkInteriorIsForbiddenAtLineEnd"); var text="如今已占据超七成份额(国产品牌)，互联网大厂排队抢购？"; var r=new ExplainableStubParagraphLayoutEngine(null,null,null,null,null,null,null,null,new LookaheadLineBreaker()).layout(QuoteClassificationEngineTestSupport.input(text,168)); var m=""; for(i in 0...r.lines.length){var l=r.lines[i];m+=Std.string(l.clusterRange)+" "+Std.string(l.range)+" "+Std.string(l.endReason)+" \""+UString.slice(text,l.range.start,l.range.end)+"\"\n";} var ok=true; for(li in 0...r.lines.length){var l=r.lines[li]; if(UString.slice(text,l.range.start,l.range.end).lastIndexOf("(")==UString.slice(text,l.range.start,l.range.end).length-1)ok=false; TracedAssertions.assertTrue(ok,m); for(i in 0...r.clusters.length) { var c=r.clusters[i]; if(c.text=="(")TracedAssertions.assertEqualsString("latin-primary",c.fontKey); } }}
    @:test public static function keepsTextStartLatinQuotePairInLatinRun():Void { var z=t("keepsTextStartLatinQuotePairInLatinRun"); var r=QuoteClassificationEngineTestSupport.layout("“Hello” world",320); TracedAssertions.assertEquals(3,r.clusters.length); TracedAssertions.assertEqualsString("“Hello”",r.clusters[0].text); TracedAssertions.assertEqualsString("latin-primary",r.clusters[0].fontKey); var ok=false; for(di in 0...r.debug.fontDecisions.length){var d=r.debug.fontDecisions[di];ok=ok||(d.sourceText=="“Hello” world"&&d.role=="LatinText"); TracedAssertions.assertTrue(ok); }}
    @:test public static function mixedQuoteContextsReachTheFontAndPunctuationPipeline():Void { var z=t("mixedQuoteContextsReachTheFontAndPunctuationPipeline"); var text="中“文”中；that’s；（如 ‘O’, ‘Q’）；他说：“She said ‘hello’.”"; var r=QuoteClassificationEngineTestSupport.layout(text,1000); var c=QuoteClassificationEngineTestSupport.indices(text); var ck=QuoteClassificationEngineTestSupport.set([1,3,29,47]); var pq=QuoteClassificationEngineTestSupport.set(c); var roles=SortedMap.builder(); for(i in c)roles.put(i,i==1||i==3||i==29||i==47?"CjkPunctuation":"LatinText"); var a=QuoteClassificationEngineTestSupport.set([1,3,29,47]); var bb=std.SortedSet.builder(); for(di in 0...r.debug.punctuationDecisions.length){var d=r.debug.punctuationDecisions[di];if(QuoteClassificationEngineTestSupport.isCurlyQuoteForTest(d.char))bb.put(d.range.start); var b=bb.build(); TracedAssertions.assertTrue(ck.size()==4&&b.size()==4); var good=true; for(i in c)good=good&&QuoteClassificationEngineTestSupport.roleAt(r,i)==(ck.has(i)?"CjkPunctuation":"LatinText"); TracedAssertions.assertTrue(good); TracedAssertions.assertEqualsIntSet(ck,b); TracedAssertions.assertEqualsString(text,r.input.content.text); }}
    @:test public static function quoteRolesSurviveStyleAndSourceBoundaries():Void { var z=t("quoteRolesSurviveStyleAndSourceBoundaries"); var text="中‘that’s’中"; var r=new ExplainableStubParagraphLayoutEngine().layout(new LayoutInput(new TiqianTextContent(text,[new TextSpan(new TextRange(2,7),new TextStyle(null,null,null,700,null))],[1,2,6,7,8,9],null),null,null,new LayoutConstraints(320))); for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.range.start==1)TracedAssertions.assertEqualsString("CjkPunctuation",d.overriddenRole); for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.range.start==6)TracedAssertions.assertEqualsString("LatinText",d.overriddenRole); for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.range.start==8)TracedAssertions.assertEqualsString("CjkPunctuation",d.overriddenRole); for(c in r.clusters)if(c.range.start==6)TracedAssertions.assertEqualsString("latin-primary",c.fontKey); var x="";for(c in r.clusters)x+=c.text;TracedAssertions.assertEqualsString(text,x); }}}}
    @:test public static function adjacentQuotedListItemsKeepCjkQuoteGeometryAcrossMixedContent():Void { var z=t("adjacentQuotedListItemsKeepCjkQuoteGeometryAcrossMixedContent"); var texts=["便延伸出了“乃子”“大波”“大灯”“大雷”“大扎”“对A”“波霸”这些词","这些太直白了是吧，\n “欧派”“double”“double may”呢"]; for(ti in 0...texts.length){var text=texts[ti];var r=QuoteClassificationEngineTestSupport.layout(text,1000);var qi=QuoteClassificationEngineTestSupport.indices(text);var a:Array<Int>=[];for(di in 0...r.debug.fontDecisions.length){var d=r.debug.fontDecisions[di];if(d.role=="CjkPunctuation"&&qi.indexOf(d.range.start)>=0)a.push(d.range.start);s(qi,a,text);var b:Array<Int>=[];for(di in 0...r.debug.punctuationDecisions.length){var d=r.debug.punctuationDecisions[di];if(QuoteClassificationEngineTestSupport.isCurlyQuoteForTest(d.char))b.push(d.range.start);s(qi,b,text);var f=[QuoteClassificationEngineTestSupport.lastIndex(text,"“"),text.lastIndexOf("”")];var o:Array<Int>=[];for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(f.indexOf(d.range.start)>=0)o.push(d.range.start);s(f,o,text);var good=true;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(f.indexOf(d.range.start)>=0)good=good&&d.source=="PairedPunctuationOuterScriptContext";TracedAssertions.assertTrue(good,text);TracedAssertions.assertEqualsString(text,r.input.content.text);}}}}}}
    @:test public static function mi10sAdjacentLatinTranscriptionsKeepTheFinalQuotePairInCjkContext():Void { var z=t("mi10sAdjacentLatinTranscriptionsKeepTheFinalQuotePairInCjkContext"); var text="所以这个和 “骑ji” “说shui”“斜xiá”不一样，港台是从众的，大陆读音大多数源自韵书。"; var e=new ExplainableStubParagraphLayoutEngine(null,null,null,null,null,null,null,null,new LookaheadLineBreaker(),null, null,new NoHyphenator());var r=e.layout(QuoteClassificationEngineTestSupport.input(text,160));var a:Array<Int>=[];for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.range.start==QuoteClassificationEngineTestSupport.lastIndex(text,"“")||d.range.start==text.lastIndexOf("”"))a.push(d.range.start);s([19,24],a);var ok=true;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(a.indexOf(d.range.start)>=0)ok=ok&&(d.overriddenRole=="CjkPunctuation")&&(d.source=="PairedPunctuationOuterScriptContext");TracedAssertions.assertTrue(ok);var no=true;var lm="";for(i in 0...r.lines.length){var l=r.lines[i];no=no&&UString.slice(text,l.range.start,l.range.end).indexOf("”")!=0;lm+=UString.slice(text,l.range.start,l.range.end);}TracedAssertions.assertTrue(no,lm); }}}
    @:test public static function skipsNeutralDashBeforeLatinQuotePairInLayout():Void { var z=t("skipsNeutralDashBeforeLatinQuotePairInLayout"); var r=QuoteClassificationEngineTestSupport.layout("English — “hello”",320);var ok=false;for(c in r.clusters)if(c.text.indexOf("“hello”")>=0)ok=ok||c.fontKey=="latin-primary";TracedAssertions.assertTrue(ok); }
    @:test public static function keepsSlashLedLatinTechnicalRunOutOfCjkPunctuationGeometry():Void { var z=t("keepsSlashLedLatinTechnicalRunOutOfCjkPunctuationGeometry");var r=QuoteClassificationEngineTestSupport.layout("恐跨/TERFism。如果",320);var d=null;for(di in 0...r.debug.fontDecisions.length){var x=r.debug.fontDecisions[di];if(x.sourceText=="/TERFism")d=x;TracedAssertions.assertEqualsString("LatinText",d.role);var none=true;for(di in 0...r.debug.punctuationDecisions.length){var x=r.debug.punctuationDecisions[di];none=none&&x.range.start!=d.range.start;TracedAssertions.assertTrue(none);for(i in 0...r.clusters.length){var c=r.clusters[i];if(c.text=="/TERFism"){TracedAssertions.assertEqualsString("latin-primary",c.fontKey);TracedAssertions.assertTrue(c.advance>16);}}}}}
    @:test public static function recordsRoleOverridesForResolvedQuotePairs():Void { var z=t("recordsRoleOverridesForResolvedQuotePairs");var r=QuoteClassificationEngineTestSupport.layout("“Hello” world",320);var a:Null<RoleOverrideInfo>=null;var b:Null<RoleOverrideInfo>=null;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];{if(d.range.start==0)a=d;if(d.range.start==6)b=d;}TracedAssertions.assertEqualsNullableString("LatinText",a.overriddenRole);TracedAssertions.assertEqualsNullableString("CjkPunctuation",a.originalRole);TracedAssertions.assertEqualsNullableString("PairedPunctuationOuterScriptContext",a.source);TracedAssertions.assertEqualsNullableString("LatinText",b.overriddenRole);}}
    @:test public static function mixedChineseQuestionAtParagraphStartKeepsCjkQuoteGeometry():Void { var z=t("mixedChineseQuestionAtParagraphStartKeepsCjkQuoteGeometry");var text="“Json是谁？”";var r=QuoteClassificationEngineTestSupport.layout(text,320);var a:Array<Int>=[];for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.range.start==0||d.range.start==8)a.push(d.range.start);s([0,8],a);var ok=true;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(a.indexOf(d.range.start)>=0)ok=ok&&d.overriddenRole=="CjkPunctuation"&&d.source=="ParagraphLanguageQuoteContext";TracedAssertions.assertTrue(ok);var b:Array<Int>=[];for(di in 0...r.debug.punctuationDecisions.length){var d=r.debug.punctuationDecisions[di];if(d.char=="“"||d.char=="”")b.push(d.range.start);s([0,8],b);var x="";for(c in r.clusters)x+=c.text;TracedAssertions.assertEqualsString(text,x);}}}}
    @:test public static function keepsNumberedCjkQuotePairOnCjkFace():Void { var z=t("keepsNumberedCjkQuotePairOnCjkFace");var r=QuoteClassificationEngineTestSupport.layout("1.\u201C\u4F60\u77E5\u9053\u674E\u767D\u662F\u600E\u4E48\u6B7B\u7684\u5417\uFF1F\u201D",320);var d:Dynamic=null;for(di in 0...r.debug.fontDecisions.length){var x=r.debug.fontDecisions[di];if(x.range.start==2)d=x;TracedAssertions.assertEqualsString("CjkPunctuation",d.role);TracedAssertions.assertEqualsString("cjk-primary",d.fontKey);var o:Dynamic=null;for(di in 0...r.debug.roleOverrides.length){var x=r.debug.roleOverrides[di];if(x.range.start==2)o=x;TracedAssertions.assertEqualsString("PairedPunctuationContentScriptContext",o.source);TracedAssertions.assertEqualsString("quoted-content-script",o.reason);TracedAssertions.assertEqualsString("CjkPunctuation",o.overriddenRole);}}}
    @:test public static function requestsFullWidthCjkQuotesAndSynthesizesTheCellWhenTheFontStaysProportional():Void { var z=t("requestsFullWidthCjkQuotesAndSynthesizesTheCellWhenTheFontStaysProportional");var e=new ExplainableStubParagraphLayoutEngine(null,null,null,null,null,null,null,null,null,null,new ProportionalQuoteTextShaper());var r=e.layout(QuoteClassificationEngineTestSupport.input("中“文”中",320));var o:Null<Cluster>=null;var c:Null<Cluster>=null;for(ci in 0...r.clusters.length){var x=r.clusters[ci];{if(x.text=="“")o=x;if(x.text=="”")c=x;}TracedAssertions.assertEqualsFloat(16,o.advance);TracedAssertions.assertEqualsFloat(16,c.advance);TracedAssertions.assertEqualsFloat(10,o.glyphInlineShift);TracedAssertions.assertEqualsFloat(0,c.glyphInlineShift);var a:Null<PunctuationDecisionInfo>=null;var b:Null<PunctuationDecisionInfo>=null;for(di in 0...r.debug.punctuationDecisions.length){var x=r.debug.punctuationDecisions[di];{if(x.char=="“")a=x;if(x.char=="”")b=x;}TracedAssertions.assertEqualsFloat(10,a.advanceExpansion);TracedAssertions.assertEqualsString("UnderwidthPunctuationFullWidthBoxPlacement",a.glyphPlacementReason);TracedAssertions.assertEqualsNullableString(null,b.glyphPlacementReason);TracedAssertions.assertEqualsString("InkBoundsFittedBodyCompression",a.geometrySource);TracedAssertions.assertEqualsString("InkBoundsFittedBodyCompression",b.geometrySource);var p=LayoutQueries.positionedClusters(r);TracedAssertions.assertEqualsFloat(p[0].left+10,p[0].drawX);TracedAssertions.assertEqualsFloat(p[2].left,p[2].drawX);var q=e.layout(QuoteClassificationEngineTestSupport.input("“文",320));TracedAssertions.assertEqualsFloat(8,q.clusters[0].advance);var qp=LayoutQueries.positionedClusters(q);TracedAssertions.assertEqualsFloat(2,qp[0].drawX);TracedAssertions.assertEqualsFloat(8,qp[1].left);}}}
    @:test public static function leavesLatinContextCurlyQuotesOutsideCjkPunctuationGeometry():Void { var z=t("leavesLatinContextCurlyQuotesOutsideCjkPunctuationGeometry");var r=QuoteClassificationEngineTestSupport.layout("“Hello” world",320);var ok=true;for(di in 0...r.debug.punctuationDecisions.length){var d=r.debug.punctuationDecisions[di];ok=ok&&!(d.char=="“"||d.char=="”");TracedAssertions.assertTrue(ok);for(c in r.clusters)TracedAssertions.assertEqualsFloat(0,c.glyphInlineShift);}}
    @:test public static function keepsContractionApostropheLatinInsideCjkSingleQuotes():Void { var z=t("keepsContractionApostropheLatinInsideCjkSingleQuotes");var r=QuoteClassificationEngineTestSupport.layout("中‘that’s’中",320);var a:Dynamic=null;var b:Dynamic=null;var c:Dynamic=null;for(di in 0...r.debug.fontDecisions.length){var d=r.debug.fontDecisions[di];{if(d.range.start==1)a=d;if(d.range.start==2)c=d;if(d.range.start==8)b=d;}TracedAssertions.assertEqualsString("CjkPunctuation",a.role);TracedAssertions.assertEqualsString("LatinText",c.role);TracedAssertions.assertEqualsString("that’s",c.sourceText);TracedAssertions.assertEqualsString("latin-primary",c.fontKey);TracedAssertions.assertEqualsString("CjkPunctuation",b.role);var x:Null<Cluster>=null;for(ci in 0...r.clusters.length){var k=r.clusters[ci];if(k.text=="that’s")x=k;TracedAssertions.assertEqualsString("latin-primary",x.fontKey);var none=true;for(di in 0...r.debug.punctuationDecisions.length){var d=r.debug.punctuationDecisions[di];none=none&&d.range.start!=6;TracedAssertions.assertTrue(none);}}}}
    static function internal(text:String, source:String, role:String, ?section:String):Void { var z=section==null?null:t(section);var r=QuoteClassificationEngineTestSupport.layout(text,320);var a:Array<RoleOverrideInfo>=[];for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.sourceText=="“"||d.sourceText=="”")a.push(d);TracedAssertions.assertEquals(2,a.length);for(d in a){TracedAssertions.assertEqualsString(role,d.overriddenRole);TracedAssertions.assertEqualsString(source,d.source);}}}
    @:test public static function keepsLatinWordInternalCurlyQuotesInLatinRunInsideMixedParagraph():Void {internal("中文 Latin: le“t”ters 中文","NonCjkWordInternalQuotePair","LatinText");}
    @:test public static function supportsSupplementaryLettersInsideLatinWordInternalQuotes():Void {internal("中文 a“𝐀”b 中文","NonCjkWordInternalQuotePair","LatinText");}
    @:test public static function keepsLetterBoundedWordInternalQuotesLatin():Void {internal("中a“b”c文","NonCjkWordInternalQuotePair","LatinText");}
    @:test public static function keepsDigitContentInsideLetterBoundedQuotesLatin():Void {internal("中a“1”c文","NonCjkWordInternalQuotePair","LatinText");}
    @:test public static function keepsDigitBoundedWordInternalQuotesCjk():Void {internal("中1“1”2文","PairedPunctuationOuterScriptContext","CjkPunctuation");}
    @:test public static function keepsFullwidthLetterBoundedWordInternalQuotesCjk():Void {internal("中Ａ“Ｂ”Ｃ文","ParagraphLanguageQuoteContext","CjkPunctuation");}
    @:test public static function keepsEmptyWordInternalQuotesLatin():Void {internal("中文a“”b中文","NonCjkWordInternalQuotePair","LatinText");}
    @:test public static function keepsAstralLetterBoundedWordInternalQuotesLatin():Void {internal("中𝐀“b”𝐁文","NonCjkWordInternalQuotePair","LatinText","keepsAstralLetterBoundedWordInternalQuotesLatin");}
    @:test public static function keepsSpaceInsidePairOutOfWordInternalFastPathLatin():Void {internal("中a“b c”d文","ParagraphLanguageQuoteContext","CjkPunctuation","keepsSpaceInsidePairOutOfWordInternalFastPathLatin");}
    @:test public static function keepsDigitBoundedSingleQuotePairCjkViaEnclosingQuotation():Void {var r=QuoteClassificationEngineTestSupport.layout("尾号是“1‘2’3”。",320);var a=0;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.sourceText=="‘"||d.sourceText=="’"){a++;TracedAssertions.assertEqualsString("CjkPunctuation",d.overriddenRole);TracedAssertions.assertEqualsString("PairedPunctuationEnclosingQuoteContext",d.source);}TracedAssertions.assertEquals(2,a);}}
    @:test public static function resolvesDigitBoundUnmatchedQuotesAsPrimes():Void {var r=QuoteClassificationEngineTestSupport.layout("他用时1’30”，屏幕是6.1”的。",320);var a=0;for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.sourceText=="’"||d.sourceText=="”"){a++;TracedAssertions.assertEqualsString("LatinText",d.overriddenRole);TracedAssertions.assertEqualsString("NumericPrimeUnmatchedQuote",d.source);}TracedAssertions.assertEquals(3,a);}}
    @:test public static function keepsDecadeStyleApostropheWithLetterFlankLatin():Void {var r=QuoteClassificationEngineTestSupport.layout("那是90’s的音乐。",320);for(di in 0...r.debug.roleOverrides.length){var d=r.debug.roleOverrides[di];if(d.sourceText=="’"){TracedAssertions.assertEqualsString("LatinText",d.overriddenRole);TracedAssertions.assertEqualsString("NonCjkInWordApostrophe",d.source);}}}
}
