package org.tiqian.layout;

import org.tiqian.core.Cluster;
import org.tiqian.core.EastAsianSpacingEdges;
import org.tiqian.core.EastAsianSpacingValue;
import org.tiqian.core.InlineAttachment;
import org.tiqian.core.IntRange;
import org.tiqian.core.TextRange;
import org.tiqian.font.FontRole;
import org.tiqian.layout.QuotePairAnalyzer.QuotePair;
import org.tiqian.layout.QuotePairAnalyzer.QuoteType;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;
import std.SortedSet;

class UnicodePunctuationBoundaryResolverCoverageSupport {
    public static function start(n:String):Void new TestTraceRecorder("UnicodePunctuationBoundaryResolverCoverageTest").section(n);
    public static function cjkClusters(t:String):Array<Cluster> { var a:Array<Cluster> = []; var i = 0; while (i < t.length) { final s = t.substring(i, i + 1); a.push(new Cluster(new TextRange(i, i + 1), s, "cjk", 16.0)); i++; } return a; }
    public static function latinClusters(t:String):Array<Cluster> { var a:Array<Cluster> = []; var i = 0; while (i < t.length) { final s = t.substring(i, i + 1); a.push(new Cluster(new TextRange(i, i + 1), s, "latin", 8.0)); i++; } return a; }
    public static function cjkRoles(t:String):Array<FontRole> { var a:Array<FontRole> = []; var i = 0; while (i < t.length) { a.push(FontRole.CjkText); i++; } return a; }
    public static function latinRoles(t:String):Array<FontRole> { var a:Array<FontRole> = []; var i = 0; while (i < t.length) { a.push(FontRole.LatinText); i++; } return a; }
    public static function surrogate(codes:Array<Int>):String { var s = ""; var i = 0; while (i < codes.length) { s += String.fromCharCode(codes[i]); i++; } return s; }
    public static function mapText(m:std.SortedMap<Int,Int>):String { var s = "{"; var i = 0; while (i < m.size()) { if (i > 0) s += ", "; s += m.keyAt(i) + "=" + m.get(m.keyAt(i)); i++; } return s + "}"; }
}

class UnicodePunctuationBoundaryResolverCoverageTest {
    @:test public static function resolveAttachedInlineVirtualBoundariesWithMultiplePrevious():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineVirtualBoundariesWithMultiplePrevious");
        final attachments:Array<InlineAttachment> = [InlineAttachment.None, InlineAttachment.Previous, InlineAttachment.Previous, InlineAttachment.None];
        final r = UnicodePunctuationBoundaryResolver.resolveAttachedInlineVirtualBoundaries(attachments);
        TracedAssertions.assertEquals(1, r.length); TracedAssertions.assertEquals(0, r[0].previousClusterIndex);
        TracedAssertions.assertEqualsIntRange(new IntRange(1, 2), r[0].attachedClusterRange); TracedAssertions.assertEquals(3, r[0].nextClusterIndex);
    }
    @:test public static function resolveAttachedInlineVirtualBoundariesWithNoPrevious():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineVirtualBoundariesWithNoPrevious");
        final attachments:Array<InlineAttachment> = [InlineAttachment.None, InlineAttachment.None];
        final r = UnicodePunctuationBoundaryResolver.resolveAttachedInlineVirtualBoundaries(attachments); TracedAssertions.assertEquals(0, r.length);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithOpenPunctuation():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithOpenPunctuation");
        final text = "\uFF08\u4E2D\u6587\uFF09"; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), []);
        var found = false; var i = 0; while (i < r.decisions.length) { if (r.decisions[i].forbiddenPosition == "LineEnd") { found = true; break; } i++; } TracedAssertions.assertTrue(found);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithPairedQuotes():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPairedQuotes");
        final text = "\u4E2D\u6587\u201C\u4F60\u597D\u201D\u4E2D\u6587"; final pairs:Array<QuotePair> = [new QuotePair(2, 5, QuoteType.Double)];
        final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), pairs);
        var a = false; var b = false; var i = 0; while (i < r.decisions.length) { if (r.decisions[i].reason == "Uax14WesternPunctuationBoundary:PairedOpeningQuote") a = true; if (r.decisions[i].reason == "Uax14WesternPunctuationBoundary:PairedClosingQuote") b = true; i++; }
        TracedAssertions.assertTrue(a); TracedAssertions.assertTrue(b);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithUnmatchedClosingPunctuation():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithUnmatchedClosingPunctuation"); final text = "\u4E2D\u3002"; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), []); TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size() > 0);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithCjkClosingAtLineStart():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCjkClosingAtLineStart"); final text = "\u3002\uFF0C"; final pairs:Array<QuotePair> = [new QuotePair(0, 1, QuoteType.Single)]; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), pairs); var f=false; var i=0; while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;} TracedAssertions.assertTrue(f);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithExclamationMark():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithExclamationMark"); final text="\u4E2D!\u4E2D"; final clusters:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),"!","latin",16.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,clusters,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithInitialQuoteForbidLineEnd():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInitialQuoteForbidLineEnd"); final text="\u4E2D\u201C\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithUnresolvedQuote():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithUnresolvedQuote"); final text="\u4E2D\u2019\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithMultipleClusters():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithMultipleClusters"); final text="\u4E2D\u6587\uFF0C\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithEmptyClusters():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithEmptyClusters"); final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries("",[],[],[]);TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithAllCjkText():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithAllCjkText"); final text="\u4E2D\u6587\u6587\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithWesternClosingForbidLineStart():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithWesternClosingForbidLineStart"); final text="\u4E2D)\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),")","latin",16.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithCjkClosingForbidLineStart():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCjkClosingForbidLineStart"); final text="\u4E2D\u3002\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithOpenPunctuationForbidLineEnd():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithOpenPunctuationForbidLineEnd"); final text="\uFF08\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithPunctuationAndSpace():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPunctuationAndSpace"); final text="\u4E2D \u3002"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2)," ","latin",16.0),new Cluster(new TextRange(2,3),"\u3002","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundary():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundary"); final text="\n\uFF08\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var found=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].sourceText=="\uFF08"&&r.decisions[i].forbiddenPosition=="LineStart"){found=true;break;}i++;}TracedAssertions.assertNullRendered(!found,"-"); }
    @:test public static function resolveUnicodePunctuationBoundariesWithClosePunctuationClass():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithClosePunctuationClass"); final text="\u4E2D\u3002"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithInfixNumericSeparator():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInfixNumericSeparator"); final text="1\uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2),"\uFF0C","cjk",16.0),new Cluster(new TextRange(2,3),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithDecimalMarkAfterSpace():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithDecimalMarkAfterSpace"); final text="1 \uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2)," ","latin",8.0),new Cluster(new TextRange(2,3),"\uFF0C","cjk",16.0),new Cluster(new TextRange(3,4),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithRuleForLineStartInfix():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithRuleForLineStartInfix"); final text="1,2"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);var found=false;var reason="";var i=0;while(i<r.decisions.length){if(r.decisions[i].sourceText==","){found=true;reason=r.decisions[i].reason;break;}i++;}TracedAssertions.assertNotNullRendered(found,found?"present":"null"); TracedAssertions.assertEqualsString("Uax14WesternPunctuationBoundary:LB15d",reason); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithCjkBothCjk():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithCjkBothCjk"); final text="\u4E2D\u6587"; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Narrow,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),e,SortedSet.builder().build(),a);TracedAssertions.assertEquals(0,r.virtualBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithWesternBracket():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithWesternBracket"); final text="(\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"(","latin",8.0),new Cluster(new TextRange(1,2),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);TracedAssertions.assertEquals(0,r.virtualBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithCjkBodyWesternBracket():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithCjkBodyWesternBracket"); final text="\u4E2D)"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),")","latin",8.0)]; final roles:Array<FontRole>=[FontRole.CjkText,FontRole.LatinText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);TracedAssertions.assertEquals(0,r.ordinaryWesternBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesRequiresMatchingClusterRoleEdgeSizes():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesRequiresMatchingClusterRoleEdgeSizes"); final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0)]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None]; TracedAssertions.assertFailsWith(null,()->UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries("ab",c,[FontRole.LatinText,FontRole.LatinText],e,SortedSet.builder().build(),a)); }
    @:test public static function resolveAttachedInlineInterCharBoundariesRequiresMatchingAttachmentSize():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesRequiresMatchingAttachmentSize"); final text="ab"; final c=UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text); final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; TracedAssertions.assertFailsWith(null,()->UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),e,SortedSet.builder().build(),[InlineAttachment.None])); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternNarrowTrailing():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternNarrowTrailing"); final text="a,\u3002"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u3002","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.CjkPunctuation]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesPreviousContentClusterReturnsNull():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesPreviousContentClusterReturnsNull"); final text="  !"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1)," ","test",8.0),new Cluster(new TextRange(1,2)," ","test",8.0),new Cluster(new TextRange(2,3),"!","test",8.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()==0); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNotNarrow():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNotNarrow"); final text="a,\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.CjkPunctuation,FontRole.CjkPunctuation,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNarrowNotCjkPunct():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNarrowNotCjkPunct"); final text="a,\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }
}
