package org.tiqian.layout;

import org.tiqian.core.Cluster;
import org.tiqian.core.ContextualKinsokuDecisionInfo;
import org.tiqian.core.EastAsianSpacingEdges;
import org.tiqian.core.EastAsianSpacingValue;
import org.tiqian.core.InlineAttachment;
import org.tiqian.core.IntRange;
import org.tiqian.core.TextRange;
import org.tiqian.font.FontRole;
import org.tiqian.layout.QuotePairAnalyzer.QuotePair;
import org.tiqian.layout.QuotePairAnalyzer.QuoteType;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TracedAssertions;
import std.SortedSet;

class UnicodePunctuationBoundaryResolverCoverageSupport {
    public static function start(n:String):Void new TestTraceRecorder("UnicodePunctuationBoundaryResolverCoverageTest").section(n);
    public static function cjkClusters(t:String):Array<Cluster> { var a:Array<Cluster> = []; var i = 0; while (i < t.length) { final s = t.substring(i, i + 1); a.push(new Cluster(new TextRange(i, i + 1), s, "cjk", 16.0)); i++; } return a; }
    public static function latinClusters(t:String):Array<Cluster> { var a:Array<Cluster> = []; var i = 0; while (i < t.length) { final s = t.substring(i, i + 1); a.push(new Cluster(new TextRange(i, i + 1), s, "latin", 8.0)); i++; } return a; }
    public static function cjkRoles(t:String):Array<FontRole> { var a:Array<FontRole> = []; var i = 0; while (i < t.length) { a.push(FontRole.CjkText); i++; } return a; }
    public static function latinRoles(t:String):Array<FontRole> { var a:Array<FontRole> = []; var i = 0; while (i < t.length) { a.push(FontRole.LatinText); i++; } return a; }
    public static function surrogate(codes:Array<Int>):String { var s = ""; var i = 0; while (i < codes.length) { s += String.fromCharCode(codes[i]); i++; } return s; }
    public static function mapText(m:std.SortedMap<Int,Int>):String { var s = "{"; var i = 0; while (i < m.size()) { if (i > 0) s += ", "; s += m.keyAt(i) + "=" + m.get(m.keyAt(i)); i++; } return s + "}"; }
}

class UnicodePunctuationBoundaryResolverCoverageTest {
    @:test public static function resolveAttachedInlineVirtualBoundariesWithMultiplePrevious():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineVirtualBoundariesWithMultiplePrevious");
        final attachments:Array<InlineAttachment> = [InlineAttachment.None, InlineAttachment.Previous, InlineAttachment.Previous, InlineAttachment.None];
        final r = UnicodePunctuationBoundaryResolver.resolveAttachedInlineVirtualBoundaries(attachments);
        TracedAssertions.assertEquals(1, r.length);
        TracedAssertions.assertEquals(0, r[0].previousClusterIndex);
        TracedAssertions.assertEqualsIntRange(new IntRange(1, 2), r[0].attachedClusterRange);
        TracedAssertions.assertEquals(3, r[0].nextClusterIndex);
    }
    @:test public static function resolveAttachedInlineVirtualBoundariesWithNoPrevious():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineVirtualBoundariesWithNoPrevious");
        final attachments:Array<InlineAttachment> = [InlineAttachment.None, InlineAttachment.None];
        final r = UnicodePunctuationBoundaryResolver.resolveAttachedInlineVirtualBoundaries(attachments);
        TracedAssertions.assertEquals(0, r.length);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithOpenPunctuation():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithOpenPunctuation");
        final text = "\uFF08\u4E2D\u6587\uFF09"; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), []);
        var found = false; var i = 0; while (i < r.decisions.length) { if (r.decisions[i].forbiddenPosition == "LineEnd") { found = true; break; } i++; } TracedAssertions.assertTrue(found);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithPairedQuotes():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPairedQuotes");
        final text = "\u4E2D\u6587\u201C\u4F60\u597D\u201D\u4E2D\u6587"; final pairs:Array<QuotePair> = [new QuotePair(2, 5, QuoteType.Double)];
        final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), pairs);
        var a = false; var b = false; var i = 0; while (i < r.decisions.length) { if (r.decisions[i].reason == "Uax14WesternPunctuationBoundary:PairedOpeningQuote") a = true; if (r.decisions[i].reason == "Uax14WesternPunctuationBoundary:PairedClosingQuote") b = true; i++; }
        TracedAssertions.assertTrue(a);
        TracedAssertions.assertTrue(b);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithUnmatchedClosingPunctuation():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithUnmatchedClosingPunctuation"); final text = "\u4E2D\u3002"; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), []);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size() > 0);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithCjkClosingAtLineStart():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCjkClosingAtLineStart"); final text = "\u3002\uFF0C"; final pairs:Array<QuotePair> = [new QuotePair(0, 1, QuoteType.Single)]; final r = UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text, UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text), UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text), pairs); var f=false; var i=0; while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;} TracedAssertions.assertTrue(f);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithExclamationMark():Void {
        UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithExclamationMark"); final text="\u4E2D!\u4E2D"; final clusters:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),"!","latin",16.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,clusters,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f);
    }
    @:test public static function resolveUnicodePunctuationBoundariesWithInitialQuoteForbidLineEnd():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInitialQuoteForbidLineEnd"); final text="\u4E2D\u201C\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithUnresolvedQuote():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithUnresolvedQuote"); final text="\u4E2D\u2019\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithMultipleClusters():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithMultipleClusters"); final text="\u4E2D\u6587\uFF0C\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithEmptyClusters():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithEmptyClusters"); final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries("",[],[],[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithAllCjkText():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithAllCjkText"); final text="\u4E2D\u6587\u6587\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithWesternClosingForbidLineStart():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithWesternClosingForbidLineStart"); final text="\u4E2D)\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),")","latin",16.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithCjkClosingForbidLineStart():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCjkClosingForbidLineStart"); final text="\u4E2D\u3002\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithOpenPunctuationForbidLineEnd():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithOpenPunctuationForbidLineEnd"); final text="\uFF08\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithPunctuationAndSpace():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPunctuationAndSpace"); final text="\u4E2D \u3002"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2)," ","latin",16.0),new Cluster(new TextRange(2,3),"\u3002","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundary():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundary"); final text="\n\uFF08\u4E2D\u6587"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);var hit:ContextualKinsokuDecisionInfo=null;var i=0;while(i<r.decisions.length){if(r.decisions[i].sourceText=="\uFF08"&&r.decisions[i].forbiddenPosition=="LineStart"){hit=r.decisions[i];break;}i++;}TracedAssertions.assertEqualsRendered("-",hit==null?"-":Std.string(hit)); }
    @:test public static function resolveUnicodePunctuationBoundariesWithClosePunctuationClass():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithClosePunctuationClass"); final text="\u4E2D\u3002"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithInfixNumericSeparator():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInfixNumericSeparator"); final text="1\uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2),"\uFF0C","cjk",16.0),new Cluster(new TextRange(2,3),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithDecimalMarkAfterSpace():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithDecimalMarkAfterSpace"); final text="1 \uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2)," ","latin",8.0),new Cluster(new TextRange(2,3),"\uFF0C","cjk",16.0),new Cluster(new TextRange(3,4),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithRuleForLineStartInfix():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithRuleForLineStartInfix"); final text="1,2"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);var hit:ContextualKinsokuDecisionInfo=null;var i=0;while(i<r.decisions.length){if(r.decisions[i].sourceText==","){hit=r.decisions[i];break;}i++;}TracedAssertions.assertNotNullRendered(hit!=null,hit==null?"null":Std.string(hit));
        TracedAssertions.assertEqualsString("Uax14WesternPunctuationBoundary:LB15d",hit==null?"":hit.reason); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithCjkBothCjk():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithCjkBothCjk"); final text="\u4E2D\u6587"; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Narrow,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),e,SortedSet.builder().build(),a);
        TracedAssertions.assertEquals(0,r.virtualBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithWesternBracket():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithWesternBracket"); final text="(\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"(","latin",8.0),new Cluster(new TextRange(1,2),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertEquals(0,r.virtualBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithCjkBodyWesternBracket():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithCjkBodyWesternBracket"); final text="\u4E2D)"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),")","latin",8.0)]; final roles:Array<FontRole>=[FontRole.CjkText,FontRole.LatinText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertEquals(0,r.ordinaryWesternBoundaryAfterClusters.size()); }
    @:test public static function resolveAttachedInlineInterCharBoundariesRequiresMatchingClusterRoleEdgeSizes():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesRequiresMatchingClusterRoleEdgeSizes"); final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0)]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None];
        TracedAssertions.assertFailsWith(null,()->UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries("ab",c,[FontRole.LatinText,FontRole.LatinText],e,SortedSet.builder().build(),a)); }
    @:test public static function resolveAttachedInlineInterCharBoundariesRequiresMatchingAttachmentSize():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesRequiresMatchingAttachmentSize"); final text="ab"; final c=UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text); final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)];
        TracedAssertions.assertFailsWith(null,()->UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),e,SortedSet.builder().build(),[InlineAttachment.None])); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternNarrowTrailing():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternNarrowTrailing"); final text="a,\u3002"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u3002","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.CjkPunctuation]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesPreviousContentClusterReturnsNull():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesPreviousContentClusterReturnsNull"); final text="  !"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1)," ","test",8.0),new Cluster(new TextRange(1,2)," ","test",8.0),new Cluster(new TextRange(2,3),"!","test",8.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()==0); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNotNarrow():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNotNarrow"); final text="a,\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.CjkPunctuation,FontRole.CjkPunctuation,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }
    @:test public static function resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNarrowNotCjkPunct():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesPunctuationWesternTrailingNarrowNotCjkPunct"); final text="a,\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"a","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.CjkPunctuation,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertTrue(r.virtualBoundaryAfterClusters.size()>0); }


    @:test public static function resolveUnicodePunctuationBoundariesWithInfixNumericSeparatorNotDecimalMark():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInfixNumericSeparatorNotDecimalMark"); final text="1\uFF0C"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2),"\uFF0C","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,[FontRole.LatinText,FontRole.LatinText],[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithDecimalMarkAfterNonSpace():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithDecimalMarkAfterNonSpace"); final text="1,\uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"1","latin",8.0),new Cluster(new TextRange(1,2),",","latin",8.0),new Cluster(new TextRange(2,3),"\uFF0C","cjk",16.0),new Cluster(new TextRange(3,4),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithQuoteDirectionFinal():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithQuoteDirectionFinal"); final text="\u4E2D\u201D\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false; var i=0; while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}
        TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithQuoteDirectionInitial():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithQuoteDirectionInitial"); final text="\u4E2D\u201C\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false; var i=0; while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}
        TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithQuoteDirectionUnresolved():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithQuoteDirectionUnresolved"); final text="\u4E2D\u00AB\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false; var i=0; while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}
        TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithWordApostrophe2019():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithWordApostrophe2019"); final text="it\u2019s"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithLatinWordCodePoint():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithLatinWordCodePoint"); final text="caf\u00E9"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFirstSignificantCodePoint():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFirstSignificantCodePoint"); final text="  \u201C"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]); var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithLastSignificantCodePoint():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithLastSignificantCodePoint"); final text="a\u201D  "; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]); var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineStart")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithHasAuthoredBreak():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithHasAuthoredBreak"); final text="\n\u201C"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithNextContentCluster():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithNextContentCluster"); final text="a\u201D\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertTrue(r.unbreakableRanges.length>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithPreviousContentClusterHasContent():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPreviousContentClusterHasContent"); final text="\u4E2D\u201D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.unbreakableRanges.length>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithClosePunctuation():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithClosePunctuation"); final text="\u4E2D\uFF09"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithExclamationClass():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithExclamationClass"); final text="\u4E2D\uFF01"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithCloseParenthesisClass():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCloseParenthesisClass"); final text="\u4E2D\uFF09"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]); var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].reason.indexOf("LB13")>=0)f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithInfixNumericSeparatorRule():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithInfixNumericSeparatorRule"); final text="1,2"; final c=UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text); final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]); var hit:ContextualKinsokuDecisionInfo=null;var i=0;while(i<r.decisions.length){if(r.decisions[i].sourceText==","){hit=r.decisions[i];break;}i++;}
        TracedAssertions.assertNotNullRendered(hit!=null,hit==null?"null":Std.string(hit));
        TracedAssertions.assertTrue(hit!=null&&hit.reason.indexOf("LB15d")>=0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithRuleForLineStartElse():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithRuleForLineStartElse"); final text="\u4E2D\u3001"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveAttachedInlineInterCharBoundariesWithSinoWesternPair():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveAttachedInlineInterCharBoundariesWithSinoWesternPair"); final text="\u4E2D\uFF0C\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0),new Cluster(new TextRange(1,2),"\uFF0C","cjk",16.0),new Cluster(new TextRange(2,3),"\u4E2D","cjk",16.0)]; final roles:Array<FontRole>=[FontRole.CjkText,FontRole.CjkPunctuation,FontRole.CjkText]; final e:Array<EastAsianSpacingEdges>=[new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Wide,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Wide,EastAsianSpacingValue.Narrow,false),new EastAsianSpacingEdges(EastAsianSpacingValue.Narrow,EastAsianSpacingValue.Wide,false)]; final a:Array<InlineAttachment>=[InlineAttachment.None,InlineAttachment.Previous,InlineAttachment.None]; final r=UnicodePunctuationBoundaryResolver.resolveAttachedInlineInterCharBoundaries(text,c,roles,e,SortedSet.builder().build(),a);
        TracedAssertions.assertTrue(r.virtualSinoWesternBoundaryAfterClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithCodePointBeforeSupplementary():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithCodePointBeforeSupplementary"); final text="\u4E2D\u201D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertTrue(r.decisions.length>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithEmptyRange():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithEmptyRange"); final text="\u4E2D"; final c:Array<Cluster>=[new Cluster(new TextRange(0,0),"","cjk",0.0),new Cluster(new TextRange(0,1),"\u4E2D","cjk",16.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,[FontRole.CjkText,FontRole.CjkText],[]);
        TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFirstCodePointLength():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFirstCodePointLength"); final text="\u4E2D"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.cjkClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.cjkRoles(text),[]);
        TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithIsWhitespaceCodePoint():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithIsWhitespaceCodePoint"); final text=" \u201C"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);var f=false;var i=0;while(i<r.decisions.length){if(r.decisions[i].forbiddenPosition=="LineEnd")f=true;i++;}TracedAssertions.assertTrue(f); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundaryMandatory():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundaryMandatory"); final text="\r\u201C"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundaryZWSP():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithFollowsAuthoredBoundaryZWSP"); final text="\u200B\u201C"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithDecimalMarkFollowingInsideDigit():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithDecimalMarkFollowingInsideDigit"); final text=" 1\uFF0C23"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1)," ","latin",8.0),new Cluster(new TextRange(1,2),"1","latin",8.0),new Cluster(new TextRange(2,3),"\uFF0C","cjk",16.0),new Cluster(new TextRange(3,5),"23","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.LatinText,FontRole.CjkPunctuation,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);
        TracedAssertions.assertEquals(0,r.forbiddenLineStartClusters.size()); }
    @:test public static function resolveUnicodePunctuationBoundariesWithDecimalMarkFollowingOutsideDigit():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithDecimalMarkFollowingOutsideDigit"); final text=" a\uFF0C2"; final c:Array<Cluster>=[new Cluster(new TextRange(0,1)," ","latin",8.0),new Cluster(new TextRange(1,2),"a","latin",8.0),new Cluster(new TextRange(2,3),"\uFF0C","cjk",16.0),new Cluster(new TextRange(3,4),"2","latin",8.0)]; final roles:Array<FontRole>=[FontRole.LatinText,FontRole.LatinText,FontRole.LatinText,FontRole.LatinText]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,roles,[]);
        TracedAssertions.assertTrue(r.decisions.length>0||r.forbiddenLineStartClusters.size()>0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithPreviousContentClusterHasAuthoredBreak():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithPreviousContentClusterHasAuthoredBreak"); final text="\n\uFF08"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertTrue(r.forbiddenLineStartClusters.size()==0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithNextContentClusterHasAuthoredBreak():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithNextContentClusterHasAuthoredBreak"); final text="\u201D\n"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertTrue(r.unbreakableRanges.length==0); }
    @:test public static function resolveUnicodePunctuationBoundariesWithIsWhitespaceCodePointNonBmp():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithIsWhitespaceCodePointNonBmp"); final text=UnicodePunctuationBoundaryResolverCoverageSupport.surrogate([0xD83D,0xDE00]); final c:Array<Cluster>=[new Cluster(new TextRange(0,2),text,"latin",8.0)]; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,c,[FontRole.LatinText],[]);
        TracedAssertions.assertEquals(0,r.decisions.length); }
    @:test public static function resolveUnicodePunctuationBoundariesWithHasAuthoredBreakBoth():Void { UnicodePunctuationBoundaryResolverCoverageSupport.start("resolveUnicodePunctuationBoundariesWithHasAuthoredBreakBoth"); final text="\n\u201C\n"; final r=UnicodePunctuationBoundaryResolver.resolveUnicodePunctuationBoundaries(text,UnicodePunctuationBoundaryResolverCoverageSupport.latinClusters(text),UnicodePunctuationBoundaryResolverCoverageSupport.latinRoles(text),[]);
        TracedAssertions.assertTrue(r.decisions.length>0); }
}
