package org.tiqian.protocol;

@:jsRequire("node:fs")
private extern class CHeaderNodeFs {
    static function writeFileSync(path:String, data:String, encoding:String):Void;
}

/**
 * Writes the generated C header carrying the C ABI constants of the
 * revision family (Stage1-P4, research 5.3: "C ABI 常量改经生成头文件
 * 供给"). This entry is a root of the haxe bundle target only: gen
 * protocol-c compiles it through stock Haxe to
 * engine-haxe/out/protocol-c/gen/c-header.js and bun runs that js from the
 * worktree root, where main() writes
 * engine-haxe/out/protocol-c/gen/tiqian_protocol_constants.h beside it.
 * The cinterop directory vendors that file; it is the single source the
 * hand-written #define in tiqian_font_backend.h used to carry.
 *
 * Host edge through @:jsRequire("node:fs"), the same shape as the existing
 * engine-haxe/src/org/tiqian/test/trace/TestTracePlatform.hx:7 prior art;
 * the haxe target compiles through stock Haxe rather than the five-target
 * generation compilers, and none of the generation bundles names this entry
 * as a root, so the four-language subset never compiles it. haxe.io.File is
 * unavailable while targeting js (Haxe 4.3 rejects sys with "You cannot
 * access the sys package while targeting js" and has no haxe.io.File on
 * the js platform), so the node:fs require is the host channel.
 */
class CHeader {

    public static function main():Void {
        final text =
            "/* Generated by org.tiqian.protocol.CHeader from the single source\n"
            + " * org.tiqian.protocol.Revision (boring cutover Stage1-P4). Do not edit.\n"
            + " */\n"
            + "#ifndef TIQIAN_PROTOCOL_CONSTANTS_H\n"
            + "#define TIQIAN_PROTOCOL_CONSTANTS_H\n"
            + "\n"
            + "/* C ABI constants of the revision family. */\n"
            + "#define TIQIAN_FONT_BACKEND_PROTOCOL_REVISION "
            + Revision.FONT_BACKEND_PROTOCOL_REVISION
            + "u\n"
            + "\n"
            + "#endif\n";
        CHeaderNodeFs.writeFileSync(
            "engine-haxe/out/protocol-c/gen/tiqian_protocol_constants.h", text, "utf8"
        );
    }
}
