// Generated by the reflaxe TypeScript target. Do not edit.

import { ClreqProfile } from "./../clreq/ClreqProfile.ts";
import { Cluster } from "./../core/Cluster.ts";
import { InlineObjectSpan } from "./../core/InlineObjectSpan.ts";
import { RoleOverrideInfo } from "./../core/RoleOverrideInfo.ts";
import { SourceInteractionBoundaries } from "./../core/SourceInteractionBoundaries.ts";
import { TextRange } from "./../core/TextRange.ts";
import { TextRangeError } from "./../core/TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./../core/TiqianIllegalArgumentException.ts";
import { UnicodeCombiningMarkData } from "./../core/UnicodeCombiningMarkData.ts";
import { UnicodeEmojiModifierBaseData } from "./../core/UnicodeEmojiModifierBaseData.ts";
import { FontDecision } from "./../font/FontPolicy.ts";
import { FontRole } from "./../font/FontRole.ts";
import { FontRoleClassifier, FontRoleContext } from "./../font/FontRoleContext.ts";
import { UnicodeEmojiData } from "./../font/UnicodeEmojiData.ts";
import { UnicodeEmojiStyleVariationData } from "./../font/UnicodeEmojiStyleVariationData.ts";
import { LineBreakFns } from "./../linebreak/LineBreakFns.ts";
import { SortedMapTable, SortedSetTable, readUnit } from "../../../runtime.ts";

export class ResolvedClusterRange {
  public readonly range: TextRange;
  public readonly role: FontRole;
  public readonly mandatoryBreak: boolean;
  public readonly zeroWidthSoftBreak: boolean;
  public readonly roleOverride: RoleOverrideInfo | null;

  constructor(range: TextRange, role: FontRole, mandatoryBreak: boolean | null = null, zeroWidthSoftBreak: boolean | null = null, roleOverride?: RoleOverrideInfo | null) {
    this.range = range;
    this.role = role;
    this.mandatoryBreak = mandatoryBreak ?? false;
    this.zeroWidthSoftBreak = zeroWidthSoftBreak ?? false;
    this.roleOverride = roleOverride;
  }

  public toString(): string {
    return `ResolvedClusterRange(range=${this.range.toString()}, role=${this.role.kind}, mandatoryBreak=${this.mandatoryBreak}, zeroWidthSoftBreak=${this.zeroWidthSoftBreak}, roleOverride=${(this.roleOverride === null ? "null" : this.roleOverride.toString())})`;
  }
}

export class ClusterRoleResolution {
  public static clusterRoleRanges(text: string, classifier: FontRoleClassifier, context: FontRoleContext, profile: ClreqProfile, spanBoundaries: SortedSetTable<number>, emojiShapingBoundaries: SortedSetTable<number>, inlineObjectsByStart?: SortedMapTable<number, InlineObjectSpan> | null): ResolvedClusterRange[] {
    const graphemes = SourceInteractionBoundaries.sourceGraphemeBoundaries(text, new TextRange(0, text.length));
    const out: ResolvedClusterRange[] = [];
    let index = 0;
    let gi = (text.length === 0 ? 0 : 1);
    let gs = graphemes[0]!;
    let ge = (gi < graphemes.length ? graphemes[gi]! : text.length);
    while (index < text.length) {
      while (index >= ge && gi < graphemes.length - 1) {
        gs = ge;
        gi++;
        ge = graphemes[gi]!;
      }
      const io = (inlineObjectsByStart === null ? null : inlineObjectsByStart.get(index));
      if (io !== null) {
        out.push(new ResolvedClusterRange(io.range, FontRole.Unknown, false, false, null));
        index = io.range.end;
        continue;
      }
      const cp = ClusterRoleResolution.codePoint(text, index);
      const count = (cp > 65535 ? 2 : 1);
      const start = index;
      if (ClusterRoleResolution.isMandatory(text, index, cp)) {
        const end = (cp === 13 && index + 1 < text.length && readUnit(text, index + 1)! === 10 ? index + 2 : index + count);
        out.push(new ResolvedClusterRange(new TextRange(start, end), FontRole.Unknown, true, false, null));
        index = end;
        continue;
      }
      if (LineBreakFns.isZeroWidthSpaceCodePoint(cp)) {
        out.push(new ResolvedClusterRange(new TextRange(start, index + count), FontRole.Unknown, false, true, null));
        index += count;
        continue;
      }
      const classified = classifier.classify(text, new TextRange(start, start + count), context);
      const promotion = ClusterRoleResolution.emojiPromotion(text, start, ge);
      const role = (classified.kind === "Emoji" || promotion !== null ? FontRole.Emoji : classified);
      const prev = (out.length === 0 ? null : out[out.length - 1]!);
      const attached = role.kind === "LatinText" && ClusterRoleResolution.isAsciiPoint(cp) && prev !== null && prev.role.kind !== "Unknown" && !ClusterRoleResolution.isWs(readUnit(text, prev.range.end - 1)!) && prev.range.end === start;
      index += count;
      if (role.kind === "Emoji") {
        let b = ge;
        let bi = 0;
        while (bi < emojiShapingBoundaries.size()) {
          const k = emojiShapingBoundaries.at(bi);
          if (k > start && k < ge && (b === ge || k < b)) {
            b = k;
          }
          bi++;
        }
        index = b;
      } else {
        if (role.kind === "LatinText") {
          if (cp === 8212 || cp === 8230) {
            if (ClusterRoleResolution.contains(profile.coalesceRepeatablePunctuation, cp)) {
              while (index < text.length && !spanBoundaries.has(index) && ClusterRoleResolution.codePoint(text, index) === cp) {
                index += (cp > 65535 ? 2 : 1);
              }
            }
          } else {
            if (attached) {
              while (index < text.length && !spanBoundaries.has(index) && ClusterRoleResolution.isAsciiPoint(ClusterRoleResolution.codePoint(text, index))) {
                index += 1;
              }
            } else {
              while (index < text.length && !spanBoundaries.has(index)) {
                const n = ClusterRoleResolution.codePoint(text, index);
                if (n === 8212 || n === 8230 || classifier.classify(text, new TextRange(index, index + (n > 65535 ? 2 : 1)), context).kind !== "LatinText" || ClusterRoleResolution.emojiPromotion(text, index, text.length) !== null) {
                  break;
                }
                index += (n > 65535 ? 2 : 1);
              }
            }
          }
        } else {
          if (role.kind === "CjkPunctuation" && ClusterRoleResolution.contains(profile.coalesceRepeatablePunctuation, cp)) {
            while (index < text.length && !spanBoundaries.has(index) && ClusterRoleResolution.codePoint(text, index) === cp) {
              index += (cp > 65535 ? 2 : 1);
            }
          }
        }
      }
      while (index < text.length && !spanBoundaries.has(index)) {
        const e = ClusterRoleResolution.codePoint(text, index);
        if (!ClusterRoleResolution.isCombining(e) && !ClusterRoleResolution.isVariation(e)) {
          break;
        }
        index += (e > 65535 ? 2 : 1);
      }
      const r = new TextRange(start, index);
      let roleInfo: RoleOverrideInfo | null = null;
      if (role.kind === "Emoji" && classified.kind !== "Emoji") {
        roleInfo = new RoleOverrideInfo(r, text.substring(r.start, r.end), classified.kind, role.kind, "UnicodeEmojiSequenceRolePromotion", (promotion === null ? "EmojiPresentationCodePoint" : promotion));
      }
      out.push(new ResolvedClusterRange(r, role, false, false, roleInfo));
    }
    return out;
  }

  public static requireCoveredBy(clusters: Cluster[], decisions: FontDecision[]): void {
    let ci = 0;
    let di = 0;
    while (di < decisions.length) {
      const d = decisions[di++]!;
      while (ci < clusters.length && clusters[ci]!.range.end <= d.range.start) {
        ci++;
      }
      let cursor = d.range.start;
      while (ci < clusters.length && clusters[ci]!.range.start < d.range.end) {
        const c = clusters[ci]!;
        if (!(c.range.start >= d.range.start && c.range.end <= d.range.end)) {
          throw new TiqianIllegalArgumentException(({ kind: "Message", text: `TextShaper returned cluster ${c.range.toString()} crossing ${d.range.toString()}` } as TextRangeError));
        }
        if (c.range.start !== cursor) {
          throw new TiqianIllegalArgumentException(({ kind: "Message", text: `TextShaper returned non-contiguous clusters for ${d.range.toString()}; expected start=${cursor}, actual=${c.range.toString()}` } as TextRangeError));
        }
        cursor = c.range.end;
        ci++;
      }
      if (cursor !== d.range.end) {
        throw new TiqianIllegalArgumentException(({ kind: "Message", text: `TextShaper must return clusters covering ${d.range.toString()}; coveredUntil=${cursor}` } as TextRangeError));
      }
    }
  }

  private static codePoint(t: string, i: number): number {
    const h = (Number.isNaN(t.charCodeAt(i)) ? null : t.charCodeAt(i))!;
    if (h < 55296 || h > 56319 || i + 1 >= t.length) {
      return h!;
    }
    const l = readUnit(t, i + 1)!;
    return (l < 56320 || l > 57343 ? h : 65536 + (h - 55296 << 10) + (l - 56320));
  }

  private static isMandatory(t: string, i: number, c: number): boolean {
    return LineBreakFns.isMandatoryBreakCodePoint(c) && !(c === 10 && i > 0 && readUnit(t, i - 1)! === 13);
  }

  private static contains(a: readonly number[], v: number): boolean {
    let i = 0;
    while (i < a.length) {
      if (a[i]! === v) {
        return true;
      }
      i++;
    }
    return false;
  }

  private static isVariation(c: number): boolean {
    return c >= 65024 && c <= 65039 || c >= 917760 && c <= 917999;
  }

  private static isCombining(c: number): boolean {
    return c <= 65535 && UnicodeCombiningMarkData.contains(c);
  }

  private static isWs(cp: number): boolean {
    return cp <= 65535 && (cp >= 9 && cp <= 13 || cp >= 28 && cp <= 32 || cp === 160 || cp === 5760 || cp >= 8192 && cp <= 8202 || cp === 8232 || cp === 8233 || cp === 8239 || cp === 8287 || cp === 12288);
  }

  private static isAsciiPoint(c: number): boolean {
    return c === 44 || c === 46 || c === 59 || c === 58 || c === 33 || c === 63;
  }

  private static emojiPromotion(t: string, s: number, e: number): string | null {
    const b = ClusterRoleResolution.codePoint(t, s);
    let n = s + (b > 65535 ? 2 : 1);
    if (b === 35 || b === 42 || b >= 48 && b <= 57) {
      if (n < e && ClusterRoleResolution.codePoint(t, n) === 65039) {
        n++;
      }
      if (n < e && ClusterRoleResolution.codePoint(t, n) === 8419) {
        return "KeycapSequence";
      }
    }
    if (UnicodeEmojiData.contains(b) && UnicodeEmojiStyleVariationData.contains(b) && n < e && ClusterRoleResolution.codePoint(t, n) === 65039) {
      return "EmojiStyleVariationSequence";
    }
    if (UnicodeEmojiModifierBaseData.contains(b)) {
      while (n < e && (ClusterRoleResolution.isCombining(ClusterRoleResolution.codePoint(t, n)) || ClusterRoleResolution.isVariation(ClusterRoleResolution.codePoint(t, n)))) {
        n += (ClusterRoleResolution.codePoint(t, n) > 65535 ? 2 : 1);
      }
      const m = (n < e ? ClusterRoleResolution.codePoint(t, n) : -1);
      if (m >= 127995 && m <= 127999) {
        return "EmojiModifierSequence";
      }
    }
    return null;
  }
}
