// Generated by the reflaxe TypeScript target. Do not edit.

import { UnicodeEastAsianSpacing } from "./../core/UnicodeEastAsianSpacing.ts";
import { UnicodeNumber } from "./../core/UnicodeNumber.ts";
import { UnicodeScriptEvidenceClassifier } from "./../core/UnicodeScriptEvidenceClassifier.ts";
import { UnicodeWordCharacter } from "./../core/UnicodeWordCharacter.ts";
import { FontRole } from "./../font/FontRole.ts";
import { FontRoleContext } from "./../font/FontRoleContext.ts";
import { QuotePair, QuoteRoleDecision } from "./QuotePairAnalyzer.ts";
import { SortedMapTable, SortedMapTableBuilder, SortedTable, readUnit } from "../../../runtime.ts";

export class ContextualQuoteRoleResolver {
  private readonly text: string;
  private readonly pairs: QuotePair[];
  private readonly context: FontRoleContext;
   readonly pairByOpen: SortedMapTable<number, QuotePair>;
  private readonly pairByClose: SortedMapTable<number, QuotePair>;
  private readonly parentByPair: SortedMapTable<number, QuotePair | null>;

  constructor(text: string, pairs: QuotePair[], context: FontRoleContext) {
    this.text = text;
    this.pairs = pairs;
    this.context = context;
    const openBuilder = SortedTable.mapBuilder<number, QuotePair>(SortedTable.compareInts);
    const closeBuilder = SortedTable.mapBuilder<number, QuotePair>(SortedTable.compareInts);
    let pi = 0;
    while (pi < pairs.length) {
      const pair = pairs[pi]!;
      pi++;
      openBuilder.put(pair.openIndex, pair);
      closeBuilder.put(pair.closeIndex, pair);
    }
    this.pairByOpen = openBuilder.build();
    this.pairByClose = closeBuilder.build();
    const parentBuilder = SortedTable.mapBuilder<number, QuotePair | null>(SortedTable.compareInts);
    pi = 0;
    while (pi < pairs.length) {
      const pair2 = pairs[pi]!;
      pi++;
      parentBuilder.put(pair2.openIndex, this.findParent(pair2));
    }
    this.parentByPair = parentBuilder.build();
  }

  public resolve(): QuoteRoleDecision[] {
    const decisions: QuoteRoleDecision[] = [];
    const resolvedPairs = SortedTable.mapBuilder<number, FontRole>(SortedTable.compareInts);
    const pipeline_result = this.pairs.slice().sort((_a, _b) => { const _ka = _a.openIndex; const _kb = _b.openIndex; return _ka < _kb ? -1 : (_ka > _kb ? 1 : 0); });
    const ordered = pipeline_result;
    for (let _g_index = 0, count = ordered.length; _g_index < count; _g_index += 1) {
      const pair = ordered[_g_index]!;
      const resolution = this.resolvePair(pair, resolvedPairs);
      resolvedPairs.put(pair.openIndex, resolution.role);
      decisions.push(new QuoteRoleDecision(pair.openIndex, resolution.role, resolution.source, resolution.reason));
      decisions.push(new QuoteRoleDecision(pair.closeIndex, resolution.role, resolution.source, resolution.reason));
    }
    const pairedIndicesBuilder = SortedTable.setBuilder<number>(SortedTable.compareInts);
    let pi = 0;
    while (pi < this.pairs.length) {
      const pair2 = this.pairs[pi]!;
      pi++;
      pairedIndicesBuilder.put(pair2.openIndex);
      pairedIndicesBuilder.put(pair2.closeIndex);
    }
    const pairedIndices = pairedIndicesBuilder.build();
    for (let index = 0, count2 = this.text.length; index < count2; index += 1) {
      if (pairedIndices.has(index) || !ContextualQuoteRoleResolver.isAmbiguousCurlyQuote((Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))!)) {
        continue;
      }
      const resolution2 = this.resolveUnmatched(index);
      decisions.push(new QuoteRoleDecision(index, resolution2.role, resolution2.source, resolution2.reason));
    }
    const pipeline_result1 = decisions.slice().sort((_a, _b) => { const _ka = _a.index; const _kb = _b.index; return _ka < _kb ? -1 : (_ka > _kb ? 1 : 0); });
    const sorted = pipeline_result1;
    return sorted;
  }

  private resolvePair(pair: QuotePair, resolvedPairs: SortedMapTableBuilder<number, FontRole>): Resolution {
    const parent = this.parentByPair.get(pair.openIndex);
    const enclosingStart = (parent === null ? 0 : parent.openIndex + 1);
    const enclosingEnd = (parent === null ? this.text.length : parent.closeIndex);
    const outerEvidence = new ScriptEvidence(this);
    outerEvidence.addRange(enclosingStart, pair.openIndex);
    outerEvidence.addRange(pair.closeIndex + 1, enclosingEnd);
    const contentEvidence = new ScriptEvidence(this);
    contentEvidence.addRange(pair.openIndex + 1, pair.closeIndex);
    if (this.charAt(pair.openIndex - 1) !== null && ContextualQuoteRoleResolver.isAsciiSpaceOrTab(this.charAt(pair.openIndex - 1)) && contentEvidence.hasWestern && !contentEvidence.hasCjk) {
      return new Resolution(FontRole.LatinText, "DelimitedWesternQuotationRun", "whitespace-delimited-wholly-western-quotation");
    }
    if (this.isNonCjkWordInternalQuotePair(pair)) {
      return new Resolution(FontRole.LatinText, "NonCjkWordInternalQuotePair", "non-cjk-word-internal-quotation");
    }
    const outerRole = outerEvidence.unambiguousRole();
    if (outerRole !== null) {
      return new Resolution(outerRole, "PairedPunctuationOuterScriptContext", "quote-pair-inherits-enclosing-level-script");
    }
    if (outerEvidence.isMixed) {
      return this.paragraphLanguageResolution("mixed-enclosing-level-script");
    }
    if (parent !== null) {
      const enclosingRole = resolvedPairs.get(parent.openIndex);
      if (enclosingRole !== null) {
        return new Resolution(enclosingRole, "PairedPunctuationEnclosingQuoteContext", "quote-pair-inherits-enclosing-quotation");
      }
    }
    const contentRole = contentEvidence.unambiguousRole();
    if (contentRole !== null) {
      return new Resolution(contentRole, "PairedPunctuationContentScriptContext", "quoted-content-script");
    }
    return this.paragraphLanguageResolution((contentEvidence.isMixed ? "mixed-quoted-content" : "no-strong-script-context"));
  }

  private resolveUnmatched(index: number): Resolution {
    if ((Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))! === 8217 && this.isNonCjkInWordApostrophe(index)) {
      return new Resolution(FontRole.LatinText, "NonCjkInWordApostrophe", "non-cjk-in-word-apostrophe");
    }
    if (this.isDigitBoundClosingQuote(index)) {
      return new Resolution(FontRole.LatinText, "NumericPrimeUnmatchedQuote", "digit-bound-unmatched-quote-as-prime");
    }
    const leftRole = this.nearestStrongScriptRole(index - 1, -1);
    const rightRole = this.nearestStrongScriptRole(index + 1, 1);
    if (ContextualQuoteRoleResolver.isAsciiSpaceOrTab(this.charAt(index - 1)) && (rightRole !== null && rightRole.kind === "LatinText")) {
      return new Resolution(FontRole.LatinText, "DelimitedUnmatchedWesternQuote", "whitespace-delimited-unmatched-western-quote");
    }
    if (leftRole !== null && (rightRole === null || rightRole === leftRole)) {
      return new Resolution(leftRole, "UnmatchedQuoteSurroundingScriptContext", "unmatched-quote-surrounding-script");
    }
    if (rightRole !== null && leftRole === null) {
      return new Resolution(rightRole, "UnmatchedQuoteSurroundingScriptContext", "unmatched-quote-surrounding-script");
    }
    const reason = (leftRole !== null && rightRole !== null ? "conflicting-unmatched-quote-context" : "no-unmatched-quote-context");
    return this.paragraphLanguageResolution(reason);
  }

  private nearestStrongScriptRole(startIndex: number, direction: number): FontRole | null {
    let index = startIndex;
    while (index >= 0 && index < this.text.length) {
      if (direction < 0) {
        const pair = this.pairByClose.get(index)!;
        if (pair !== null) {
          index = pair.openIndex - 1;
          continue;
        }
      } else {
        const pair2 = this.pairByOpen.get(index)!;
        if (pair2 !== null) {
          index = pair2.closeIndex + 1;
          continue;
        }
      }
      const scalarStart = (direction < 0 && ContextualQuoteRoleResolver.isLowSurrogate((Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))!) && index > 0 && ContextualQuoteRoleResolver.isHighSurrogate(readUnit(this.text, index - 1)!) ? index - 1 : index);
      const length = this.codePointLengthAt(scalarStart, this.text.length);
      const role = this.strongScriptRole(scalarStart, length);
      if (role !== null) {
        return role;
      }
      index = (direction < 0 ? scalarStart - 1 : scalarStart + length);
    }
    return null;
  }

  private paragraphLanguageResolution(reason: string): Resolution {
    const role = (UnicodeEastAsianSpacing.isChineseLanguageContext(this.context.locale) ? FontRole.CjkPunctuation : FontRole.LatinText);
    return new Resolution(role, "ParagraphLanguageQuoteContext", reason + "; paragraph-language=" + this.context.locale);
  }

  private findParent(pair: QuotePair): QuotePair | null {
    let result: QuotePair | null = null;
    let ci = 0;
    while (ci < this.pairs.length) {
      const candidate = this.pairs[ci]!;
      ci++;
      if (candidate !== pair && candidate.openIndex < pair.openIndex && candidate.closeIndex > pair.closeIndex && (result === null || candidate.closeIndex - candidate.openIndex < result.closeIndex - result.openIndex)) {
        result = candidate;
      }
    }
    return result;
  }

   strongScriptRole(index: number, length: number): FontRole | null {
    const evidence = UnicodeScriptEvidenceClassifier.classify(this.codePointAt(index, index + length));
    switch (evidence.kind) {
      case "Neutral":
        return null;
      case "EastAsian":
        return FontRole.CjkPunctuation;
      case "Other":
        return FontRole.LatinText;
    }
  }

  private isNonCjkInWordApostrophe(index: number): boolean {
    const before = this.codePointBefore(index);
    const after = this.codePointAtOrNull(index + 1);
    return before !== null && after !== null && this.isNonCjkWordCharacter(before) && this.isNonCjkWordCharacter(after) && (this.isNonCjkNonNumericWordCharacter(before) || this.isNonCjkNonNumericWordCharacter(after));
  }

  private isDigitBoundClosingQuote(index: number): boolean {
    const before = this.codePointBefore(index);
    return ((Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))! === 8217 || (Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))! === 8221) && before !== null && UnicodeNumber.contains(before);
  }

  private isNonCjkWordInternalQuotePair(pair: QuotePair): boolean {
    const before = this.codePointBefore(pair.openIndex);
    const after = this.codePointAtOrNull(pair.closeIndex + 1);
    if (before === null || after === null || !this.isNonCjkNonNumericWordCharacter(before) || !this.isNonCjkNonNumericWordCharacter(after)) {
      return false;
    }
    let index = pair.openIndex + 1;
    while (index < pair.closeIndex) {
      const codePoint = this.codePointAtOrNull(index);
      if (codePoint === null || !this.isNonCjkWordCharacter(codePoint)) {
        return false;
      }
      index += (codePoint > 65535 ? 2 : 1);
    }
    return true;
  }

  private isNonCjkWordCharacter(codePoint: number): boolean {
    return UnicodeWordCharacter.contains(codePoint) && UnicodeScriptEvidenceClassifier.classify(codePoint).kind !== "EastAsian";
  }

  private isNonCjkNonNumericWordCharacter(codePoint: number): boolean {
    return this.isNonCjkWordCharacter(codePoint) && !UnicodeNumber.contains(codePoint) && !this.isFullwidth(codePoint);
  }

  private isFullwidth(codePoint: number): boolean {
    return codePoint === 12288 || codePoint >= 65281 && codePoint <= 65376 || codePoint >= 65504 && codePoint <= 65510;
  }

  private charAt(index: number): number | null {
    return (index >= 0 && index < this.text.length ? (Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))! : null);
  }

  private codePointAt(index: number, end: number): number {
    const high = (Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))!!;
    if (!ContextualQuoteRoleResolver.isHighSurrogate(high) || index + 1 >= end) {
      return high;
    }
    const low = readUnit(this.text, index + 1)!!;
    return (ContextualQuoteRoleResolver.isLowSurrogate(low) ? 65536 + (high - 55296 << 10) + low - 56320 : high);
  }

   codePointLengthAt(index: number, end: number): number {
    return (ContextualQuoteRoleResolver.isHighSurrogate((Number.isNaN(this.text.charCodeAt(index)) ? null : this.text.charCodeAt(index))!) && index + 1 < end && ContextualQuoteRoleResolver.isLowSurrogate(readUnit(this.text, index + 1)!) ? 2 : 1);
  }

  private codePointBefore(index: number): number | null {
    if (index <= 0) {
      return null;
    }
    const low = readUnit(this.text, index - 1)!!;
    if (!ContextualQuoteRoleResolver.isLowSurrogate(low) || index < 2) {
      return low;
    }
    const high = readUnit(this.text, index - 2)!!;
    return (ContextualQuoteRoleResolver.isHighSurrogate(high) ? 65536 + (high - 55296 << 10) + low - 56320 : low);
  }

  private codePointAtOrNull(index: number): number | null {
    return (index < 0 || index >= this.text.length ? null : this.codePointAt(index, this.text.length));
  }

  private static isAmbiguousCurlyQuote(codePoint: number): boolean {
    return codePoint === 8216 || codePoint === 8217 || codePoint === 8220 || codePoint === 8221;
  }

  private static isAsciiSpaceOrTab(codePoint: number | null): boolean {
    return codePoint !== null && (codePoint === 32 || codePoint === 9);
  }

  private static isHighSurrogate(codePoint: number): boolean {
    return codePoint >= 55296 && codePoint <= 56319;
  }

  private static isLowSurrogate(codePoint: number): boolean {
    return codePoint >= 56320 && codePoint <= 57343;
  }
}

export class ScriptEvidence {
  public hasCjk: boolean;
  public hasWestern: boolean;
  private readonly resolver: ContextualQuoteRoleResolver;

  constructor(resolver: ContextualQuoteRoleResolver) {
    this.hasWestern = false;
    this.hasCjk = false;
    this.resolver = resolver;
  }

  public get isMixed(): boolean {
    return this.get_isMixed();
  }
   get_isMixed(): boolean {
    return this.hasCjk && this.hasWestern;
  }

  public addRange(start: number, end: number): void {
    let index = start;
    while (index < end) {
      const nested = this.resolver.pairByOpen.get(index);
      if (nested !== null && nested.closeIndex < end) {
        index = nested.closeIndex + 1;
        continue;
      }
      const length = this.resolver.codePointLengthAt(index, end);
      const role = this.resolver.strongScriptRole(index, length);
      if ((role !== null && role.kind === "CjkPunctuation")) {
        this.hasCjk = true;
      } else {
        if ((role !== null && role.kind === "LatinText")) {
          this.hasWestern = true;
        }
      }
      index += length;
    }
  }

  public unambiguousRole(): FontRole | null {
    return (this.hasCjk && !this.hasWestern ? FontRole.CjkPunctuation : (this.hasWestern && !this.hasCjk ? FontRole.LatinText : null));
  }
}

export class Resolution {
  public readonly role: FontRole;
  public readonly source: string;
  public readonly reason: string;

  constructor(role: FontRole, source: string, reason: string) {
    this.role = role;
    this.source = source;
    this.reason = reason;
  }
}
