// Generated by the reflaxe TypeScript target. Do not edit.

import { RoleOverrideInfo } from "./../core/RoleOverrideInfo.ts";
import { TextRange, compareTextRange } from "./../core/TextRange.ts";
import { UnicodeEastAsianSpacing } from "./../core/UnicodeEastAsianSpacing.ts";
import { UnicodeScriptEvidenceClassifier } from "./../core/UnicodeScriptEvidenceClassifier.ts";
import { UnicodeWordCharacter } from "./../core/UnicodeWordCharacter.ts";
import { FontRole } from "./../font/FontRole.ts";
import { FontRoleClassifier, FontRoleContext } from "./../font/FontRoleContext.ts";
import { LineBreakFns } from "./../linebreak/LineBreakFns.ts";
import { SortedMapTable, SortedTable, readUnit } from "../../../runtime.ts";

export class DashEllipsisRoleDecision {
  public readonly range: TextRange;
  public readonly role: FontRole;
  public readonly source: string;
  public readonly reason: string;

  constructor(range: TextRange, role: FontRole, source: string, reason: string) {
    this.range = range;
    this.role = role;
    this.source = source;
    this.reason = reason;
  }

  public toString(): string {
    return `DashEllipsisRoleDecision(range=${this.range.toString()}, role=${this.role.kind}, source=${this.source}, reason=${this.reason})`;
  }
}

export function DashEllipsisRoleDecisionroleOrder(v: FontRole): number {
  if (v.kind === "Unknown") return 5;
  if (v.kind === "Symbol") return 3;
  if (v.kind === "LatinText") return 2;
  if (v.kind === "Emoji") return 4;
  if (v.kind === "CjkText") return 0;
  if (v.kind === "CjkPunctuation") return 1;
  return 0;
}

export function compareDashEllipsisRoleDecision(a: DashEllipsisRoleDecision, b: DashEllipsisRoleDecision): number {
  if (a === b) return 0;
  { const cmp = compareTextRange(a.range, b.range); if (cmp !== 0) return cmp; }
  if (DashEllipsisRoleDecisionroleOrder(a.role) !== DashEllipsisRoleDecisionroleOrder(b.role)) return DashEllipsisRoleDecisionroleOrder(a.role) - DashEllipsisRoleDecisionroleOrder(b.role);
  if (a.source !== b.source) return a.source < b.source ? -1 : 1;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  return 0;
}

export class ContextualDashEllipsisRoleResolver {
  constructor() {
  }

  public resolve(text: string, context?: FontRoleContext | null): DashEllipsisRoleDecision[] {
    const actualContext = context ?? new FontRoleContext("zh-Hans", null);
    let hasMark = false;
    let ci = 0;
    while (ci < text.length) {
      if (ContextualDashEllipsisRoleResolver.isContextualDashOrEllipsis((Number.isNaN(text.charCodeAt(ci)) ? null : text.charCodeAt(ci))!)) {
        hasMark = true;
        break;
      }
      ci++;
    }
    if (!hasMark) {
      return [];
    }
    const strongScriptContext = new StrongScriptContextIndex(text);
    const runs = this.collectRuns(text);
    const pairResolutions = this.resolveParentheticalPairs(text, runs, strongScriptContext, actualContext);
    const result: DashEllipsisRoleDecision[] = [];
    let ri = 0;
    while (ri < runs.length) {
      const range = runs[ri]!;
      const paired = pairResolutions.get(range.start);
      const resolution = (paired === null ? this.resolveSingleRun(range, strongScriptContext, actualContext) : paired);
      result.push(new DashEllipsisRoleDecision(range, resolution.role, resolution.source, resolution.reason));
      ri++;
    }
    return result;
  }

  private collectRuns(text: string): TextRange[] {
    const runs: TextRange[] = [];
    let index = 0;
    while (index < text.length) {
      if (!ContextualDashEllipsisRoleResolver.isContextualDashOrEllipsis((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!)) {
        index += ContextualDashEllipsisRoleResolver.codePointLengthAt(text, index);
        continue;
      }
      const start = index;
      while (index < text.length && ContextualDashEllipsisRoleResolver.isContextualDashOrEllipsis((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!)) {
        index++;
      }
      runs.push(new TextRange(start, index));
    }
    return runs;
  }

  private resolveSingleRun(range: TextRange, strongScriptContext: StrongScriptContextIndex, context: FontRoleContext): Resolution {
    const leftRole = strongScriptContext.leftOf(range.start);
    const rightRole = strongScriptContext.rightOf(range.end);
    if (leftRole !== null && rightRole === leftRole) {
      return new Resolution(leftRole, "DashEllipsisSurroundingScriptContext", "matching-surrounding-script");
    }
    if (leftRole !== null && rightRole === null) {
      return new Resolution(leftRole, "DashEllipsisSurroundingScriptContext", "only-left-strong-script");
    }
    if (rightRole !== null && leftRole === null) {
      return new Resolution(rightRole, "DashEllipsisSurroundingScriptContext", "only-right-strong-script");
    }
    const reason = (leftRole !== null && rightRole !== null ? "conflicting-surrounding-script" : "no-strong-script-context");
    return this.paragraphLanguageResolution(context, reason);
  }

  private resolveParentheticalPairs(text: string, runs: TextRange[], strongScriptContext: StrongScriptContextIndex, context: FontRoleContext): SortedMapTable<number, Resolution> {
    const resolutions = SortedTable.mapBuilder<number, Resolution>(SortedTable.compareInts);
    let index = 0;
    while (index + 1 < runs.length) {
      const first = runs[index]!;
      const second = runs[index + 1]!;
      if (!ContextualDashEllipsisRoleResolver.isParentheticalDashPair(text, first, second)) {
        index++;
        continue;
      }
      const leftRole = strongScriptContext.leftOf(first.start);
      const rightRole = strongScriptContext.rightOf(second.end);
      const resolution = this.parentheticalPairResolution(leftRole, rightRole, context);
      resolutions.put(first.start, resolution);
      resolutions.put(second.start, resolution);
      index += 2;
    }
    return resolutions.build();
  }

  private parentheticalPairResolution(leftRole: FontRole | null, rightRole: FontRole | null, context: FontRoleContext): Resolution {
    if (leftRole !== null && rightRole === leftRole) {
      return new Resolution(leftRole, "ParentheticalDashPairContext", "matching-outer-script");
    }
    if (leftRole !== null && rightRole === null) {
      return new Resolution(leftRole, "ParentheticalDashPairContext", "only-left-outer-script");
    }
    if (rightRole !== null && leftRole === null) {
      return new Resolution(rightRole, "ParentheticalDashPairContext", "only-right-outer-script");
    }
    const reason = (leftRole !== null && rightRole !== null ? "parenthetical-pair-conflicting-outer-script" : "parenthetical-pair-no-outer-context");
    return this.paragraphLanguageResolution(context, reason);
  }

  private paragraphLanguageResolution(context: FontRoleContext, reason: string): Resolution {
    const role = (UnicodeEastAsianSpacing.isChineseLanguageContext(context.locale) ? FontRole.CjkPunctuation : FontRole.LatinText);
    return new Resolution(role, "ParagraphLanguageDashEllipsisContext", reason + "; paragraph-language=" + context.locale);
  }

  private static isContextualDashOrEllipsis(codePoint: number): boolean {
    return codePoint === 8212 || codePoint === 8230;
  }

  private static isParentheticalDashPair(text: string, first: TextRange, second: TextRange): boolean {
    if (!ContextualDashEllipsisRoleResolver.isPureDashRun(text, first) || !ContextualDashEllipsisRoleResolver.isPureDashRun(text, second)) {
      return false;
    }
    if (first.end - first.start !== second.end - second.start) {
      return false;
    }
    let index = first.end;
    while (index < second.start) {
      const cp = ContextualDashEllipsisRoleResolver.codePointAtCompat(text, index);
      if (cp !== 32 && !UnicodeWordCharacter.contains(cp)) {
        return false;
      }
      index += ContextualDashEllipsisRoleResolver.charCount(cp);
    }
    return true;
  }

  private static isPureDashRun(text: string, range: TextRange): boolean {
    let index = range.start;
    while (index < range.end) {
      if ((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))! !== 8212) {
        return false;
      }
      index++;
    }
    return true;
  }

  public static codePointAtCompat(text: string, index: number): number {
    const high = (Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!;
    if (high < 55296 || high > 56319 || index + 1 >= text.length) {
      return high!;
    }
    const low = readUnit(text, index + 1)!;
    if (low < 56320 || low > 57343) {
      return high!;
    }
    return 65536 + (high - 55296 << 10) + (low - 56320);
  }

  public static codePointLengthAt(text: string, index: number): number {
    return ContextualDashEllipsisRoleResolver.charCount(ContextualDashEllipsisRoleResolver.codePointAtCompat(text, index));
  }

  public static charCount(codePoint: number): number {
    return (codePoint > 65535 ? 2 : 1);
  }
}

export class ContextualDashEllipsisAwareFontRoleClassifier implements FontRoleClassifier {
  private readonly delegate: FontRoleClassifier;
  private readonly roleByIndex: SortedMapTable<number, FontRole>;

  constructor(delegate: FontRoleClassifier, decisions: DashEllipsisRoleDecision[]) {
    this.delegate = delegate;
    const builder = SortedTable.mapBuilder<number, FontRole>(SortedTable.compareInts);
    let di = 0;
    while (di < decisions.length) {
      const d = decisions[di]!;
      let index = d.range.start;
      while (index < d.range.end) {
        builder.put(index, d.role);
        index++;
      }
      di++;
    }
    this.roleByIndex = builder.build();
  }

  public classify(text: string, range: TextRange, context?: FontRoleContext | null): FontRole {
    const role = this.roleByIndex.get(range.start);
    return (role === null ? this.delegate.classify(text, range, context) : role);
  }
}

export class ContextualDashEllipsisRoles {
  public static withContextualDashEllipsisRoles(base: FontRoleClassifier, text: string, context?: FontRoleContext | null): FontRoleClassifier {
    const decisions = new ContextualDashEllipsisRoleResolver().resolve(text, context);
    return (decisions.length === 0 ? base : new ContextualDashEllipsisAwareFontRoleClassifier(base, decisions));
  }

  public static toRoleOverrideInfos(decisions: DashEllipsisRoleDecision[], text: string, baseClassifier: FontRoleClassifier, context: FontRoleContext): RoleOverrideInfo[] {
    const result: RoleOverrideInfo[] = [];
    let index = 0;
    while (index < decisions.length) {
      const d = decisions[index]!;
      const first = new TextRange(d.range.start, d.range.start + 1);
      result.push(new RoleOverrideInfo(d.range, text.substring(d.range.start, d.range.end), baseClassifier.classify(text, first, context).kind, d.role.kind, d.source, d.reason));
      index++;
    }
    return result;
  }
}

export class Resolution {
  public readonly role: FontRole;
  public readonly source: string;
  public readonly reason: string;

  constructor(role: FontRole, source: string, reason: string) {
    this.role = role;
    this.source = source;
    this.reason = reason;
  }
}

export class StrongScriptContextIndex {
  private readonly leftRoleBeforeBoundary: (FontRole | null)[];
  private readonly rightRoleFromBoundary: (FontRole | null)[];

  constructor(text: string) {
    this.leftRoleBeforeBoundary = [];
    this.rightRoleFromBoundary = [];
    let i = 0;
    while (i <= text.length) {
      this.leftRoleBeforeBoundary[i] = null;
      this.rightRoleFromBoundary[i] = null;
      i++;
    }
    let currentRole: FontRole | null = null;
    let scalarStart = 0;
    while (scalarStart < text.length) {
      const cp = ContextualDashEllipsisRoleResolver.codePointAtCompat(text, scalarStart);
      const scalarEnd = scalarStart + ContextualDashEllipsisRoleResolver.charCount(cp);
      currentRole = StrongScriptContextIndex.nextStrongScriptRole(cp, currentRole);
      let boundary = scalarStart + 1;
      while (boundary <= scalarEnd) {
        this.leftRoleBeforeBoundary[boundary] = currentRole;
        boundary++;
      }
      scalarStart = scalarEnd;
    }
    currentRole = null;
    let scalarEnd2 = text.length;
    while (scalarEnd2 > 0) {
      scalarStart = StrongScriptContextIndex.scalarStartBefore(text, scalarEnd2);
      const cp2 = ContextualDashEllipsisRoleResolver.codePointAtCompat(text, scalarStart);
      currentRole = StrongScriptContextIndex.nextStrongScriptRole(cp2, currentRole);
      let boundary2 = scalarStart;
      while (boundary2 < scalarEnd2) {
        this.rightRoleFromBoundary[boundary2] = currentRole;
        boundary2++;
      }
      scalarEnd2 = scalarStart;
    }
  }

  public leftOf(boundary: number): FontRole | null {
    return this.leftRoleBeforeBoundary[boundary]!;
  }

  public rightOf(boundary: number): FontRole | null {
    return this.rightRoleFromBoundary[boundary]!;
  }

  private static nextStrongScriptRole(codePoint: number, currentRole: FontRole | null): FontRole | null {
    if (LineBreakFns.isMandatoryBreakCodePoint(codePoint)) {
      return null;
    }
    const evidence = UnicodeScriptEvidenceClassifier.classify(codePoint);
    switch (evidence.kind) {
      case "Neutral":
        return currentRole;
      case "EastAsian":
        return FontRole.CjkPunctuation;
      case "Other":
        return FontRole.LatinText;
    }
  }

  private static scalarStartBefore(text: string, endExclusive: number): number {
    const lastIndex = endExclusive - 1;
    const last = (Number.isNaN(text.charCodeAt(lastIndex)) ? null : text.charCodeAt(lastIndex))!;
    if (last >= 56320 && last <= 57343 && lastIndex > 0) {
      const before = readUnit(text, lastIndex - 1)!;
      if (before >= 55296 && before <= 56319) {
        return lastIndex - 1;
      }
    }
    return lastIndex;
  }
}
