// Generated by the reflaxe TypeScript target. Do not edit.

import { CjkPunctuationGlyphSubstitution } from "./../clreq/CjkPunctuationGlyphSubstitution.ts";
import { ClreqPunctuationGlyphSubstitutor } from "./../clreq/ClreqPunctuationGlyphSubstitutor.ts";
import { FontRole } from "./../font/FontRole.ts";

export class ContextualPunctuationDisplaySubstitutionFns {
  public static substituteForRole(self: ClreqPunctuationGlyphSubstitutor, sourceText: string, role: FontRole): CjkPunctuationGlyphSubstitution {
    const candidate = self.substitute(sourceText);
    return (role.kind === "CjkPunctuation" || candidate.displayText === sourceText ? candidate : new CjkPunctuationGlyphSubstitution(sourceText, sourceText, `CjkRoleGatedDisplaySubstitution:preserve-role-${role.kind}`));
  }
}
