// Generated by the reflaxe TypeScript target. Do not edit.

import { ClreqProfile } from "./../clreq/ClreqProfile.ts";
import { PunctuationClass } from "./../clreq/PunctuationClass.ts";
import { AccurateSum } from "./../core/AccurateSum.ts";
import { AutoSpaceDecisionInfo } from "./../core/AutoSpaceDecisionInfo.ts";
import { Cluster } from "./../core/Cluster.ts";
import { ClusterGeometryDecisionInfo } from "./../core/ClusterGeometryDecisionInfo.ts";
import { ContextualKinsokuDecisionInfo } from "./../core/ContextualKinsokuDecisionInfo.ts";
import { Glyph } from "./../core/Glyph.ts";
import { GlyphRun } from "./../core/GlyphRun.ts";
import { InlineObjectBoundaryAdjustment } from "./../core/InlineObjectBoundaryAdjustment.ts";
import { InlineObjectDecisionInfo } from "./../core/InlineObjectDecisionInfo.ts";
import { InlineObjectSpan } from "./../core/InlineObjectSpan.ts";
import { IntRange } from "./../core/IntRange.ts";
import { LayoutInput } from "./../core/LayoutInput.ts";
import { LayoutResult } from "./../core/LayoutResult.ts";
import { LineBox } from "./../core/LineBox.ts";
import { LineDebugInfo } from "./../core/LineDebugInfo.ts";
import { LineEdgeTrimDecisionInfo } from "./../core/LineEdgeTrimDecisionInfo.ts";
import { MaxLinesDecisionInfo } from "./../core/MaxLinesDecisionInfo.ts";
import { RubySpan } from "./../core/RubySpan.ts";
import { Size } from "./../core/Size.ts";
import { TextRange, compareTextRange } from "./../core/TextRange.ts";
import { FontRole } from "./../font/FontRole.ts";
import { AnnotationGeometryStage, AnnotationGeometryStageResult, RubyFontGeometry } from "./AnnotationGeometryStage.ts";
import { JustificationPlan } from "./Justifier.ts";
import { LayoutDebugAssembly, LayoutDebugStageInput } from "./LayoutDebugAssembly.ts";
import { LineBreakPlanningStageResult, ParagraphLayoutPrep } from "./LineBreakPlanningStage.ts";
import { ClusterMetricDecision, LineBoxStageResult, LineGeometryStageFns } from "./LineGeometryStage.ts";
import { LineCandidate, LineSolution, RepairOption, RepairOptions } from "./LineOptimization.ts";
import { ExplainableStubParagraphLayoutEngine } from "./ParagraphLayoutEngine.ts";
import { ParagraphShapingStage } from "./ParagraphShapingStage.ts";
import { ShrinkOpportunity } from "./ProgressiveBreakDecisions.ts";
import { ProgressiveBreakTierPriority } from "./ProgressiveBreakTierPriority.ts";
import { PunctuationGeometryStage } from "./PunctuationGeometryStage.ts";
import { SortedMapTable, SortedSetTable, SortedTable } from "../../../runtime.ts";

export class LineAdjustmentStage {
  private static repairOptionName(repair: RepairOption): string {
    switch (repair.kind) {
      case "PushIn":
        return "PushIn";
      case "Hang":
        return "Hang";
      case "CarryPrevious":
        return "CarryPrevious";
      case "CarryNext":
        return "CarryNext";
      case "LeaveRagged":
        return "LeaveRagged";
    }
  }

  private static lineHyphenAdvanceAt(lineIndex: number, lines: LineCandidate[], hyphenOffsets: SortedSetTable<number>, naturalClusters: Cluster[], hyphenAdvance: number): number {
    if (hyphenOffsets.size() === 0 || lineIndex >= lines.length - 1) {
      return 0.0;
    }
    const next = lines[lineIndex + 1]!;
    if (next.clusterRange.isEmpty) {
      return 0.0;
    }
    const nextFirst = next.clusterRange.start;
    return (hyphenOffsets.has(naturalClusters[nextFirst]!.range.start) ? hyphenAdvance : 0.0);
  }

  private static renderableGlyphRunClusters(clusters: Cluster[], openTypeFeaturesByClusterRange: SortedMapTable<TextRange, string[]>): Cluster[][] {
    const renderable = new Array<Cluster>();
    for (let _g_index = 0, count = clusters.length; _g_index < count; _g_index += 1) {
      const c = clusters[_g_index]!;
      if (c.displayText.length > 0 && !ParagraphShapingStage.isInlineObjectCluster(c)) {
        renderable.push(c);
      }
    }
    const count2 = renderable.length;
    if (count2 === 0) {
      return [];
    }
    const groups = new Array<Cluster[]>();
    let currentGroup = [renderable[0]!];
    for (let i = 1; i < count2; i += 1) {
      const prev = currentGroup[currentGroup.length - 1]!;
      const curr = renderable[i]!;
      const prevFeat = (openTypeFeaturesByClusterRange.has(prev.range) ? openTypeFeaturesByClusterRange.get(prev.range) : []);
      const currFeat = (openTypeFeaturesByClusterRange.has(curr.range) ? openTypeFeaturesByClusterRange.get(curr.range) : []);
      let sameFeatures = prevFeat.length === currFeat.length;
      if (sameFeatures) {
        for (let f = 0, count3 = prevFeat.length; f < count3; f += 1) {
          if (prevFeat[f]! !== currFeat[f]!) {
            sameFeatures = false;
            break;
          }
        }
      }
      if (prev.fontKey === curr.fontKey && prev.range.end === curr.range.start && sameFeatures) {
        currentGroup.push(curr);
      } else {
        groups.push(currentGroup);
        currentGroup = [curr];
      }
    }
    groups.push(currentGroup);
    return groups;
  }

  private static centerDashInk(glyphs: Glyph[], cluster: Cluster, atomClassByRange: SortedMapTable<TextRange, PunctuationClass>): Glyph[] {
    if (!atomClassByRange.has(cluster.range) || (atomClassByRange.get(cluster.range) === null || atomClassByRange.get(cluster.range).kind !== "Dash")) {
      return glyphs;
    }
    if (glyphs.length !== 1) {
      return glyphs;
    }
    const glyph = glyphs[0]!;
    const ink = glyph.bounds;
    if (ink === null) {
      return glyphs;
    }
    const inset = (cluster.advance - (ink.right - ink.left)) / 2.0 - ink.left;
    if (inset <= 0.5) {
      return glyphs;
    }
    return [new Glyph(glyph.id, glyph.clusterRange, glyph.advance, glyph.x + inset, glyph.y, glyph.renderFontKey, glyph.bounds, glyph.haltAdvance, glyph.haltPlacementX)];
  }

  private static buildLineBoxes(input: LayoutInput, lineSolution: LineSolution, trimmedClusters: Cluster[], finalClusters: Cluster[], firstLineIndent: number, blockIndent: number, measure: number, gridBodyOffset: number, lineBaseline: number[], lineTop: number[], lineBottom: number[], hyphenOffsets: SortedSetTable<number>, naturalClusters: Cluster[], hyphenAdvance: number, hyphenGlyphs: Glyph[], justificationPlans: (JustificationPlan | null)[]): LineBoxStageResult {
    const laidOutLines = new Array<LineBox>();
    for (let lineIndex = 0, count5 = lineSolution.lines.length; lineIndex < count5; lineIndex += 1) {
      const lineCandidate = lineSolution.lines[lineIndex]!;
      const adjustedTerms: number[] = [];
      const visualTerms: number[] = [];
      if (!lineCandidate.clusterRange.isEmpty) {
        for (let idx = lineCandidate.clusterRange.start, count6 = lineCandidate.clusterRange.end + 1; idx < count6; idx += 1) {
          adjustedTerms.push((lineCandidate.hangingClusterIndices.has(idx) ? 0.0 : trimmedClusters[idx]!.advance));
          visualTerms.push(finalClusters[idx]!.advance);
        }
      }
      const adjustedWidth = AccurateSum.of(adjustedTerms);
      const visualWidth = AccurateSum.of(visualTerms);
      const hangingTerms: number[] = [];
      for (let hIdx = 0, count7 = lineCandidate.hangingClusterIndices.size(); hIdx < count7; hIdx += 1) {
        hangingTerms.push(finalClusters[lineCandidate.hangingClusterIndices.at(hIdx)]!.advance);
      }
      const hangingPunctuationAdvance = AccurateSum.of(hangingTerms);
      let hasDrawableContent = false;
      if (!lineCandidate.clusterRange.isEmpty) {
        for (let idx2 = lineCandidate.clusterRange.start, count8 = lineCandidate.clusterRange.end + 1; idx2 < count8; idx2 += 1) {
          if (finalClusters[idx2]!.displayText.length > 0) {
            hasDrawableContent = true;
            break;
          }
        }
      }
      let baseIndent = 0.0;
      if (hasDrawableContent) {
        if (lineCandidate.clusterRange.start === 0) {
          baseIndent = firstLineIndent;
        } else {
          baseIndent = blockIndent;
        }
      }
      const lineHyphenAdvance = LineAdjustmentStage.lineHyphenAdvanceAt(lineIndex, lineSolution.lines, hyphenOffsets, naturalClusters, hyphenAdvance);
      const limit = measure - baseIndent;
      let alignmentInset = 0.0;
      if (lineCandidate.endReason.kind !== "AutoWrap") {
        if (input.paragraphStyle.lastLineAlignment.kind === "Center") {
          const diff = (limit - visualWidth) / 2.0;
          alignmentInset = (diff < 0.0 ? 0.0 : diff);
        } else {
          if (input.paragraphStyle.lastLineAlignment.kind === "End") {
            const diff2 = limit - visualWidth;
            alignmentInset = (diff2 < 0.0 ? 0.0 : diff2);
          }
        }
      }
      const repairStr = (lineCandidate.repair !== null ? LineAdjustmentStage.repairOptionName(lineCandidate.repair) + ":" + RepairOptions.reason(lineCandidate.repair) : null);
      const notes = new Array<string>();
      if (lineCandidate.clusterRange.isEmpty) {
        notes.push(`line:${lineIndex}:clusters=empty`);
      } else {
        notes.push(`line:${lineIndex}:clusters=${lineCandidate.clusterRange.start}-${lineCandidate.clusterRange.end}`);
      }
      notes.push(`end:${lineCandidate.endReason.kind}`);
      notes.push(`natural=${lineCandidate.naturalWidth},adjusted=${lineCandidate.adjustedWidth},visual=${visualWidth}`);
      const planForLine = justificationPlans[lineIndex]!;
      if (planForLine !== null && planForLine.fallbackReason !== null) {
        notes.push(`justify-fallback:${planForLine.fallbackReason}`);
      }
      const hGlyphs = (lineHyphenAdvance > 0.0 ? hyphenGlyphs : []);
      laidOutLines.push(new LineBox(lineCandidate.sourceRange, lineCandidate.clusterRange, lineBaseline[lineIndex]!, lineTop[lineIndex]!, lineBottom[lineIndex]!, lineCandidate.naturalWidth, adjustedWidth, visualWidth, hangingPunctuationAdvance, gridBodyOffset + baseIndent + alignmentInset, lineCandidate.endReason, lineHyphenAdvance, hGlyphs, new LineDebugInfo(repairStr, notes)));
    }
    const visibleLines = new Array<LineBox>();
    const maxLines = input.constraints.maxLines;
    const count = (laidOutLines.length > maxLines ? maxLines : laidOutLines.length);
    for (let i = 0; i < count; i += 1) {
      visibleLines.push(laidOutLines[i]!);
    }
    const count4 = visibleLines.length;
    const maxLinesDecision = (count4 < laidOutLines.length ? new MaxLinesDecisionInfo(laidOutLines.length, count4) : null);
    const visibleLineRanges: IntRange[] = [];
    for (let i2 = 0; i2 < count4; i2 += 1) {
      visibleLineRanges.push(lineSolution.lines[i2]!.clusterRange);
    }
    return new LineBoxStageResult(laidOutLines, visibleLines, maxLinesDecision, visibleLineRanges);
  }

  private static isFixedBoundary(b: InlineObjectBoundaryAdjustment): boolean {
    return !b.participatesInUniformStretch && b.preferredStretch === null && b.shrinkCapacity === 0.0 && b.lineEndDiscardableAdvance === 0.0 && !b.preventsLineBreak;
  }

  public static resolveAnnotationGeometry(engine: ExplainableStubParagraphLayoutEngine, input: LayoutInput, fontSize: number, inlineObjectByClusterIndex: SortedMapTable<number, InlineObjectSpan>, lineSolution: LineSolution, clreqProfile: ClreqProfile, geometryDecisions: ClusterGeometryDecisionInfo[], autoSpaceDecisions: AutoSpaceDecisionInfo[], visibleLineRanges: IntRange[], lines: LineBox[], finalClusters: Cluster[], clusterRoles: FontRole[], justifyDeltaByCluster: SortedMapTable<number, number>, rubyAndBopomofoSpread: SortedMapTable<number, number>, metricDecisions: ClusterMetricDecision[], pinyinSpans: RubySpan[], naturalClusters: Cluster[], rubyFontGeometryBySpan: SortedMapTable<RubySpan, RubyFontGeometry>, rubyStackGap: number, baseAscent: number, rubyFontSize: number, rubyFontWeight: number, baseDescent: number, bopomofoFontWeightAt: (a0: number) => number): AnnotationGeometryStageResult {
    const inlineObjectDecisions: InlineObjectDecisionInfo[] = [];
    for (let i = 0; i < inlineObjectByClusterIndex.size(); i += 1) {
      const clusterIndex = inlineObjectByClusterIndex.keyAt(i);
      const inlineObject = inlineObjectByClusterIndex.valueAt(i);
      let lineIdx = -1;
      for (let l = 0, count11 = lineSolution.lines.length; l < count11; l += 1) {
        const cr = lineSolution.lines[l]!.clusterRange;
        if (!cr.isEmpty && clusterIndex >= cr.start && clusterIndex <= cr.end) {
          lineIdx = l;
          break;
        }
      }
      const leadingPreferred = inlineObject.leadingBoundary.preferredStretch;
      const trailingPreferred = inlineObject.trailingBoundary.preferredStretch;
      const reason = (!LineAdjustmentStage.isFixedBoundary(inlineObject.leadingBoundary) || !LineAdjustmentStage.isFixedBoundary(inlineObject.trailingBoundary) ? "AdjustableInlineObject" : "MeasurableOpaqueInlineObject");
      inlineObjectDecisions.push(new InlineObjectDecisionInfo(inlineObject.range, inlineObject.advance, inlineObject.ascent, inlineObject.descent, clusterIndex, lineIdx, inlineObject.leadingBoundary.participatesInUniformStretch, (leadingPreferred !== null ? leadingPreferred.kind.kind : null), ((leadingPreferred !== null ? leadingPreferred.naturalWidth : 0.0) ?? 0.0), ((leadingPreferred !== null ? leadingPreferred.targetWidth : 0.0) ?? 0.0), ((leadingPreferred !== null ? leadingPreferred.capacity : 0.0) ?? 0.0), inlineObject.leadingBoundary.preventsLineBreak, inlineObject.leadingBoundary.shrinkCapacity, inlineObject.leadingBoundary.lineEndDiscardableAdvance, inlineObject.trailingBoundary.participatesInUniformStretch, (trailingPreferred !== null ? trailingPreferred.kind.kind : null), ((trailingPreferred !== null ? trailingPreferred.naturalWidth : 0.0) ?? 0.0), ((trailingPreferred !== null ? trailingPreferred.targetWidth : 0.0) ?? 0.0), ((trailingPreferred !== null ? trailingPreferred.capacity : 0.0) ?? 0.0), inlineObject.trailingBoundary.preventsLineBreak, inlineObject.trailingBoundary.shrinkCapacity, inlineObject.trailingBoundary.lineEndDiscardableAdvance, reason));
    }
    const decorationDecisions = AnnotationGeometryStage.computeDecorationDecisions(input.decorations, visibleLineRanges, lines, finalClusters, clusterRoles, justifyDeltaByCluster, rubyAndBopomofoSpread, metricDecisions, fontSize, input.paragraphStyle.emphasisDotGapEm);
    const autoSpaceGapPx = clreqProfile.autoSpace.gapEm * fontSize;
    const geometryByRangeBuilder = SortedTable.mapBuilder<TextRange, ClusterGeometryDecisionInfo>(compareTextRange);
    for (let gi = 0, count9 = geometryDecisions.length; gi < count9; gi += 1) {
      const gd = geometryDecisions[gi]!;
      geometryByRangeBuilder.put(gd.range, gd);
    }
    const geometryByRange = geometryByRangeBuilder.build();
    const leadingGapRangesBuilder = SortedTable.setBuilder<TextRange>(compareTextRange);
    const trailingGapRangesBuilder = SortedTable.setBuilder<TextRange>(compareTextRange);
    for (let ai = 0, count10 = autoSpaceDecisions.length; ai < count10; ai += 1) {
      const ad = autoSpaceDecisions[ai]!;
      if (ad.side === "leading") {
        leadingGapRangesBuilder.put(ad.clusterRange);
      } else {
        if (ad.side === "trailing") {
          trailingGapRangesBuilder.put(ad.clusterRange);
        }
      }
    }
    const leadingGapRanges = leadingGapRangesBuilder.build();
    const trailingGapRanges = trailingGapRangesBuilder.build();
    const decorationSegments = AnnotationGeometryStage.computeDecorationSegments(input.decorations, visibleLineRanges, lines, finalClusters, justifyDeltaByCluster, geometryByRange, leadingGapRanges, trailingGapRanges, autoSpaceGapPx, fontSize);
    const rubyDecisions = AnnotationGeometryStage.computeRubyDecisions(pinyinSpans, visibleLineRanges, lines, finalClusters, naturalClusters, metricDecisions, rubyFontGeometryBySpan, rubyStackGap, baseAscent, rubyFontSize, rubyFontWeight, input.textStyle.locale);
    const bopomofoSpans = new Array<RubySpan>();
    for (let ri = 0, count12 = input.rubySpans.length; ri < count12; ri += 1) {
      const rs = input.rubySpans[ri]!;
      if (rs.kind.kind === "Bopomofo") {
        bopomofoSpans.push(rs);
      }
    }
    const bopomofoDecisions = AnnotationGeometryStage.computeBopomofoDecisions(engine, bopomofoSpans, visibleLineRanges, lines, finalClusters, naturalClusters, baseAscent, baseDescent, fontSize, bopomofoFontWeightAt, input.textStyle);
    return new AnnotationGeometryStageResult(inlineObjectDecisions, decorationDecisions, decorationSegments, rubyDecisions, bopomofoDecisions);
  }

  private static trimEdge(lineSourceRange: TextRange, clusterIdx: number, side: string, naturalClusters: Cluster[], autoSpaceDecisions: AutoSpaceDecisionInfo[], autoSpaceGap: number, autoSpaceEdgeTrims: number[], autoSpaceEdgeDecisions: LineEdgeTrimDecisionInfo[]): void {
    let foundDecision: AutoSpaceDecisionInfo | null = null;
    const cRange = naturalClusters[clusterIdx]!.range;
    for (let _g_index = 0, count13 = autoSpaceDecisions.length; _g_index < count13; _g_index += 1) {
      const dec = autoSpaceDecisions[_g_index]!;
      if (dec.clusterRange.start === cRange.start && dec.clusterRange.end === cRange.end && dec.side === side) {
        foundDecision = dec;
        break;
      }
    }
    if (foundDecision !== null) {
      autoSpaceEdgeTrims[clusterIdx] += autoSpaceGap;
      autoSpaceEdgeDecisions.push(new LineEdgeTrimDecisionInfo(lineSourceRange, foundDecision.clusterRange, side, autoSpaceGap, 0.0, autoSpaceGap, "TextAutoSpaceLineEdgeTrim"));
    }
  }

  private static collapseEdgeSpace(lineSourceRange: TextRange, clusterIdx: number, side: string, naturalClusters: Cluster[], inlineObjectSeparatorSpaceTrims: SortedMapTable<number, number>, autoSpaceEdgeTrims: number[], autoSpaceEdgeDecisions: LineEdgeTrimDecisionInfo[]): void {
    const cluster = naturalClusters[clusterIdx]!;
    if (!PunctuationGeometryStage.isSpaceRun(cluster)) {
      return;
    }
    if (inlineObjectSeparatorSpaceTrims.has(clusterIdx)) {
      return;
    }
    const advance = cluster.advance;
    if (advance <= 0.0) {
      return;
    }
    autoSpaceEdgeTrims[clusterIdx] += advance;
    autoSpaceEdgeDecisions.push(new LineEdgeTrimDecisionInfo(lineSourceRange, cluster.range, side, advance, 0.0, advance, "LineEdgeWordSpaceCollapse"));
  }

  public static finishParagraphLayout(engine: ExplainableStubParagraphLayoutEngine, prep: ParagraphLayoutPrep, plan: LineBreakPlanningStageResult): LayoutResult {
    const appliedHangingClustersBuilder = SortedTable.setBuilder<number>(SortedTable.compareInts);
    {
      const _g1 = plan.lineSolution.lines;
      for (let _g_index = 0, count20 = _g1.length; _g_index < count20; _g_index += 1) {
        const line = _g1[_g_index]!;
        for (let i = 0, count21 = line.hangingClusterIndices.size(); i < count21; i += 1) {
          appliedHangingClustersBuilder.put(line.hangingClusterIndices.at(i));
        }
      }
    }
    const appliedHangingClusters = appliedHangingClustersBuilder.build();
    const impossibleMeasureContextualHangClustersBuilder = SortedTable.setBuilder<number>(SortedTable.compareInts);
    for (let i2 = 0, count22 = plan.asciiPointMarkKinsoku.impossibleMeasureHangEligibleClusters.size(); i2 < count22; i2 += 1) {
      impossibleMeasureContextualHangClustersBuilder.put(plan.asciiPointMarkKinsoku.impossibleMeasureHangEligibleClusters.at(i2));
    }
    for (let i3 = 0, count23 = plan.inlineObjectKinsoku.impossibleMeasureHangEligibleClusters.size(); i3 < count23; i3 += 1) {
      impossibleMeasureContextualHangClustersBuilder.put(plan.inlineObjectKinsoku.impossibleMeasureHangEligibleClusters.at(i3));
    }
    const impossibleMeasureContextualHangClusters = impossibleMeasureContextualHangClustersBuilder.build();
    const rawDecisions = new Array<ContextualKinsokuDecisionInfo>();
    {
      const _g15 = plan.asciiPointMarkKinsoku.decisions;
      for (let _g_index1 = 0, count24 = _g15.length; _g_index1 < count24; _g_index1 += 1) {
        const d = _g15[_g_index1]!;
        rawDecisions.push(d);
      }
    }
    {
      const _g16 = plan.inlineObjectKinsoku.decisions;
      for (let _g_index2 = 0, count25 = _g16.length; _g_index2 < count25; _g_index2 += 1) {
        const d2 = _g16[_g_index2]!;
        rawDecisions.push(d2);
      }
    }
    {
      const _g17 = plan.unicodePunctuationBoundaries.decisions;
      for (let _g_index3 = 0, count26 = _g17.length; _g_index3 < count26; _g_index3 += 1) {
        const d3 = _g17[_g_index3]!;
        rawDecisions.push(d3);
      }
    }
    const seenDecisionKeys = new Array<string>();
    const contextualKinsokuDecisions = new Array<ContextualKinsokuDecisionInfo>();
    for (let _g_index4 = 0, count14 = rawDecisions.length; _g_index4 < count14; _g_index4 += 1) {
      const decision = rawDecisions[_g_index4]!;
      const key = decision.range.toString() + ":" + decision.forbiddenPosition;
      let alreadySeen = false;
      {
        let _g4 = 0;
        while (_g4 < seenDecisionKeys.length) {
          const s = seenDecisionKeys[_g4]!;
          _g4++;
          if (s === key) {
            alreadySeen = true;
            break;
          }
        }
      }
      if (!alreadySeen) {
        seenDecisionKeys.push(key);
        const cIdx = decision.clusterIndex;
        if (impossibleMeasureContextualHangClusters.has(cIdx) && appliedHangingClusters.has(cIdx)) {
          const fallback = (decision.reason === "AttachedAsciiPointMarkKinsoku" ? "AttachedAsciiPointMarkImpossibleMeasureHang" : "InlineObjectAttachedMarkImpossibleMeasureHang");
          contextualKinsokuDecisions.push(new ContextualKinsokuDecisionInfo(decision.range, decision.sourceText, decision.clusterIndex, decision.forbiddenPosition, decision.reason, fallback));
        } else {
          contextualKinsokuDecisions.push(decision);
        }
      }
    }
    const pushInTrailing = new Array<number>();
    const pushInLeading = new Array<number>();
    const pushInRawTrims = new Array<number>();
    for (let i4 = 0, count27 = prep.naturalClusters.length; i4 < count27; i4 += 1) {
      pushInTrailing.push(0.0);
      pushInLeading.push(0.0);
      pushInRawTrims.push(0.0);
    }
    for (let lIdx = 0, count28 = plan.lineSolution.lines.length; lIdx < count28; lIdx += 1) {
      const line2 = plan.lineSolution.lines[lIdx]!;
      const repair = line2.repair;
      if (repair !== null) {
        const allocations = RepairOptions.pushInAllocations(repair);
        if (allocations !== null) {
          for (let aIdx = 0, count29 = allocations.length; aIdx < count29; aIdx += 1) {
            const alloc = allocations[aIdx]!;
            if (alloc.clusterIndex >= 0 && alloc.clusterIndex < prep.naturalClusters.length) {
              if (alloc.channel.kind === "TrailingGlue") {
                const index = alloc.clusterIndex;
                pushInTrailing[index] += alloc.shrink;
              } else {
                if (alloc.channel.kind === "LeadingGlue") {
                  const index2 = alloc.clusterIndex;
                  pushInLeading[index2] += alloc.shrink;
                } else {
                  if (alloc.channel.kind === "LeadingAndTrailingGlue") {
                    const index3 = alloc.clusterIndex;
                    pushInLeading[index3] += alloc.shrink / 2.0;
                    const index4 = alloc.clusterIndex;
                    pushInTrailing[index4] += alloc.shrink / 2.0;
                  } else {
                    if (alloc.channel.kind === "RawAdvance") {
                      const index5 = alloc.clusterIndex;
                      pushInRawTrims[index5] += alloc.shrink;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (prep.hyphenOffsets.size() > 0) {
      for (let lineIndex = 0, count30 = plan.lineSolution.lines.length; lineIndex < count30; lineIndex += 1) {
        const line3 = plan.lineSolution.lines[lineIndex]!;
        if (line3.clusterRange.isEmpty) {
          continue;
        }
        const hyphen = LineAdjustmentStage.lineHyphenAdvanceAt(lineIndex, plan.lineSolution.lines, prep.hyphenOffsets, prep.naturalClusters, prep.hyphenAdvance);
        if (hyphen <= 0.0) {
          continue;
        }
        const lineLimit = (line3.clusterRange.start === 0 ? prep.measure - plan.firstLineIndent : prep.measure - plan.blockIndent);
        const contentTerms: number[] = [];
        for (let cIdx2 = line3.clusterRange.start, count31 = line3.clusterRange.end + 1; cIdx2 < count31; cIdx2 += 1) {
          contentTerms.push(prep.clusters[cIdx2]!.advance);
        }
        const content = AccurateSum.of(contentTerms);
        let shortfall = content + hyphen - lineLimit;
        if (shortfall <= 0.001) {
          continue;
        }
        const sortedOpportunities = new Array<ShrinkOpportunity>();
        for (let oppIdx = 0, count32 = prep.shrinkOpportunities.length; oppIdx < count32; oppIdx += 1) {
          const opp = prep.shrinkOpportunities[oppIdx]!;
          if (opp.clusterIndex >= line3.clusterRange.start && opp.clusterIndex <= line3.clusterRange.end && !opp.lineEndOnly) {
            sortedOpportunities.push(opp);
          }
        }
        let rIdx = 1;
        while (rIdx < sortedOpportunities.length) {
          const curr = sortedOpportunities[rIdx]!;
          let j = rIdx - 1;
          while (j >= 0 && sortedOpportunities[j]!.tier > curr.tier) {
            sortedOpportunities[j + 1] = sortedOpportunities[j]!;
            j--;
          }
          sortedOpportunities[j + 1] = curr;
          rIdx++;
        }
        for (let oIdx = 0, count33 = sortedOpportunities.length; oIdx < count33; oIdx += 1) {
          const opp2 = sortedOpportunities[oIdx]!;
          if (shortfall <= 0.001) {
            break;
          }
          let used = 0.0;
          if (opp2.channel.kind === "TrailingGlue") {
            used = pushInTrailing[opp2.clusterIndex]!;
          } else {
            if (opp2.channel.kind === "LeadingGlue") {
              used = pushInLeading[opp2.clusterIndex]!;
            } else {
              if (opp2.channel.kind === "RawAdvance") {
                used = pushInRawTrims[opp2.clusterIndex]!;
              } else {
                if (opp2.channel.kind === "LeadingAndTrailingGlue") {
                  used = pushInLeading[opp2.clusterIndex]! + pushInTrailing[opp2.clusterIndex]!;
                }
              }
            }
          }
          const avail = opp2.capacity - used;
          const target = (shortfall < avail ? shortfall : avail);
          const take = (target < 0.0 ? 0.0 : target);
          if (take <= 0.0) {
            continue;
          }
          if (opp2.channel.kind === "TrailingGlue") {
            const index6 = opp2.clusterIndex;
            pushInTrailing[index6] += take;
          } else {
            if (opp2.channel.kind === "LeadingGlue") {
              const index7 = opp2.clusterIndex;
              pushInLeading[index7] += take;
            } else {
              if (opp2.channel.kind === "LeadingAndTrailingGlue") {
                const index8 = opp2.clusterIndex;
                pushInLeading[index8] += take / 2.0;
                const index9 = opp2.clusterIndex;
                pushInTrailing[index9] += take / 2.0;
              } else {
                if (opp2.channel.kind === "RawAdvance") {
                  const index10 = opp2.clusterIndex;
                  pushInRawTrims[index10] += take;
                }
              }
            }
          }
          shortfall -= take;
        }
      }
    }
    const pushInTrailingMapBuilder = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    const pushInLeadingMapBuilder = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    for (let i5 = 0, count34 = prep.naturalClusters.length; i5 < count34; i5 += 1) {
      if (pushInTrailing[i5]! !== 0.0) {
        pushInTrailingMapBuilder.put(i5, pushInTrailing[i5]!);
      }
      if (pushInLeading[i5]! !== 0.0) {
        pushInLeadingMapBuilder.put(i5, pushInLeading[i5]!);
      }
    }
    const pushInGeometry = prep.baseGeometry.consumeTrailingByCluster(pushInTrailingMapBuilder.build()).consumeLeadingByCluster(pushInLeadingMapBuilder.build());
    const edgeTrimResult = pushInGeometry.consumeLineEdgeGlue(plan.lineSolution.lines, prep.adjustmentStyle.lineEndPunctuation.kind === "ForceHalfWidth");
    const autoSpaceGap = prep.clreqProfile.autoSpace.gapEm * prep.fontSize;
    const autoSpaceEdgeTrims: number[] = [];
    for (let i6 = 0; i6 < prep.naturalClusters.length; i6 += 1) {
      autoSpaceEdgeTrims.push(0.0);
    }
    const autoSpaceEdgeDecisions = new Array<LineEdgeTrimDecisionInfo>();
    {
      const _g117 = plan.lineSolution.lines;
      for (let _g_index5 = 0, count35 = _g117.length; _g_index5 < count35; _g_index5 += 1) {
        const line4 = _g117[_g_index5]!;
        if (line4.clusterRange.isEmpty) {
          continue;
        }
        LineAdjustmentStage.trimEdge(line4.sourceRange, line4.clusterRange.end, "trailing", prep.naturalClusters, prep.autoSpaceDecisions, autoSpaceGap, autoSpaceEdgeTrims, autoSpaceEdgeDecisions);
        LineAdjustmentStage.trimEdge(line4.sourceRange, line4.clusterRange.start, "leading", prep.naturalClusters, prep.autoSpaceDecisions, autoSpaceGap, autoSpaceEdgeTrims, autoSpaceEdgeDecisions);
        LineAdjustmentStage.collapseEdgeSpace(line4.sourceRange, line4.clusterRange.end, "trailing", prep.naturalClusters, prep.inlineObjectSeparatorSpaceTrims, autoSpaceEdgeTrims, autoSpaceEdgeDecisions);
        LineAdjustmentStage.collapseEdgeSpace(line4.sourceRange, line4.clusterRange.start, "leading", prep.naturalClusters, prep.inlineObjectSeparatorSpaceTrims, autoSpaceEdgeTrims, autoSpaceEdgeDecisions);
        const attachedGlueCluster = line4.clusterRange.end;
        const attachedGlue = (prep.attachedPunctuationTrailingGlueByCluster.has(attachedGlueCluster) ? prep.attachedPunctuationTrailingGlueByCluster.get(attachedGlueCluster) : 0.0);
        if (attachedGlue > 0.0) {
          autoSpaceEdgeTrims[attachedGlueCluster] += attachedGlue;
          autoSpaceEdgeDecisions.push(new LineEdgeTrimDecisionInfo(line4.sourceRange, prep.naturalClusters[attachedGlueCluster]!.range, "trailing", attachedGlue, 0.0, attachedGlue, "AttachedInlineVirtualBoundaryLineEndTrim"));
        }
        if (line4.endReason.kind === "AutoWrap") {
          const clusterIdx = line4.clusterRange.end;
          const discardable = (prep.inlineObjectByClusterIndex.has(clusterIdx) ? prep.inlineObjectByClusterIndex.get(clusterIdx).trailingBoundary.lineEndDiscardableAdvance : 0.0);
          const consumedBefore = (pushInRawTrims[clusterIdx]! < discardable ? pushInRawTrims[clusterIdx]! : discardable);
          const diff = discardable - consumedBefore;
          const remaining = (diff < 0.0 ? 0.0 : diff);
          if (remaining > 0.0) {
            autoSpaceEdgeTrims[clusterIdx] += remaining;
            autoSpaceEdgeDecisions.push(new LineEdgeTrimDecisionInfo(line4.sourceRange, prep.naturalClusters[clusterIdx]!.range, "trailing", remaining, consumedBefore, discardable, "InlineObjectLineEndDiscardableGlue"));
          }
        }
      }
    }
    const rawTrimsBuilder = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    for (let i7 = 0, count36 = prep.naturalClusters.length; i7 < count36; i7 += 1) {
      const total = autoSpaceEdgeTrims[i7]! + pushInRawTrims[i7]!;
      if (total !== 0.0) {
        rawTrimsBuilder.put(i7, total);
      }
    }
    const trimmedGeometry = edgeTrimResult.geometry.withRawEdgeTrims(rawTrimsBuilder.build());
    const trimmedClusters = trimmedGeometry.resolveClusters();
    const edgeTrimDecisions = new Array<LineEdgeTrimDecisionInfo>();
    {
      const _g119 = edgeTrimResult.decisions;
      for (let _g_index6 = 0, count37 = _g119.length; _g_index6 < count37; _g_index6 += 1) {
        const d4 = _g119[_g_index6]!;
        edgeTrimDecisions.push(d4);
      }
    }
    for (let _g_index7 = 0, count15 = autoSpaceEdgeDecisions.length; _g_index7 < count15; _g_index7 += 1) {
      const d5 = autoSpaceEdgeDecisions[_g_index7]!;
      edgeTrimDecisions.push(d5);
    }
    const justificationPlans = new Array<JustificationPlan | null>();
    for (let lineIndex2 = 0, count38 = plan.lineSolution.lines.length; lineIndex2 < count38; lineIndex2 += 1) {
      const lineCandidate = plan.lineSolution.lines[lineIndex2]!;
      const isLast = lineIndex2 === plan.lineSolution.lines.length - 1;
      if (isLast || lineCandidate.clusterRange.isEmpty || lineCandidate.endReason.kind !== "AutoWrap") {
        justificationPlans.push(null);
      } else {
        const nextIdx = lineCandidate.clusterRange.end + 1;
        const selectedTechnicalBreak = (plan.progressiveBreakOpportunities.has(nextIdx) ? plan.progressiveBreakOpportunities.get(nextIdx) : null);
        const preferredTrackingSpan = (selectedTechnicalBreak !== null && selectedTechnicalBreak.tier.kind === "Emergency" ? selectedTechnicalBreak.spanRange : null);
        const preferredEmergencyTrackingBoundariesBuilder = SortedTable.mapBuilder<number, string>(SortedTable.compareInts);
        if (preferredTrackingSpan !== null) {
          for (let i8 = 0, count39 = plan.emergencyTrackingBoundaryAfterClusters.size(); i8 < count39; i8 += 1) {
            const leftIndex = plan.emergencyTrackingBoundaryAfterClusters.keyAt(i8);
            const reason = plan.emergencyTrackingBoundaryAfterClusters.valueAt(i8);
            const rightIndex = leftIndex + 1;
            if (prep.naturalClusters[leftIndex]!.range.start >= preferredTrackingSpan.start && prep.naturalClusters[rightIndex]!.range.end <= preferredTrackingSpan.end) {
              preferredEmergencyTrackingBoundariesBuilder.put(leftIndex, reason);
            }
          }
        }
        const preferredEmergencyTrackingBoundaries = preferredEmergencyTrackingBoundariesBuilder.build();
        const hyphenAdvanceForLine = LineAdjustmentStage.lineHyphenAdvanceAt(lineIndex2, plan.lineSolution.lines, prep.hyphenOffsets, prep.naturalClusters, prep.hyphenAdvance);
        const lineLimit2 = (lineCandidate.clusterRange.start === 0 ? prep.measure - plan.firstLineIndent : prep.measure - plan.blockIndent) - hyphenAdvanceForLine;
        const planResult = engine.justifier.justify(trimmedClusters, prep.clusterRoles, prep.eastAsianSpacingEdges, lineCandidate.inMeasureClusterRange, lineLimit2, prep.fontSize, false, null, prep.adjustmentStyle.allowSinoWesternGapAdjustment, prep.clreqProfile.autoSpace.gapEm, prep.clreqProfile.autoSpace.stretchMaxEm, plan.noStretchBoundaryClusters, plan.noStretchBoundaryAfterClusters, plan.westernBracketCjkInterCharBoundaryAfterClusters, plan.attachedInlinePhysicalBoundaryAfterClusters, plan.attachedInlineVirtualBoundaryAfterClusters, plan.attachedInlineVirtualSinoWesternBoundaryAfterClusters, prep.uniformInlineObjectBoundaryAfterClusters, prep.preferredInlineObjectBoundaryAfterClusters, plan.technicalBoundaryAfterClusters, plan.emergencyTrackingBoundaryAfterClusters, preferredEmergencyTrackingBoundaries);
        justificationPlans.push(planResult);
      }
    }
    const currentLineTechnicalBodyStretchLimit = 0.0 * prep.fontSize;
    const newlyRejectedSpans = new Array<TextRange>();
    const newlyRejectedTiersList = new Array<SortedSetTable<number>>();
    for (let lineIndex3 = 0, count40 = plan.lineSolution.lines.length; lineIndex3 < count40; lineIndex3 += 1) {
      const line5 = plan.lineSolution.lines[lineIndex3]!;
      if (line5.endReason.kind !== "AutoWrap" || line5.clusterRange.start > line5.clusterRange.end) {
        continue;
      }
      const nextCluster = line5.clusterRange.end + 1;
      if (!plan.progressiveBreakOpportunities.has(nextCluster)) {
        continue;
      }
      const selectedTechnicalBreak2 = plan.progressiveBreakOpportunities.get(nextCluster);
      if (selectedTechnicalBreak2.tier.kind === "Emergency") {
        continue;
      }
      const spanRange = selectedTechnicalBreak2.spanRange;
      if (prep.rejectedTechnicalTiersBySpan.has(spanRange)) {
        const rejectedForSpan = prep.rejectedTechnicalTiersBySpan.get(spanRange);
        if (rejectedForSpan.has(ProgressiveBreakTierPriority.priority(selectedTechnicalBreak2.tier))) {
          continue;
        }
      }
      const currentLinePlan = justificationPlans[lineIndex3]!;
      if (currentLinePlan === null) {
        continue;
      }
      let currentLineUsesUnboundedTracking = false;
      {
        const _g123 = currentLinePlan.allocations;
        for (let _g_index8 = 0, count41 = _g123.length; _g_index8 < count41; _g_index8 += 1) {
          const alloc2 = _g123[_g_index8]!;
          if ((alloc2.kind.kind === "CjkInterChar" || alloc2.kind.kind === "EmergencyGraphemeTracking") && alloc2.delta > currentLineTechnicalBodyStretchLimit + 0.001) {
            currentLineUsesUnboundedTracking = true;
            break;
          }
        }
      }
      if (currentLineUsesUnboundedTracking) {
        let foundSpanIdx = -1;
        for (let sIdx = 0, count42 = newlyRejectedSpans.length; sIdx < count42; sIdx += 1) {
          if (newlyRejectedSpans[sIdx]!.start === spanRange.start && newlyRejectedSpans[sIdx]!.end === spanRange.end) {
            foundSpanIdx = sIdx;
            break;
          }
        }
        if (foundSpanIdx < 0) {
          newlyRejectedSpans.push(spanRange);
          const b = SortedTable.setBuilder<number>(SortedTable.compareInts);
          b.put(ProgressiveBreakTierPriority.priority(selectedTechnicalBreak2.tier));
          newlyRejectedTiersList.push(b.build());
        } else {
          const b2 = SortedTable.setBuilder<number>(SortedTable.compareInts);
          const existing = newlyRejectedTiersList[foundSpanIdx]!;
          for (let e = 0, count43 = existing.size(); e < count43; e += 1) {
            b2.put(existing.at(e));
          }
          b2.put(ProgressiveBreakTierPriority.priority(selectedTechnicalBreak2.tier));
          newlyRejectedTiersList[foundSpanIdx] = b2.build();
        }
      }
    }
    if (newlyRejectedSpans.length > 0) {
      const updatedRejectedTiersBuilder = SortedTable.mapBuilder<TextRange, SortedSetTable<number>>(compareTextRange);
      const count44 = newlyRejectedSpans.length;
      for (let i9 = 0, count45 = prep.rejectedTechnicalTiersBySpan.size(); i9 < count45; i9 += 1) {
        const span = prep.rejectedTechnicalTiersBySpan.keyAt(i9);
        const tiers = prep.rejectedTechnicalTiersBySpan.valueAt(i9);
        const b3 = SortedTable.setBuilder<number>(SortedTable.compareInts);
        for (let t = 0, count47 = tiers.size(); t < count47; t += 1) {
          b3.put(tiers.at(t));
        }
        for (let nIdx = 0, count46 = newlyRejectedSpans.length; nIdx < count46; nIdx += 1) {
          if (newlyRejectedSpans[nIdx]!.start === span.start && newlyRejectedSpans[nIdx]!.end === span.end) {
            const addTiers = newlyRejectedTiersList[nIdx]!;
            for (let at = 0, count48 = addTiers.size(); at < count48; at += 1) {
              b3.put(addTiers.at(at));
            }
          }
        }
        updatedRejectedTiersBuilder.put(span, b3.build());
      }
      for (let nIdx2 = 0, count49 = newlyRejectedSpans.length; nIdx2 < count49; nIdx2 += 1) {
        const span2 = newlyRejectedSpans[nIdx2]!;
        if (!prep.rejectedTechnicalTiersBySpan.has(span2)) {
          updatedRejectedTiersBuilder.put(span2, newlyRejectedTiersList[nIdx2]!);
        }
      }
      return engine.layoutWithRejectedTechnicalTiers(prep.input, updatedRejectedTiersBuilder.build());
    }
    const justifyDeltas: number[] = [];
    for (let i10 = 0; i10 < prep.naturalClusters.length; i10 += 1) {
      justifyDeltas.push(0.0);
    }
    for (let _g_index9 = 0, count16 = justificationPlans.length; _g_index9 < count16; _g_index9 += 1) {
      const p = justificationPlans[_g_index9]!;
      if (p !== null) {
        let _g26 = 0;
        const _g132 = p.allocations;
        while (_g26 < _g132.length) {
          const alloc3 = _g132[_g26]!;
          _g26++;
          if (alloc3.targetClusterIndex >= 0 && alloc3.targetClusterIndex < justifyDeltas.length) {
            const index11 = alloc3.targetClusterIndex;
            justifyDeltas[index11] += alloc3.delta;
          }
        }
      }
    }
    const justifyDeltaBuilder = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    for (let i11 = 0, count50 = justifyDeltas.length; i11 < count50; i11 += 1) {
      if (justifyDeltas[i11]! !== 0.0) {
        justifyDeltaBuilder.put(i11, justifyDeltas[i11]!);
      }
    }
    const justifyDeltaByCluster = justifyDeltaBuilder.build();
    const finalGeometry = trimmedGeometry.addJustificationDeltas(justifyDeltaByCluster);
    const resolvedFinalClusters = finalGeometry.resolveClusters();
    const finalClusters = new Array<Cluster>();
    for (let _g_index10 = 0, count17 = resolvedFinalClusters.length; _g_index10 < count17; _g_index10 += 1) {
      const c = resolvedFinalClusters[_g_index10]!;
      if (!plan.metricDecisionByRange.has(c.range)) {
        finalClusters.push(c);
      } else {
        const m = plan.metricDecisionByRange.get(c.range).layoutMetrics;
        const metricShift = (m.baselineClass.kind === "Roman" ? 0.0 : plan.baseBoxDescent - m.descent);
        const shift = c.baselineShift + metricShift + prep.styleAt(c.range.start).baselineShift;
        if (shift > -0.01 && shift < 0.01) {
          finalClusters.push(c);
        } else {
          finalClusters.push(new Cluster(c.range, c.text, c.fontKey, c.advance, c.displayText, shift, c.leadingLayoutAdvance, c.glyphInlineShift));
        }
      }
    }
    const geometryDecisions = finalGeometry.toDecisionInfo();
    const runGroups = LineAdjustmentStage.renderableGlyphRunClusters(finalClusters, prep.openTypeFeaturesByClusterRange);
    const count18 = runGroups.length;
    const glyphRuns: GlyphRun[] = [];
    for (let _g_index11 = 0; _g_index11 < count18; _g_index11 += 1) {
      const runClusters = runGroups[_g_index11]!;
      const firstC = runClusters[0]!;
      const count51 = runClusters.length;
      const lastC = runClusters[count51 - 1]!;
      const openTypeFeatures = (prep.openTypeFeaturesByClusterRange.has(firstC.range) ? prep.openTypeFeaturesByClusterRange.get(firstC.range) : []);
      const runGlyphs = new Array<Glyph>();
      const runAdvanceTerms: number[] = [];
      for (let clusterIdx2 = 0; clusterIdx2 < count51; clusterIdx2 += 1) {
        const cluster = runClusters[clusterIdx2]!;
        runAdvanceTerms.push(cluster.advance);
        if (prep.shapedGlyphsByClusterRange.has(cluster.range)) {
          const shaped = prep.shapedGlyphsByClusterRange.get(cluster.range);
          const mapped = ParagraphShapingStage.mapToClusterRange(shaped, cluster);
          const centered = LineAdjustmentStage.centerDashInk(mapped, cluster, prep.atomClassByRange);
          {
            let _g29 = 0;
            while (_g29 < centered.length) {
              const g = centered[_g29]!;
              _g29++;
              runGlyphs.push(g);
            }
          }
        } else {
          runGlyphs.push(new Glyph(clusterIdx2, cluster.range, cluster.advance));
        }
      }
      glyphRuns.push(new GlyphRun(new TextRange(firstC.range.start, lastC.range.end), firstC.fontKey, runGlyphs, AccurateSum.of(runAdvanceTerms), (openTypeFeatures ?? [])));
    }
    const verticalGeometry = LineGeometryStageFns.resolveLineVerticalGeometrySorted(prep.input, prep.fontSize, prep.pinyinSpans, prep.naturalClusters, plan.lineSolution, prep.rubyFontGeometryBySpan, plan.existingInterlineSpace, plan.baseLineMetrics, plan.baseFaceHeight, plan.rubyExtent, prep.inlineObjectByClusterIndex, plan.baseAscent, plan.baseDescent);
    const rubyLineHeightDecision = verticalGeometry.rubyLineHeightDecision;
    const inlineObjectLineHeightDecision = verticalGeometry.inlineObjectLineHeightDecision;
    const lineBaseline = verticalGeometry.lineBaseline;
    const lineTop = verticalGeometry.lineTop;
    const lineBottom = verticalGeometry.lineBottom;
    const lineBoxes = LineAdjustmentStage.buildLineBoxes(prep.input, plan.lineSolution, trimmedClusters, finalClusters, plan.firstLineIndent, plan.blockIndent, prep.measure, prep.gridBodyOffset, lineBaseline, lineTop, lineBottom, prep.hyphenOffsets, prep.naturalClusters, prep.hyphenAdvance, prep.hyphenGlyphs, justificationPlans);
    const laidOutLines = lineBoxes.laidOutLines;
    const lines = lineBoxes.visibleLines;
    const maxLinesDecision = lineBoxes.maxLinesDecision;
    const visibleLineRanges = lineBoxes.visibleLineRanges;
    const annotationGeometry = LineAdjustmentStage.resolveAnnotationGeometry(engine, prep.input, prep.fontSize, prep.inlineObjectByClusterIndex, plan.lineSolution, prep.clreqProfile, geometryDecisions, prep.autoSpaceDecisions, visibleLineRanges, lines, finalClusters, prep.clusterRoles, justifyDeltaByCluster, prep.rubyAndBopomofoSpread, plan.metricDecisions, prep.pinyinSpans, prep.naturalClusters, prep.rubyFontGeometryBySpan, prep.rubyStackGap, plan.baseAscent, prep.rubyFontSize, prep.rubyFontWeight, plan.baseDescent, prep.bopomofoFontWeightAt);
    const inlineObjectDecisions = annotationGeometry.inlineObjectDecisions;
    const decorationDecisions = annotationGeometry.decorationDecisions;
    const decorationSegments = annotationGeometry.decorationSegments;
    const rubyDecisions = annotationGeometry.rubyDecisions;
    const bopomofoDecisions = annotationGeometry.bopomofoDecisions;
    let widestLine = 0.0;
    for (let i12 = 0, count19 = lines.length; i12 < count19; i12 += 1) {
      const line6 = lines[i12]!;
      const w = line6.indent + line6.visualWidth + line6.hyphenAdvance;
      if (w > widestLine) {
        widestLine = w;
      }
    }
    let totalHeight = 0.0;
    if (lines.length > 0) {
      totalHeight = lines[lines.length - 1]!.bottom;
    } else {
      if (prep.text.length === 0) {
        totalHeight = 0.0;
      } else {
        totalHeight = plan.baseLineMetrics.height;
      }
    }
    const maxWidthConstraint = prep.input.constraints.maxWidth;
    const resultWidth = (widestLine > maxWidthConstraint ? maxWidthConstraint : widestLine);
    return new LayoutResult(prep.input, new Size(resultWidth, totalHeight), finalClusters, glyphRuns, lines, LayoutDebugAssembly.buildLayoutDebugInfo(engine, new LayoutDebugStageInput(prep.text, prep.fontDecisions, prep.punctuationGlyphSubstitutor, prep.substitutionRollbacks, prep.shapingDecisions, plan.metricDecisions, prep.punctuationAtoms, geometryDecisions, prep.spacingPlan, prep.attachedPunctuationBoundary, prep.roleOverrideInfos, laidOutLines, plan.lineSolution, prep.clusters, justificationPlans, prep.autoSpaceDecisions, edgeTrimDecisions, decorationDecisions, decorationSegments, rubyDecisions, bopomofoDecisions, prep.mandatoryBreakDecisions, maxLinesDecision, plan.lineSpacingDecision, rubyLineHeightDecision, inlineObjectLineHeightDecision, plan.kinsokuDecision, contextualKinsokuDecisions, prep.lineLengthGridDecision, plan.firstLineIndentDecision, prep.inlineBoxResult.decisions, inlineObjectDecisions, prep.inlineObjectPunctuationAttachmentDecisions, prep.zeroWidthBreakDecisions, prep.breakOpportunityDecisions, prep.emergencyTrackingEligibilityDecisions, plan.progressiveBreakOpportunities)));
  }
}
