// Generated by the reflaxe TypeScript target. Do not edit.

import { AccurateSum } from "./../core/AccurateSum.ts";
import { Cluster } from "./../core/Cluster.ts";
import { IntRange } from "./../core/IntRange.ts";
import { LineEndReason } from "./../core/LineEndReason.ts";
import { TextRange } from "./../core/TextRange.ts";
import { TextRangeError } from "./../core/TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./../core/TiqianIllegalArgumentException.ts";
import { KinsokuRule } from "./KinsokuRule.ts";
import { LineBreakerLines } from "./LineBreaker.ts";
import { LineCandidate, LineSolution, PushInAllocation, RepairCandidate, RepairOption, RepairOptions } from "./LineOptimization.ts";
import { ProgressiveBreakDecisions, ProgressiveBreakOpportunity, ShrinkOpportunity, UnbreakableRanges } from "./ProgressiveBreakDecisions.ts";
import { ProgressiveBreakTierPriority } from "./ProgressiveBreakTierPriority.ts";
import { SortedMapTable, SortedSetTable, SortedTable } from "../../../runtime.ts";

export class PushInResult {
  public readonly previous: LineCandidate;
  public readonly current: LineCandidate | null;
  public readonly candidate: RepairCandidate;

  constructor(previous: LineCandidate, current: LineCandidate | null, candidate: RepairCandidate) {
    this.previous = previous;
    this.current = current;
    this.candidate = candidate;
  }

  public toString(): string {
    return `PushInResult(previous=${this.previous.toString()}, current=${(this.current === null ? "null" : this.current.toString())}, candidate=${this.candidate.toString()})`;
  }
}

export class LineRepair {
  public static applyKinsokuRepairs(initial: LineCandidate[], naturalClusters: Cluster[], adjustedClusters: Cluster[], maxWidth: number, kinsoku: KinsokuRule, shrinkOpportunities: ShrinkOpportunity[], pushInPenalty: number, carryPreviousPenalty: number, leaveRaggedPenalty: number, unbreakableRanges?: UnbreakableRanges | null, firstLineIndent?: number | null, hangableClusters?: SortedSetTable<number> | null, extendableHangRanges?: IntRange[] | null, hangPenalty?: number | null, forbiddenLineStartClusters?: SortedSetTable<number> | null): LineSolution {
    if (initial.length < 2) {
      return new LineSolution(initial);
    }
    const ranges = unbreakableRanges ?? UnbreakableRanges.Empty;
    const indent = firstLineIndent ?? 0;
    const hangables = hangableClusters ?? LineRepair.emptyIntSet();
    const extendables = extendableHangRanges ?? [];
    const hangCost = hangPenalty ?? 5;
    const mutable = initial.slice();
    let i = 1;
    while (i < mutable.length) {
      const curr = mutable[i]!;
      const firstIndex = curr.clusterRange.start;
      const prev = mutable[i - 1]!;
      if (prev.endReason.kind === "MandatoryBreak" || curr.clusterRange.isEmpty) {
        i++;
        continue;
      }
      const firstCluster = adjustedClusters[firstIndex]!;
      const forbidden = (forbiddenLineStartClusters !== null ? forbiddenLineStartClusters.has(firstIndex) : kinsoku.forbiddenAtLineStart(firstCluster));
      if (!forbidden) {
        i++;
        continue;
      }
      const repairCandidates: RepairCandidate[] = [];
      const pushIn = LineRepair.tryPushIn(prev, curr, naturalClusters, adjustedClusters, ProgressiveBreakDecisions.lineLimit(maxWidth, indent, prev.clusterRange.start), shrinkOpportunities, pushInPenalty, null, "ForbiddenAtLineStart");
      repairCandidates.push(pushIn.candidate);
      if (pushIn.candidate.accepted) {
        mutable[i - 1] = pushIn.previous;
        if (pushIn.current === null) {
          mutable.splice(i, 1);
        } else {
          mutable[i] = pushIn.current;
        }
        continue;
      }
      const offenderIndex = curr.clusterRange.start;
      const existingHanging = prev.hangingClusterIndices;
      let extendsContextualHang = false;
      if (existingHanging.size() > 0 && prev.clusterRange.end + 1 === offenderIndex) {
        let gi = 0;
        while (gi < extendables.length) {
          const group = extendables[gi]!;
          if (offenderIndex >= group.start && offenderIndex <= group.end) {
            let all = true;
            let hi = 0;
            while (hi < existingHanging.size()) {
              const idx = existingHanging.at(hi);
              if (idx < group.start || idx > group.end) {
                all = false;
                break;
              }
              hi++;
            }
            if (all) {
              extendsContextualHang = true;
              break;
            }
          }
          gi++;
        }
      }
      if (hangables.has(offenderIndex) && (existingHanging.size() === 0 || extendsContextualHang)) {
        const mergeEndIndex = LineRepair.mandatoryBreakTailEnd(curr, offenderIndex, adjustedClusters);
        const hangCandidate = new RepairCandidate("Hang", "ForbiddenAtLineStart", offenderIndex, hangCost, true, null, null, null);
        repairCandidates.push(hangCandidate);
        const mergedRange = new IntRange(prev.clusterRange.start, mergeEndIndex);
        const mergedTerms: number[] = [];
        let wi = prev.clusterRange.end + 1;
        while (wi <= mergeEndIndex) {
          mergedTerms.push(naturalClusters[wi]!.advance);
          wi++;
        }
        const mergedNatural = prev.naturalWidth + AccurateSum.of(mergedTerms);
        const hangIndices = SortedTable.setBuilder<number>(SortedTable.compareInts);
        let ai = 0;
        while (ai < existingHanging.size()) {
          hangIndices.put(existingHanging.at(ai));
          ai++;
        }
        let xi = offenderIndex;
        while (xi <= mergeEndIndex) {
          hangIndices.put(xi);
          xi++;
        }
        const candidateList = prev.repairCandidates.slice();
        let cpi = 0;
        while (cpi < repairCandidates.length) {
          candidateList.push(repairCandidates[cpi]!);
          cpi++;
        }
        mutable[i - 1] = new LineCandidate(mergedRange, new TextRange(adjustedClusters[mergedRange.start]!.range.start, adjustedClusters[mergeEndIndex]!.range.end), mergedNatural, prev.adjustedWidth, ((mergeEndIndex === curr.clusterRange.end ? curr.endReason : prev.endReason) ?? (LineEndReason.AutoWrap as LineEndReason)), ({ kind: "Hang", penalty: hangCost, reason: `ForbiddenAtLineStart:${firstCluster.text}:hang`, offenderClusterIndex: offenderIndex } as RepairOption), candidateList, hangIndices.build());
        if (mergeEndIndex === curr.clusterRange.end) {
          mutable.splice(i, 1);
        } else {
          mutable[i] = LineBreakerLines.rebuildLine(new IntRange(mergeEndIndex + 1, curr.clusterRange.end), naturalClusters, adjustedClusters, curr.endReason, null, null);
        }
        continue;
      }
      const canCarry = prev.clusterRange.start < prev.clusterRange.end;
      if (!canCarry) {
        repairCandidates.push(new RepairCandidate("CarryPrevious", "ForbiddenAtLineStart", firstIndex, carryPreviousPenalty, false, "no-room-to-carry", null, null));
        repairCandidates.push(new RepairCandidate("LeaveRagged", "ForbiddenAtLineStart", firstIndex, leaveRaggedPenalty, true, null, null, null));
        mutable[i] = new LineCandidate(curr.clusterRange, curr.sourceRange, curr.naturalWidth, curr.adjustedWidth, curr.endReason, ({ kind: "LeaveRagged", penalty: leaveRaggedPenalty, reason: `ForbiddenAtLineStart:${firstCluster.text}:no-room-to-carry`, offenderClusterIndex: firstIndex } as RepairOption), repairCandidates, curr.hangingClusterIndices);
        i++;
        continue;
      }
      const carriedIndex = prev.clusterRange.end;
      if (ranges.containsBoundary(carriedIndex)) {
        repairCandidates.push(new RepairCandidate("CarryPrevious", "ForbiddenAtLineStart", firstIndex, carryPreviousPenalty, false, "carry-would-split-mourning-span", null, carriedIndex));
        repairCandidates.push(new RepairCandidate("LeaveRagged", "ForbiddenAtLineStart", firstIndex, leaveRaggedPenalty, true, null, null, null));
        mutable[i] = new LineCandidate(curr.clusterRange, curr.sourceRange, curr.naturalWidth, curr.adjustedWidth, curr.endReason, ({ kind: "LeaveRagged", penalty: leaveRaggedPenalty, reason: `ForbiddenAtLineStart:${firstCluster.text}:carry-would-split-mourning-span`, offenderClusterIndex: firstIndex } as RepairOption), repairCandidates, curr.hangingClusterIndices);
        i++;
        continue;
      }
      const newPrevRange = new IntRange(prev.clusterRange.start, carriedIndex - 1);
      const newCurrRange = new IntRange(carriedIndex, curr.clusterRange.end);
      const carriedCurrent = LineBreakerLines.rebuildLine(newCurrRange, naturalClusters, adjustedClusters, curr.endReason, null, null);
      if (carriedCurrent.adjustedWidth > maxWidth) {
        repairCandidates.push(new RepairCandidate("CarryPrevious", "ForbiddenAtLineStart", firstIndex, carryPreviousPenalty, false, "carry-overflows", null, carriedIndex));
        repairCandidates.push(new RepairCandidate("LeaveRagged", "ForbiddenAtLineStart", firstIndex, leaveRaggedPenalty, true, null, null, null));
        mutable[i] = new LineCandidate(curr.clusterRange, curr.sourceRange, curr.naturalWidth, curr.adjustedWidth, curr.endReason, ({ kind: "LeaveRagged", penalty: leaveRaggedPenalty, reason: `ForbiddenAtLineStart:${firstCluster.text}:carry-overflows`, offenderClusterIndex: firstIndex } as RepairOption), repairCandidates, curr.hangingClusterIndices);
        i++;
        continue;
      }
      repairCandidates.push(new RepairCandidate("CarryPrevious", "ForbiddenAtLineStart", firstIndex, carryPreviousPenalty, true, null, null, carriedIndex));
      mutable[i - 1] = LineBreakerLines.rebuildLine(newPrevRange, naturalClusters, adjustedClusters, prev.endReason, null, null);
      mutable[i] = new LineCandidate(carriedCurrent.clusterRange, carriedCurrent.sourceRange, carriedCurrent.naturalWidth, carriedCurrent.adjustedWidth, carriedCurrent.endReason, ({ kind: "CarryPrevious", penalty: carryPreviousPenalty, reason: `ForbiddenAtLineStart:${firstCluster.text}:carried=${adjustedClusters[carriedIndex]!.text}`, offenderClusterIndex: firstIndex, carriedClusterIndex: carriedIndex } as RepairOption), repairCandidates, carriedCurrent.hangingClusterIndices);
      i++;
    }
    const badnessTerms: number[] = [];
    for (let bi = 0, count = mutable.length; bi < count; bi += 1) {
      badnessTerms.push((mutable[bi]!.repair === null ? 0.0 : RepairOptions.penalty(mutable[bi]!.repair) * 1.0));
    }
    const totalBadness = AccurateSum.of(badnessTerms);
    return new LineSolution(mutable, totalBadness);
  }

  public static tryPushIn(prev: LineCandidate, curr: LineCandidate, naturalClusters: Cluster[], adjustedClusters: Cluster[], maxWidth: number, shrinkOpportunities: ShrinkOpportunity[], pushInPenalty: number, mergeThroughClusterIndex?: number | null, reasonCode?: string | null): PushInResult {
    const code = reasonCode ?? "ForbiddenAtLineStart";
    const offenderIndex = mergeThroughClusterIndex ?? curr.clusterRange.start;
    if (offenderIndex < curr.clusterRange.start || offenderIndex > curr.clusterRange.end) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "PushIn merge-through cluster must belong to the current line." } as TextRangeError));
    }
    const mergeEndIndex = LineRepair.mandatoryBreakTailEnd(curr, offenderIndex, adjustedClusters);
    const expandedRange = new IntRange(prev.clusterRange.start, mergeEndIndex);
    const expanded = LineBreakerLines.rebuildLine(expandedRange, naturalClusters, adjustedClusters, null, null, null);
    const overflow = expanded.adjustedWidth - maxWidth;
    const pipeline_result = new Array<ShrinkOpportunity>();
    for (let pipeline_index = 0, count2 = shrinkOpportunities.length; pipeline_index < count2; pipeline_index += 1) {
      const v = shrinkOpportunities[pipeline_index]!;
      if (v.clusterIndex >= expandedRange.start && v.clusterIndex <= expandedRange.end && v.capacity > 0 && (!v.lineEndOnly || v.clusterIndex === offenderIndex)) {
        pipeline_result.push(v);
      }
    }
    const _this = pipeline_result;
    const count3 = _this.length;
    const pipeline_result1: ShrinkOpportunity[] = new Array<ShrinkOpportunity>(count3);
    for (let pipeline_index1 = 0; pipeline_index1 < count3; pipeline_index1 += 1) {
      const v2 = _this[pipeline_index1]!;
      pipeline_result1[pipeline_index1] = (v2.clusterIndex === offenderIndex && (v2.channel.kind === "TrailingGlue" || v2.channel.kind === "LeadingAndTrailingGlue") ? new ShrinkOpportunity(v2.clusterIndex, 1, v2.capacity, v2.channel, v2.lineEndOnly) : v2);
    }
    const inLine = pipeline_result1;
    const capacityTerms: number[] = [];
    for (let ci = 0, count4 = inLine.length; ci < count4; ci += 1) {
      capacityTerms.push(inLine[ci]!.capacity);
    }
    const totalCapacity = AccurateSum.of(capacityTerms);
    if (overflow > totalCapacity) {
      const required = (overflow > 0 ? overflow : 0);
      return new PushInResult(prev, curr, new RepairCandidate("PushIn", code, offenderIndex, pushInPenalty, false, "insufficient-capacity", offenderIndex, null, 0, required, totalCapacity));
    }
    const shrink = (overflow > 0 ? overflow : 0);
    const allocations = (shrink > 0 ? LineRepair.distributePushInShrink(inLine, shrink) : []);
    const offender = adjustedClusters[offenderIndex]!;
    const candidate = new RepairCandidate("PushIn", code, offenderIndex, pushInPenalty, true, null, offenderIndex, null, shrink, shrink, totalCapacity);
    const reasonText = (shrink > 0 ? code + ":" + offender.text + ":pushed-in=" + LineRepair.toPortableDebugString(shrink) + "/" + LineRepair.toPortableDebugString(totalCapacity) : code + ":" + offender.text + ":fits-no-shrink");
    const candidateList = prev.repairCandidates.slice();
    candidateList.push(candidate);
    const repairedPrevious = new LineCandidate(expanded.clusterRange, expanded.sourceRange, expanded.naturalWidth, expanded.adjustedWidth - shrink, ((mergeEndIndex === curr.clusterRange.end ? curr.endReason : prev.endReason) ?? (LineEndReason.AutoWrap as LineEndReason)), ({ kind: "PushIn", penalty: pushInPenalty, reason: reasonText, offenderClusterIndex: offenderIndex, allocations, totalShrink: shrink, totalAvailableCapacity: totalCapacity } as RepairOption), candidateList, expanded.hangingClusterIndices);
    const repairedCurrent = (mergeEndIndex === curr.clusterRange.end ? null : LineBreakerLines.rebuildLine(new IntRange(mergeEndIndex + 1, curr.clusterRange.end), naturalClusters, adjustedClusters, curr.endReason, null, null));
    return new PushInResult(repairedPrevious, repairedCurrent, candidate);
  }

  private static mandatoryBreakTailEnd(curr: LineCandidate, mergeThroughClusterIndex: number, adjustedClusters: Cluster[]): number {
    if (curr.endReason.kind !== "MandatoryBreak") {
      return mergeThroughClusterIndex;
    }
    if (mergeThroughClusterIndex >= curr.clusterRange.end) {
      return mergeThroughClusterIndex;
    }
    let tailIsZeroWidthBreak = true;
    let idx = mergeThroughClusterIndex + 1;
    while (idx <= curr.clusterRange.end) {
      if (!(adjustedClusters[idx]!.displayText.length === 0 && adjustedClusters[idx]!.advance === 0)) {
        tailIsZeroWidthBreak = false;
        break;
      }
      idx++;
    }
    return (tailIsZeroWidthBreak ? curr.clusterRange.end : mergeThroughClusterIndex);
  }

  private static distributePushInShrink(opportunities: ShrinkOpportunity[], totalShrink: number): PushInAllocation[] {
    const count5 = opportunities.length;
    if (count5 === 0 || totalShrink <= 0) {
      return [];
    }
    const allocations: PushInAllocation[] = [];
    let remaining = totalShrink;
    const pipeline_builder = SortedTable.mapBuilder<number, ShrinkOpportunity[]>(SortedTable.compareInts);
    for (let pipeline_index = 0; pipeline_index < count5; pipeline_index += 1) {
      const opp = opportunities[pipeline_index]!;
      {
        const pipeline_entry = { key: opp.tier, value: opp };
        let pipeline_bucket = pipeline_builder.get(pipeline_entry.key)!;
        if (pipeline_bucket === null) {
          pipeline_bucket = new Array<ShrinkOpportunity>();
          pipeline_builder.put(pipeline_entry.key, pipeline_bucket);
        }
        pipeline_bucket.push(pipeline_entry.value);
      }
    }
    const pipeline_result = pipeline_builder.build();
    const byTier = pipeline_result;
    let tierIdx = 0;
    while (tierIdx < byTier.size()) {
      const tierOpps = byTier.valueAt(tierIdx);
      const tierTerms: number[] = [];
      for (let ti = 0, count6 = tierOpps.length; ti < count6; ti += 1) {
        tierTerms.push(tierOpps[ti]!.capacity);
      }
      const tierCapacity = AccurateSum.of(tierTerms);
      if (tierCapacity > 0) {
        const tierShrink = (remaining < tierCapacity ? remaining : tierCapacity);
        let tierRemaining = tierShrink;
        const ordered = LineRepair.sortByClusterIndex(tierOpps);
        let i2 = 0;
        while (i2 < ordered.length) {
          const opp2 = ordered[i2]!;
          const isLast = i2 === tierOpps.length - 1;
          let share = 0.0;
          if (isLast) {
            share = (tierRemaining < opp2.capacity ? tierRemaining : opp2.capacity);
          } else {
            const proportional = tierShrink * opp2.capacity / tierCapacity;
            share = (proportional < opp2.capacity ? proportional : opp2.capacity);
          }
          if (share > 0) {
            allocations.push(new PushInAllocation(opp2.clusterIndex, share, opp2.capacity, opp2.channel));
            tierRemaining -= share;
          }
          i2++;
        }
        remaining -= tierShrink - (tierRemaining > 0 ? tierRemaining : 0);
      }
      tierIdx++;
    }
    return allocations;
  }

  private static sortByClusterIndex(opportunities: ShrinkOpportunity[]): ShrinkOpportunity[] {
    const pipeline_result = opportunities.slice().sort((_a, _b) => { const _ka = _a.clusterIndex; const _kb = _b.clusterIndex; return _ka < _kb ? -1 : (_ka > _kb ? 1 : 0); });
    return pipeline_result;
  }

  private static toPortableDebugString(value: number): string {
    const text = `${value}`;
    if (text.indexOf(".") === -1 && text.toLowerCase().indexOf("e") === -1) {
      return text + ".0";
    }
    return text;
  }

  private static emptyIntSet(): SortedSetTable<number> {
    const b = SortedTable.setBuilder<number>(SortedTable.compareInts);
    return b.build();
  }

  private static isContinuableZeroShrinkFillPushIn(repair: RepairOption | null): boolean {
    if (repair === null) {
      return false;
    }
    const r = repair!;
    switch (r.kind) {
      case "PushIn":
      {
        return r.totalShrink <= 0.001 && r.reason.startsWith("LineAdjustmentPushIn:");
      }
      case "Hang":
        return false;
      case "CarryPrevious":
        return false;
      case "CarryNext":
        return false;
      case "LeaveRagged":
        return false;
    }
  }

  public static fillPushInGroupEnd(curr: LineCandidate, forbiddenLineStartClusters: SortedSetTable<number> | null, forbiddenLineEndClusters: SortedSetTable<number>, unbreakableRanges: UnbreakableRanges): number | null {
    let groupEnd = curr.clusterRange.start;
    while (groupEnd <= curr.clusterRange.end) {
      const containing = unbreakableRanges.containingFromClosedStartOrNull(groupEnd);
      if (containing !== null) {
        groupEnd = containing.end;
        if (groupEnd > curr.clusterRange.end) {
          return null;
        }
        continue;
      }
      if (forbiddenLineEndClusters.has(groupEnd)) {
        groupEnd += 1;
        continue;
      }
      const nextHead = groupEnd + 1;
      if (nextHead <= curr.clusterRange.end && forbiddenLineStartClusters !== null && forbiddenLineStartClusters.has(nextHead)) {
        groupEnd = nextHead;
        continue;
      }
      return groupEnd;
    }
    return null;
  }

  public static applyFillPushIn(lines: LineCandidate[], naturalClusters: Cluster[], adjustedClusters: Cluster[], maxWidth: number, shrinkOpportunities: ShrinkOpportunity[], firstLineIndent: number, compressBias: number, forbiddenLineStartClusters: SortedSetTable<number> | null, forbiddenLineEndClusters: SortedSetTable<number>, unbreakableRanges: UnbreakableRanges, pushInPenalty: number, gapBoundaries?: SortedSetTable<number> | null, progressiveBreakOpportunities?: SortedMapTable<number, ProgressiveBreakOpportunity> | null): LineCandidate[] {
    if (lines.length < 2 || compressBias <= 0) {
      return lines;
    }
    const gaps = gapBoundaries ?? LineBreakerLines.emptyIntSet();
    const progressive = progressiveBreakOpportunities ?? LineBreakerLines.emptyProgressiveMap();
    const out = lines.slice();
    let i = 0;
    while (i < out.length - 1) {
      const prev = out[i]!;
      const curr = out[i + 1]!;
      const canExtendZeroShrinkFill = LineRepair.isContinuableZeroShrinkFillPushIn(prev.repair);
      if (prev.repair !== null && !canExtendZeroShrinkFill || prev.hangingClusterIndex !== null || prev.endReason.kind !== "AutoWrap") {
        i += 1;
        continue;
      }
      const limit = ProgressiveBreakDecisions.lineLimit(maxWidth, firstLineIndent, prev.clusterRange.start);
      const deficit = limit - prev.adjustedWidth;
      if (deficit <= 0) {
        i += 1;
        continue;
      }
      const curr0 = curr.clusterRange.start;
      let groupEnd = LineRepair.fillPushInGroupEnd(curr, forbiddenLineStartClusters, forbiddenLineEndClusters, unbreakableRanges);
      if (groupEnd === null) {
        i += 1;
        continue;
      }
      const currentBreak = progressive.get(prev.clusterRange.end + 1);
      let resultingBreak = progressive.get(groupEnd + 1);
      const addedTerms: number[] = [];
      let cIdx = curr0;
      while (cIdx <= groupEnd) {
        addedTerms.push(adjustedClusters[cIdx]!.advance);
        cIdx++;
      }
      let addedAdvance = AccurateSum.of(addedTerms);
      let promotesProgressiveTier = currentBreak !== null && resultingBreak !== null && currentBreak.spanRange.start === resultingBreak.spanRange.start && currentBreak.spanRange.end === resultingBreak.spanRange.end && ProgressiveBreakTierPriority.priority(resultingBreak.tier) < ProgressiveBreakTierPriority.priority(currentBreak.tier);
      if (promotesProgressiveTier && addedAdvance < deficit - 0.001) {
        const activeBreak = currentBreak;
        const searchStart = groupEnd + 2;
        const searchEnd = curr.clusterRange.end + 1;
        let matchingTierBoundary: number | null = null;
        if (searchStart <= searchEnd) {
          let boundary = searchStart;
          while (boundary <= searchEnd) {
            const opp = progressive.get(boundary);
            if (opp !== null && opp.spanRange.start === activeBreak.spanRange.start && opp.spanRange.end === activeBreak.spanRange.end && opp.tier === activeBreak.tier) {
              matchingTierBoundary = boundary;
              break;
            }
            boundary++;
          }
        }
        if (matchingTierBoundary !== null) {
          groupEnd = matchingTierBoundary - 1;
          resultingBreak = progressive.get(matchingTierBoundary);
          const reassignedTerms: number[] = [];
          let cIdx2 = curr0;
          while (cIdx2 <= groupEnd) {
            reassignedTerms.push(adjustedClusters[cIdx2]!.advance);
            cIdx2++;
          }
          addedAdvance = AccurateSum.of(reassignedTerms);
          promotesProgressiveTier = false;
        }
      }
      if (currentBreak !== null && resultingBreak !== null && currentBreak.spanRange.start === resultingBreak.spanRange.start && currentBreak.spanRange.end === resultingBreak.spanRange.end && ProgressiveBreakTierPriority.priority(resultingBreak.tier) > ProgressiveBreakTierPriority.priority(currentBreak.tier)) {
        i += 1;
        continue;
      }
      const overflow = addedAdvance - deficit;
      if (promotesProgressiveTier && overflow < -0.001) {
        i += 1;
        continue;
      }
      if (overflow >= deficit * compressBias) {
        i += 1;
        continue;
      }
      if (overflow > 0.0 && !promotesProgressiveTier) {
        const prevGaps = LineBreakerLines.lineGapCount(prev.clusterRange, gaps);
        const dStretchCured = (prevGaps === 0 ? 0.0 : deficit / prevGaps);
        const groupGaps = LineBreakerLines.lineGapCount(new IntRange(prev.clusterRange.start, groupEnd), gaps);
        const dCompressionIntroduced = overflow / (groupGaps > 1 ? groupGaps : 1);
        if (dCompressionIntroduced > dStretchCured) {
          i += 1;
          continue;
        }
      }
      const result = LineRepair.tryPushIn(prev, curr, naturalClusters, adjustedClusters, limit, shrinkOpportunities, pushInPenalty, groupEnd, (promotesProgressiveTier ? "ProgressiveTechnicalTierPromotion" : "LineAdjustmentPushIn"));
      if (result.candidate.accepted) {
        out[i] = result.previous;
        if (result.current === null) {
          out.splice(i + 1, 1);
        } else {
          out[i + 1] = result.current;
        }
        if (LineRepair.isContinuableZeroShrinkFillPushIn(result.previous.repair) && result.current !== null) {
          continue;
        }
      }
      i += 1;
    }
    return out;
  }

  public static withFillPushIn(solution: LineSolution, enabled: boolean, naturalClusters: Cluster[], adjustedClusters: Cluster[], maxWidth: number, shrinkOpportunities: ShrinkOpportunity[], firstLineIndent: number, compressBias: number, forbiddenLineStartClusters: SortedSetTable<number> | null, forbiddenLineEndClusters: SortedSetTable<number>, unbreakableRanges: UnbreakableRanges, pushInPenalty: number, gapBoundaries?: SortedSetTable<number> | null, progressiveBreakOpportunities?: SortedMapTable<number, ProgressiveBreakOpportunity> | null): LineSolution {
    if (!enabled) {
      return solution;
    }
    return new LineSolution(LineRepair.applyFillPushIn(solution.lines, naturalClusters, adjustedClusters, maxWidth, shrinkOpportunities, firstLineIndent, compressBias, forbiddenLineStartClusters, forbiddenLineEndClusters, unbreakableRanges, pushInPenalty, gapBoundaries, progressiveBreakOpportunities), solution.totalBadness);
  }
}

export interface ShrinkTierEntry {
  key: number;
  value: ShrinkOpportunity;
}
