// Generated by the reflaxe TypeScript target. Do not edit.

import { DecorationKind } from "./../core/DecorationKind.ts";
import { LayoutQueries } from "./../core/LayoutQueries.ts";
import { LayoutResult } from "./../core/LayoutResult.ts";
import { LineEndReason } from "./../core/LineEndReason.ts";
import { PunctuationDecisionInfo } from "./../core/PunctuationDecisionInfo.ts";
import { ShapingDecisionInfo } from "./../core/ShapingDecisionInfo.ts";
import { TextRange } from "./../core/TextRange.ts";
import { TextStyle } from "./../core/TextStyle.ts";
import { FontRole } from "./../font/FontRole.ts";
import { Plan, PlanBopomofo, PlanBopomofoPlacement, PlanCell, PlanDecorationSegment, PlanEmphasisDot, PlanEmphasisRange, PlanInlineEdge, PlanLine, PlanRuby } from "./../protocol/Plan.ts";
import { PlanEndReason } from "./../protocol/PlanEndReason.ts";
import { PlanStyleDelta } from "./../protocol/PlanStyleDelta.ts";
import { SortedTable } from "../../../runtime.ts";

export class PlanLowering {
  private static f32(v: number): number {
    return v;
  }

  private static rangeKey(r: TextRange): string {
    return String(r.start) + ":" + String(r.end);
  }

  private static styleAt(result: LayoutResult, offset: number): TextStyle {
    const spanSrc = result.input.content.spans;
    for (let si = 0, count = spanSrc.length; si < count; si += 1) {
      const span = spanSrc[si]!;
      if (offset >= span.range.start && offset < span.range.end) {
        return span.style;
      }
    }
    return result.input.textStyle;
  }

  public static toPlan(result: LayoutResult, renderEvidence: boolean): Plan {
    const naturalB = SortedTable.mapBuilder<string, number>(SortedTable.compareStrings);
    const featuresB = SortedTable.mapBuilder<string, string[]>(SortedTable.compareStrings);
    const fontsB = SortedTable.mapBuilder<string, string>(SortedTable.compareStrings);
    const glyphIdsB = SortedTable.mapBuilder<string, string[]>(SortedTable.compareStrings);
    for (let ri = 0, count7 = result.glyphRuns.length; ri < count7; ri += 1) {
      const run = result.glyphRuns[ri]!;
      for (let gi = 0, count8 = run.glyphs.length; gi < count8; gi += 1) {
        const glyph = run.glyphs[gi]!;
        const k = PlanLowering.rangeKey(glyph.clusterRange);
        const priorNatural = naturalB.get(k);
        const priorN = (priorNatural === null ? 0.0 : priorNatural);
        naturalB.put(k, priorN + glyph.advance);
        if (run.openTypeFeatures.length > 0) {
          let fs = featuresB.get(k);
          if (fs === null) {
            fs = [];
          }
          for (let fi = 0, count9 = run.openTypeFeatures.length; fi < count9; fi += 1) {
            const f = run.openTypeFeatures[fi]!;
            if (fs.indexOf(f) < 0) {
              fs.push(f);
            }
          }
          featuresB.put(k, fs);
        }
        const rfk = glyph.renderFontKey;
        if (rfk !== null) {
          fontsB.put(k, rfk);
        }
        let ids = glyphIdsB.get(k);
        if (ids === null) {
          ids = [];
        }
        ids.push(String(glyph.id));
        glyphIdsB.put(k, ids);
      }
    }
    const zeroB = SortedTable.mapBuilder<string, boolean>(SortedTable.compareStrings);
    const zeroSrc = result.debug.zeroWidthBreakDecisions;
    for (let zi = 0, count2 = zeroSrc.length; zi < count2; zi += 1) {
      zeroB.put(PlanLowering.rangeKey(zeroSrc[zi]!.range), true);
    }
    const shapingB = SortedTable.mapBuilder<string, ShapingDecisionInfo>(SortedTable.compareStrings);
    const shapingSrc = result.debug.shapingDecisions;
    for (let zi2 = 0, count3 = shapingSrc.length; zi2 < count3; zi2 += 1) {
      shapingB.put(PlanLowering.rangeKey(shapingSrc[zi2]!.range), shapingSrc[zi2]!);
    }
    const punctB = SortedTable.mapBuilder<string, PunctuationDecisionInfo>(SortedTable.compareStrings);
    const punctSrc = result.debug.punctuationDecisions;
    for (let zi3 = 0, count4 = punctSrc.length; zi3 < count4; zi3 += 1) {
      punctB.put(PlanLowering.rangeKey(punctSrc[zi3]!.range), punctSrc[zi3]!);
    }
    const inlineAdvanceB = SortedTable.mapBuilder<string, number>(SortedTable.compareStrings);
    const inlineObjSrc = result.input.inlineObjects;
    for (let zi4 = 0, count5 = inlineObjSrc.length; zi4 < count5; zi4 += 1) {
      inlineAdvanceB.put(PlanLowering.rangeKey(inlineObjSrc[zi4]!.range), inlineObjSrc[zi4]!.advance);
    }
    const edgeStartB = SortedTable.mapBuilder<string, number>(SortedTable.compareStrings);
    const edgeEndB = SortedTable.mapBuilder<string, number>(SortedTable.compareStrings);
    const boxSrc = result.input.inlineBoxes;
    for (let bi = 0, count6 = boxSrc.length; bi < count6; bi += 1) {
      const b = boxSrc[bi]!;
      if (b.inlineStart !== 0) {
        const sk = String(b.range.start);
        const priorStart = edgeStartB.get(sk);
        const pStart = (priorStart === null ? 0.0 : priorStart);
        edgeStartB.put(sk, pStart + b.inlineStart);
      }
      if (b.inlineEnd !== 0) {
        const ek = String(b.range.end);
        const priorEnd = edgeEndB.get(ek);
        const pEnd = (priorEnd === null ? 0.0 : priorEnd);
        edgeEndB.put(ek, pEnd + b.inlineEnd);
      }
    }
    const natural = naturalB.build();
    const features = featuresB.build();
    const fonts = fontsB.build();
    const glyphIds = glyphIdsB.build();
    const zero = zeroB.build();
    const shaping = shapingB.build();
    const punct = punctB.build();
    const inlineAdvance = inlineAdvanceB.build();
    const edgeStart = edgeStartB.build();
    const edgeEnd = edgeEndB.build();
    const lines: PlanLine[] = [];
    for (let li = 0, count10 = result.lines.length; li < count10; li += 1) {
      const line = result.lines[li]!;
      const cells: PlanCell[] = [];
      {
        const _g110 = LayoutQueries.positionedClustersForLine(result, line);
        for (let _g_index = 0, count11 = _g110.length; _g_index < count11; _g_index += 1) {
          const p = _g110[_g_index]!;
          const c = result.clusters[p.clusterIndex]!;
          const ck = PlanLowering.rangeKey(c.range);
          if (!(c.displayText.length > 0 || zero.has(ck) || renderEvidence && inlineAdvance.has(ck))) {
            continue;
          }
          const natW = (natural.has(ck) ? natural.get(ck) : c.advance);
          let inlineObj: number | null = null;
          let advOverride: number | null = null;
          let renderFam: string | null = null;
          let dash: string | null = null;
          let lang: string | null = null;
          let face: string | null = null;
          let gIds: string | null = null;
          let ev: string | null = null;
          let inkFloor: number | null = null;
          let bodyW: number | null = null;
          let latin = false;
          let styleDelta: PlanStyleDelta | null = null;
          if (renderEvidence) {
            inlineObj = (inlineAdvance.has(ck) ? inlineAdvance.get(ck) : null);
            const glyphW = (inlineObj === null ? natW : inlineObj);
            advOverride = (c.advance !== glyphW ? c.advance : null);
            renderFam = (fonts.has(ck) ? fonts.get(ck) : null);
            const sd = shaping.get(ck);
            dash = (sd !== null ? sd.strategy : null);
            lang = (sd !== null ? sd.language : null);
            face = (sd !== null ? sd.resolvedFace : null);
            gIds = (glyphIds.has(ck) && glyphIds.get(ck).length > 0 ? glyphIds.get(ck).join(",") : null);
            ev = (sd !== null ? sd.reason : null);
            const pd = punct.get(ck);
            if (pd !== null && pd.inkContainmentApplied && pd.inkContainmentBodyFloor !== null) {
              inkFloor = pd.inkContainmentBodyFloor;
              bodyW = pd.bodyWidth;
            }
            const fdSrc = result.debug.fontDecisions;
            for (let fi2 = 0, count12 = fdSrc.length; fi2 < count12; fi2 += 1) {
              const fd = fdSrc[fi2]!;
              if (c.range.start >= fd.range.start && c.range.end <= fd.range.end && fd.role === FontRole.LatinText.kind) {
                latin = true;
              }
            }
            const cs = PlanLowering.styleAt(result, c.range.start);
            styleDelta = (cs !== result.input.textStyle ? { fontSize: (cs.fontSize !== result.input.textStyle.fontSize ? cs.fontSize : null), fontWeight: (cs.fontWeight !== result.input.textStyle.fontWeight ? cs.fontWeight : null), italic: (cs.italic !== result.input.textStyle.italic ? cs.italic : null) } : null);
          }
          const feats = features.get(ck);
          cells.push({ rangeStart: c.range.start, rangeEnd: c.range.end, source: c.text, display: c.displayText, drawX: p.drawX, naturalWidth: natW, leadingLayoutAdvance: c.leadingLayoutAdvance, shapingBoundary: c.range.end - c.range.start > 1, openTypeFeatures: (feats !== null ? feats : []), renderFontFamily: renderFam, dashStrategy: dash, shapingLanguage: lang, resolvedFace: face, glyphIds: gIds, shapingEvidence: ev, punctuationInkFloor: inkFloor, punctuationBodyWidth: bodyW, latin, advance: advOverride, inlineObject: inlineObj, styleDelta });
        }
      }
      lines.push({ rangeStart: line.range.start, rangeEnd: line.range.end, top: line.top, bottom: line.bottom, baseline: line.baseline, indent: line.indent, visualWidth: line.visualWidth, hyphenAdvance: line.hyphenAdvance, endReason: PlanLowering.endReasonFrom(line.endReason), cells });
    }
    const emphasisRanges: PlanEmphasisRange[] = [];
    const inlineEdges: PlanInlineEdge[] = [];
    const rubyDecisions: PlanRuby[] = [];
    const bopomofoDecisions: PlanBopomofo[] = [];
    const decorationSegments: PlanDecorationSegment[] = [];
    const emphasisDots: PlanEmphasisDot[] = [];
    let fontSize: number | null = null;
    let overlayWidth: number | null = null;
    if (renderEvidence) {
      fontSize = result.input.textStyle.fontSize;
      overlayWidth = result.size.width;
      const emphSrc = result.input.decorations;
      for (let ei = 0, count13 = emphSrc.length; ei < count13; ei += 1) {
        const d = emphSrc[ei]!;
        if (d.kind.kind === "Emphasis") {
          emphasisRanges.push({ start: d.range.start, end: d.range.end });
        }
      }
      const offsets: number[] = [];
      const parseHexCode = (s: string): number | null => { let a = 0, z = s.length; while (a < z) { const c = s.charCodeAt(a); if (c === 32 || (c >= 9 && c <= 13)) { a++; } else { break; } } while (z > a) { const c = s.charCodeAt(z - 1); if (c === 32 || (c >= 9 && c <= 13)) { z--; } else { break; } } let i = a; const c0 = s.charCodeAt(i); if (c0 === 43 || c0 === 45) { i++; } let radix = 10; if (i + 1 < z && s.charCodeAt(i) === 48 && (s.charCodeAt(i + 1) === 120 || s.charCodeAt(i + 1) === 88)) { i += 2; radix = 16; } const st = i; while (i < z) { const c = s.charCodeAt(i); if ((c >= 48 && c <= 57) || (radix === 16 && ((c >= 97 && c <= 102) || (c >= 65 && c <= 70)))) { i++; } else { break; } } if (i === st || i !== z) { return null; } const n = Number.parseInt(s.substring(a, z), radix); if (n >= -2147483648 && n <= 2147483647) { return n; } return null; };
      for (let oi = 0, count18 = edgeStart.size(); oi < count18; oi += 1) {
        offsets.push(parseHexCode(edgeStart.keyAt(oi)));
      }
      const parseHexCode2 = (s: string): number | null => { let a = 0, z = s.length; while (a < z) { const c = s.charCodeAt(a); if (c === 32 || (c >= 9 && c <= 13)) { a++; } else { break; } } while (z > a) { const c = s.charCodeAt(z - 1); if (c === 32 || (c >= 9 && c <= 13)) { z--; } else { break; } } let i = a; const c0 = s.charCodeAt(i); if (c0 === 43 || c0 === 45) { i++; } let radix = 10; if (i + 1 < z && s.charCodeAt(i) === 48 && (s.charCodeAt(i + 1) === 120 || s.charCodeAt(i + 1) === 88)) { i += 2; radix = 16; } const st = i; while (i < z) { const c = s.charCodeAt(i); if ((c >= 48 && c <= 57) || (radix === 16 && ((c >= 97 && c <= 102) || (c >= 65 && c <= 70)))) { i++; } else { break; } } if (i === st || i !== z) { return null; } const n = Number.parseInt(s.substring(a, z), radix); if (n >= -2147483648 && n <= 2147483647) { return n; } return null; };
      for (let ei2 = 0, count19 = edgeEnd.size(); ei2 < count19; ei2 += 1) {
        const ev2 = parseHexCode2(edgeEnd.keyAt(ei2));
        if (offsets.indexOf(ev2) < 0) {
          offsets.push(ev2);
        }
      }
      let oi2 = 1;
      while (oi2 < offsets.length) {
        const ov = offsets[oi2]!;
        let oj = oi2 - 1;
        while (oj >= 0 && offsets[oj]! > ov) {
          offsets[oj + 1] = offsets[oj]!;
          oj--;
        }
        offsets[oj + 1] = ov;
        oi2++;
      }
      for (let _g_index1 = 0, count20 = offsets.length; _g_index1 < count20; _g_index1 += 1) {
        const offset = offsets[_g_index1]!;
        const sk2 = String(offset);
        inlineEdges.push({ offset, inlineStart: (edgeStart.has(sk2) ? edgeStart.get(sk2) : null), inlineEnd: (edgeEnd.has(sk2) ? edgeEnd.get(sk2) : null) });
      }
      const rubySrc = result.debug.rubyDecisions;
      for (let ri2 = 0, count14 = rubySrc.length; ri2 < count14; ri2 += 1) {
        const r = rubySrc[ri2]!;
        rubyDecisions.push({ baseRangeStart: r.baseRange.start, baseRangeEnd: r.baseRange.end, text: r.text, centerX: r.centerX, baselineY: r.baselineY, fontSize: r.fontSize, fontWeight: r.fontWeight, fontFamilies: PlanLowering.toArray(r.fontFamilies), ascent: r.ascent });
      }
      const bopoSrc = result.debug.bopomofoDecisions;
      for (let bi2 = 0, count15 = bopoSrc.length; bi2 < count15; bi2 += 1) {
        const z = bopoSrc[bi2]!;
        const placements: PlanBopomofoPlacement[] = [];
        for (let pj = 0, count21 = z.placements.length; pj < count21; pj += 1) {
          const pl = z.placements[pj]!;
          placements.push({ text: pl.text, role: pl.role.kind, left: pl.left, top: pl.top, width: pl.width, height: pl.height });
        }
        bopomofoDecisions.push({ baseRangeStart: z.baseRange.start, baseRangeEnd: z.baseRange.end, text: z.text, fontWeight: z.fontWeight, fontFamilies: PlanLowering.toArray(z.fontFamilies), placements });
      }
      const segSrc = result.debug.decorationSegments;
      for (let si = 0, count16 = segSrc.length; si < count16; si += 1) {
        const s = segSrc[si]!;
        if (s.kind === DecorationKind.ProperNoun.kind || s.kind === DecorationKind.BookTitle.kind) {
          decorationSegments.push({ kind: s.kind, left: s.left, top: s.top, right: s.right, sourceRangeStart: s.sourceRange.start, sourceRangeEnd: s.sourceRange.end });
        }
      }
      const dotSrc = result.debug.decorationDecisions;
      for (let di = 0, count17 = dotSrc.length; di < count17; di += 1) {
        const d2 = dotSrc[di]!;
        if (d2.applied && d2.kind === DecorationKind.Emphasis.kind && d2.dotDiameter > 0) {
          emphasisDots.push({ clusterRangeStart: PlanLowering.f32(d2.clusterRange.start), anchorX: d2.anchorX, anchorY: d2.anchorY, dotDiameter: d2.dotDiameter });
        }
      }
    }
    return { width: result.input.constraints.maxWidth, height: result.size.height, lines, emphasisRanges, inlineEdges, rubyDecisions, bopomofoDecisions, fontSize, overlayWidth, decorationSegments, emphasisDots };
  }

  private static endReasonFrom(reason: LineEndReason): PlanEndReason {
    switch (reason.kind) {
      case "AutoWrap":
        return PlanEndReason.AutoWrap;
      case "MandatoryBreak":
        return PlanEndReason.MandatoryBreak;
      case "ParagraphEnd":
        return PlanEndReason.ParagraphEnd;
    }
  }

  private static toArray(src: readonly string[]): string[] {
    const out: string[] = [];
    for (let i = 0, count22 = src.length; i < count22; i += 1) {
      out.push(src[i]!);
    }
    return out;
  }
}
