// Generated by the reflaxe TypeScript target. Do not edit.

import { ProgressiveBreakTier } from "./ProgressiveBreakDecisions.ts";

export class ProgressiveBreakTierPriority {
  public static priority(tier: ProgressiveBreakTier): number {
    switch (tier.kind) {
      case "Whitespace":
        return 0;
      case "Structural":
        return 1;
      case "Syllable":
        return 2;
      case "WholeToken":
        return 3;
      case "Emergency":
        return 4;
    }
  }

  public static fromPriority(value: number): ProgressiveBreakTier {
    if (value === 0) {
      return ProgressiveBreakTier.Whitespace;
    }
    if (value === 1) {
      return ProgressiveBreakTier.Structural;
    }
    if (value === 2) {
      return ProgressiveBreakTier.Syllable;
    }
    if (value === 3) {
      return ProgressiveBreakTier.WholeToken;
    }
    return ProgressiveBreakTier.Emergency;
  }
}
