// Generated by the reflaxe TypeScript target. Do not edit.

import { Cluster } from "./../core/Cluster.ts";
import { IntRange } from "./../core/IntRange.ts";
import { TextRange } from "./../core/TextRange.ts";
import { ProgressiveBreakTierPriority } from "./ProgressiveBreakTierPriority.ts";
import { SortedMapTable, SortedSetTable, SortedTable } from "../../../runtime.ts";

export class ProgressiveBreakOpportunity {
  public readonly tier: ProgressiveBreakTier;
  public readonly spanRange: TextRange;
  public readonly precedingWhitespaceStretchCapacity: number;

  constructor(tier: ProgressiveBreakTier, spanRange: TextRange, precedingWhitespaceStretchCapacity: number | null = null) {
    this.tier = tier;
    this.spanRange = spanRange;
    this.precedingWhitespaceStretchCapacity = precedingWhitespaceStretchCapacity ?? 0.0;
  }

  public toString(): string {
    return `ProgressiveBreakOpportunity(tier=${this.tier.kind}, spanRange=${this.spanRange.toString()}, precedingWhitespaceStretchCapacity=${this.precedingWhitespaceStretchCapacity})`;
  }
}

export class ProgressiveBreakDecisions {
  public static decideProgressiveBreak(lineStart: number, overflowAt: number, opportunities: SortedMapTable<number, ProgressiveBreakOpportunity>, adjustedClusters?: Cluster[] | null, lineLimit?: number | null, cjkInterCharBoundaries?: SortedSetTable<number> | null, maxCjkStretchPerGap?: number | null, sinoWesternBoundaries?: SortedSetTable<number> | null, sinoWesternStretchCap?: number | null): number {
    const limit = lineLimit ?? Infinity;
    const cjk = cjkInterCharBoundaries ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const max = maxCjkStretchPerGap ?? Infinity;
    const sino = sinoWesternBoundaries ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const cap = sinoWesternStretchCap ?? 0.0;
    const active = opportunities.get(overflowAt);
    if (active === null) {
      return overflowAt;
    }
    const bestPriority = ProgressiveBreakDecisions.progressiveBreakPriorityForLine(lineStart, overflowAt, active, opportunities, adjustedClusters, limit, cjk, max, sino, cap);
    let best: number | null = null;
    let boundary = lineStart + 1;
    while (boundary <= overflowAt) {
      const o = opportunities.get(boundary);
      if (o !== null && o.spanRange.start === active.spanRange.start && o.spanRange.end === active.spanRange.end && ProgressiveBreakTierPriority.priority(o.tier) === bestPriority && (best === null || boundary > best)) {
        best = boundary;
      }
      boundary++;
    }
    return (best === null ? overflowAt : best);
  }

  public static progressiveCandidateAllowed(lineStart: number, rawGreedy: number, candidateEnd: number, opportunities: SortedMapTable<number, ProgressiveBreakOpportunity>, adjustedClusters?: Cluster[] | null, lineLimit?: number | null, cjkInterCharBoundaries?: SortedSetTable<number> | null, maxCjkStretchPerGap?: number | null, sinoWesternBoundaries?: SortedSetTable<number> | null, sinoWesternStretchCap?: number | null): boolean {
    const limit = lineLimit ?? Infinity;
    const cjk = cjkInterCharBoundaries ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const max = maxCjkStretchPerGap ?? Infinity;
    const sino = sinoWesternBoundaries ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const cap = sinoWesternStretchCap ?? 0.0;
    const active = opportunities.get(rawGreedy);
    if (active === null) {
      return true;
    }
    const candidate = opportunities.get(candidateEnd);
    if (candidate === null) {
      if (adjustedClusters === null || candidateEnd < 0 || candidateEnd >= adjustedClusters.length) {
        return true;
      }
      const source = adjustedClusters[candidateEnd]!.range.start;
      return source <= active.spanRange.start || source >= active.spanRange.end;
    }
    if (candidate.spanRange.start !== active.spanRange.start || candidate.spanRange.end !== active.spanRange.end) {
      return true;
    }
    if (candidateEnd > rawGreedy) {
      return ProgressiveBreakTierPriority.priority(candidate.tier) <= ProgressiveBreakTierPriority.priority(active.tier);
    }
    const selected = ProgressiveBreakDecisions.decideProgressiveBreak(lineStart, rawGreedy, opportunities, adjustedClusters, limit, cjk, max, sino, cap);
    return candidateEnd === selected;
  }

  private static progressiveBreakPriorityForLine(lineStart: number, overflowAt: number, active: ProgressiveBreakOpportunity, opportunities: SortedMapTable<number, ProgressiveBreakOpportunity>, adjustedClusters: Cluster[] | null, lineLimit: number, cjkInterCharBoundaries: SortedSetTable<number>, maxCjkStretchPerGap: number, sinoWesternBoundaries: SortedSetTable<number>, sinoWesternStretchCap: number): number {
    const prioritiesBuilder = SortedTable.setBuilder<number>(SortedTable.compareInts);
    let i = lineStart + 1;
    while (i <= overflowAt) {
      const o = opportunities.get(i);
      if (o !== null && o.spanRange.start === active.spanRange.start && o.spanRange.end === active.spanRange.end) {
        prioritiesBuilder.put(ProgressiveBreakTierPriority.priority(o.tier));
      }
      i++;
    }
    const priorities = prioritiesBuilder.build();
    if (priorities.size() === 0) {
      return ProgressiveBreakTierPriority.priority(active.tier);
    }
    if (adjustedClusters === null || !Number.isFinite(lineLimit) || !Number.isFinite(maxCjkStretchPerGap)) {
      return priorities.at(0);
    }
    const stretch = maxCjkStretchPerGap * 0.0;
    let least = priorities.at(0);
    let density = Infinity;
    let leastBoundary = lineStart + 1;
    let pi = 0;
    while (pi < priorities.size()) {
      const priority = priorities.at(pi);
      let b = 0;
      i = lineStart + 1;
      while (i <= overflowAt) {
        const o2 = opportunities.get(i);
        if (o2 !== null && o2.spanRange.start === active.spanRange.start && o2.spanRange.end === active.spanRange.end && ProgressiveBreakTierPriority.priority(o2.tier) === priority) {
          b = i;
        }
        i++;
      }
      if (b === 0) {
        pi++;
        continue;
      }
      const d = ProgressiveBreakDecisions.progressiveCandidateStretchDensity(lineStart, b, opportunities, adjustedClusters, lineLimit, cjkInterCharBoundaries, sinoWesternBoundaries, sinoWesternStretchCap);
      if (d < density) {
        density = d;
        least = priority;
        leastBoundary = b;
      }
      if (d <= stretch) {
        return priority;
      }
      pi++;
    }
    let emergency = 0;
    i = lineStart + 1;
    while (i <= overflowAt) {
      const o3 = opportunities.get(i);
      if (o3 !== null && o3.spanRange.start === active.spanRange.start && o3.spanRange.end === active.spanRange.end && o3.tier.kind === "Emergency") {
        emergency = i;
      }
      i++;
    }
    return (emergency !== 0 && emergency >= leastBoundary ? ProgressiveBreakTierPriority.priority(ProgressiveBreakTier.Emergency) : least);
  }

  private static progressiveCandidateStretchDensity(lineStart: number, boundary: number, opportunities: SortedMapTable<number, ProgressiveBreakOpportunity>, adjustedClusters: Cluster[], lineLimit: number, cjkInterCharBoundaries: SortedSetTable<number>, sinoWesternBoundaries: SortedSetTable<number>, sinoWesternStretchCap: number): number {
    let width = 0.0;
    let i = lineStart;
    while (i < boundary) {
      width += adjustedClusters[i]!.advance;
      i++;
    }
    const deficit = Math.max(lineLimit - width, 0);
    let technical = 0.0;
    i = lineStart + 1;
    while (i < boundary) {
      const o = opportunities.get(i);
      if (o !== null && o.tier.kind === "Whitespace") {
        technical += o.precedingWhitespaceStretchCapacity;
      }
      i++;
    }
    let sino = 0;
    i = lineStart + 1;
    while (i < boundary) {
      if (sinoWesternBoundaries.has(i)) {
        sino++;
      }
      i++;
    }
    const cjkDeficit = Math.max(deficit - technical - sino * sinoWesternStretchCap, 0);
    const active = opportunities.get(boundary);
    let units = 0;
    if (active !== null) {
      i = lineStart;
      while (i < boundary) {
        const c = adjustedClusters[i]!;
        if (c.range.start >= active.spanRange.start && c.range.end <= active.spanRange.end && !ProgressiveBreakDecisions.hasWhitespaceUnit(c.text)) {
          units += c.text.length;
        }
        i++;
      }
    }
    const technicalGaps = Math.max(units - 1, 0);
    if (technicalGaps > 0) {
      return cjkDeficit / technicalGaps;
    }
    let gaps = 0;
    i = lineStart + 1;
    while (i < boundary) {
      if (cjkInterCharBoundaries.has(i)) {
        gaps++;
      }
      i++;
    }
    return (gaps === 0 ? cjkDeficit : cjkDeficit / gaps);
  }

  private static hasWhitespaceUnit(s: string): boolean {
    let i = 0;
    while (i < s.length) {
      const c = (Number.isNaN(s.charCodeAt(i)) ? null : s.charCodeAt(i))!;
      if (c >= 9 && c <= 13 || c >= 28 && c <= 32 || c === 160 || c === 5760 || c >= 8192 && c <= 8202 || c === 8232 || c === 8233 || c === 8239 || c === 8287 || c === 12288) {
        return true;
      }
      i++;
    }
    return false;
  }

  public static decideHyphenBreak(lineStart: number, overflowAt: number, adjustedClusters: Cluster[], lineLimit: number, hyphenBreakClusters: SortedSetTable<number>, cjkInterCharBoundaries: SortedSetTable<number>, maxCjkStretchPerGap: number, sinoWesternBoundaries?: SortedSetTable<number> | null, sinoWesternStretchCap?: number | null): number {
    const sino = sinoWesternBoundaries ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const cap = sinoWesternStretchCap ?? 0.0;
    if (!hyphenBreakClusters.has(overflowAt)) {
      return overflowAt;
    }
    let whole = overflowAt;
    while (whole > lineStart && hyphenBreakClusters.has(whole)) {
      whole--;
    }
    if (whole <= lineStart) {
      return overflowAt;
    }
    let width = 0.0;
    let k = lineStart;
    while (k < whole) {
      width += adjustedClusters[k]!.advance;
      k++;
    }
    const deficit = lineLimit - width;
    if (deficit <= 0) {
      return whole;
    }
    let sw = 0;
    k = lineStart + 1;
    while (k < whole) {
      if (sino.has(k)) {
        sw++;
      }
      k++;
    }
    const cjk = Math.max(deficit - sw * cap, 0);
    let gaps = 0;
    k = lineStart + 1;
    while (k < whole) {
      if (cjkInterCharBoundaries.has(k)) {
        gaps++;
      }
      k++;
    }
    return (gaps === 0 || cjk / gaps > maxCjkStretchPerGap ? overflowAt : whole);
  }

  public static adjustBreakForLineEnd(breakAt: number, lineStart: number, forbiddenLineEndClusters: SortedSetTable<number>): number {
    let b = breakAt;
    while (b - 1 > lineStart && forbiddenLineEndClusters.has(b - 1)) {
      b--;
    }
    return b;
  }

  public static lineLimit(maxWidth: number, firstLineIndent: number, lineStartCluster: number): number {
    return (lineStartCluster === 0 ? maxWidth - firstLineIndent : maxWidth);
  }

  public static adjustBreakForUnbreakables(breakAt: number, lineStart: number, unbreakableRanges: UnbreakableRanges): number {
    let candidate = breakAt;
    while (true) {
      const containing = unbreakableRanges.containingOrNull(candidate);
      if (containing === null) {
        return candidate;
      }
      if (containing.start <= lineStart) {
        return breakAt;
      }
      candidate = containing.start;
    }
  }
}

export class ShrinkOpportunity {
  public readonly clusterIndex: number;
  public readonly tier: number;
  public readonly capacity: number;
  public readonly channel: ShrinkChannel;
  public readonly lineEndOnly: boolean;

  constructor(clusterIndex: number, tier: number, capacity: number, channel: ShrinkChannel, lineEndOnly: boolean | null = null) {
    this.clusterIndex = clusterIndex;
    this.tier = tier;
    this.capacity = capacity;
    this.channel = channel;
    this.lineEndOnly = lineEndOnly ?? false;
  }

  public toString(): string {
    return `ShrinkOpportunity(clusterIndex=${this.clusterIndex}, tier=${this.tier}, capacity=${this.capacity}, channel=${this.channel.kind}, lineEndOnly=${this.lineEndOnly})`;
  }
}

export class UnbreakableRanges {
  public readonly ranges: IntRange[];
  private readonly byStart: IntRange[];
  private readonly startsSorted: number[];
  private readonly prefixMaxLast: number[];
  public static readonly Empty: UnbreakableRanges = new UnbreakableRanges([]);

  constructor(ranges: IntRange[]) {
    this.ranges = ranges;
    this.byStart = ranges.slice();
    let s0 = 1;
    while (s0 < this.byStart.length) {
      const key = this.byStart[s0]!;
      let s1 = s0;
      while (s1 > 0 && this.byStart[s1 - 1]!.start > key.start) {
        this.byStart[s1] = this.byStart[s1 - 1]!;
        s1--;
      }
      this.byStart[s1] = key;
      s0++;
    }
    this.startsSorted = [];
    let si = 0;
    while (si < this.byStart.length) {
      this.startsSorted.push(this.byStart[si]!.start);
      si++;
    }
    this.prefixMaxLast = [];
    let running = -2147483648;
    let sj = 0;
    while (sj < this.byStart.length) {
      running = Math.trunc(Math.max(running, this.byStart[sj]!.end));
      this.prefixMaxLast.push(running);
      sj++;
    }
  }

  public containsBoundary(candidate: number): boolean {
    let low = 0;
    let high = this.startsSorted.length;
    while (low < high) {
      const mid = low + high >> 1;
      if (this.startsSorted[mid]! < candidate) {
        low = mid + 1;
      } else {
        high = mid;
      }
    }
    return low > 0 && this.prefixMaxLast[low - 1]! >= candidate;
  }

  public containingOrNull(candidate: number): IntRange | null {
    if (!this.containsBoundary(candidate)) {
      return null;
    }
    let ri = 0;
    while (ri < this.ranges.length) {
      const r = this.ranges[ri]!;
      if (candidate > r.start && candidate <= r.end) {
        return r;
      }
      ri++;
    }
    return null;
  }

  public containingFromClosedStartOrNull(index: number): IntRange | null {
    let low = 0;
    let high = this.startsSorted.length;
    while (low < high) {
      const mid = low + high >> 1;
      if (this.startsSorted[mid]! <= index) {
        low = mid + 1;
      } else {
        high = mid;
      }
    }
    if (low === 0 || this.prefixMaxLast[low - 1]! <= index) {
      return null;
    }
    let rj = 0;
    while (rj < this.ranges.length) {
      const r = this.ranges[rj]!;
      if (index >= r.start && index <= r.end && r.end > index) {
        return r;
      }
      rj++;
    }
    return null;
  }
}

export interface Whitespace {
  readonly kind: "Whitespace"
}

export interface Structural {
  readonly kind: "Structural"
}

export interface Syllable {
  readonly kind: "Syllable"
}

export interface WholeToken {
  readonly kind: "WholeToken"
}

export interface Emergency {
  readonly kind: "Emergency"
}

export type ProgressiveBreakTier =
  | Whitespace
  | Structural
  | Syllable
  | WholeToken
  | Emergency;

export const ProgressiveBreakTier = Object.freeze({
  Whitespace: Object.freeze({ kind: "Whitespace" } as Whitespace),
  Structural: Object.freeze({ kind: "Structural" } as Structural),
  Syllable: Object.freeze({ kind: "Syllable" } as Syllable),
  WholeToken: Object.freeze({ kind: "WholeToken" } as WholeToken),
  Emergency: Object.freeze({ kind: "Emergency" } as Emergency)
});

export function compareProgressiveBreakTier(a: ProgressiveBreakTier, b: ProgressiveBreakTier): number {
  if (a === b) return 0;
  if (a.kind === "Whitespace") return 0 - (b.kind === "Whitespace" ? 0 : 0);
  if (a.kind === "Structural") return 1 - (b.kind === "Structural" ? 1 : 0);
  if (a.kind === "Syllable") return 2 - (b.kind === "Syllable" ? 2 : 0);
  if (a.kind === "WholeToken") return 3 - (b.kind === "WholeToken" ? 3 : 0);
  if (a.kind === "Emergency") return 4 - (b.kind === "Emergency" ? 4 : 0);
  return 0;
}

export interface TrailingGlue {
  readonly kind: "TrailingGlue"
}

export interface LeadingGlue {
  readonly kind: "LeadingGlue"
}

export interface LeadingAndTrailingGlue {
  readonly kind: "LeadingAndTrailingGlue"
}

export interface RawAdvance {
  readonly kind: "RawAdvance"
}

export type ShrinkChannel =
  | TrailingGlue
  | LeadingGlue
  | LeadingAndTrailingGlue
  | RawAdvance;

export const ShrinkChannel = Object.freeze({
  TrailingGlue: Object.freeze({ kind: "TrailingGlue" } as TrailingGlue),
  LeadingGlue: Object.freeze({ kind: "LeadingGlue" } as LeadingGlue),
  LeadingAndTrailingGlue: Object.freeze({ kind: "LeadingAndTrailingGlue" } as LeadingAndTrailingGlue),
  RawAdvance: Object.freeze({ kind: "RawAdvance" } as RawAdvance)
});

export function compareShrinkChannel(a: ShrinkChannel, b: ShrinkChannel): number {
  if (a === b) return 0;
  if (a.kind === "TrailingGlue") return 0 - (b.kind === "TrailingGlue" ? 0 : 0);
  if (a.kind === "LeadingGlue") return 1 - (b.kind === "LeadingGlue" ? 1 : 0);
  if (a.kind === "LeadingAndTrailingGlue") return 2 - (b.kind === "LeadingAndTrailingGlue" ? 2 : 0);
  if (a.kind === "RawAdvance") return 3 - (b.kind === "RawAdvance" ? 3 : 0);
  return 0;
}
