// Generated by the reflaxe TypeScript target. Do not edit.

import { AutoSpaceMode } from "./../clreq/AutoSpaceMode.ts";
import { AutoSpacePolicy } from "./../clreq/AutoSpacePolicy.ts";
import { ClreqPunctuationPolicies } from "./../clreq/ClreqPunctuationPolicies.ts";
import { KinsokuLevel } from "./../clreq/KinsokuLevel.ts";
import { PunctuationGluePlacement } from "./../clreq/PunctuationGluePlacement.ts";
import { PunctuationWidthPolicy } from "./../clreq/PunctuationWidthPolicy.ts";
import { AccurateSum } from "./../core/AccurateSum.ts";
import { AutoSpaceDecisionInfo } from "./../core/AutoSpaceDecisionInfo.ts";
import { Cluster } from "./../core/Cluster.ts";
import { ContextualKinsokuDecisionInfo } from "./../core/ContextualKinsokuDecisionInfo.ts";
import { EastAsianSpacingEdges } from "./../core/EastAsianSpacingEdges.ts";
import { EastAsianSpacingValue } from "./../core/EastAsianSpacingValue.ts";
import { Glyph } from "./../core/Glyph.ts";
import { InlineAttachment } from "./../core/InlineAttachment.ts";
import { InlineBoxDecisionInfo } from "./../core/InlineBoxDecisionInfo.ts";
import { InlineBoxSpan } from "./../core/InlineBoxSpan.ts";
import { IntRange } from "./../core/IntRange.ts";
import { Rect } from "./../core/Rect.ts";
import { TextRange } from "./../core/TextRange.ts";
import { TextRangeError } from "./../core/TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./../core/TiqianIllegalArgumentException.ts";
import { FontRole } from "./../font/FontRole.ts";
import { KinsokuRule } from "./KinsokuRule.ts";
import { PunctuationAtom, PunctuationAtomBuilder, PunctuationInkInput } from "./PunctuationModel.ts";
import { UnicodePunctuationBoundaryResolver } from "./UnicodePunctuationBoundaryResolver.ts";
import { SortedMapTable, SortedSetTable, SortedTable, formatFloatRuntime, readUnit } from "../../../runtime.ts";

export class ContextualKinsoku {
  public readonly forbiddenLineStartClusters: SortedSetTable<number>;
  public readonly unbreakableRanges: IntRange[];
  public readonly impossibleMeasureHangEligibleClusters: SortedSetTable<number>;
  public readonly extendableHangRanges: IntRange[];
  public readonly decisions: ContextualKinsokuDecisionInfo[];

  constructor(forbiddenLineStartClusters: SortedSetTable<number>, unbreakableRanges: IntRange[], impossibleMeasureHangEligibleClusters: SortedSetTable<number>, extendableHangRanges: IntRange[], decisions: ContextualKinsokuDecisionInfo[]) {
    this.forbiddenLineStartClusters = forbiddenLineStartClusters;
    this.unbreakableRanges = unbreakableRanges;
    this.impossibleMeasureHangEligibleClusters = impossibleMeasureHangEligibleClusters;
    this.extendableHangRanges = extendableHangRanges;
    this.decisions = decisions;
  }

  public toString(): string {
    return `ContextualKinsoku(forbiddenLineStartClusters=${(() => { let out = "["; const n = this.forbiddenLineStartClusters.size(); for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.forbiddenLineStartClusters.at(i); } out += "]"; return out; })()}, unbreakableRanges=${(() => { let out = "["; const n = this.unbreakableRanges.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.unbreakableRanges[i]!.toString(); } out += "]"; return out; })()}, impossibleMeasureHangEligibleClusters=${(() => { let out = "["; const n = this.impossibleMeasureHangEligibleClusters.size(); for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.impossibleMeasureHangEligibleClusters.at(i); } out += "]"; return out; })()}, extendableHangRanges=${(() => { let out = "["; const n = this.extendableHangRanges.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.extendableHangRanges[i]!.toString(); } out += "]"; return out; })()}, decisions=${(() => { let out = "["; const n = this.decisions.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.decisions[i]!.toString(); } out += "]"; return out; })()})`;
  }
}

export class InlineObjectAttachedMark {
  public readonly objectClusterIndex: number;
  public readonly separatorClusterIndices: number[];
  public readonly markClusterIndex: number;

  constructor(objectClusterIndex: number, separatorClusterIndices: number[], markClusterIndex: number) {
    this.objectClusterIndex = objectClusterIndex;
    this.separatorClusterIndices = separatorClusterIndices;
    this.markClusterIndex = markClusterIndex;
  }

  public toString(): string {
    return `InlineObjectAttachedMark(objectClusterIndex=${this.objectClusterIndex}, separatorClusterIndices=${(() => { let out = "["; const n = this.separatorClusterIndices.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.separatorClusterIndices[i]!; } out += "]"; return out; })()}, markClusterIndex=${this.markClusterIndex})`;
  }
}

export class AutoSpaceApplicationResult {
  public readonly clusters: Cluster[];
  public readonly decisions: AutoSpaceDecisionInfo[];

  constructor(clusters: Cluster[], decisions: AutoSpaceDecisionInfo[]) {
    this.clusters = clusters;
    this.decisions = decisions;
  }

  public toString(): string {
    return `AutoSpaceApplicationResult(clusters=${(() => { let out = "["; const n = this.clusters.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.clusters[i]!.toString(); } out += "]"; return out; })()}, decisions=${(() => { let out = "["; const n = this.decisions.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.decisions[i]!.toString(); } out += "]"; return out; })()})`;
  }
}

export class InlineBoxApplicationResult {
  public readonly clusters: Cluster[];
  public readonly advanceByCluster: SortedMapTable<number, number>;
  public readonly decisions: InlineBoxDecisionInfo[];

  constructor(clusters: Cluster[], advanceByCluster: SortedMapTable<number, number>, decisions: InlineBoxDecisionInfo[]) {
    this.clusters = clusters;
    this.advanceByCluster = advanceByCluster;
    this.decisions = decisions;
  }

  public toString(): string {
    return `InlineBoxApplicationResult(clusters=${(() => { let out = "["; const n = this.clusters.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.clusters[i]!.toString(); } out += "]"; return out; })()}, advanceByCluster=${(() => { let out = "{"; const n = this.advanceByCluster.size(); for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.advanceByCluster.keyAt(i) + "=" + this.advanceByCluster.valueAt(i); } out += "}"; return out; })()}, decisions=${(() => { let out = "["; const n = this.decisions.length; for (let i = 0; i < n; i += 1) { if (i > 0) { out += ", "; } out += this.decisions[i]!.toString(); } out += "]"; return out; })()})`;
  }
}

export class PunctuationGeometryStage {
  public static inlineObjectAttachedMarks(c: Cluster[], clusterRoles: FontRole[], level: KinsokuLevel, kinsokuRule: KinsokuRule): InlineObjectAttachedMark[] {
    if (level.kind === "None") {
      return [];
    }
    const result: InlineObjectAttachedMark[] = [];
    let markIndex = 1;
    while (markIndex < c.length) {
      const mark = c[markIndex]!;
      const role = (markIndex < clusterRoles.length ? clusterRoles[markIndex]! : null);
      const isCjkForbidden = PunctuationGeometryStage.isCjkKinsokuRole(role) && kinsokuRule.forbiddenAtLineStart(mark);
      const isAttachedAsciiPointMark = (role !== null && role.kind === "LatinText") && PunctuationGeometryStage.isAsciiPointMarkChar(PunctuationGeometryStage.firstChar(mark.text));
      if (!isCjkForbidden && !isAttachedAsciiPointMark) {
        markIndex++;
        continue;
      }
      let previousIndex = markIndex - 1;
      const separatorIndices: number[] = [];
      while (previousIndex >= 0 && PunctuationGeometryStage.isSpaceRun(c[previousIndex]!) && c[previousIndex]!.range.end === c[previousIndex + 1]!.range.start) {
        separatorIndices.unshift(previousIndex);
        previousIndex--;
      }
      if (previousIndex < 0) {
        markIndex++;
        continue;
      }
      const previous = c[previousIndex]!;
      if (!PunctuationGeometryStage.isInlineObjectCluster(previous) || previous.range.end !== c[previousIndex + 1]!.range.start) {
        markIndex++;
        continue;
      }
      result.push(new InlineObjectAttachedMark(previousIndex, separatorIndices, markIndex));
      markIndex++;
    }
    return result;
  }

  public static inlineObjectAttachedKinsoku(c: Cluster[], attachments: InlineObjectAttachedMark[], lineBreakClusters: Cluster[], level: KinsokuLevel, bodyLineWidth: number, firstLineWidth: number): ContextualKinsoku {
    if (level.kind === "None") {
      return PunctuationGeometryStage.emptyContextualKinsoku();
    }
    if (c.length !== lineBreakClusters.length) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Inline-object kinsoku requires cluster-for-cluster line-break geometry" } as TextRangeError));
    }
    const forbidden = SortedTable.setBuilder<number>(SortedTable.compareInts);
    const unbreakableRanges: IntRange[] = [];
    const forcedHangable = SortedTable.setBuilder<number>(SortedTable.compareInts);
    const extendableHangRanges: IntRange[] = [];
    const decisions: ContextualKinsokuDecisionInfo[] = [];
    for (let _g_index = 0, count = attachments.length; _g_index < count; _g_index += 1) {
      const attachment = attachments[_g_index]!;
      const previousIndex = attachment.objectClusterIndex;
      const index = attachment.markClusterIndex;
      const mark = c[index]!;
      const isAttachedAsciiPointMark = PunctuationGeometryStage.isAsciiPointMarkChar(PunctuationGeometryStage.firstChar(mark.text));
      let si = 0;
      while (si < attachment.separatorClusterIndices.length) {
        forbidden.put(attachment.separatorClusterIndices[si]!);
        si++;
      }
      forbidden.put(index);
      const protectedPair = new IntRange(previousIndex, index);
      const pairTerms: number[] = [];
      let wi = previousIndex;
      while (wi <= index) {
        pairTerms.push(lineBreakClusters[wi]!.advance);
        wi++;
      }
      const pairWidth = AccurateSum.of(pairTerms);
      const availableWidth = (previousIndex === 0 ? firstLineWidth : bodyLineWidth);
      if (pairWidth <= availableWidth) {
        unbreakableRanges.push(protectedPair);
      } else {
        const mayHang = PunctuationGeometryStage.isHangablePunctuationMark(mark.displayText) || isAttachedAsciiPointMark;
        if (mayHang) {
          let sj = 0;
          while (sj < attachment.separatorClusterIndices.length) {
            forcedHangable.put(attachment.separatorClusterIndices[sj]!);
            sj++;
          }
          forcedHangable.put(index);
          extendableHangRanges.push(protectedPair);
        }
      }
      decisions.push(new ContextualKinsokuDecisionInfo(mark.range, mark.text, index, "LineStart", (attachment.separatorClusterIndices.length === 0 ? "InlineObjectAttachedKinsoku" : "InlineObjectAttachedKinsokuAcrossCollapsedSeparatorSpace")));
    }
    return new ContextualKinsoku(forbidden.build(), unbreakableRanges, forcedHangable.build(), extendableHangRanges, decisions);
  }

  public static attachedAsciiPointMarkKinsoku(c: Cluster[], clusterRoles: FontRole[], lineBreakClusters: Cluster[], level: KinsokuLevel, bodyLineWidth: number, firstLineWidth: number): ContextualKinsoku {
    if (level.kind === "None") {
      return PunctuationGeometryStage.emptyContextualKinsoku();
    }
    if (c.length !== lineBreakClusters.length) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Contextual kinsoku requires cluster-for-cluster line-break geometry" } as TextRangeError));
    }
    const forbidden = SortedTable.setBuilder<number>(SortedTable.compareInts);
    const unbreakableRanges: IntRange[] = [];
    const forcedHangable = SortedTable.setBuilder<number>(SortedTable.compareInts);
    const extendableHangRanges: IntRange[] = [];
    const decisions: ContextualKinsokuDecisionInfo[] = [];
    let index = 1;
    while (index < c.length) {
      const cluster = c[index]!;
      const previous = c[index - 1]!;
      const startsAttachedPointMarkRun = ((index < clusterRoles.length ? clusterRoles[index]! : null) !== null && (index < clusterRoles.length ? clusterRoles[index]! : null).kind === "LatinText") && PunctuationGeometryStage.isAsciiPointMarkChar(PunctuationGeometryStage.firstChar(cluster.text)) && previous.displayText.length > 0 && previous.text.length > 0 && !PunctuationGeometryStage.isWhitespaceCode(readUnit(previous.text, previous.text.length - 1)!) && previous.range.end === cluster.range.start;
      if (!startsAttachedPointMarkRun) {
        index++;
        continue;
      }
      const runStart = index;
      let runEnd = index;
      while (runEnd + 1 < c.length) {
        const next = c[runEnd + 1]!;
        const continuesRun = ((runEnd + 1 < clusterRoles.length ? clusterRoles[runEnd + 1]! : null) !== null && (runEnd + 1 < clusterRoles.length ? clusterRoles[runEnd + 1]! : null).kind === "LatinText") && PunctuationGeometryStage.isAsciiPointMarkChar(PunctuationGeometryStage.firstChar(next.text)) && c[runEnd]!.range.end === next.range.start;
        if (!continuesRun) {
          break;
        }
        runEnd++;
      }
      let fi = runStart;
      while (fi <= runEnd) {
        forbidden.put(fi);
        fi++;
      }
      unbreakableRanges.push(new IntRange(runStart - 1, runEnd));
      const runLineWidth = (runStart - 1 === 0 ? firstLineWidth : bodyLineWidth);
      const runTerms: number[] = [];
      let wi = runStart - 1;
      while (wi <= runEnd) {
        runTerms.push(lineBreakClusters[wi]!.advance);
        wi++;
      }
      const runWidth = AccurateSum.of(runTerms);
      if (runWidth > runLineWidth) {
        fi = runStart;
        while (fi <= runEnd) {
          forcedHangable.put(fi);
          fi++;
        }
        extendableHangRanges.push(new IntRange(runStart - 1, runEnd));
      }
      fi = runStart;
      while (fi <= runEnd) {
        const pointMark = c[fi]!;
        decisions.push(new ContextualKinsokuDecisionInfo(pointMark.range, pointMark.text, fi, "LineStart", "AttachedAsciiPointMarkKinsoku"));
        fi++;
      }
      index = runEnd + 1;
    }
    return new ContextualKinsoku(forbidden.build(), unbreakableRanges, forcedHangable.build(), extendableHangRanges, decisions);
  }

  public static isCjkKinsokuRole(role: FontRole | null): boolean {
    return (role !== null && role.kind === "CjkPunctuation");
  }

  public static punctuationAtoms(c: Cluster, em: number, builder: PunctuationAtomBuilder, shapedGlyphs: Glyph[], gluePlacement: PunctuationGluePlacement, widthPolicy: PunctuationWidthPolicy): PunctuationAtom[] {
    const out: PunctuationAtom[] = [];
    if (c.displayText.length === 0) {
      return out;
    }
    let i = 0;
    while (i < c.displayText.length) {
      const atom = builder.build(c.displayText.charAt(i), PunctuationGeometryStage.displayCharSourceRange(c, i), em, PunctuationGeometryStage.punctuationInkInputFor(c, i, shapedGlyphs), gluePlacement, widthPolicy);
      if (atom !== null) {
        out.push(atom);
      }
      i++;
    }
    return out;
  }

  private static punctuationInkInputFor(c: Cluster, displayIndex: number, shapedGlyphs: Glyph[]): PunctuationInkInput | null {
    if (shapedGlyphs.length === 0) {
      return null;
    }
    let glyph: Glyph | null = null;
    if (shapedGlyphs.length === c.displayText.length) {
      const source = shapedGlyphs[displayIndex]!;
      const penTerms: number[] = [];
      let i = 0;
      while (i < displayIndex) {
        penTerms.push(shapedGlyphs[i]!.advance);
        i++;
      }
      const characterPen = AccurateSum.of(penTerms);
      glyph = new Glyph(source.id, source.clusterRange, source.advance, source.x - characterPen, source.y, source.renderFontKey, source.bounds, source.haltAdvance, source.haltPlacementX);
    } else {
      if (c.displayText.length === 1) {
        glyph = PunctuationGeometryStage.unionAsSingleGlyph(shapedGlyphs);
      }
    }
    if (glyph === null) {
      return new PunctuationInkInput(0, null, null, null, "glyph-cluster-mapping-ambiguous");
    }
    return new PunctuationInkInput(glyph.advance, (glyph.bounds === null ? null : new Rect(glyph.bounds.left + glyph.x, glyph.bounds.top + glyph.y, glyph.bounds.right + glyph.x, glyph.bounds.bottom + glyph.y)), glyph.haltAdvance, glyph.haltPlacementX, (glyph.bounds === null ? "shaper-no-ink-bounds" : null));
  }

  private static unionAsSingleGlyph(g: Glyph[]): Glyph | null {
    if (g.length === 0) {
      return null;
    }
    const first = g[0]!;
    const bounds: Rect[] = [];
    const unionTerms: number[] = [];
    let i = 0;
    while (i < g.length) {
      const glyph = g[i]!;
      unionTerms.push(glyph.advance);
      if (glyph.bounds !== null) {
        bounds.push(new Rect(glyph.bounds.left + glyph.x, glyph.bounds.top + glyph.y, glyph.bounds.right + glyph.x, glyph.bounds.bottom + glyph.y));
      }
      i++;
    }
    if (bounds.length === 0) {
      return first;
    }
    const totalAdvance = AccurateSum.of(unionTerms);
    let left = bounds[0]!.left;
    let top = bounds[0]!.top;
    let right = bounds[0]!.right;
    let bottom = bounds[0]!.bottom;
    i = 1;
    while (i < bounds.length) {
      left = Math.min(left, bounds[i]!.left);
      top = Math.min(top, bounds[i]!.top);
      right = Math.max(right, bounds[i]!.right);
      bottom = Math.max(bottom, bounds[i]!.bottom);
      i++;
    }
    return new Glyph(first.id, first.clusterRange, totalAdvance, 0, 0, first.renderFontKey, new Rect(left, top, right, bottom), null, null);
  }

  private static displayCharSourceRange(c: Cluster, displayIndex: number): TextRange {
    return (c.displayText.length === c.text.length ? new TextRange(c.range.start + displayIndex, c.range.start + displayIndex + 1) : c.range);
  }

  public static isSpaceRun(c: Cluster): boolean {
    if (c.text.length === 0) {
      return false;
    }
    let i = 0;
    while (i < c.text.length) {
      if (c.text.charAt(i) !== " ") {
        return false;
      }
      i++;
    }
    return true;
  }

  public static applyAutoSpacePolicy(c: Cluster[], eastAsianSpacingEdges: EastAsianSpacingEdges[], inlineAttachments: InlineAttachment[], policy: AutoSpacePolicy, fontSize: number, narrowInlineBoxLeadingClusters?: SortedSetTable<number> | null, narrowInlineBoxTrailingClusters?: SortedSetTable<number> | null): AutoSpaceApplicationResult {
    const count2 = c.length;
    if (count2 === 0) {
      return new AutoSpaceApplicationResult([], []);
    }
    if (eastAsianSpacingEdges.length !== count2) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "East_Asian_Spacing values must align with natural clusters." } as TextRangeError));
    }
    if (inlineAttachments.length !== count2) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: "Inline attachments must align with natural clusters." } as TextRangeError));
    }
    const narrowLeading = narrowInlineBoxLeadingClusters ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const narrowTrailing = narrowInlineBoxTrailingClusters ?? SortedTable.setBuilder<number>(SortedTable.compareInts).build();
    const decisions: AutoSpaceDecisionInfo[] = [];
    const gap = policy.gapEm * fontSize;
    const attachedBoundaries = UnicodePunctuationBoundaryResolver.resolveAttachedInlineVirtualBoundaries(inlineAttachments);
    const suppressed = SortedTable.setBuilder<number>(SortedTable.compareInts);
    let bi = 0;
    while (bi < attachedBoundaries.length) {
      const boundary = attachedBoundaries[bi]!;
      bi++;
      suppressed.put(boundary.previousClusterIndex);
      if (boundary.nextClusterIndex !== null) {
        suppressed.put(boundary.attachedClusterRange.end);
      }
    }
    const virtualGapAtRunEnd: boolean[] = [];
    for (let gi = 0; gi < count2; gi += 1) {
      virtualGapAtRunEnd.push(false);
    }
    bi = 0;
    while (bi < attachedBoundaries.length) {
      const boundary2 = attachedBoundaries[bi]!;
      bi++;
      if (boundary2.nextClusterIndex === null) {
        continue;
      }
      const nextIndex = boundary2.nextClusterIndex;
      if (nextIndex >= c.length) {
        continue;
      }
      const nextCluster = c[nextIndex]!;
      if (PunctuationGeometryStage.isSpaceRun(nextCluster) || PunctuationGeometryStage.isMandatoryBreakCluster(nextCluster)) {
        continue;
      }
      const previousIndex = boundary2.previousClusterIndex;
      const previousEdge = eastAsianSpacingEdges[previousIndex]!.trailing;
      const nextEdge = eastAsianSpacingEdges[nextIndex]!.leading;
      let narrowChar: string | null = null;
      if (previousEdge.kind === "Wide" && nextEdge.kind === "Narrow") {
        narrowChar = PunctuationGeometryStage.firstChar(nextCluster.text);
      } else {
        if (previousEdge.kind === "Narrow" && nextEdge.kind === "Wide") {
          narrowChar = PunctuationGeometryStage.lastChar(c[previousIndex]!.text);
        }
      }
      virtualGapAtRunEnd[boundary2.attachedClusterRange.end] = (PunctuationGeometryStage.modeForNarrow(policy, narrowChar) !== null && PunctuationGeometryStage.modeForNarrow(policy, narrowChar).kind === "Insert");
    }
    const suppressedSet = suppressed.build();
    const updated: Cluster[] = [];
    let idx = 0;
    while (idx < c.length) {
      const cluster = c[idx]!;
      const previousSpacing = (idx - 1 >= 0 ? eastAsianSpacingEdges[idx - 1]!.trailing : null);
      const currentSpacing = eastAsianSpacingEdges[idx]!;
      const nextSpacing = (idx + 1 < eastAsianSpacingEdges.length ? eastAsianSpacingEdges[idx + 1]!.leading : null);
      if (PunctuationGeometryStage.isSpaceRun(cluster)) {
        let narrowBoundaryChar: string | null = null;
        if ((previousSpacing !== null && previousSpacing.kind === "Wide") && (nextSpacing !== null && nextSpacing.kind === "Narrow")) {
          narrowBoundaryChar = (idx + 1 < c.length ? PunctuationGeometryStage.firstChar(c[idx + 1]!.text) : null);
        } else {
          if ((previousSpacing !== null && previousSpacing.kind === "Narrow") && (nextSpacing !== null && nextSpacing.kind === "Wide")) {
            narrowBoundaryChar = (idx - 1 >= 0 ? PunctuationGeometryStage.lastChar(c[idx - 1]!.text) : null);
          }
        }
        const mode = PunctuationGeometryStage.modeForNarrow(policy, narrowBoundaryChar);
        if (mode === null || (mode !== null && mode.kind === "Disabled")) {
          updated.push(cluster);
          idx++;
          continue;
        }
        const reduction = cluster.advance - gap;
        if (reduction === 0) {
          updated.push(cluster);
          idx++;
          continue;
        }
        decisions.push(new AutoSpaceDecisionInfo(cluster.range, "gap", "EastAsianSpacing.Wide", AutoSpaceMode.Replace.kind, cluster.text.length, reduction / cluster.text.length, reduction, "TextAutoSpaceReplace:east-asian-spacing-W-space-N"));
        updated.push(new Cluster(cluster.range, cluster.text, cluster.fontKey, gap, cluster.displayText, cluster.baselineShift, cluster.leadingLayoutAdvance, cluster.glyphInlineShift));
        idx++;
        continue;
      }
      let added = 0.;
      if ((previousSpacing !== null && previousSpacing.kind === "Wide") && currentSpacing.leading.kind === "Narrow" && (PunctuationGeometryStage.modeForNarrow(policy, PunctuationGeometryStage.firstChar(cluster.text)) !== null && PunctuationGeometryStage.modeForNarrow(policy, PunctuationGeometryStage.firstChar(cluster.text)).kind === "Insert") && !suppressedSet.has(idx - 1)) {
        added += gap;
        decisions.push(new AutoSpaceDecisionInfo(cluster.range, "leading", (narrowLeading.has(idx) ? "InlineBox.Narrow" : "EastAsianSpacing.Wide"), AutoSpaceMode.Insert.kind, 0, 0, -gap, (narrowLeading.has(idx) ? "InlineBoxOuterAutoSpace:leading-W-N" : "TextAutoSpaceInsert:east-asian-spacing-W-N")));
      }
      const normalTrailingGap = (nextSpacing !== null && nextSpacing.kind === "Wide") && currentSpacing.trailing.kind === "Narrow" && (PunctuationGeometryStage.modeForNarrow(policy, PunctuationGeometryStage.lastChar(cluster.text)) !== null && PunctuationGeometryStage.modeForNarrow(policy, PunctuationGeometryStage.lastChar(cluster.text)).kind === "Insert") && !suppressedSet.has(idx);
      const virtualTrailingGap = virtualGapAtRunEnd[idx]!;
      if (normalTrailingGap || virtualTrailingGap) {
        added += gap;
        decisions.push(new AutoSpaceDecisionInfo(cluster.range, "trailing", (narrowTrailing.has(idx) ? "InlineBox.Narrow" : (virtualTrailingGap ? "InlineAttachment.Previous" : "EastAsianSpacing.Wide")), AutoSpaceMode.Insert.kind, 0, 0, -gap, (narrowTrailing.has(idx) ? "InlineBoxOuterAutoSpace:trailing-N-W" : (virtualTrailingGap ? "AttachedInlineVirtualAutoSpace:east-asian-spacing-W-N" : "TextAutoSpaceInsert:east-asian-spacing-W-N"))));
      }
      if (added === 0) {
        updated.push(cluster);
      } else {
        updated.push(new Cluster(cluster.range, cluster.text, cluster.fontKey, cluster.advance + added, cluster.displayText, cluster.baselineShift, cluster.leadingLayoutAdvance, cluster.glyphInlineShift));
      }
      idx++;
    }
    return new AutoSpaceApplicationResult(updated, decisions);
  }

  public static isEastAsianSpacingBoundaryAt(rightIndex: number, clusters: Cluster[], spacingEdges: EastAsianSpacingEdges[]): boolean {
    const leftIndex = rightIndex - 1;
    const left = spacingEdges[leftIndex]!.trailing;
    const right = spacingEdges[rightIndex]!.leading;
    if (PunctuationGeometryStage.isWideNarrowPairWith(left, right)) {
      return true;
    }
    if (PunctuationGeometryStage.isSpaceRun(clusters[rightIndex]!) && left.kind === "Wide" && ((rightIndex + 1 < spacingEdges.length ? spacingEdges[rightIndex + 1]!.leading : null) !== null && (rightIndex + 1 < spacingEdges.length ? spacingEdges[rightIndex + 1]!.leading : null).kind === "Narrow")) {
      return true;
    }
    if (PunctuationGeometryStage.isSpaceRun(clusters[leftIndex]!) && right.kind === "Wide" && ((leftIndex - 1 >= 0 ? spacingEdges[leftIndex - 1]!.trailing : null) !== null && (leftIndex - 1 >= 0 ? spacingEdges[leftIndex - 1]!.trailing : null).kind === "Narrow")) {
      return true;
    }
    return false;
  }

  private static isWideNarrowPairWith(v: EastAsianSpacingValue, other: EastAsianSpacingValue): boolean {
    return v.kind === "Wide" && other.kind === "Narrow" || v.kind === "Narrow" && other.kind === "Wide";
  }

  public static isAttachedAsciiPointMarkAt(c: Cluster[], index: number): boolean {
    if (index <= 0) {
      return false;
    }
    const cluster = c[index]!;
    const previous = c[index - 1]!;
    return PunctuationGeometryStage.isAsciiPointMarkChar(PunctuationGeometryStage.firstChar(cluster.text)) && previous.displayText.length > 0 && previous.text.length > 0 && !PunctuationGeometryStage.isWhitespaceCode(readUnit(previous.text, previous.text.length - 1)!) && previous.range.end === cluster.range.start;
  }

  public static applyInlineBoxSpans(c: Cluster[], spans: InlineBoxSpan[]): InlineBoxApplicationResult {
    const count3 = spans.length;
    if (c.length === 0 || count3 === 0) {
      const emptyAdvance = SortedTable.mapBuilder<number, number>(SortedTable.compareInts).build();
      return new InlineBoxApplicationResult(c, emptyAdvance, []);
    }
    const leadingByCluster = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    const trailingByCluster = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    const decisions: InlineBoxDecisionInfo[] = [];
    for (let _g_index = 0; _g_index < count3; _g_index += 1) {
      const span = spans[_g_index]!;
      if (span.range.start >= span.range.end) {
        continue;
      }
      const clusterRange = PunctuationGeometryStage.clusterIndexRangeFor(c, span.range);
      if (clusterRange === null) {
        continue;
      }
      if (span.inlineStart !== 0) {
        const existing = leadingByCluster.get(clusterRange.start);
        leadingByCluster.put(clusterRange.start, (existing === null ? span.inlineStart : existing + span.inlineStart));
      }
      if (span.inlineEnd !== 0) {
        const existing2 = trailingByCluster.get(clusterRange.end);
        trailingByCluster.put(clusterRange.end, (existing2 === null ? span.inlineEnd : existing2 + span.inlineEnd));
      }
      decisions.push(new InlineBoxDecisionInfo(span.range, span.inlineStart, span.inlineEnd, span.outerSpacing.kind, clusterRange.start, clusterRange.end));
    }
    const advanceByCluster = SortedTable.mapBuilder<number, number>(SortedTable.compareInts);
    const resolved: Cluster[] = [];
    let idx = 0;
    while (idx < c.length) {
      const cluster = c[idx]!;
      const leading = leadingByCluster.get(idx);
      const trailing = trailingByCluster.get(idx);
      const lead = (leading === null ? 0. : leading);
      const trail = (trailing === null ? 0. : trailing);
      const structural = lead + trail;
      if (structural !== 0) {
        advanceByCluster.put(idx, structural);
      }
      if (structural === 0 && lead === 0) {
        resolved.push(cluster);
      } else {
        resolved.push(new Cluster(cluster.range, cluster.text, cluster.fontKey, (cluster.advance + structural < 0 ? 0 : cluster.advance + structural), cluster.displayText, cluster.baselineShift, cluster.leadingLayoutAdvance + lead, cluster.glyphInlineShift));
      }
      idx++;
    }
    return new InlineBoxApplicationResult(resolved, advanceByCluster.build(), decisions);
  }

  private static clusterIndexRangeFor(c: Cluster[], sourceRange: TextRange): IntRange | null {
    if (c.length === 0) {
      return null;
    }
    let low = 0;
    let high = c.length;
    while (low < high) {
      const mid = low + high >> 1;
      if (c[mid]!.range.start < sourceRange.start) {
        low = mid + 1;
      } else {
        high = mid;
      }
    }
    const first = low;
    low = first;
    high = c.length;
    while (low < high) {
      const mid2 = low + high >> 1;
      if (c[mid2]!.range.end <= sourceRange.end) {
        low = mid2 + 1;
      } else {
        high = mid2;
      }
    }
    const lastExclusive = low;
    return (first < lastExclusive ? new IntRange(first, lastExclusive - 1) : null);
  }

  private static emptyContextualKinsoku(): ContextualKinsoku {
    return new ContextualKinsoku(SortedTable.setBuilder<number>(SortedTable.compareInts).build(), [], SortedTable.setBuilder<number>(SortedTable.compareInts).build(), [], []);
  }

  private static modeForNarrow(policy: AutoSpacePolicy, boundaryChar: string | null): AutoSpaceMode | null {
    if (boundaryChar === null) {
      return null;
    }
    return (PunctuationGeometryStage.isDigitChar((Number.isNaN(boundaryChar.charCodeAt(0)) ? null : boundaryChar.charCodeAt(0))!) ? policy.cjkDigit : policy.cjkLatin);
  }

  private static isDigitChar(code: number | null): boolean {
    return code >= 48 && code <= 57 || code >= 65296 && code <= 65305;
  }

  private static isAsciiPointMarkChar(ch: string | null): boolean {
    return ch !== null && ClreqPunctuationPolicies.isAsciiPointMark(ch);
  }

  private static isHangablePunctuationMark(displayText: string): boolean {
    if (displayText.length !== 1) {
      return false;
    }
    return displayText === "、" || displayText === "，" || displayText === "。";
  }

  private static isInlineObjectCluster(c: Cluster): boolean {
    return c.fontKey === "inline-object";
  }

  private static isMandatoryBreakCluster(c: Cluster): boolean {
    return c.fontKey === "mandatory-break" && c.displayText.length === 0;
  }

  private static isWhitespaceCode(code: number): boolean {
    return code >= 9 && code <= 13 || code === 32 || code === 12288;
  }

  private static firstChar(s: string): string | null {
    return (s.length > 0 ? s.charAt(0) : null);
  }

  private static lastChar(s: string): string | null {
    return (s.length > 0 ? s.charAt(s.length - 1) : null);
  }
}
