// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRange } from "./../core/TextRange.ts";
import { UnicodeNumber } from "./../core/UnicodeNumber.ts";
import { UnicodeScriptEvidenceClassifier } from "./../core/UnicodeScriptEvidenceClassifier.ts";
import { UnicodeWordCharacter } from "./../core/UnicodeWordCharacter.ts";
import { FontRole } from "./../font/FontRole.ts";
import { FontRoleClassifier, FontRoleContext } from "./../font/FontRoleContext.ts";
import { ContextualQuoteRoleResolver } from "./ContextualQuoteRoleResolver.ts";
import { SortedMapTable, SortedTable, readUnit } from "../../../runtime.ts";

export class QuotePair {
  public readonly openIndex: number;
  public readonly closeIndex: number;
  public readonly quoteType: QuoteType;

  constructor(openIndex: number, closeIndex: number, quoteType: QuoteType) {
    this.openIndex = openIndex;
    this.closeIndex = closeIndex;
    this.quoteType = quoteType;
  }

  public toString(): string {
    return `QuotePair(openIndex=${this.openIndex}, closeIndex=${this.closeIndex}, quoteType=${this.quoteType.kind})`;
  }
}

export function QuotePairquoteTypeOrder(v: QuoteType): number {
  if (v.kind === "Single") return 1;
  if (v.kind === "Double") return 0;
  return 0;
}

export function compareQuotePair(a: QuotePair, b: QuotePair): number {
  if (a === b) return 0;
  if (a.openIndex !== b.openIndex) return a.openIndex - b.openIndex;
  if (a.closeIndex !== b.closeIndex) return a.closeIndex - b.closeIndex;
  if (QuotePairquoteTypeOrder(a.quoteType) !== QuotePairquoteTypeOrder(b.quoteType)) return QuotePairquoteTypeOrder(a.quoteType) - QuotePairquoteTypeOrder(b.quoteType);
  return 0;
}

export class QuoteRoleDecision {
  public readonly index: number;
  public readonly role: FontRole;
  public readonly source: string;
  public readonly reason: string;

  constructor(index: number, role: FontRole, source: string, reason: string) {
    this.index = index;
    this.role = role;
    this.source = source;
    this.reason = reason;
  }

  public toString(): string {
    return `QuoteRoleDecision(index=${this.index}, role=${this.role.kind}, source=${this.source}, reason=${this.reason})`;
  }
}

export function QuoteRoleDecisionroleOrder(v: FontRole): number {
  if (v.kind === "Unknown") return 5;
  if (v.kind === "Symbol") return 3;
  if (v.kind === "LatinText") return 2;
  if (v.kind === "Emoji") return 4;
  if (v.kind === "CjkText") return 0;
  if (v.kind === "CjkPunctuation") return 1;
  return 0;
}

export function compareQuoteRoleDecision(a: QuoteRoleDecision, b: QuoteRoleDecision): number {
  if (a === b) return 0;
  if (a.index !== b.index) return a.index - b.index;
  if (QuoteRoleDecisionroleOrder(a.role) !== QuoteRoleDecisionroleOrder(b.role)) return QuoteRoleDecisionroleOrder(a.role) - QuoteRoleDecisionroleOrder(b.role);
  if (a.source !== b.source) return a.source < b.source ? -1 : 1;
  if (a.reason !== b.reason) return a.reason < b.reason ? -1 : 1;
  return 0;
}

export class QuotePairAnalyzer {
  constructor() {
  }

  public analyze(text: string): QuotePair[] {
    const stack: OpenQuoteEntry[] = [];
    const pairs: QuotePair[] = [];
    let index = 0;
    while (index < text.length) {
      const c = (Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!;
      if (c === 8220) {
        stack.push({ index, type: QuoteType.Double });
      } else {
        if (c === 8216) {
          stack.push({ index, type: QuoteType.Single });
        } else {
          if (c === 8221) {
            if (stack.length > 0 && stack[stack.length - 1]!.type.kind === "Double") {
              const match = stack.pop();
              pairs.push(new QuotePair(match.index, index, QuoteType.Double));
            }
          } else {
            if (c === 8217) {
              if (!QuotePairAnalyzer.isNonCjkInWordApostrophe(text, index) && stack.length > 0 && stack[stack.length - 1]!.type.kind === "Single") {
                const match2 = stack.pop();
                pairs.push(new QuotePair(match2.index, index, QuoteType.Single));
              }
            }
          }
        }
      }
      index++;
    }
    return pairs;
  }

  public classifyPairs(text: string, pairs: QuotePair[], context?: FontRoleContext | null): SortedMapTable<number, FontRole> {
    return QuotePairAnalyzer.mapDecisions(this.classifyQuoteRoles(text, pairs, context));
  }

  public classifyPairsWithClassifier(text: string, pairs: QuotePair[], fontRoleClassifier: FontRoleClassifier, context?: FontRoleContext | null): SortedMapTable<number, FontRole> {
    return this.classifyPairs(text, pairs, context);
  }

  public classifyQuoteRoles(text: string, pairs: QuotePair[], context?: FontRoleContext | null): QuoteRoleDecision[] {
    return new ContextualQuoteRoleResolver(text, pairs, (context === null ? new FontRoleContext("zh-Hans", null) : context)).resolve();
  }

  public classifyQuoteRolesWithClassifier(text: string, pairs: QuotePair[], fontRoleClassifier: FontRoleClassifier, context?: FontRoleContext | null): QuoteRoleDecision[] {
    return this.classifyQuoteRoles(text, pairs, context);
  }

  private static mapDecisions(decisions: QuoteRoleDecision[]): SortedMapTable<number, FontRole> {
    const out = SortedTable.mapBuilder<number, FontRole>(SortedTable.compareInts);
    for (let pipeline_index = 0, count = decisions.length; pipeline_index < count; pipeline_index += 1) {
      const d = decisions[pipeline_index]!;
      out.put(d.index, d.role);
    }
    return out.build();
  }

  public static isNonCjkInWordApostrophe(text: string, index: number): boolean {
    const before = QuotePairAnalyzer.codePointBefore(text, index);
    if (before === null) {
      return false;
    }
    const after = QuotePairAnalyzer.codePointAtOrNull(text, index + 1);
    if (after === null) {
      return false;
    }
    return QuotePairAnalyzer.isNonCjkWordCharacter(before) && QuotePairAnalyzer.isNonCjkWordCharacter(after) && (QuotePairAnalyzer.isNonCjkNonNumericWordCharacter(before) || QuotePairAnalyzer.isNonCjkNonNumericWordCharacter(after));
  }

  public static isDigitBoundClosingQuote(text: string, index: number): boolean {
    return ((Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))! === 8217 || (Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))! === 8221) && QuotePairAnalyzer.codePointBefore(text, index) !== null && UnicodeNumber.contains(QuotePairAnalyzer.codePointBefore(text, index));
  }

  public static isNonCjkWordInternalQuotePair(text: string, pair: QuotePair): boolean {
    const before = QuotePairAnalyzer.codePointBefore(text, pair.openIndex);
    const after = QuotePairAnalyzer.codePointAtOrNull(text, pair.closeIndex + 1);
    if (before === null || after === null || !QuotePairAnalyzer.isNonCjkNonNumericWordCharacter(before) || !QuotePairAnalyzer.isNonCjkNonNumericWordCharacter(after)) {
      return false;
    }
    let index = pair.openIndex + 1;
    while (index < pair.closeIndex) {
      const cp = QuotePairAnalyzer.codePointAtOrNull(text, index);
      if (cp === null || !QuotePairAnalyzer.isNonCjkWordCharacter(cp)) {
        return false;
      }
      index += (cp > 65535 ? 2 : 1);
    }
    return true;
  }

  private static isNonCjkWordCharacter(cp: number): boolean {
    return UnicodeWordCharacter.contains(cp) && UnicodeScriptEvidenceClassifier.classify(cp).kind !== "EastAsian";
  }

  private static isNonCjkNonNumericWordCharacter(cp: number): boolean {
    return QuotePairAnalyzer.isNonCjkWordCharacter(cp) && !UnicodeNumber.contains(cp) && !QuotePairAnalyzer.isFullwidthEastAsianWidth(cp);
  }

  private static isFullwidthEastAsianWidth(cp: number): boolean {
    return cp === 12288 || cp >= 65281 && cp <= 65376 || cp >= 65504 && cp <= 65510;
  }

  public static codePointBefore(text: string, index: number): number | null {
    if (index <= 0) {
      return null;
    }
    const low = readUnit(text, index - 1)!;
    if (low < 56320 || low > 57343 || index < 2) {
      return low;
    }
    const high = readUnit(text, index - 2)!;
    if (high < 55296 || high > 56319) {
      return low;
    }
    return 65536 + (high - 55296 << 10) + (low - 56320);
  }

  public static codePointAtOrNull(text: string, index: number): number | null {
    if (index < 0 || index >= text.length) {
      return null;
    }
    const high = (Number.isNaN(text.charCodeAt(index)) ? null : text.charCodeAt(index))!;
    if (high < 55296 || high > 56319 || index + 1 >= text.length) {
      return high;
    }
    const low = readUnit(text, index + 1)!;
    if (low < 56320 || low > 57343) {
      return high;
    }
    return 65536 + (high - 55296 << 10) + (low - 56320);
  }
}

export class QuotePairAwareFontRoleClassifier implements FontRoleClassifier {
  private readonly delegate: FontRoleClassifier;
  private readonly quoteRoles: SortedMapTable<number, FontRole>;

  constructor(delegate: FontRoleClassifier, quoteRoles: SortedMapTable<number, FontRole>) {
    this.delegate = delegate;
    this.quoteRoles = quoteRoles;
  }

  public classify(text: string, range: TextRange, context?: FontRoleContext | null): FontRole {
    const role = this.quoteRoles.get(range.start);
    return (role === null ? this.delegate.classify(text, range, context) : role);
  }

  public static withContextualQuoteRoles(base: FontRoleClassifier, text: string, context?: FontRoleContext | null): FontRoleClassifier {
    const analyzer = new QuotePairAnalyzer();
    const decisions = analyzer.classifyQuoteRoles(text, analyzer.analyze(text), context);
    const count2 = decisions.length;
    if (count2 === 0) {
      return base;
    }
    const roles = SortedTable.mapBuilder<number, FontRole>(SortedTable.compareInts);
    for (let pipeline_index = 0; pipeline_index < count2; pipeline_index += 1) {
      const decision = decisions[pipeline_index]!;
      roles.put(decision.index, decision.role);
    }
    return new QuotePairAwareFontRoleClassifier(base, roles.build());
  }
}

export interface Double {
  readonly kind: "Double"
}

export interface Single {
  readonly kind: "Single"
}

export type QuoteType =
  | Double
  | Single;

export const QuoteType = Object.freeze({
  Double: Object.freeze({ kind: "Double" } as Double),
  Single: Object.freeze({ kind: "Single" } as Single)
});

export function compareQuoteType(a: QuoteType, b: QuoteType): number {
  if (a === b) return 0;
  if (a.kind === "Double") return 0 - (b.kind === "Double" ? 0 : 0);
  if (a.kind === "Single") return 1 - (b.kind === "Single" ? 1 : 0);
  return 0;
}

export interface OpenQuoteEntry {
  index: number;
  type: QuoteType;
}
