// Generated by the reflaxe TypeScript target. Do not edit.

import { BytesBuffer } from "../../runtime.js";

export class Sha256 {
  private state: number[];
  private block: Uint8Array;
  private blockPos: number;
  private totalLength: number;

  constructor() {
    this.state = [1779033703, -1150833019, 1013904242, -1521486534, 1359893119, -1694144372, 528734635, 1541459225];
    this.block = new Uint8Array(64);
    this.blockPos = 0;
    this.totalLength = 0;
  }

  public update(data: Uint8Array): void {
    let sourcePos = 0;
    while (sourcePos < data.length) {
      this.block[this.blockPos] = data[sourcePos]!;
      this.blockPos += 1;
      sourcePos += 1;
      this.totalLength += 1;
      if (this.blockPos === 64) {
        Sha256.processBlock(this.state, this.block);
        this.blockPos = 0;
      }
    }
  }

  public digest(): Uint8Array {
    const finalState: number[] = [];
    {
      finalState.push(this.state[0]!);
      finalState.push(this.state[1]!);
      finalState.push(this.state[2]!);
      finalState.push(this.state[3]!);
      finalState.push(this.state[4]!);
      finalState.push(this.state[5]!);
      finalState.push(this.state[6]!);
      finalState.push(this.state[7]!);
    }
    const finalBlock = new Uint8Array(64);
    for (let i = 0; i < 64; i += 1) {
      finalBlock[i] = 0;
    }
    for (let i2 = 0, count = this.blockPos; i2 < count; i2 += 1) {
      finalBlock[i2] = this.block[i2]!;
    }
    finalBlock[this.blockPos] = 128;
    const position = this.blockPos + 1;
    if (position > 56) {
      Sha256.processBlock(finalState, finalBlock);
      for (let i3 = 0; i3 < 56; i3 += 1) {
        finalBlock[i3] = 0;
      }
    } else {
      for (let i4 = position; i4 < 56; i4 += 1) {
        finalBlock[i4] = 0;
      }
    }
    finalBlock[56] = 0;
    finalBlock[57] = 0;
    finalBlock[58] = 0;
    finalBlock[59] = 0;
    finalBlock[60] = (this.totalLength >>> 21) & 255;
    finalBlock[61] = (this.totalLength >>> 13) & 255;
    finalBlock[62] = (this.totalLength >>> 5) & 255;
    finalBlock[63] = this.totalLength << 3;
    Sha256.processBlock(finalState, finalBlock);
    const output = new BytesBuffer();
    {
      {
        output.addByte(finalState[0]! >>> 24);
        output.addByte(finalState[0]! >>> 16);
        output.addByte(finalState[0]! >>> 8);
        output.addByte(finalState[0]!);
      }
      {
        output.addByte(finalState[1]! >>> 24);
        output.addByte(finalState[1]! >>> 16);
        output.addByte(finalState[1]! >>> 8);
        output.addByte(finalState[1]!);
      }
      {
        output.addByte(finalState[2]! >>> 24);
        output.addByte(finalState[2]! >>> 16);
        output.addByte(finalState[2]! >>> 8);
        output.addByte(finalState[2]!);
      }
      {
        output.addByte(finalState[3]! >>> 24);
        output.addByte(finalState[3]! >>> 16);
        output.addByte(finalState[3]! >>> 8);
        output.addByte(finalState[3]!);
      }
      {
        output.addByte(finalState[4]! >>> 24);
        output.addByte(finalState[4]! >>> 16);
        output.addByte(finalState[4]! >>> 8);
        output.addByte(finalState[4]!);
      }
      {
        output.addByte(finalState[5]! >>> 24);
        output.addByte(finalState[5]! >>> 16);
        output.addByte(finalState[5]! >>> 8);
        output.addByte(finalState[5]!);
      }
      {
        output.addByte(finalState[6]! >>> 24);
        output.addByte(finalState[6]! >>> 16);
        output.addByte(finalState[6]! >>> 8);
        output.addByte(finalState[6]!);
      }
      {
        output.addByte(finalState[7]! >>> 24);
        output.addByte(finalState[7]! >>> 16);
        output.addByte(finalState[7]! >>> 8);
        output.addByte(finalState[7]!);
      }
    }
    return output.getBytes();
  }

  public static make(data: Uint8Array): Uint8Array {
    const hash = new Sha256();
    hash.update(data);
    return hash.digest();
  }

  private static processBlock(hash: number[], input: Uint8Array): void {
    const words: number[] = [];
    for (let i = 0; i < 64; i += 1) {
      words.push(0);
    }
    for (let i2 = 0; i2 < 16; i2 += 1) {
      const offset = i2 * 4;
      words[i2] = (input[offset]! << 24) | (input[offset + 1]! << 16) | (input[offset + 2]! << 8) | input[offset + 3]!;
    }
    for (let i3 = 16; i3 < 64; i3 += 1) {
      words[i3] = Sha256.safeAdd(Sha256.safeAdd(Sha256.safeAdd(Sha256.gamma1(words[i3 - 2]!), words[i3 - 7]!), Sha256.gamma0(words[i3 - 15]!)), words[i3 - 16]!);
    }
    let a = hash[0]!;
    let b = hash[1]!;
    let c = hash[2]!;
    let d = hash[3]!;
    let e = hash[4]!;
    let f = hash[5]!;
    let g = hash[6]!;
    let h = hash[7]!;
    const k = [1116352408, 1899447441, -1245643825, -373957723, 961987163, 1508970993, -1841331548, -1424204075, -670586216, 310598401, 607225278, 1426881987, 1925078388, -2132889090, -1680079193, -1046744716, -459576895, -272742522, 264347078, 604807628, 770255983, 1249150122, 1555081692, 1996064986, -1740746414, -1473132947, -1341970488, -1084653625, -958395405, -710438585, 113926993, 338241895, 666307205, 773529912, 1294757372, 1396182291, 1695183700, 1986661051, -2117940946, -1838011259, -1564481375, -1474664885, -1035236496, -949202525, -778901479, -694614492, -200395387, 275423344, 430227734, 506948616, 659060556, 883997877, 958139571, 1322822218, 1537002063, 1747873779, 1955562222, 2024104815, -2067236844, -1933114872, -1866530822, -1538233109, -1090935817, -965641998];
    for (let i4 = 0; i4 < 64; i4 += 1) {
      const t1 = Sha256.safeAdd(Sha256.safeAdd(Sha256.safeAdd(Sha256.safeAdd(h, Sha256.sigma1(e)), Sha256.choose(e, f, g)), k[i4]!), words[i4]!);
      const t2 = Sha256.safeAdd(Sha256.sigma0(a), Sha256.majority(a, b, c));
      h = g;
      g = f;
      f = e;
      e = Sha256.safeAdd(d, t1);
      d = c;
      c = b;
      b = a;
      a = Sha256.safeAdd(t1, t2);
    }
    hash[0] = Sha256.safeAdd(hash[0]!, a);
    hash[1] = Sha256.safeAdd(hash[1]!, b);
    hash[2] = Sha256.safeAdd(hash[2]!, c);
    hash[3] = Sha256.safeAdd(hash[3]!, d);
    hash[4] = Sha256.safeAdd(hash[4]!, e);
    hash[5] = Sha256.safeAdd(hash[5]!, f);
    hash[6] = Sha256.safeAdd(hash[6]!, g);
    hash[7] = Sha256.safeAdd(hash[7]!, h);
  }

  private static rotate(value: number, distance: number): number {
    return (value >>> distance) | (value << 32 - distance);
  }

  private static choose(x: number, y: number, z: number): number {
    return x & y ^ ~x & z;
  }

  private static majority(x: number, y: number, z: number): number {
    return x & y ^ x & z ^ y & z;
  }

  private static sigma0(x: number): number {
    return Sha256.rotate(x, 2) ^ Sha256.rotate(x, 13) ^ Sha256.rotate(x, 22);
  }

  private static sigma1(x: number): number {
    return Sha256.rotate(x, 6) ^ Sha256.rotate(x, 11) ^ Sha256.rotate(x, 25);
  }

  private static gamma0(x: number): number {
    return Sha256.rotate(x, 7) ^ Sha256.rotate(x, 18) ^ (x >>> 3);
  }

  private static gamma1(x: number): number {
    return Sha256.rotate(x, 17) ^ Sha256.rotate(x, 19) ^ (x >>> 10);
  }

  private static safeAdd(x: number, y: number): number {
    const low = (x & 65535) + (y & 65535);
    const high = (x >> 16) + (y >> 16) + (low >> 16);
    return (high << 16) | low & 65535;
  }
}
