package;

import org.tiqian.core.TiqianIllegalArgumentException;
import org.tiqian.core.CoreUnitsGeometryTest;
import org.tiqian.core.CoreLayoutQueriesGapsTest;
import org.tiqian.core.LayoutQueriesTest;
import org.tiqian.core.LayoutQueriesResidualCoverageTest;
import org.tiqian.core.CoreBoundaryTest;
import org.tiqian.core.LinkAddressDisplayTest;
import org.tiqian.core.SourceInteractionBoundariesCoverageTest;
import org.tiqian.core.TextModelCoverageTest;
import org.tiqian.core.EastAsianSpacingTest;
import org.tiqian.core.EastAsianSpacingCoverageTest;
import org.tiqian.core.EastAsianSpacingLookupCoverageTest;
import org.tiqian.core.TextRangeTest;
import org.tiqian.core.UnicodeNumberTest;
import org.tiqian.core.UnicodeScriptEvidenceTest;
import org.tiqian.core.UnicodeWordCharacterTest;
import org.tiqian.clreq.BopomofoParserTest;
import org.tiqian.clreq.NumberSymbolCohesionTest;
import org.tiqian.clreq.KinsokuLevelTest;
import org.tiqian.clreq.PunctuationGluePlacementTest;
import org.tiqian.clreq.ClreqPunctuationGlyphSubstitutorTest;
import org.tiqian.clreq.ClreqProfileCoverageTest;
import org.tiqian.clreq.ClreqPolicyTailCoverageTest;
import org.tiqian.font.CjkDashCapabilityPolicyTest;
import org.tiqian.font.CjkFontRoleClassifierTest;
import org.tiqian.font.FontPolicyCoverageTest;
import org.tiqian.font.FontRoleTailCoverageTest;
import org.tiqian.font.InlineShapingStylePolicyTest;
import org.tiqian.font.ScriptAwareFontMetricsNormalizerTest;
import org.tiqian.font.UsesLatinFaceTest;
import org.tiqian.shaping.TextShaperCoverageTest;
import org.tiqian.shaping.ExplainableStubTextShaperTest;
import org.tiqian.linebreak.EnglishHyphenationTest;
import org.tiqian.linebreak.LiangHyphenatorTest;
import org.tiqian.layout.ProgressiveBreakDecisionsCoverageTest;
import org.tiqian.layout.ProgressiveBreakDecisionsTailTest;
import org.tiqian.layout.DecideHyphenBreakTest;
import org.tiqian.layout.QuotePairAnalyzerTest;
import org.tiqian.layout.QuotePairAnalyzerCoverageTest;
import org.tiqian.layout.QuotePairAnalyzerSurrogateAdjacencyTest;
import org.tiqian.layout.PunctuationModelCoverageTest;
import org.tiqian.layout.PunctuationAtomBuilderHaltTest;
import org.tiqian.layout.LineOptimizationCoverageTest;
import org.tiqian.layout.ContextualDashEllipsisRoleResolverCoverageTest;
import org.tiqian.layout.ContextualRoleExtensionCoverageTest;
import org.tiqian.layout.ContextualQuoteRoleResolverCoverageTest;
import org.tiqian.layout.ContextualQuoteRoleResolverNestedAndSurrogateTest;
import org.tiqian.linebreak.LineBreakCoverageTest;
import org.tiqian.linebreak.MandatoryBreakTest;
import org.tiqian.linebreak.UnicodePunctuationLineBreakCoverageTest;
import org.tiqian.linebreak.UnicodePunctuationLineBreakTest;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TraceAssertionException;
import std.Console;
import std.Process;

class Main {
    private static var failures:Int = 0;

    private static function run(name:String, test:()->Void):Void {
        try {
            test();
        } catch (error:TraceAssertionException) {
            failures += 1;
            Console.log("FAIL " + name + ": " + error.message);
        } catch (error:TiqianIllegalArgumentException) {
            failures += 1;
            Console.log("FAIL " + name + ": " + error.message);
        }
    }

    public static function main():Void {
        StringBufOracle.install();
        SortedTablesOracle.install();
        FunctionalOracle.install();
        js.Syntax.code("globalThis.std = globalThis.std || {}; globalThis.std.UStringPlatform = {0};", UStringPlatform);
        UStringRTOracle.install();
        run("hyphenatesCommonWordsAtSyllablePoints", EnglishHyphenationTest.hyphenatesCommonWordsAtSyllablePoints);
        run("respectsMarginsAndShortWords", EnglishHyphenationTest.respectsMarginsAndShortWords);
        run("honoursTheExceptionList", EnglishHyphenationTest.honoursTheExceptionList);
        run("noHyphenatorYieldsNoOpportunities", LiangHyphenatorTest.noHyphenatorYieldsNoOpportunities);
        run("oddLevelGapBecomesABreakOutsideTheMargins", LiangHyphenatorTest.oddLevelGapBecomesABreakOutsideTheMargins);
        run("maxLevelWinsAndEvenForbidsTheBreak", LiangHyphenatorTest.maxLevelWinsAndEvenForbidsTheBreak);
        run("marginsAndShortWordsAreRespected", LiangHyphenatorTest.marginsAndShortWordsAreRespected);
        run("exceptionsOverridePatternsAndAreCaseInsensitive", LiangHyphenatorTest.exceptionsOverridePatternsAndAreCaseInsensitive);
        run("parsesPatternsAndExceptionBlocksStrippingComments", LiangHyphenatorTest.parsesPatternsAndExceptionBlocksStrippingComments);
        run("matchesDoubleQuotePair", QuotePairAnalyzerTest.matchesDoubleQuotePair);
        run("matchesSingleQuotePair", QuotePairAnalyzerTest.matchesSingleQuotePair);
        run("matchesNestedQuotePairs", QuotePairAnalyzerTest.matchesNestedQuotePairs);
        run("unmatchedQuotesProduceNoPairs", QuotePairAnalyzerTest.unmatchedQuotesProduceNoPairs);
        run("contractionApostropheDoesNotCloseOuterSingleQuote", QuotePairAnalyzerTest.contractionApostropheDoesNotCloseOuterSingleQuote);
        run("contractionInsideCjkSingleQuotesKeepsApostropheLatin", QuotePairAnalyzerTest.contractionInsideCjkSingleQuotesKeepsApostropheLatin);
        run("inWordApostropheMatrixDoesNotConsumeOuterQuotePairs", QuotePairAnalyzerTest.inWordApostropheMatrixDoesNotConsumeOuterQuotePairs);
        run("unmatchedCurlyQuotesUseDirectionalContext", QuotePairAnalyzerTest.unmatchedCurlyQuotesUseDirectionalContext);
        run("mismatchedNestingLeavesQuotesUnmatched", QuotePairAnalyzerTest.mismatchedNestingLeavesQuotesUnmatched);
        run("classifiesPairAsCjkWhenOuterContextIsCjk", QuotePairAnalyzerTest.classifiesPairAsCjkWhenOuterContextIsCjk);
        run("classifiesPairAsLatinWhenOuterContextIsLatin", QuotePairAnalyzerTest.classifiesPairAsLatinWhenOuterContextIsLatin);
        run("classifiesBothQuotesAsCjkForCjkQuotedLatinContent", QuotePairAnalyzerTest.classifiesBothQuotesAsCjkForCjkQuotedLatinContent);
        run("whitespaceDelimitedLatinQuotePairOverridesCjkOuterContext", QuotePairAnalyzerTest.whitespaceDelimitedLatinQuotePairOverridesCjkOuterContext);
        run("unspacedCjkQuotationOfLatinTextRemainsCjk", QuotePairAnalyzerTest.unspacedCjkQuotationOfLatinTextRemainsCjk);
        run("adjacentQuotedListItemsDoNotUsePreviousItemContentAsOuterContext", QuotePairAnalyzerTest.adjacentQuotedListItemsDoNotUsePreviousItemContentAsOuterContext);
        run("spacedCjkQuotedContentRemainsCjk", QuotePairAnalyzerTest.spacedCjkQuotedContentRemainsCjk);
        run("classifiesPairAsCjkAtTextBoundary", QuotePairAnalyzerTest.classifiesPairAsCjkAtTextBoundary);
        run("classifiesTextStartLatinPairFromQuotedContent", QuotePairAnalyzerTest.classifiesTextStartLatinPairFromQuotedContent);
        run("mixedChineseQuestionAtParagraphStartUsesParagraphLanguage", QuotePairAnalyzerTest.mixedChineseQuestionAtParagraphStartUsesParagraphLanguage);
        run("explicitEnglishParagraphLanguageWinsForMixedQuotation", QuotePairAnalyzerTest.explicitEnglishParagraphLanguageWinsForMixedQuotation);
        run("commonDigitsDoNotChooseTheQuoteRole", QuotePairAnalyzerTest.commonDigitsDoNotChooseTheQuoteRole);
        run("nonLatinWesternScriptsParticipateAsStrongScriptEvidence", QuotePairAnalyzerTest.nonLatinWesternScriptsParticipateAsStrongScriptEvidence);
        run("numberedCjkQuotePrefixUsesQuotedContent", QuotePairAnalyzerTest.numberedCjkQuotePrefixUsesQuotedContent);
        run("numberedLatinQuotePrefixStillUsesLatinContent", QuotePairAnalyzerTest.numberedLatinQuotePrefixStillUsesLatinContent);
        run("classifiesNestedPairsByOutermostContext", QuotePairAnalyzerTest.classifiesNestedPairsByOutermostContext);
        run("classifiesLatinNestedQuotesByOuterContext", QuotePairAnalyzerTest.classifiesLatinNestedQuotesByOuterContext);
        run("skipsAsciiPunctuationWhenResolvingContext", QuotePairAnalyzerTest.skipsAsciiPunctuationWhenResolvingContext);
        run("skipsNeutralDashWhenResolvingContext", QuotePairAnalyzerTest.skipsNeutralDashWhenResolvingContext);
        run("endOfTextQuotePairClassifiedByOuterContext", QuotePairAnalyzerTest.endOfTextQuotePairClassifiedByOuterContext);
        run("representativeQuoteContextMatrixRemainsStable", QuotePairAnalyzerTest.representativeQuoteContextMatrixRemainsStable);
        run("roleDecisionSourcesStayExplainableAcrossFallbackPaths", QuotePairAnalyzerTest.roleDecisionSourcesStayExplainableAcrossFallbackPaths);
        TestTraceRecorder.flushClass("QuotePairAnalyzerTest");
        run("deprecatedClassifyPairsWithFontRoleClassifierDelegates", QuotePairAnalyzerCoverageTest.deprecatedClassifyPairsWithFontRoleClassifierDelegates);
        run("deprecatedClassifyQuoteRolesWithFontRoleClassifierDelegates", QuotePairAnalyzerCoverageTest.deprecatedClassifyQuoteRolesWithFontRoleClassifierDelegates);
        run("codePointBeforeSurrogatePairReturnsSupplementary", QuotePairAnalyzerCoverageTest.codePointBeforeSurrogatePairReturnsSupplementary);
        run("codePointAtOrNullSurrogatePairReturnsSupplementary", QuotePairAnalyzerCoverageTest.codePointAtOrNullSurrogatePairReturnsSupplementary);
        run("codePointAtOrNullNonSurrogateReturnsSelf", QuotePairAnalyzerCoverageTest.codePointAtOrNullNonSurrogateReturnsSelf);
        run("codePointBeforeReturnsNullAtStart", QuotePairAnalyzerCoverageTest.codePointBeforeReturnsNullAtStart);
        run("codePointBeforeReturnsSupplementaryForSurrogatePair", QuotePairAnalyzerCoverageTest.codePointBeforeReturnsSupplementaryForSurrogatePair);
        run("quotePairAwareFontRoleClassifierUsesOverride", QuotePairAnalyzerCoverageTest.quotePairAwareFontRoleClassifierUsesOverride);
        run("quotePairAwareFontRoleClassifierDelegatesWhenNoOverride", QuotePairAnalyzerCoverageTest.quotePairAwareFontRoleClassifierDelegatesWhenNoOverride);
        run("doubleQuoteCloseWithEmptyStackIgnores", QuotePairAnalyzerCoverageTest.doubleQuoteCloseWithEmptyStackIgnores);
        run("singleQuoteCloseWithEmptyStackIgnores", QuotePairAnalyzerCoverageTest.singleQuoteCloseWithEmptyStackIgnores);
        run("inWordApostropheAfterSupplementaryDoesNotClose", QuotePairAnalyzerCoverageTest.inWordApostropheAfterSupplementaryDoesNotClose);
        run("codePointAtOrNullWithSupplementaryAfterQuote", QuotePairAnalyzerCoverageTest.codePointAtOrNullWithSupplementaryAfterQuote);
        run("codePointBeforeWithHighSurrogateBeforeQuote", QuotePairAnalyzerCoverageTest.codePointBeforeWithHighSurrogateBeforeQuote);
        run("codePointBeforeWithLowSurrogateAtStart", QuotePairAnalyzerCoverageTest.codePointBeforeWithLowSurrogateAtStart);
        run("codePointBeforeWithLowSurrogateAfterNonHighSurrogate", QuotePairAnalyzerCoverageTest.codePointBeforeWithLowSurrogateAfterNonHighSurrogate);
        run("codePointAtOrNullWithIndexOutOfRange", QuotePairAnalyzerCoverageTest.codePointAtOrNullWithIndexOutOfRange);
        run("codePointAtOrNullWithHighSurrogateAtEnd", QuotePairAnalyzerCoverageTest.codePointAtOrNullWithHighSurrogateAtEnd);
        run("codePointAtOrNullWithHighSurrogateFollowedByNonLowSurrogate", QuotePairAnalyzerCoverageTest.codePointAtOrNullWithHighSurrogateFollowedByNonLowSurrogate);
        run("analyzeWithDoubleQuoteOpen", QuotePairAnalyzerCoverageTest.analyzeWithDoubleQuoteOpen);
        run("codePointAtOrNullHighSurrogateNotInRangeReturnsHigh", QuotePairAnalyzerCoverageTest.codePointAtOrNullHighSurrogateNotInRangeReturnsHigh);
        run("codePointBeforeLowInRangeIndexGe2HighNotInRange", QuotePairAnalyzerCoverageTest.codePointBeforeLowInRangeIndexGe2HighNotInRange);
        run("singleQuotePairMatch", QuotePairAnalyzerCoverageTest.singleQuotePairMatch);
        run("codePointAtOrNullLoneHighSurrogateAfterQuote", QuotePairAnalyzerCoverageTest.codePointAtOrNullLoneHighSurrogateAfterQuote);
        run("codePointAtOrNullHighSurrogateAtStringEnd", QuotePairAnalyzerCoverageTest.codePointAtOrNullHighSurrogateAtStringEnd);
        run("analyzeWithAllQuoteTypes", QuotePairAnalyzerCoverageTest.analyzeWithAllQuoteTypes);
        run("codePointBeforeNonSurrogateBmpChar", QuotePairAnalyzerCoverageTest.codePointBeforeNonSurrogateBmpChar);
        TestTraceRecorder.flushClass("QuotePairAnalyzerCoverageTest");
        run("lowQuoteCodePointsTakeTheSwitchDefaultWithoutPairing", QuotePairAnalyzerSurrogateAdjacencyTest.lowQuoteCodePointsTakeTheSwitchDefaultWithoutPairing);
        run("apostropheAfterASurrogatePairWalksTheCombineArmBefore", QuotePairAnalyzerSurrogateAdjacencyTest.apostropheAfterASurrogatePairWalksTheCombineArmBefore);
        run("apostropheBeforeASurrogateWalksBothLowCheckArms", QuotePairAnalyzerSurrogateAdjacencyTest.apostropheBeforeASurrogateWalksBothLowCheckArms);
        run("plainAndBoundaryNeighboursWalkTheNonSurrogateArms", QuotePairAnalyzerSurrogateAdjacencyTest.plainAndBoundaryNeighboursWalkTheNonSurrogateArms);
        TestTraceRecorder.flushClass("QuotePairAnalyzerSurrogateAdjacencyTest");
        TestTraceRecorder.flushClass("EnglishHyphenationTest");
        TestTraceRecorder.flushClass("LiangHyphenatorTest");
        run("defaultsAdmitTheCleanTierWithoutGeometryInputs", ProgressiveBreakDecisionsCoverageTest.defaultsAdmitTheCleanTierWithoutGeometryInputs);
        run("lineStartAtTheOverflowBoundaryScansAnEmptyRange", ProgressiveBreakDecisionsCoverageTest.lineStartAtTheOverflowBoundaryScansAnEmptyRange);
        run("twoSameTierBoundariesPickTheRightmost", ProgressiveBreakDecisionsCoverageTest.twoSameTierBoundariesPickTheRightmost);
        run("visiblyLooseCleanTiersFallThroughToEmergency", ProgressiveBreakDecisionsCoverageTest.visiblyLooseCleanTiersFallThroughToEmergency);
        run("aLeftwardEmergencyBoundaryKeepsTheBestCleanTier", ProgressiveBreakDecisionsCoverageTest.aLeftwardEmergencyBoundaryKeepsTheBestCleanTier);
        run("spanEdgeAndWhitespaceClustersDoNotCountAsTechnicalUnits", ProgressiveBreakDecisionsCoverageTest.spanEdgeAndWhitespaceClustersDoNotCountAsTechnicalUnits);
        run("singleTechnicalUnitFallsBackToTheCjkGapDensity", ProgressiveBreakDecisionsCoverageTest.singleTechnicalUnitFallsBackToTheCjkGapDensity);
        run("candidateOutsideTheClusterListIsAllowed", ProgressiveBreakDecisionsCoverageTest.candidateOutsideTheClusterListIsAllowed);
        run("candidatesOutsideTheActiveSpanAreAllowed", ProgressiveBreakDecisionsCoverageTest.candidatesOutsideTheActiveSpanAreAllowed);
        run("candidatesOfADifferentSpanAreAllowed", ProgressiveBreakDecisionsCoverageTest.candidatesOfADifferentSpanAreAllowed);
        run("sameTierPastTheRawGreedyIsAllowedAndWorseTiersAreNot", ProgressiveBreakDecisionsCoverageTest.sameTierPastTheRawGreedyIsAllowedAndWorseTiersAreNot);
        run("candidatesBeforeTheRawGreedyMustMatchTheSelectedBoundary", ProgressiveBreakDecisionsCoverageTest.candidatesBeforeTheRawGreedyMustMatchTheSelectedBoundary);
        run("hyphenBreakReturnsOverflowAtPlainWordBoundaries", ProgressiveBreakDecisionsCoverageTest.hyphenBreakReturnsOverflowAtPlainWordBoundaries);
        run("overLongWordsMustHyphenateFromTheLineStart", ProgressiveBreakDecisionsCoverageTest.overLongWordsMustHyphenateFromTheLineStart);
        run("aFittingWholeWordBreaksThere", ProgressiveBreakDecisionsCoverageTest.aFittingWholeWordBreaksThere);
        run("sinoWesternGapsAbsorbingTheDeficitKeepTheWholeWord", ProgressiveBreakDecisionsCoverageTest.sinoWesternGapsAbsorbingTheDeficitKeepTheWholeWord);
        run("gaplessOrTooLooseLinesHyphenateInstead", ProgressiveBreakDecisionsCoverageTest.gaplessOrTooLooseLinesHyphenateInstead);
        TestTraceRecorder.flushClass("ProgressiveBreakDecisionsCoverageTest");
        run("infiniteLineLimitWithClustersAdmitsTheCleanestTier", ProgressiveBreakDecisionsTailTest.infiniteLineLimitWithClustersAdmitsTheCleanestTier);
        run("infiniteStretchCeilingWithFiniteLineLimitAdmitsTheCleanestTier", ProgressiveBreakDecisionsTailTest.infiniteStretchCeilingWithFiniteLineLimitAdmitsTheCleanestTier);
        TestTraceRecorder.flushClass("ProgressiveBreakDecisionsTailTest");
        run("chargesAllDeficitToCjkWhenNoSinoWesternCapacityIsKnown", DecideHyphenBreakTest.chargesAllDeficitToCjkWhenNoSinoWesternCapacityIsKnown);
        run("discountsSinoWesternCapacityBeforeChargingCjkLooseness", DecideHyphenBreakTest.discountsSinoWesternCapacityBeforeChargingCjkLooseness);
        TestTraceRecorder.flushClass("DecideHyphenBreakTest");
        run("testBundledHyphenationResource", LineBreakCoverageTest.testBundledHyphenationResource);
        run("testLineBreakModelsAndEnums", LineBreakCoverageTest.testLineBreakModelsAndEnums);
        run("testMandatoryBreakAndZeroWidthSpaceCodePoints", LineBreakCoverageTest.testMandatoryBreakAndZeroWidthSpaceCodePoints);
        run("testSimpleCharacterLineBreakAnalyzer", LineBreakCoverageTest.testSimpleCharacterLineBreakAnalyzer);
        run("testHyphenationComponents", LineBreakCoverageTest.testHyphenationComponents);
        run("testUnicodePunctuationLineBreak", LineBreakCoverageTest.testUnicodePunctuationLineBreak);
        TestTraceRecorder.flushClass("LineBreakCoverageTest");
        run("recognizesMandatoryBreakCodePoints", MandatoryBreakTest.recognizesMandatoryBreakCodePoints);
        run("recognizesZeroWidthSpaceWithoutConflatingNoBreakControls", MandatoryBreakTest.recognizesZeroWidthSpaceWithoutConflatingNoBreakControls);
        run("marksRequiredAfterLineFeed", MandatoryBreakTest.marksRequiredAfterLineFeed);
        run("collapsesCrlfToASingleBreakAfterLf", MandatoryBreakTest.collapsesCrlfToASingleBreakAfterLf);
        run("preservesEachBlankLineBreak", MandatoryBreakTest.preservesEachBlankLineBreak);
        TestTraceRecorder.flushClass("MandatoryBreakTest");
        run("lookupClassesCoverTheUaxTailorablePunctuationClasses", UnicodePunctuationLineBreakCoverageTest.lookupClassesCoverTheUaxTailorablePunctuationClasses);
        run("nonScalarCodePointsAreRejected", UnicodePunctuationLineBreakCoverageTest.nonScalarCodePointsAreRejected);
        TestTraceRecorder.flushClass("UnicodePunctuationLineBreakCoverageTest");
        run("exposesPinnedWesternAndCjkPunctuationClasses", UnicodePunctuationLineBreakTest.exposesPinnedWesternAndCjkPunctuationClasses);
        run("ordinaryLettersAreOutsideThePunctuationSubset", UnicodePunctuationLineBreakTest.ordinaryLettersAreOutsideThePunctuationSubset);
        TestTraceRecorder.flushClass("UnicodePunctuationLineBreakTest");

        run("exposesLength", TextRangeTest.exposesLength);
        run("rejectsNegativeStart", TextRangeTest.rejectsNegativeStart);
        TestTraceRecorder.flushClass("TextRangeTest");
        run("icPlusReturnsSum", CoreUnitsGeometryTest.icPlusReturnsSum);
        run("icUnaryMinusReturnsNegated", CoreUnitsGeometryTest.icUnaryMinusReturnsNegated);
        run("floatIcExtensionCreatesIc", CoreUnitsGeometryTest.floatIcExtensionCreatesIc);
        run("intIcExtensionCreatesIc", CoreUnitsGeometryTest.intIcExtensionCreatesIc);
        run("icToPxMultipliesByEmSize", CoreUnitsGeometryTest.icToPxMultipliesByEmSize);
        run("rectHeightReturnsDifference", CoreUnitsGeometryTest.rectHeightReturnsDifference);
        run("rectWidthReturnsDifference", CoreUnitsGeometryTest.rectWidthReturnsDifference);
        run("textRangeRejectsStartGreaterThanEnd", CoreUnitsGeometryTest.textRangeRejectsStartGreaterThanEnd);
        run("textRangeRejectsNegativeStart", CoreUnitsGeometryTest.textRangeRejectsNegativeStart);
        run("layoutConstraintsRejectsNonPositiveMaxWidth", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxWidth);
        run("layoutConstraintsRejectsNonPositiveMaxHeight", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxHeight);
        run("layoutConstraintsRejectsNonPositiveMaxLines", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxLines);
        run("maxLinesDecisionInfoRecordsTruncationDetails", CoreUnitsGeometryTest.maxLinesDecisionInfoRecordsTruncationDetails);
        run("layoutDebugInfoAcceptsMaxLinesDecision", CoreUnitsGeometryTest.layoutDebugInfoAcceptsMaxLinesDecision);
        TestTraceRecorder.flushClass("CoreUnitsGeometryTest");
        run("positionedClusterHeightReturnsDifference", CoreLayoutQueriesGapsTest.positionedClusterHeightReturnsDifference);
        run("getLineForOffsetUsesNearestLineWhenGapBetweenLines", CoreLayoutQueriesGapsTest.getLineForOffsetUsesNearestLineWhenGapBetweenLines);
        run("getBoundingBoxesIntDelegatesToTextRange", CoreLayoutQueriesGapsTest.getBoundingBoxesIntDelegatesToTextRange);
        run("richTextBackgroundUsesHorizontalPadding", CoreLayoutQueriesGapsTest.richTextBackgroundUsesHorizontalPadding);
        run("richTextBackgroundTrailingPaddingWhenSpanEndsAtSegmentEnd", CoreLayoutQueriesGapsTest.richTextBackgroundTrailingPaddingWhenSpanEndsAtSegmentEnd);
        run("richTextBackgroundUniformParagraphStyleUsesParagraphStyle", CoreLayoutQueriesGapsTest.richTextBackgroundUniformParagraphStyleUsesParagraphStyle);
        run("markedFaceVerticalBoundsUsesFallbackWhenNoMetricMatches", CoreLayoutQueriesGapsTest.markedFaceVerticalBoundsUsesFallbackWhenNoMetricMatches);
        run("getSelectionOffsetForPositionReturnsNearestWhenBeforeFirstCluster", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsNearestWhenBeforeFirstCluster);
        run("getSelectionOffsetForPositionReturnsNearestWhenAfterLastCluster", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsNearestWhenAfterLastCluster);
        run("getSelectionOffsetForPositionReturnsStartOfLineWhenClustersEmpty", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsStartOfLineWhenClustersEmpty);
        run("getSelectionWordBoundaryForEmojiZwjSequence", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryForEmojiZwjSequence);
        run("getSelectionWordBoundaryForPunctuationReturnsSingle", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryForPunctuationReturnsSingle);
        run("positionedClustersProducesSourceStopsForLatinRun", CoreLayoutQueriesGapsTest.positionedClustersProducesSourceStopsForLatinRun);
        run("offsetForXUsesSourceStopsWhenAvailable", CoreLayoutQueriesGapsTest.offsetForXUsesSourceStopsWhenAvailable);
        run("getBoundingBoxesEmptyRangeReturnsEmptyList", CoreLayoutQueriesGapsTest.getBoundingBoxesEmptyRangeReturnsEmptyList);
        run("getLineForOffsetReturnsNearestLine", CoreLayoutQueriesGapsTest.getLineForOffsetReturnsNearestLine);
        run("getCursorRectReturnsCaretInCluster", CoreLayoutQueriesGapsTest.getCursorRectReturnsCaretInCluster);
        run("getOffsetForPositionUsesMinByWhenOutsideClusters", CoreLayoutQueriesGapsTest.getOffsetForPositionUsesMinByWhenOutsideClusters);
        run("getSelectionWordBoundaryReturnsEmptyForEmptyText", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryReturnsEmptyForEmptyText);
        TestTraceRecorder.flushClass("CoreLayoutQueriesGapsTest");
        run("clipboardProjectionRestoresSourceAndAddsFullySelectedAnnotations", LayoutQueriesTest.clipboardProjectionRestoresSourceAndAddsFullySelectedAnnotations);
        run("positionedClustersFollowLineIndentAndAdvance", LayoutQueriesTest.positionedClustersFollowLineIndentAndAdvance);
        run("positionedClustersSeparateOccupiedBoxFromAutoSpaceDrawOrigin", LayoutQueriesTest.positionedClustersSeparateOccupiedBoxFromAutoSpaceDrawOrigin);
        run("positionedClustersSeparateOccupiedBoxFromConsumedLeadingGlueDrawOrigin", LayoutQueriesTest.positionedClustersSeparateOccupiedBoxFromConsumedLeadingGlueDrawOrigin);
        run("glyphInkBoundsKeepItalicOverhangSeparateFromOccupiedGeometry", LayoutQueriesTest.glyphInkBoundsKeepItalicOverhangSeparateFromOccupiedGeometry);
        run("lineAndBoxQueriesUseTiqianLineGeometry", LayoutQueriesTest.lineAndBoxQueriesUseTiqianLineGeometry);
        run("rangeBoxesSplitMultiUnitClustersBySourceRange", LayoutQueriesTest.rangeBoxesSplitMultiUnitClustersBySourceRange);
        run("richTextSegmentsReusePositionedClusterGeometryAndSplitLines", LayoutQueriesTest.richTextSegmentsReusePositionedClusterGeometryAndSplitLines);
        run("richTextDecorationTrimsOnlyOuterPunctuationGlue", LayoutQueriesTest.richTextDecorationTrimsOnlyOuterPunctuationGlue);
        run("richTextDecorationKeepsPunctuationGlueInsideItsRange", LayoutQueriesTest.richTextDecorationKeepsPunctuationGlueInsideItsRange);
        run("richTextDecorationDoesNotTrimAlreadyConsumedOpeningGlueTwice", LayoutQueriesTest.richTextDecorationDoesNotTrimAlreadyConsumedOpeningGlueTwice);
        run("customLineStylesReuseTheRendererUnderlineHeight", LayoutQueriesTest.customLineStylesReuseTheRendererUnderlineHeight);
        run("lineThroughBisectsTheIdeographicMetricBox", LayoutQueriesTest.lineThroughBisectsTheIdeographicMetricBox);
        run("richTextBackgroundKeepsInternalGapsButTrimsItsOuterLayoutSpace", LayoutQueriesTest.richTextBackgroundKeepsInternalGapsButTrimsItsOuterLayoutSpace);
        run("uniformTextStyleBackgroundIgnoresFallbackFaceHeightAndAddsPadding", LayoutQueriesTest.uniformTextStyleBackgroundIgnoresFallbackFaceHeightAndAddsPadding);
        run("backgroundContinuationCornersKeepOnlyTrueSourceEndsFullyRounded", LayoutQueriesTest.backgroundContinuationCornersKeepOnlyTrueSourceEndsFullyRounded);
        run("backgroundContinuationRadiusDefaultsToTheAuthoredCornerRadius", LayoutQueriesTest.backgroundContinuationRadiusDefaultsToTheAuthoredCornerRadius);
        run("adjacentBackgroundsWithTheSameStyleShareOneClearance", LayoutQueriesTest.adjacentBackgroundsWithTheSameStyleShareOneClearance);
        run("adjacentLineDecorationsWithTheSameStyleShareOneClearance", LayoutQueriesTest.adjacentLineDecorationsWithTheSameStyleShareOneClearance);
        run("adjacentBackgroundAndUnderlineDoNotAvoidAcrossStyles", LayoutQueriesTest.adjacentBackgroundAndUnderlineDoNotAvoidAcrossStyles);
        run("hitTestingChoosesOffsetFromTiqianClusterAdvances", LayoutQueriesTest.hitTestingChoosesOffsetFromTiqianClusterAdvances);
        run("selectionHitTestingKeepsSupportedSourceSequencesAtomic", LayoutQueriesTest.selectionHitTestingKeepsSupportedSourceSequencesAtomic);
        run("externalSelectionOffsetsRespectDirectionalBoundaryBias", LayoutQueriesTest.externalSelectionOffsetsRespectDirectionalBoundaryBias);
        run("supportedSourceSequenceRemainsAtomicAcrossEngineClusterBoundaries", LayoutQueriesTest.supportedSourceSequenceRemainsAtomicAcrossEngineClusterBoundaries);
        run("inlineObjectSourceRangeIsOneSelectionUnit", LayoutQueriesTest.inlineObjectSourceRangeIsOneSelectionUnit);
        run("selectionWordBoundaryExpandsLatinButKeepsHanAtomic", LayoutQueriesTest.selectionWordBoundaryExpandsLatinButKeepsHanAtomic);
        run("rubySelectionGeometryRedistributesAvoidanceSpreadWithoutOverlap", LayoutQueriesTest.rubySelectionGeometryRedistributesAvoidanceSpreadWithoutOverlap);
        TestTraceRecorder.flushClass("LayoutQueriesTest");
        run("cornerRadiiPredicatesCoverEveryComparison", LayoutQueriesResidualCoverageTest.cornerRadiiPredicatesCoverEveryComparison);
        run("resolvedCornerRadiiRejectsInvalidInsetsAndResolvesContinuations", LayoutQueriesResidualCoverageTest.resolvedCornerRadiiRejectsInvalidInsetsAndResolvesContinuations);
        run("copyProjectionAppendsFullySelectedAnnotationsOnly", LayoutQueriesResidualCoverageTest.copyProjectionAppendsFullySelectedAnnotationsOnly);
        run("positionedClustersByLineRejectsForeignLines", LayoutQueriesResidualCoverageTest.positionedClustersByLineRejectsForeignLines);
        run("glyphInkBoundsSkipsUnmatchedGlyphsAndReturnsNullWithoutInk", LayoutQueriesResidualCoverageTest.glyphInkBoundsSkipsUnmatchedGlyphsAndReturnsNullWithoutInk);
        run("emptyLineResultsShortCircuitEveryQuery", LayoutQueriesResidualCoverageTest.emptyLineResultsShortCircuitEveryQuery);
        run("boundingBoxFallsBackToTheCursorRectAtClusterGaps", LayoutQueriesResidualCoverageTest.boundingBoxFallsBackToTheCursorRectAtClusterGaps);
        run("richTextSegmentsSplitOnLineBreaksAndClusterGaps", LayoutQueriesResidualCoverageTest.richTextSegmentsSplitOnLineBreaksAndClusterGaps);
        run("richTextSegmentsSkipZeroLengthClustersBetweenSlices", LayoutQueriesResidualCoverageTest.richTextSegmentsSkipZeroLengthClustersBetweenSlices);
        run("trimmedDecorationSegmentsKeepOnlyDecorationRoles", LayoutQueriesResidualCoverageTest.trimmedDecorationSegmentsKeepOnlyDecorationRoles);
        run("backgroundSegmentsPassThroughUnmatchableSegments", LayoutQueriesResidualCoverageTest.backgroundSegmentsPassThroughUnmatchableSegments);
        run("backgroundSegmentsTrimGlueApplyPaddingAndUseGlyphAdvances", LayoutQueriesResidualCoverageTest.backgroundSegmentsTrimGlueApplyPaddingAndUseGlyphAdvances);
        run("markedFacesUseMetricDecisionsWhenTheyCoverTheCluster", LayoutQueriesResidualCoverageTest.markedFacesUseMetricDecisionsWhenTheyCoverTheCluster);
        run("uniformTextStyleFallsBackWhenEveryMetricFieldDiffers", LayoutQueriesResidualCoverageTest.uniformTextStyleFallsBackWhenEveryMetricFieldDiffers);
        run("uniformTextStylePrefersIdeographicMetricsThenAnyMatchingFace", LayoutQueriesResidualCoverageTest.uniformTextStylePrefersIdeographicMetricsThenAnyMatchingFace);
        run("adjacentSameStyleSegmentsShareClearance", LayoutQueriesResidualCoverageTest.adjacentSameStyleSegmentsShareClearance);
        run("decorationLineYRequiresValidStrokeAndDecorationRoles", LayoutQueriesResidualCoverageTest.decorationLineYRequiresValidStrokeAndDecorationRoles);
        run("cursorRectCoversEmptyLinesEmptyClustersAndMultiUnitClusters", LayoutQueriesResidualCoverageTest.cursorRectCoversEmptyLinesEmptyClustersAndMultiUnitClusters);
        run("offsetForPositionCoversVerticalDistancesAndNaNPoints", LayoutQueriesResidualCoverageTest.offsetForPositionCoversVerticalDistancesAndNaNPoints);
        run("selectionSnapPrefersTheCloserInlineObjectBoundary", LayoutQueriesResidualCoverageTest.selectionSnapPrefersTheCloserInlineObjectBoundary);
        run("selectionWordBoundaryForPositionRejectsDegenerateContent", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionRejectsDegenerateContent);
        run("zeroWidthClustersReturnTheirStartInHitTests", LayoutQueriesResidualCoverageTest.zeroWidthClustersReturnTheirStartInHitTests);
        run("coerceSelectionOffsetHonoursInlineObjectBoundaries", LayoutQueriesResidualCoverageTest.coerceSelectionOffsetHonoursInlineObjectBoundaries);
        run("selectionWordBoundaryExpandsWordsAndHonoursInlineObjects", LayoutQueriesResidualCoverageTest.selectionWordBoundaryExpandsWordsAndHonoursInlineObjects);
        run("selectionWordKindCoversEveryHanBlock", LayoutQueriesResidualCoverageTest.selectionWordKindCoversEveryHanBlock);
        run("nearestLineFallsBackToTheOnlyLineAtItsEndOffset", LayoutQueriesResidualCoverageTest.nearestLineFallsBackToTheOnlyLineAtItsEndOffset);
        run("rubyGeometryRedistributesSelectionBoxesAndDropsSourceStops", LayoutQueriesResidualCoverageTest.rubyGeometryRedistributesSelectionBoxesAndDropsSourceStops);
        run("boundingBoxesSliceZeroWidthAndEmptyClusters", LayoutQueriesResidualCoverageTest.boundingBoxesSliceZeroWidthAndEmptyClusters);
        run("positionedClustersAndSegmentsReturnEmptyWithoutLines", LayoutQueriesResidualCoverageTest.positionedClustersAndSegmentsReturnEmptyWithoutLines);
        run("sameSpanSlicesAcrossASourceBoundaryMergeIntoOneSegment", LayoutQueriesResidualCoverageTest.sameSpanSlicesAcrossASourceBoundaryMergeIntoOneSegment);
        run("glyphInkBoundsSkipsUnusableGlyphsAndReportsNull", LayoutQueriesResidualCoverageTest.glyphInkBoundsSkipsUnusableGlyphsAndReportsNull);
        run("backgroundTrailingEdgeUsesGlyphAdvancesWhenAvailable", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgeUsesGlyphAdvancesWhenAvailable);
        run("clearanceNeedsSameRoleAndUsesTheSmallerSide", LayoutQueriesResidualCoverageTest.clearanceNeedsSameRoleAndUsesTheSmallerSide);
        run("metricDecisionsMustFullyContainTheCluster", LayoutQueriesResidualCoverageTest.metricDecisionsMustFullyContainTheCluster);
        run("decorationStyleResolvesInsideSpansAndAtTheirEdges", LayoutQueriesResidualCoverageTest.decorationStyleResolvesInsideSpansAndAtTheirEdges);
        run("glueTrimSkipsInteriorSegmentEdges", LayoutQueriesResidualCoverageTest.glueTrimSkipsInteriorSegmentEdges);
        run("backgroundSegmentOutsideEverySpanUsesTheParagraphStyle", LayoutQueriesResidualCoverageTest.backgroundSegmentOutsideEverySpanUsesTheParagraphStyle);
        run("cursorRectFindsLaterClustersAndRejectsGappedRanges", LayoutQueriesResidualCoverageTest.cursorRectFindsLaterClustersAndRejectsGappedRanges);
        run("emptyMidClusterHoldsTheCaretAndSlicesKeepDegenerateRects", LayoutQueriesResidualCoverageTest.emptyMidClusterHoldsTheCaretAndSlicesKeepDegenerateRects);
        run("selectionWordBoundarySkipsInlineObjectsItDoesNotContain", LayoutQueriesResidualCoverageTest.selectionWordBoundarySkipsInlineObjectsItDoesNotContain);
        run("selectionWordBoundaryForPositionCoversDistancesAndFallbacks", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionCoversDistancesAndFallbacks);
        run("lineForOffsetInsideARangeTakesTheZeroDistanceArm", LayoutQueriesResidualCoverageTest.lineForOffsetInsideARangeTakesTheZeroDistanceArm);
        run("compatibilityIdeographsFormIndividualWordUnits", LayoutQueriesResidualCoverageTest.compatibilityIdeographsFormIndividualWordUnits);
        run("rubySpreadShiftsSelectionBoxesAndZeroWidthRubiesAreIgnored", LayoutQueriesResidualCoverageTest.rubySpreadShiftsSelectionBoxesAndZeroWidthRubiesAreIgnored);
        run("noArgPositionedClustersWalksEveryLine", LayoutQueriesResidualCoverageTest.noArgPositionedClustersWalksEveryLine);
        run("glyphInkBoundsRejectsEachNonFiniteEdgeIndependently", LayoutQueriesResidualCoverageTest.glyphInkBoundsRejectsEachNonFiniteEdgeIndependently);
        run("clearanceTakesTheSmallerSideWhicheverSegmentOwnsIt", LayoutQueriesResidualCoverageTest.clearanceTakesTheSmallerSideWhicheverSegmentOwnsIt);
        run("uniformTextStylePolicyResolvesSpanStyleOrParagraphStyle", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyResolvesSpanStyleOrParagraphStyle);
        run("trailingGlueIsSkippedWhenNoClusterEndsBeforeTheSegmentEnd", LayoutQueriesResidualCoverageTest.trailingGlueIsSkippedWhenNoClusterEndsBeforeTheSegmentEnd);
        run("decorationLineYWithoutSpansUsesTheParagraphStyle", LayoutQueriesResidualCoverageTest.decorationLineYWithoutSpansUsesTheParagraphStyle);
        run("wordBoundaryForPositionHandlesANonFiniteY", LayoutQueriesResidualCoverageTest.wordBoundaryForPositionHandlesANonFiniteY);
        run("supplementaryIdeographBeyondTheHanRangesIsItsOwnUnit", LayoutQueriesResidualCoverageTest.supplementaryIdeographBeyondTheHanRangesIsItsOwnUnit);
        run("planeFourCodepointAboveTheHanBandsIsItsOwnUnit", LayoutQueriesResidualCoverageTest.planeFourCodepointAboveTheHanBandsIsItsOwnUnit);
        run("nearestLineSearchCoversAllThreeDistanceArms", LayoutQueriesResidualCoverageTest.nearestLineSearchCoversAllThreeDistanceArms);
        run("rubiesOnOtherLinesDoNotAffectThisLineGeometry", LayoutQueriesResidualCoverageTest.rubiesOnOtherLinesDoNotAffectThisLineGeometry);
        run("backgroundTrailingEdgePicksTheLargestGlyphAdvance", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgePicksTheLargestGlyphAdvance);
        run("backgroundTrailingEdgeKeepsTheFirstGlyphWhenItIsLargest", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgeKeepsTheFirstGlyphWhenItIsLargest);
        run("selectionWordBoundaryForPositionPrefersTheCloserLaterLine", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionPrefersTheCloserLaterLine);
        run("nearestLineSearchUpdatesToAStrictlyCloserLaterLine", LayoutQueriesResidualCoverageTest.nearestLineSearchUpdatesToAStrictlyCloserLaterLine);
        run("nearestLineSearchCoversBothLambdaCopiesOfEachArm", LayoutQueriesResidualCoverageTest.nearestLineSearchCoversBothLambdaCopiesOfEachArm);
        run("uniformTextStylePolicyPicksTheLastMatchingSpan", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyPicksTheLastMatchingSpan);
        run("decorationLineYPicksTheLastMatchingSpan", LayoutQueriesResidualCoverageTest.decorationLineYPicksTheLastMatchingSpan);
        run("uniformTextStylePolicyKeepsTheEarlierSpanWhenALaterOneMisses", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyKeepsTheEarlierSpanWhenALaterOneMisses);
        run("decorationLineYKeepsTheEarlierSpanWhenALaterOneMisses", LayoutQueriesResidualCoverageTest.decorationLineYKeepsTheEarlierSpanWhenALaterOneMisses);
        TestTraceRecorder.flushClass("LayoutQueriesResidualCoverageTest");
        run("coerceToInteractionBoundaryBackwardReturnsBoundaryWhenAtEnd", CoreBoundaryTest.coerceToInteractionBoundaryBackwardReturnsBoundaryWhenAtEnd);
        run("coerceToInteractionBoundaryForwardReturnsNextBoundary", CoreBoundaryTest.coerceToInteractionBoundaryForwardReturnsNextBoundary);
        run("coerceToInteractionBoundaryNearestChoosesCloser", CoreBoundaryTest.coerceToInteractionBoundaryNearestChoosesCloser);
        run("coerceToInteractionBoundaryWithSurrogatePair", CoreBoundaryTest.coerceToInteractionBoundaryWithSurrogatePair);
        run("coerceToInteractionBoundaryWithInvalidSurrogatePair", CoreBoundaryTest.coerceToInteractionBoundaryWithInvalidSurrogatePair);
        run("sourceGraphemeBoundariesWithHangulLeadingJamo", CoreBoundaryTest.sourceGraphemeBoundariesWithHangulLeadingJamo);
        run("sourceGraphemeBoundariesWithHangulSyllable", CoreBoundaryTest.sourceGraphemeBoundariesWithHangulSyllable);
        run("sourceGraphemeBoundariesWithRegionalIndicator", CoreBoundaryTest.sourceGraphemeBoundariesWithRegionalIndicator);
        run("sourceGraphemeBoundariesWithEmojiZwjSequence", CoreBoundaryTest.sourceGraphemeBoundariesWithEmojiZwjSequence);
        run("sourceGraphemeBoundariesWithEmojiModifier", CoreBoundaryTest.sourceGraphemeBoundariesWithEmojiModifier);
        run("sourceGraphemeBoundariesReturnsSingleBoundaryForEmptyText", CoreBoundaryTest.sourceGraphemeBoundariesReturnsSingleBoundaryForEmptyText);
        run("interactionBoundariesWithTextRange", CoreBoundaryTest.interactionBoundariesWithTextRange);
        run("getSelectionOffsetForPositionReturnsStartOfFirstCluster", CoreBoundaryTest.getSelectionOffsetForPositionReturnsStartOfFirstCluster);
        run("getSelectionOffsetForPositionReturnsStartOfLineWhenEmptyClusters", CoreBoundaryTest.getSelectionOffsetForPositionReturnsStartOfLineWhenEmptyClusters);
        TestTraceRecorder.flushClass("CoreBoundaryTest");
        run("identicalDisplayAndTargetIsAnAddress", LinkAddressDisplayTest.identicalDisplayAndTargetIsAnAddress);
        run("proseDisplayTextIsNotAnAddress", LinkAddressDisplayTest.proseDisplayTextIsNotAnAddress);
        run("schemeLessDisplayOfTheTargetIsAnAddress", LinkAddressDisplayTest.schemeLessDisplayOfTheTargetIsAnAddress);
        TestTraceRecorder.flushClass("LinkAddressDisplayTest");
        run("crlfStaysOneUnit", SourceInteractionBoundariesCoverageTest.crlfStaysOneUnit);
        run("regionalIndicatorsPairUp", SourceInteractionBoundariesCoverageTest.regionalIndicatorsPairUp);
        run("hangulJamoRunsMergeIntoSyllableBlocks", SourceInteractionBoundariesCoverageTest.hangulJamoRunsMergeIntoSyllableBlocks);
        run("precomposedHangulSyllablesAbsorbJamo", SourceInteractionBoundariesCoverageTest.precomposedHangulSyllablesAbsorbJamo);
        run("extendersAttachToThePrecedingUnit", SourceInteractionBoundariesCoverageTest.extendersAttachToThePrecedingUnit);
        run("bandEdgesAndGapsExerciseEveryRangeArm", SourceInteractionBoundariesCoverageTest.bandEdgesAndGapsExerciseEveryRangeArm);
        run("emojiModifiersOnlyAttachToBases", SourceInteractionBoundariesCoverageTest.emojiModifiersOnlyAttachToBases);
        run("zwjChainsJoinOnlyExtendedPictographic", SourceInteractionBoundariesCoverageTest.zwjChainsJoinOnlyExtendedPictographic);
        run("unpairedSurrogatesFallBackToSingleUnits", SourceInteractionBoundariesCoverageTest.unpairedSurrogatesFallBackToSingleUnits);
        run("codePointAtCompatCoversEverySurrogateCase", SourceInteractionBoundariesCoverageTest.codePointAtCompatCoversEverySurrogateCase);
        run("rangeBoundariesRespectTheRequestedWindow", SourceInteractionBoundariesCoverageTest.rangeBoundariesRespectTheRequestedWindow);
        run("coercionHonoursEveryBiasAndEdgeCase", SourceInteractionBoundariesCoverageTest.coercionHonoursEveryBiasAndEdgeCase);
        TestTraceRecorder.flushClass("SourceInteractionBoundariesCoverageTest");
        run("chineseLanguageContextUsesPinnedMacrolanguageRegistry", EastAsianSpacingTest.chineseLanguageContextUsesPinnedMacrolanguageRegistry);
        run("usesPinnedUnicodeDraftDataAcrossScripts", EastAsianSpacingTest.usesPinnedUnicodeDraftDataAcrossScripts);
        run("resolvesConditionalValuesFromChineseLanguageContext", EastAsianSpacingTest.resolvesConditionalValuesFromChineseLanguageContext);
        run("enclosingMarkMakesTheWholeGraphemeClusterOther", EastAsianSpacingTest.enclosingMarkMakesTheWholeGraphemeClusterOther);
        run("resolvesTheActualSourceUnitAtEachShapingClusterEdge", EastAsianSpacingTest.resolvesTheActualSourceUnitAtEachShapingClusterEdge);
        TestTraceRecorder.flushClass("EastAsianSpacingTest");
        run("testUnicodeWordCharacter", EastAsianSpacingCoverageTest.testUnicodeWordCharacter);
        run("testUnicodeScriptEvidence", EastAsianSpacingCoverageTest.testUnicodeScriptEvidence);
        run("testEastAsianSpacingDataAndValues", EastAsianSpacingCoverageTest.testEastAsianSpacingDataAndValues);
        run("testEastAsianSpacingEdgesModel", EastAsianSpacingCoverageTest.testEastAsianSpacingEdgesModel);
        run("testUnicodeEastAsianSpacing", EastAsianSpacingCoverageTest.testUnicodeEastAsianSpacing);
        TestTraceRecorder.flushClass("EastAsianSpacingCoverageTest");
        run("lookupCoversEveryGeneratedValueAndBothMissDirections", EastAsianSpacingLookupCoverageTest.lookupCoversEveryGeneratedValueAndBothMissDirections);
        TestTraceRecorder.flushClass("EastAsianSpacingLookupCoverageTest");
        run("numbersAreMembersAcrossScriptsAndNonScalarsAreRejected", UnicodeNumberTest.numbersAreMembersAcrossScriptsAndNonScalarsAreRejected);
        TestTraceRecorder.flushClass("UnicodeNumberTest");
        run("commonAndInheritedScalarsDoNotVote", UnicodeScriptEvidenceTest.commonAndInheritedScalarsDoNotVote);
        run("eastAsianScriptsAreDistinctFromOtherStrongScripts", UnicodeScriptEvidenceTest.eastAsianScriptsAreDistinctFromOtherStrongScripts);
        TestTraceRecorder.flushClass("UnicodeScriptEvidenceTest");
        run("lettersAndNumbersAreWordCharactersAcrossScripts", UnicodeWordCharacterTest.lettersAndNumbersAreWordCharactersAcrossScripts);
        TestTraceRecorder.flushClass("UnicodeWordCharacterTest");
        run("testTiqianTextContentAndLinkAddressDisplay", TextModelCoverageTest.testTiqianTextContentAndLinkAddressDisplay);
        run("testSpansAndInlineBox", TextModelCoverageTest.testSpansAndInlineBox);
        run("testInlineObjectPreferredStretchAndAdjustment", TextModelCoverageTest.testInlineObjectPreferredStretchAndAdjustment);
        run("testTextStyleAndDecorations", TextModelCoverageTest.testTextStyleAndDecorations);
        run("testRichTextSpansAndPatterns", TextModelCoverageTest.testRichTextSpansAndPatterns);
        run("testRubyAndParagraphModels", TextModelCoverageTest.testRubyAndParagraphModels);
        TestTraceRecorder.flushClass("TextModelCoverageTest");
        run("yinpingHasNoMark", BopomofoParserTest.yinpingHasNoMark);
        run("suffixMarksAreToneAndStripped", BopomofoParserTest.suffixMarksAreToneAndStripped);
        run("neutralToneIsPrefixed", BopomofoParserTest.neutralToneIsPrefixed);
        run("singleSymbol", BopomofoParserTest.singleSymbol);
        TestTraceRecorder.flushClass("BopomofoParserTest");
        run("bareNumberIsItsOwnGroup", NumberSymbolCohesionTest.bareNumberIsItsOwnGroup);
        run("bindsDigitsWithSuffixUnitPrefixSignAndCurrency", NumberSymbolCohesionTest.bindsDigitsWithSuffixUnitPrefixSignAndCurrency);
        run("keepsInteriorDecimalAndThousandsSeparators", NumberSymbolCohesionTest.keepsInteriorDecimalAndThousandsSeparators);
        TestTraceRecorder.flushClass("NumberSymbolCohesionTest");
        run("noneForbidsNothing", KinsokuLevelTest.noneForbidsNothing);
        run("basicForbidsPauseStopsClosingConnectorsAtStartAndOpeningAtEnd", KinsokuLevelTest.basicForbidsPauseStopsClosingConnectorsAtStartAndOpeningAtEnd);
        run("gbStyleAddsSeparatorAtLineEnd", KinsokuLevelTest.gbStyleAddsSeparatorAtLineEnd);
        run("strictAddsDashAndEllipsisAtLineStart", KinsokuLevelTest.strictAddsDashAndEllipsisAtLineStart);
        run("profileDefaultsToMeasureAdaptive", KinsokuLevelTest.profileDefaultsToMeasureAdaptive);
        run("cjkBracketVariantsClassifyAsOpeningAndClosing", KinsokuLevelTest.cjkBracketVariantsClassifyAsOpeningAndClosing);
        run("exposesUnambiguousAsciiPointMarksWithoutGuessingQuotesOrConnectors", KinsokuLevelTest.exposesUnambiguousAsciiPointMarksWithoutGuessingQuotesOrConnectors);
        run("measureAdaptiveResolvesPerLineWidth", KinsokuLevelTest.measureAdaptiveResolvesPerLineWidth);
        TestTraceRecorder.flushClass("KinsokuLevelTest");
        run("mainlandAnchorsClosingAndPauseStopToTrailing", PunctuationGluePlacementTest.mainlandAnchorsClosingAndPauseStopToTrailing);
        run("mainlandAnchorsOpeningToLeading", PunctuationGluePlacementTest.mainlandAnchorsOpeningToLeading);
        run("mainlandSplitsSymmetricPunctuationOnBothSides", PunctuationGluePlacementTest.mainlandSplitsSymmetricPunctuationOnBothSides);
        run("traditionalCentresClosingAndPauseStop", PunctuationGluePlacementTest.traditionalCentresClosingAndPauseStop);
        run("traditionalCentresOpening", PunctuationGluePlacementTest.traditionalCentresOpening);
        run("forRegionMapsClreqRegionsToCorrectPlacement", PunctuationGluePlacementTest.forRegionMapsClreqRegionsToCorrectPlacement);
        run("builtInTaiwanAndHongKongProfilesUseTraditionalPlacement", PunctuationGluePlacementTest.builtInTaiwanAndHongKongProfilesUseTraditionalPlacement);
        TestTraceRecorder.flushClass("PunctuationGluePlacementTest");
        run("preferPolicyUsesClreqRecommendedDisplayCodepoints", ClreqPunctuationGlyphSubstitutorTest.preferPolicyUsesClreqRecommendedDisplayCodepoints);
        run("preservePolicyKeepsInputDisplayCodepoints", ClreqPunctuationGlyphSubstitutorTest.preservePolicyKeepsInputDisplayCodepoints);
        run("preferPolicyDoesNotRewriteAmbiguousConnectorOrSolidusForms", ClreqPunctuationGlyphSubstitutorTest.preferPolicyDoesNotRewriteAmbiguousConnectorOrSolidusForms);
        run("recommendedDashCodepointOccupiesTwoEm", ClreqPunctuationGlyphSubstitutorTest.recommendedDashCodepointOccupiesTwoEm);
        TestTraceRecorder.flushClass("ClreqPunctuationGlyphSubstitutorTest");
        run("testBopomofoModelsAndParser", ClreqProfileCoverageTest.testBopomofoModelsAndParser);
        run("testClreqProfileAndResolver", ClreqProfileCoverageTest.testClreqProfileAndResolver);
        run("testClreqPunctuationPoliciesAndClassification", ClreqProfileCoverageTest.testClreqPunctuationPoliciesAndClassification);
        run("testForcedHalfWidthAndPolicyFor", ClreqProfileCoverageTest.testForcedHalfWidthAndPolicyFor);
        run("testForbiddenAtLineStartAndEnd", ClreqProfileCoverageTest.testForbiddenAtLineStartAndEnd);
        run("testPunctuationAdvanceAndSubstitutor", ClreqProfileCoverageTest.testPunctuationAdvanceAndSubstitutor);
        TestTraceRecorder.flushClass("ClreqProfileCoverageTest");
        run("forbiddenAtLineStartCoversEveryPunctuationClass", ClreqPolicyTailCoverageTest.forbiddenAtLineStartCoversEveryPunctuationClass);
        run("forbiddenAtLineEndCoversOpeningSolidusAndOther", ClreqPolicyTailCoverageTest.forbiddenAtLineEndCoversOpeningSolidusAndOther);
        run("kinsokuRuleAllowsClustersWithoutDisplayText", ClreqPolicyTailCoverageTest.kinsokuRuleAllowsClustersWithoutDisplayText);
        run("bopomofoParserCoversEveryToneArm", ClreqPolicyTailCoverageTest.bopomofoParserCoversEveryToneArm);
        TestTraceRecorder.flushClass("ClreqPolicyTailCoverageTest");
        run("nullStatusNamesMissingConformingGlyphAndUnpreparedDetail", CjkDashCapabilityPolicyTest.nullStatusNamesMissingConformingGlyphAndUnpreparedDetail);
        run("conformingStatusWithBlankDetailNamesTheMissingSession", CjkDashCapabilityPolicyTest.conformingStatusWithBlankDetailNamesTheMissingSession);
        run("conformingStatusWithDetailAppendsHostEvidence", CjkDashCapabilityPolicyTest.conformingStatusWithDetailAppendsHostEvidence);
        run("nonConformingStatusWithDetailNamesMissingGlyphAndAppendsEvidence", CjkDashCapabilityPolicyTest.nonConformingStatusWithDetailNamesMissingGlyphAndAppendsEvidence);
        run("nonConformingStatusWithBlankDetailKeepsOnlyStatusPrefix", CjkDashCapabilityPolicyTest.nonConformingStatusWithBlankDetailKeepsOnlyStatusPrefix);
        TestTraceRecorder.flushClass("CjkDashCapabilityPolicyTest");
        run("classifiesAsciiBracketsAsLatin", CjkFontRoleClassifierTest.classifiesAsciiBracketsAsLatin);
        run("classifiesAsciiHyphenSlashTildeAsLatinRegardlessOfContext", CjkFontRoleClassifierTest.classifiesAsciiHyphenSlashTildeAsLatinRegardlessOfContext);
        run("classifiesAsciiSymbolsAndPunctuationAsLatin", CjkFontRoleClassifierTest.classifiesAsciiSymbolsAndPunctuationAsLatin);
        run("classifiesCjkPunctuation", CjkFontRoleClassifierTest.classifiesCjkPunctuation);
        run("classifiesCjkText", CjkFontRoleClassifierTest.classifiesCjkText);
        run("classifiesCurlyQuotesAsCjkAtTextBoundary", CjkFontRoleClassifierTest.classifiesCurlyQuotesAsCjkAtTextBoundary);
        run("classifiesCurlyQuotesAsCjkInMixedContext", CjkFontRoleClassifierTest.classifiesCurlyQuotesAsCjkInMixedContext);
        run("classifiesCurlyQuotesAsCjkWhenSurroundedByCjk", CjkFontRoleClassifierTest.classifiesCurlyQuotesAsCjkWhenSurroundedByCjk);
        run("classifiesCurlyQuotesAsLatinWhenSurroundedByLatin", CjkFontRoleClassifierTest.classifiesCurlyQuotesAsLatinWhenSurroundedByLatin);
        run("classifiesLatinText", CjkFontRoleClassifierTest.classifiesLatinText);
        run("classifiesUnicodeEmojiPresentationWithoutReclassifyingPlainKeycapBases", CjkFontRoleClassifierTest.classifiesUnicodeEmojiPresentationWithoutReclassifyingPlainKeycapBases);
        TestTraceRecorder.flushClass("CjkFontRoleClassifierTest");
        run("emitGoldenTrace", FontPolicyCoverageTest.emitGoldenTrace);
        TestTraceRecorder.flushClass("FontPolicyCoverageTest");

        run("supplementarySymbolIsUnknownBecauseItHasNoBmpCategory", FontRoleTailCoverageTest.supplementarySymbolIsUnknownBecauseItHasNoBmpCategory);
        run("bmpMathAndCurrencySymbolsResolveToSymbolRole", FontRoleTailCoverageTest.bmpMathAndCurrencySymbolsResolveToSymbolRole);
        TestTraceRecorder.flushClass("FontRoleTailCoverageTest");
        run("reportsFirstPropertyWhenItDiverges", InlineShapingStylePolicyTest.reportsFirstPropertyWhenItDiverges);
        run("reportsMiddlePropertyWhenItIsFirstDivergence", InlineShapingStylePolicyTest.reportsMiddlePropertyWhenItIsFirstDivergence);
        run("returnsNullWhenAllValuesMatch", InlineShapingStylePolicyTest.returnsNullWhenAllValuesMatch);
        run("returnsNullForEmptyLists", InlineShapingStylePolicyTest.returnsNullForEmptyLists);
        run("longerValueListsStopAtThePropertyListBoundary", InlineShapingStylePolicyTest.longerValueListsStopAtThePropertyListBoundary);
        TestTraceRecorder.flushClass("InlineShapingStylePolicyTest");
        run("cjkTextUsesFontDeclaredTypoBoxInsteadOfSynthesizedSquare", ScriptAwareFontMetricsNormalizerTest.cjkTextUsesFontDeclaredTypoBoxInsteadOfSynthesizedSquare);
        run("cjkTextFallsBackToHheaWhenFontHasNoTypoMetrics", ScriptAwareFontMetricsNormalizerTest.cjkTextFallsBackToHheaWhenFontHasNoTypoMetrics);
        run("latinTextKeepsRomanRawMetrics", ScriptAwareFontMetricsNormalizerTest.latinTextKeepsRomanRawMetrics);
        TestTraceRecorder.flushClass("ScriptAwareFontMetricsNormalizerTest");
        run("onlyLatinTextUsesLatinFace", UsesLatinFaceTest.onlyLatinTextUsesLatinFace);
        run("nameOverloadAgreesWithEnum", UsesLatinFaceTest.nameOverloadAgreesWithEnum);
        TestTraceRecorder.flushClass("UsesLatinFaceTest");
        run("coversAllShapingSourceEnumEntries", TextShaperCoverageTest.coversAllShapingSourceEnumEntries);
        run("unimplementedTextShaperThrowsOnShape", TextShaperCoverageTest.unimplementedTextShaperThrowsOnShape);
        run("explainableStubNominalAdvanceBranches", TextShaperCoverageTest.explainableStubNominalAdvanceBranches);
        run("surrogatePairHandlingInCodePointCount", TextShaperCoverageTest.surrogatePairHandlingInCodePointCount);
        run("shapingInputWithFeaturesAndConstants", TextShaperCoverageTest.shapingInputWithFeaturesAndConstants);
        TestTraceRecorder.flushClass("TextShaperCoverageTest");
        run("shapesSingleCjkClusterWithOneEmAdvance", ExplainableStubTextShaperTest.shapesSingleCjkClusterWithOneEmAdvance);
        run("keepsLatinRunAsSingleShapedClusterWithNominalGlyphs", ExplainableStubTextShaperTest.keepsLatinRunAsSingleShapedClusterWithNominalGlyphs);
        run("shapesClreqDashSubstitutionAsTwoEmDisplayCluster", ExplainableStubTextShaperTest.shapesClreqDashSubstitutionAsTwoEmDisplayCluster);
        TestTraceRecorder.flushClass("ExplainableStubTextShaperTest");

        run("glueRejectsInvertedBounds", PunctuationModelCoverageTest.glueRejectsInvertedBounds);
        run("adjustmentOpportunityCarriesRangeAndGlue", PunctuationModelCoverageTest.adjustmentOpportunityCarriesRangeAndGlue);
        run("compressionResultSumsAdjustmentReductions", PunctuationModelCoverageTest.compressionResultSumsAdjustmentReductions);
        run("adjacentPunctuationInnerGlueCollapsesByHalfEm", PunctuationModelCoverageTest.adjacentPunctuationInnerGlueCollapsesByHalfEm);
        run("adjacentPunctuationTargetsTheWiderSide", PunctuationModelCoverageTest.adjacentPunctuationTargetsTheWiderSide);
        run("adjacentPunctuationSkipsNonAdjacentZeroGlueAndZeroEm", PunctuationModelCoverageTest.adjacentPunctuationSkipsNonAdjacentZeroGlueAndZeroEm);
        run("cjkClosingBeforeAsciiPointMarkCollapsesTrailingGlue", PunctuationModelCoverageTest.cjkClosingBeforeAsciiPointMarkCollapsesTrailingGlue);
        run("cjkClosingCompressionRejectsNonMatchingNeighbours", PunctuationModelCoverageTest.cjkClosingCompressionRejectsNonMatchingNeighbours);
        run("indexedBuildRejectsOutOfRangeIndex", PunctuationModelCoverageTest.indexedBuildRejectsOutOfRangeIndex);
        run("nonPunctuationCharactersProduceNoAtom", PunctuationModelCoverageTest.nonPunctuationCharactersProduceNoAtom);
        run("policyFallbackSplitsGlueByClassSide", PunctuationModelCoverageTest.policyFallbackSplitsGlueByClassSide);
        run("underwidthGlyphsExpandIntoFullWidthCellByClassSide", PunctuationModelCoverageTest.underwidthGlyphsExpandIntoFullWidthCellByClassSide);
        run("haltFittedCompressionUsesFontMeasurements", PunctuationModelCoverageTest.haltFittedCompressionUsesFontMeasurements);
        run("haltTrimIsLimitedByInkBoundsAndRecordsWhy", PunctuationModelCoverageTest.haltTrimIsLimitedByInkBoundsAndRecordsWhy);
        run("haltAdvanceWithoutPlacementFallsBackToFittedInkOrProfile", PunctuationModelCoverageTest.haltAdvanceWithoutPlacementFallsBackToFittedInkOrProfile);
        run("haltFromProportionalGlyphIsRejected", PunctuationModelCoverageTest.haltFromProportionalGlyphIsRejected);
        run("inkBoundsFittedFramePicksTheNarrowestContainingAnchor", PunctuationModelCoverageTest.inkBoundsFittedFramePicksTheNarrowestContainingAnchor);
        run("forcedHalfWidthConnectorsConsumeGlueUpFront", PunctuationModelCoverageTest.forcedHalfWidthConnectorsConsumeGlueUpFront);
        run("inkInputRecordsWhyBoundsAreMissing", PunctuationModelCoverageTest.inkInputRecordsWhyBoundsAreMissing);
        run("glueSideForMainlandSimplifiedMapsClassesToSides", PunctuationModelCoverageTest.glueSideForMainlandSimplifiedMapsClassesToSides);
        TestTraceRecorder.flushClass("PunctuationModelCoverageTest");
        run("haltAdvanceWithoutPlacementUsesNamedProfileFallback", PunctuationAtomBuilderHaltTest.haltAdvanceWithoutPlacementUsesNamedProfileFallback);
        run("haltPlacementDirectlyDefinesBothCompressionSides", PunctuationAtomBuilderHaltTest.haltPlacementDirectlyDefinesBothCompressionSides);
        run("haltPlacementOverridesRegionalProfileDirection", PunctuationAtomBuilderHaltTest.haltPlacementOverridesRegionalProfileDirection);
        run("defaultInkCapsAHaltTrimThatWouldCutIntoThePaintedGlyph", PunctuationAtomBuilderHaltTest.defaultInkCapsAHaltTrimThatWouldCutIntoThePaintedGlyph);
        run("equalHaltAdvanceFallsThroughToInkBounds", PunctuationAtomBuilderHaltTest.equalHaltAdvanceFallsThroughToInkBounds);
        run("microsoftYaheiCentredCommaCompressesFromBothSides", PunctuationAtomBuilderHaltTest.microsoftYaheiCentredCommaCompressesFromBothSides);
        run("microsoftYaheiBottomLeftStopKeepsItsLeadingSafetyMargin", PunctuationAtomBuilderHaltTest.microsoftYaheiBottomLeftStopKeepsItsLeadingSafetyMargin);
        run("founderHeitiCentredParenthesesStayMirrorImages", PunctuationAtomBuilderHaltTest.founderHeitiCentredParenthesesStayMirrorImages);
        run("underwidthOpeningQuoteCompletesTheLeadingSideOfItsFullWidthCell", PunctuationAtomBuilderHaltTest.underwidthOpeningQuoteCompletesTheLeadingSideOfItsFullWidthCell);
        run("fixedHalfConsumesMeasuredSidebearingsInsteadOfApplyingAProfileShift", PunctuationAtomBuilderHaltTest.fixedHalfConsumesMeasuredSidebearingsInsteadOfApplyingAProfileShift);
        run("overhangReducesCompressionCapacityWithoutMovingInk", PunctuationAtomBuilderHaltTest.overhangReducesCompressionCapacityWithoutMovingInk);
        TestTraceRecorder.flushClass("PunctuationAtomBuilderHaltTest");
        run("breakCandidateDefaultsAreUsable", LineOptimizationCoverageTest.breakCandidateDefaultsAreUsable);
        run("breakCandidateCarriesExplicitForbiddenReasonAndRepairs", LineOptimizationCoverageTest.breakCandidateCarriesExplicitForbiddenReasonAndRepairs);
        run("lineCandidateRejectsHangingThatIsNotATrailingSuffix", LineOptimizationCoverageTest.lineCandidateRejectsHangingThatIsNotATrailingSuffix);
        run("lineCandidateRejectsDiscontiguousHanging", LineOptimizationCoverageTest.lineCandidateRejectsDiscontiguousHanging);
        run("lineCandidateAcceptsAContiguousTrailingHangingSuffix", LineOptimizationCoverageTest.lineCandidateAcceptsAContiguousTrailingHangingSuffix);
        run("hangingClusterIndexPrefersTheHangOffenderOverTheSuffixEnd", LineOptimizationCoverageTest.hangingClusterIndexPrefersTheHangOffenderOverTheSuffixEnd);
        run("inMeasureClusterRangeExcludesTheHangingSuffix", LineOptimizationCoverageTest.inMeasureClusterRangeExcludesTheHangingSuffix);
        run("carryNextRecordsTheMovedMark", LineOptimizationCoverageTest.carryNextRecordsTheMovedMark);
        run("repairCandidateDefaultsAreUsable", LineOptimizationCoverageTest.repairCandidateDefaultsAreUsable);
        run("lineSolutionDefaultsToZeroBadness", LineOptimizationCoverageTest.lineSolutionDefaultsToZeroBadness);
        run("optimizationStrategyEnumeratesAllThreeStrategies", LineOptimizationCoverageTest.optimizationStrategyEnumeratesAllThreeStrategies);
        TestTraceRecorder.flushClass("LineOptimizationCoverageTest");
        run("parentheticalPairWithOnlyLeftOuterScriptTakesTheLeftRole", ContextualDashEllipsisRoleResolverCoverageTest.parentheticalPairWithOnlyLeftOuterScriptTakesTheLeftRole);
        run("parentheticalPairWithOnlyRightOuterScriptTakesTheRightRole", ContextualDashEllipsisRoleResolverCoverageTest.parentheticalPairWithOnlyRightOuterScriptTakesTheRightRole);
        run("parentheticalPairWithoutOuterScriptFallsBackToParagraphLanguage", ContextualDashEllipsisRoleResolverCoverageTest.parentheticalPairWithoutOuterScriptFallsBackToParagraphLanguage);
        run("forwardPassWalkerArmsRunBeforeTheClassifierRejectsLoneSurrogates", ContextualDashEllipsisRoleResolverCoverageTest.forwardPassWalkerArmsRunBeforeTheClassifierRejectsLoneSurrogates);
        TestTraceRecorder.flushClass("ContextualDashEllipsisRoleResolverCoverageTest");
        run("contextualRoleExtensionsWrapOutsideThePipeline", ContextualRoleExtensionCoverageTest.contextualRoleExtensionsWrapOutsideThePipeline);
        TestTraceRecorder.flushClass("ContextualRoleExtensionCoverageTest");
        run("nestedPairInheritsEnclosingQuoteRole", ContextualQuoteRoleResolverCoverageTest.nestedPairInheritsEnclosingQuoteRole);
        run("nestedPairLatinInnerInheritsCjkEnclosing", ContextualQuoteRoleResolverCoverageTest.nestedPairLatinInnerInheritsCjkEnclosing);
        run("unmatchedRightSingleQuoteUsesSurroundingScript", ContextualQuoteRoleResolverCoverageTest.unmatchedRightSingleQuoteUsesSurroundingScript);
        run("unmatchedRightDoubleQuote", ContextualQuoteRoleResolverCoverageTest.unmatchedRightDoubleQuote);
        run("unmatchedLeftDoubleQuote", ContextualQuoteRoleResolverCoverageTest.unmatchedLeftDoubleQuote);
        run("unmatchedLeftSingleQuote", ContextualQuoteRoleResolverCoverageTest.unmatchedLeftSingleQuote);
        run("conflictingUnmatchedQuotesUsesParagraphLanguage", ContextualQuoteRoleResolverCoverageTest.conflictingUnmatchedQuotesUsesParagraphLanguage);
        run("unmatchedQuoteWithSurrogatePairContent", ContextualQuoteRoleResolverCoverageTest.unmatchedQuoteWithSurrogatePairContent);
        run("codePointAtCompatWithSupplementaryChar", ContextualQuoteRoleResolverCoverageTest.codePointAtCompatWithSupplementaryChar);
        run("codePointLengthAtSupplementaryInContent", ContextualQuoteRoleResolverCoverageTest.codePointLengthAtSupplementaryInContent);
        run("nonCjkInWordApostropheWithSurrogateBefore", ContextualQuoteRoleResolverCoverageTest.nonCjkInWordApostropheWithSurrogateBefore);
        run("whitespaceDelimitedWesternQuoteUnmatched", ContextualQuoteRoleResolverCoverageTest.whitespaceDelimitedWesternQuoteUnmatched);
        run("enclosingPairResolvedBeforeInner", ContextualQuoteRoleResolverCoverageTest.enclosingPairResolvedBeforeInner);
        run("pairByCloseSkipInNearestStrongScript", ContextualQuoteRoleResolverCoverageTest.pairByCloseSkipInNearestStrongScript);
        run("pairByOpenSkipInNearestStrongScript", ContextualQuoteRoleResolverCoverageTest.pairByOpenSkipInNearestStrongScript);
        run("ambiguousCurlyQuoteUnmatchedInText", ContextualQuoteRoleResolverCoverageTest.ambiguousCurlyQuoteUnmatchedInText);
        run("resolveUnmatchedWithBothSurroundingRolesNull", ContextualQuoteRoleResolverCoverageTest.resolveUnmatchedWithBothSurroundingRolesNull);
        run("nearestStrongScriptRoleBackwardSkipsPairedCloseQuote", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleBackwardSkipsPairedCloseQuote);
        run("nearestStrongScriptRoleForwardSkipsPairedOpenQuote", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleForwardSkipsPairedOpenQuote);
        run("enclosingPairResolvedBeforeInnerPair", ContextualQuoteRoleResolverCoverageTest.enclosingPairResolvedBeforeInnerPair);
        run("whitespaceDelimitedWesternQuotePaired", ContextualQuoteRoleResolverCoverageTest.whitespaceDelimitedWesternQuotePaired);
        run("conflictingUnmatchedQuotesBothNonNull", ContextualQuoteRoleResolverCoverageTest.conflictingUnmatchedQuotesBothNonNull);
        run("noUnmatchedQuoteContext", ContextualQuoteRoleResolverCoverageTest.noUnmatchedQuoteContext);
        run("nearestStrongScriptRoleBackwardThroughSurrogatePair", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleBackwardThroughSurrogatePair);
        run("nearestStrongScriptRoleForwardThroughSurrogatePair", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleForwardThroughSurrogatePair);
        run("nestedPairSkipsInnerInScriptEvidence", ContextualQuoteRoleResolverCoverageTest.nestedPairSkipsInnerInScriptEvidence);
        run("mixedScriptEnclosingLevelUsesParagraphLanguage", ContextualQuoteRoleResolverCoverageTest.mixedScriptEnclosingLevelUsesParagraphLanguage);
        run("unmatchedRightSingleQuoteWithLeftRole", ContextualQuoteRoleResolverCoverageTest.unmatchedRightSingleQuoteWithLeftRole);
        run("unmatchedRightSingleQuoteWithRightRole", ContextualQuoteRoleResolverCoverageTest.unmatchedRightSingleQuoteWithRightRole);
        run("unmatchedQuoteWithWhitespaceBeforeAndLatinRight", ContextualQuoteRoleResolverCoverageTest.unmatchedQuoteWithWhitespaceBeforeAndLatinRight);
        run("nonCjkInWordApostrophePaired", ContextualQuoteRoleResolverCoverageTest.nonCjkInWordApostrophePaired);
        run("codePointLengthAtSurrogatePairInContent", ContextualQuoteRoleResolverCoverageTest.codePointLengthAtSurrogatePairInContent);
        run("codePointAtCompatSupplementaryInOuterEvidence", ContextualQuoteRoleResolverCoverageTest.codePointAtCompatSupplementaryInOuterEvidence);
        run("conflictingUnmatchedQuotesLeftAndRightNonNull", ContextualQuoteRoleResolverCoverageTest.conflictingUnmatchedQuotesLeftAndRightNonNull);
        run("unmatchedQuoteNonWhitespaceBefore", ContextualQuoteRoleResolverCoverageTest.unmatchedQuoteNonWhitespaceBefore);
        run("nearestStrongScriptRoleBackwardHitsSupplementary", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleBackwardHitsSupplementary);
        run("nearestStrongScriptRoleForwardHitsSupplementary", ContextualQuoteRoleResolverCoverageTest.nearestStrongScriptRoleForwardHitsSupplementary);
        run("enclosingPairUnresolvedFallsThroughToContent", ContextualQuoteRoleResolverCoverageTest.enclosingPairUnresolvedFallsThroughToContent);
        run("unmatchedQuoteAtStartWithRightRole", ContextualQuoteRoleResolverCoverageTest.unmatchedQuoteAtStartWithRightRole);
        TestTraceRecorder.flushClass("ContextualQuoteRoleResolverCoverageTest");
        run("nestedPairInsideNeutralEnclosingInheritsTheOuterQuotation", ContextualQuoteRoleResolverNestedAndSurrogateTest.nestedPairInsideNeutralEnclosingInheritsTheOuterQuotation);
        run("spaceBeforeUnmatchedQuoteWithCjkRightSkipsTheDelimitedRule", ContextualQuoteRoleResolverNestedAndSurrogateTest.spaceBeforeUnmatchedQuoteWithCjkRightSkipsTheDelimitedRule);
        run("leftwardScanFromALowSurrogateWalksEveryBacktrackArm", ContextualQuoteRoleResolverNestedAndSurrogateTest.leftwardScanFromALowSurrogateWalksEveryBacktrackArm);
        run("tabBeforeAWhollyWesternPairDelimitsLikeASpace", ContextualQuoteRoleResolverNestedAndSurrogateTest.tabBeforeAWhollyWesternPairDelimitsLikeASpace);
        run("spaceBeforeAPairWithNonWesternContentSkipsTheDelimitedRule", ContextualQuoteRoleResolverNestedAndSurrogateTest.spaceBeforeAPairWithNonWesternContentSkipsTheDelimitedRule);
        run("spaceBeforeAMixedContentPairReportsMixedContent", ContextualQuoteRoleResolverNestedAndSurrogateTest.spaceBeforeAMixedContentPairReportsMixedContent);
        run("mixedEnclosingLevelFallsBackToParagraphLanguage", ContextualQuoteRoleResolverNestedAndSurrogateTest.mixedEnclosingLevelFallsBackToParagraphLanguage);
        run("nonChineseLocaleResolvesNeutralContextToLatinText", ContextualQuoteRoleResolverNestedAndSurrogateTest.nonChineseLocaleResolvesNeutralContextToLatinText);
        run("privateUseCharBeforeAQuoteFailsTheLowSurrogateRangeAbove", ContextualQuoteRoleResolverNestedAndSurrogateTest.privateUseCharBeforeAQuoteFailsTheLowSurrogateRangeAbove);
        run("highSurrogateAtTheContentEndHasNoRoomAndThrows", ContextualQuoteRoleResolverNestedAndSurrogateTest.highSurrogateAtTheContentEndHasNoRoomAndThrows);
        run("siblingPairsInsideOneQuotationEachInheritTheOuterRole", ContextualQuoteRoleResolverNestedAndSurrogateTest.siblingPairsInsideOneQuotationEachInheritTheOuterRole);
        run("plainFollowerOfAHighSurrogateCountsAsOneUnit", ContextualQuoteRoleResolverNestedAndSurrogateTest.plainFollowerOfAHighSurrogateCountsAsOneUnit);
        run("privateUseFollowerOfAHighSurrogateCountsAsOneUnit", ContextualQuoteRoleResolverNestedAndSurrogateTest.privateUseFollowerOfAHighSurrogateCountsAsOneUnit);
        TestTraceRecorder.flushClass("ContextualQuoteRoleResolverNestedAndSurrogateTest");

        if (failures > 0) {
            Process.exit(1);
        }
        Console.log("all CoreUnitsGeometryTest checks passed");
    }
}
