package;

import org.tiqian.core.TiqianIllegalArgumentException;
import org.tiqian.core.CoreUnitsGeometryTest;
import org.tiqian.core.CoreLayoutQueriesGapsTest;
import org.tiqian.core.LayoutQueriesTest;
import org.tiqian.core.LayoutQueriesResidualCoverageTest;
import org.tiqian.core.CoreBoundaryTest;
import org.tiqian.core.LinkAddressDisplayTest;
import org.tiqian.core.SourceInteractionBoundariesCoverageTest;
import org.tiqian.core.TextModelCoverageTest;
import org.tiqian.core.EastAsianSpacingTest;
import org.tiqian.core.EastAsianSpacingCoverageTest;
import org.tiqian.core.EastAsianSpacingLookupCoverageTest;
import org.tiqian.core.TextRangeTest;
import org.tiqian.core.UnicodeNumberTest;
import org.tiqian.core.UnicodeScriptEvidenceTest;
import org.tiqian.core.UnicodeWordCharacterTest;
import org.tiqian.test.trace.TestTraceRecorder;
import org.tiqian.test.trace.TraceAssertionException;
import std.Console;
import std.Process;

class Main {
    private static var failures:Int = 0;

    private static function run(name:String, test:()->Void):Void {
        try {
            test();
        } catch (error:TraceAssertionException) {
            failures += 1;
            Console.log("FAIL " + name + ": " + error.message);
        } catch (error:TiqianIllegalArgumentException) {
            failures += 1;
            Console.log("FAIL " + name + ": " + error.message);
        }
    }

    public static function main():Void {
        StringBufOracle.install();
        run("exposesLength", TextRangeTest.exposesLength);
        run("rejectsNegativeStart", TextRangeTest.rejectsNegativeStart);
        TestTraceRecorder.flushClass("TextRangeTest");
        run("icPlusReturnsSum", CoreUnitsGeometryTest.icPlusReturnsSum);
        run("icUnaryMinusReturnsNegated", CoreUnitsGeometryTest.icUnaryMinusReturnsNegated);
        run("floatIcExtensionCreatesIc", CoreUnitsGeometryTest.floatIcExtensionCreatesIc);
        run("intIcExtensionCreatesIc", CoreUnitsGeometryTest.intIcExtensionCreatesIc);
        run("icToPxMultipliesByEmSize", CoreUnitsGeometryTest.icToPxMultipliesByEmSize);
        run("rectHeightReturnsDifference", CoreUnitsGeometryTest.rectHeightReturnsDifference);
        run("rectWidthReturnsDifference", CoreUnitsGeometryTest.rectWidthReturnsDifference);
        run("textRangeRejectsStartGreaterThanEnd", CoreUnitsGeometryTest.textRangeRejectsStartGreaterThanEnd);
        run("textRangeRejectsNegativeStart", CoreUnitsGeometryTest.textRangeRejectsNegativeStart);
        run("layoutConstraintsRejectsNonPositiveMaxWidth", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxWidth);
        run("layoutConstraintsRejectsNonPositiveMaxHeight", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxHeight);
        run("layoutConstraintsRejectsNonPositiveMaxLines", CoreUnitsGeometryTest.layoutConstraintsRejectsNonPositiveMaxLines);
        run("maxLinesDecisionInfoRecordsTruncationDetails", CoreUnitsGeometryTest.maxLinesDecisionInfoRecordsTruncationDetails);
        run("layoutDebugInfoAcceptsMaxLinesDecision", CoreUnitsGeometryTest.layoutDebugInfoAcceptsMaxLinesDecision);
        TestTraceRecorder.flushClass("CoreUnitsGeometryTest");
        run("positionedClusterHeightReturnsDifference", CoreLayoutQueriesGapsTest.positionedClusterHeightReturnsDifference);
        run("getLineForOffsetUsesNearestLineWhenGapBetweenLines", CoreLayoutQueriesGapsTest.getLineForOffsetUsesNearestLineWhenGapBetweenLines);
        run("getBoundingBoxesIntDelegatesToTextRange", CoreLayoutQueriesGapsTest.getBoundingBoxesIntDelegatesToTextRange);
        run("richTextBackgroundUsesHorizontalPadding", CoreLayoutQueriesGapsTest.richTextBackgroundUsesHorizontalPadding);
        run("richTextBackgroundTrailingPaddingWhenSpanEndsAtSegmentEnd", CoreLayoutQueriesGapsTest.richTextBackgroundTrailingPaddingWhenSpanEndsAtSegmentEnd);
        run("richTextBackgroundUniformParagraphStyleUsesParagraphStyle", CoreLayoutQueriesGapsTest.richTextBackgroundUniformParagraphStyleUsesParagraphStyle);
        run("markedFaceVerticalBoundsUsesFallbackWhenNoMetricMatches", CoreLayoutQueriesGapsTest.markedFaceVerticalBoundsUsesFallbackWhenNoMetricMatches);
        run("getSelectionOffsetForPositionReturnsNearestWhenBeforeFirstCluster", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsNearestWhenBeforeFirstCluster);
        run("getSelectionOffsetForPositionReturnsNearestWhenAfterLastCluster", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsNearestWhenAfterLastCluster);
        run("getSelectionOffsetForPositionReturnsStartOfLineWhenClustersEmpty", CoreLayoutQueriesGapsTest.getSelectionOffsetForPositionReturnsStartOfLineWhenClustersEmpty);
        run("getSelectionWordBoundaryForEmojiZwjSequence", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryForEmojiZwjSequence);
        run("getSelectionWordBoundaryForPunctuationReturnsSingle", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryForPunctuationReturnsSingle);
        run("positionedClustersProducesSourceStopsForLatinRun", CoreLayoutQueriesGapsTest.positionedClustersProducesSourceStopsForLatinRun);
        run("offsetForXUsesSourceStopsWhenAvailable", CoreLayoutQueriesGapsTest.offsetForXUsesSourceStopsWhenAvailable);
        run("getBoundingBoxesEmptyRangeReturnsEmptyList", CoreLayoutQueriesGapsTest.getBoundingBoxesEmptyRangeReturnsEmptyList);
        run("getLineForOffsetReturnsNearestLine", CoreLayoutQueriesGapsTest.getLineForOffsetReturnsNearestLine);
        run("getCursorRectReturnsCaretInCluster", CoreLayoutQueriesGapsTest.getCursorRectReturnsCaretInCluster);
        run("getOffsetForPositionUsesMinByWhenOutsideClusters", CoreLayoutQueriesGapsTest.getOffsetForPositionUsesMinByWhenOutsideClusters);
        run("getSelectionWordBoundaryReturnsEmptyForEmptyText", CoreLayoutQueriesGapsTest.getSelectionWordBoundaryReturnsEmptyForEmptyText);
        TestTraceRecorder.flushClass("CoreLayoutQueriesGapsTest");
        run("clipboardProjectionRestoresSourceAndAddsFullySelectedAnnotations", LayoutQueriesTest.clipboardProjectionRestoresSourceAndAddsFullySelectedAnnotations);
        run("positionedClustersFollowLineIndentAndAdvance", LayoutQueriesTest.positionedClustersFollowLineIndentAndAdvance);
        run("positionedClustersSeparateOccupiedBoxFromAutoSpaceDrawOrigin", LayoutQueriesTest.positionedClustersSeparateOccupiedBoxFromAutoSpaceDrawOrigin);
        run("positionedClustersSeparateOccupiedBoxFromConsumedLeadingGlueDrawOrigin", LayoutQueriesTest.positionedClustersSeparateOccupiedBoxFromConsumedLeadingGlueDrawOrigin);
        run("glyphInkBoundsKeepItalicOverhangSeparateFromOccupiedGeometry", LayoutQueriesTest.glyphInkBoundsKeepItalicOverhangSeparateFromOccupiedGeometry);
        run("lineAndBoxQueriesUseTiqianLineGeometry", LayoutQueriesTest.lineAndBoxQueriesUseTiqianLineGeometry);
        run("rangeBoxesSplitMultiUnitClustersBySourceRange", LayoutQueriesTest.rangeBoxesSplitMultiUnitClustersBySourceRange);
        run("richTextSegmentsReusePositionedClusterGeometryAndSplitLines", LayoutQueriesTest.richTextSegmentsReusePositionedClusterGeometryAndSplitLines);
        run("richTextDecorationTrimsOnlyOuterPunctuationGlue", LayoutQueriesTest.richTextDecorationTrimsOnlyOuterPunctuationGlue);
        run("richTextDecorationKeepsPunctuationGlueInsideItsRange", LayoutQueriesTest.richTextDecorationKeepsPunctuationGlueInsideItsRange);
        run("richTextDecorationDoesNotTrimAlreadyConsumedOpeningGlueTwice", LayoutQueriesTest.richTextDecorationDoesNotTrimAlreadyConsumedOpeningGlueTwice);
        run("customLineStylesReuseTheRendererUnderlineHeight", LayoutQueriesTest.customLineStylesReuseTheRendererUnderlineHeight);
        run("lineThroughBisectsTheIdeographicMetricBox", LayoutQueriesTest.lineThroughBisectsTheIdeographicMetricBox);
        run("richTextBackgroundKeepsInternalGapsButTrimsItsOuterLayoutSpace", LayoutQueriesTest.richTextBackgroundKeepsInternalGapsButTrimsItsOuterLayoutSpace);
        run("uniformTextStyleBackgroundIgnoresFallbackFaceHeightAndAddsPadding", LayoutQueriesTest.uniformTextStyleBackgroundIgnoresFallbackFaceHeightAndAddsPadding);
        run("backgroundContinuationCornersKeepOnlyTrueSourceEndsFullyRounded", LayoutQueriesTest.backgroundContinuationCornersKeepOnlyTrueSourceEndsFullyRounded);
        run("backgroundContinuationRadiusDefaultsToTheAuthoredCornerRadius", LayoutQueriesTest.backgroundContinuationRadiusDefaultsToTheAuthoredCornerRadius);
        run("adjacentBackgroundsWithTheSameStyleShareOneClearance", LayoutQueriesTest.adjacentBackgroundsWithTheSameStyleShareOneClearance);
        run("adjacentLineDecorationsWithTheSameStyleShareOneClearance", LayoutQueriesTest.adjacentLineDecorationsWithTheSameStyleShareOneClearance);
        run("adjacentBackgroundAndUnderlineDoNotAvoidAcrossStyles", LayoutQueriesTest.adjacentBackgroundAndUnderlineDoNotAvoidAcrossStyles);
        run("hitTestingChoosesOffsetFromTiqianClusterAdvances", LayoutQueriesTest.hitTestingChoosesOffsetFromTiqianClusterAdvances);
        run("selectionHitTestingKeepsSupportedSourceSequencesAtomic", LayoutQueriesTest.selectionHitTestingKeepsSupportedSourceSequencesAtomic);
        run("externalSelectionOffsetsRespectDirectionalBoundaryBias", LayoutQueriesTest.externalSelectionOffsetsRespectDirectionalBoundaryBias);
        run("supportedSourceSequenceRemainsAtomicAcrossEngineClusterBoundaries", LayoutQueriesTest.supportedSourceSequenceRemainsAtomicAcrossEngineClusterBoundaries);
        run("inlineObjectSourceRangeIsOneSelectionUnit", LayoutQueriesTest.inlineObjectSourceRangeIsOneSelectionUnit);
        run("selectionWordBoundaryExpandsLatinButKeepsHanAtomic", LayoutQueriesTest.selectionWordBoundaryExpandsLatinButKeepsHanAtomic);
        run("rubySelectionGeometryRedistributesAvoidanceSpreadWithoutOverlap", LayoutQueriesTest.rubySelectionGeometryRedistributesAvoidanceSpreadWithoutOverlap);
        TestTraceRecorder.flushClass("LayoutQueriesTest");
        run("cornerRadiiPredicatesCoverEveryComparison", LayoutQueriesResidualCoverageTest.cornerRadiiPredicatesCoverEveryComparison);
        run("resolvedCornerRadiiRejectsInvalidInsetsAndResolvesContinuations", LayoutQueriesResidualCoverageTest.resolvedCornerRadiiRejectsInvalidInsetsAndResolvesContinuations);
        run("copyProjectionAppendsFullySelectedAnnotationsOnly", LayoutQueriesResidualCoverageTest.copyProjectionAppendsFullySelectedAnnotationsOnly);
        run("positionedClustersByLineRejectsForeignLines", LayoutQueriesResidualCoverageTest.positionedClustersByLineRejectsForeignLines);
        run("glyphInkBoundsSkipsUnmatchedGlyphsAndReturnsNullWithoutInk", LayoutQueriesResidualCoverageTest.glyphInkBoundsSkipsUnmatchedGlyphsAndReturnsNullWithoutInk);
        run("emptyLineResultsShortCircuitEveryQuery", LayoutQueriesResidualCoverageTest.emptyLineResultsShortCircuitEveryQuery);
        run("boundingBoxFallsBackToTheCursorRectAtClusterGaps", LayoutQueriesResidualCoverageTest.boundingBoxFallsBackToTheCursorRectAtClusterGaps);
        run("richTextSegmentsSplitOnLineBreaksAndClusterGaps", LayoutQueriesResidualCoverageTest.richTextSegmentsSplitOnLineBreaksAndClusterGaps);
        run("richTextSegmentsSkipZeroLengthClustersBetweenSlices", LayoutQueriesResidualCoverageTest.richTextSegmentsSkipZeroLengthClustersBetweenSlices);
        run("trimmedDecorationSegmentsKeepOnlyDecorationRoles", LayoutQueriesResidualCoverageTest.trimmedDecorationSegmentsKeepOnlyDecorationRoles);
        run("backgroundSegmentsPassThroughUnmatchableSegments", LayoutQueriesResidualCoverageTest.backgroundSegmentsPassThroughUnmatchableSegments);
        run("backgroundSegmentsTrimGlueApplyPaddingAndUseGlyphAdvances", LayoutQueriesResidualCoverageTest.backgroundSegmentsTrimGlueApplyPaddingAndUseGlyphAdvances);
        run("markedFacesUseMetricDecisionsWhenTheyCoverTheCluster", LayoutQueriesResidualCoverageTest.markedFacesUseMetricDecisionsWhenTheyCoverTheCluster);
        run("uniformTextStyleFallsBackWhenEveryMetricFieldDiffers", LayoutQueriesResidualCoverageTest.uniformTextStyleFallsBackWhenEveryMetricFieldDiffers);
        run("uniformTextStylePrefersIdeographicMetricsThenAnyMatchingFace", LayoutQueriesResidualCoverageTest.uniformTextStylePrefersIdeographicMetricsThenAnyMatchingFace);
        run("adjacentSameStyleSegmentsShareClearance", LayoutQueriesResidualCoverageTest.adjacentSameStyleSegmentsShareClearance);
        run("decorationLineYRequiresValidStrokeAndDecorationRoles", LayoutQueriesResidualCoverageTest.decorationLineYRequiresValidStrokeAndDecorationRoles);
        run("cursorRectCoversEmptyLinesEmptyClustersAndMultiUnitClusters", LayoutQueriesResidualCoverageTest.cursorRectCoversEmptyLinesEmptyClustersAndMultiUnitClusters);
        run("offsetForPositionCoversVerticalDistancesAndNaNPoints", LayoutQueriesResidualCoverageTest.offsetForPositionCoversVerticalDistancesAndNaNPoints);
        run("selectionSnapPrefersTheCloserInlineObjectBoundary", LayoutQueriesResidualCoverageTest.selectionSnapPrefersTheCloserInlineObjectBoundary);
        run("selectionWordBoundaryForPositionRejectsDegenerateContent", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionRejectsDegenerateContent);
        run("zeroWidthClustersReturnTheirStartInHitTests", LayoutQueriesResidualCoverageTest.zeroWidthClustersReturnTheirStartInHitTests);
        run("coerceSelectionOffsetHonoursInlineObjectBoundaries", LayoutQueriesResidualCoverageTest.coerceSelectionOffsetHonoursInlineObjectBoundaries);
        run("selectionWordBoundaryExpandsWordsAndHonoursInlineObjects", LayoutQueriesResidualCoverageTest.selectionWordBoundaryExpandsWordsAndHonoursInlineObjects);
        run("selectionWordKindCoversEveryHanBlock", LayoutQueriesResidualCoverageTest.selectionWordKindCoversEveryHanBlock);
        run("nearestLineFallsBackToTheOnlyLineAtItsEndOffset", LayoutQueriesResidualCoverageTest.nearestLineFallsBackToTheOnlyLineAtItsEndOffset);
        run("rubyGeometryRedistributesSelectionBoxesAndDropsSourceStops", LayoutQueriesResidualCoverageTest.rubyGeometryRedistributesSelectionBoxesAndDropsSourceStops);
        run("boundingBoxesSliceZeroWidthAndEmptyClusters", LayoutQueriesResidualCoverageTest.boundingBoxesSliceZeroWidthAndEmptyClusters);
        run("positionedClustersAndSegmentsReturnEmptyWithoutLines", LayoutQueriesResidualCoverageTest.positionedClustersAndSegmentsReturnEmptyWithoutLines);
        run("sameSpanSlicesAcrossASourceBoundaryMergeIntoOneSegment", LayoutQueriesResidualCoverageTest.sameSpanSlicesAcrossASourceBoundaryMergeIntoOneSegment);
        run("glyphInkBoundsSkipsUnusableGlyphsAndReportsNull", LayoutQueriesResidualCoverageTest.glyphInkBoundsSkipsUnusableGlyphsAndReportsNull);
        run("backgroundTrailingEdgeUsesGlyphAdvancesWhenAvailable", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgeUsesGlyphAdvancesWhenAvailable);
        run("clearanceNeedsSameRoleAndUsesTheSmallerSide", LayoutQueriesResidualCoverageTest.clearanceNeedsSameRoleAndUsesTheSmallerSide);
        run("metricDecisionsMustFullyContainTheCluster", LayoutQueriesResidualCoverageTest.metricDecisionsMustFullyContainTheCluster);
        run("decorationStyleResolvesInsideSpansAndAtTheirEdges", LayoutQueriesResidualCoverageTest.decorationStyleResolvesInsideSpansAndAtTheirEdges);
        run("glueTrimSkipsInteriorSegmentEdges", LayoutQueriesResidualCoverageTest.glueTrimSkipsInteriorSegmentEdges);
        run("backgroundSegmentOutsideEverySpanUsesTheParagraphStyle", LayoutQueriesResidualCoverageTest.backgroundSegmentOutsideEverySpanUsesTheParagraphStyle);
        run("cursorRectFindsLaterClustersAndRejectsGappedRanges", LayoutQueriesResidualCoverageTest.cursorRectFindsLaterClustersAndRejectsGappedRanges);
        run("emptyMidClusterHoldsTheCaretAndSlicesKeepDegenerateRects", LayoutQueriesResidualCoverageTest.emptyMidClusterHoldsTheCaretAndSlicesKeepDegenerateRects);
        run("selectionWordBoundarySkipsInlineObjectsItDoesNotContain", LayoutQueriesResidualCoverageTest.selectionWordBoundarySkipsInlineObjectsItDoesNotContain);
        run("selectionWordBoundaryForPositionCoversDistancesAndFallbacks", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionCoversDistancesAndFallbacks);
        run("lineForOffsetInsideARangeTakesTheZeroDistanceArm", LayoutQueriesResidualCoverageTest.lineForOffsetInsideARangeTakesTheZeroDistanceArm);
        run("compatibilityIdeographsFormIndividualWordUnits", LayoutQueriesResidualCoverageTest.compatibilityIdeographsFormIndividualWordUnits);
        run("rubySpreadShiftsSelectionBoxesAndZeroWidthRubiesAreIgnored", LayoutQueriesResidualCoverageTest.rubySpreadShiftsSelectionBoxesAndZeroWidthRubiesAreIgnored);
        run("noArgPositionedClustersWalksEveryLine", LayoutQueriesResidualCoverageTest.noArgPositionedClustersWalksEveryLine);
        run("glyphInkBoundsRejectsEachNonFiniteEdgeIndependently", LayoutQueriesResidualCoverageTest.glyphInkBoundsRejectsEachNonFiniteEdgeIndependently);
        run("clearanceTakesTheSmallerSideWhicheverSegmentOwnsIt", LayoutQueriesResidualCoverageTest.clearanceTakesTheSmallerSideWhicheverSegmentOwnsIt);
        run("uniformTextStylePolicyResolvesSpanStyleOrParagraphStyle", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyResolvesSpanStyleOrParagraphStyle);
        run("trailingGlueIsSkippedWhenNoClusterEndsBeforeTheSegmentEnd", LayoutQueriesResidualCoverageTest.trailingGlueIsSkippedWhenNoClusterEndsBeforeTheSegmentEnd);
        run("decorationLineYWithoutSpansUsesTheParagraphStyle", LayoutQueriesResidualCoverageTest.decorationLineYWithoutSpansUsesTheParagraphStyle);
        run("wordBoundaryForPositionHandlesANonFiniteY", LayoutQueriesResidualCoverageTest.wordBoundaryForPositionHandlesANonFiniteY);
        run("supplementaryIdeographBeyondTheHanRangesIsItsOwnUnit", LayoutQueriesResidualCoverageTest.supplementaryIdeographBeyondTheHanRangesIsItsOwnUnit);
        run("planeFourCodepointAboveTheHanBandsIsItsOwnUnit", LayoutQueriesResidualCoverageTest.planeFourCodepointAboveTheHanBandsIsItsOwnUnit);
        run("nearestLineSearchCoversAllThreeDistanceArms", LayoutQueriesResidualCoverageTest.nearestLineSearchCoversAllThreeDistanceArms);
        run("rubiesOnOtherLinesDoNotAffectThisLineGeometry", LayoutQueriesResidualCoverageTest.rubiesOnOtherLinesDoNotAffectThisLineGeometry);
        run("backgroundTrailingEdgePicksTheLargestGlyphAdvance", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgePicksTheLargestGlyphAdvance);
        run("backgroundTrailingEdgeKeepsTheFirstGlyphWhenItIsLargest", LayoutQueriesResidualCoverageTest.backgroundTrailingEdgeKeepsTheFirstGlyphWhenItIsLargest);
        run("selectionWordBoundaryForPositionPrefersTheCloserLaterLine", LayoutQueriesResidualCoverageTest.selectionWordBoundaryForPositionPrefersTheCloserLaterLine);
        run("nearestLineSearchUpdatesToAStrictlyCloserLaterLine", LayoutQueriesResidualCoverageTest.nearestLineSearchUpdatesToAStrictlyCloserLaterLine);
        run("nearestLineSearchCoversBothLambdaCopiesOfEachArm", LayoutQueriesResidualCoverageTest.nearestLineSearchCoversBothLambdaCopiesOfEachArm);
        run("uniformTextStylePolicyPicksTheLastMatchingSpan", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyPicksTheLastMatchingSpan);
        run("decorationLineYPicksTheLastMatchingSpan", LayoutQueriesResidualCoverageTest.decorationLineYPicksTheLastMatchingSpan);
        run("uniformTextStylePolicyKeepsTheEarlierSpanWhenALaterOneMisses", LayoutQueriesResidualCoverageTest.uniformTextStylePolicyKeepsTheEarlierSpanWhenALaterOneMisses);
        run("decorationLineYKeepsTheEarlierSpanWhenALaterOneMisses", LayoutQueriesResidualCoverageTest.decorationLineYKeepsTheEarlierSpanWhenALaterOneMisses);
        TestTraceRecorder.flushClass("LayoutQueriesResidualCoverageTest");
        run("coerceToInteractionBoundaryBackwardReturnsBoundaryWhenAtEnd", CoreBoundaryTest.coerceToInteractionBoundaryBackwardReturnsBoundaryWhenAtEnd);
        run("coerceToInteractionBoundaryForwardReturnsNextBoundary", CoreBoundaryTest.coerceToInteractionBoundaryForwardReturnsNextBoundary);
        run("coerceToInteractionBoundaryNearestChoosesCloser", CoreBoundaryTest.coerceToInteractionBoundaryNearestChoosesCloser);
        run("coerceToInteractionBoundaryWithSurrogatePair", CoreBoundaryTest.coerceToInteractionBoundaryWithSurrogatePair);
        run("coerceToInteractionBoundaryWithInvalidSurrogatePair", CoreBoundaryTest.coerceToInteractionBoundaryWithInvalidSurrogatePair);
        run("sourceGraphemeBoundariesWithHangulLeadingJamo", CoreBoundaryTest.sourceGraphemeBoundariesWithHangulLeadingJamo);
        run("sourceGraphemeBoundariesWithHangulSyllable", CoreBoundaryTest.sourceGraphemeBoundariesWithHangulSyllable);
        run("sourceGraphemeBoundariesWithRegionalIndicator", CoreBoundaryTest.sourceGraphemeBoundariesWithRegionalIndicator);
        run("sourceGraphemeBoundariesWithEmojiZwjSequence", CoreBoundaryTest.sourceGraphemeBoundariesWithEmojiZwjSequence);
        run("sourceGraphemeBoundariesWithEmojiModifier", CoreBoundaryTest.sourceGraphemeBoundariesWithEmojiModifier);
        run("sourceGraphemeBoundariesReturnsSingleBoundaryForEmptyText", CoreBoundaryTest.sourceGraphemeBoundariesReturnsSingleBoundaryForEmptyText);
        run("interactionBoundariesWithTextRange", CoreBoundaryTest.interactionBoundariesWithTextRange);
        run("getSelectionOffsetForPositionReturnsStartOfFirstCluster", CoreBoundaryTest.getSelectionOffsetForPositionReturnsStartOfFirstCluster);
        run("getSelectionOffsetForPositionReturnsStartOfLineWhenEmptyClusters", CoreBoundaryTest.getSelectionOffsetForPositionReturnsStartOfLineWhenEmptyClusters);
        TestTraceRecorder.flushClass("CoreBoundaryTest");
        run("identicalDisplayAndTargetIsAnAddress", LinkAddressDisplayTest.identicalDisplayAndTargetIsAnAddress);
        run("proseDisplayTextIsNotAnAddress", LinkAddressDisplayTest.proseDisplayTextIsNotAnAddress);
        run("schemeLessDisplayOfTheTargetIsAnAddress", LinkAddressDisplayTest.schemeLessDisplayOfTheTargetIsAnAddress);
        TestTraceRecorder.flushClass("LinkAddressDisplayTest");
        run("crlfStaysOneUnit", SourceInteractionBoundariesCoverageTest.crlfStaysOneUnit);
        run("regionalIndicatorsPairUp", SourceInteractionBoundariesCoverageTest.regionalIndicatorsPairUp);
        run("hangulJamoRunsMergeIntoSyllableBlocks", SourceInteractionBoundariesCoverageTest.hangulJamoRunsMergeIntoSyllableBlocks);
        run("precomposedHangulSyllablesAbsorbJamo", SourceInteractionBoundariesCoverageTest.precomposedHangulSyllablesAbsorbJamo);
        run("extendersAttachToThePrecedingUnit", SourceInteractionBoundariesCoverageTest.extendersAttachToThePrecedingUnit);
        run("bandEdgesAndGapsExerciseEveryRangeArm", SourceInteractionBoundariesCoverageTest.bandEdgesAndGapsExerciseEveryRangeArm);
        run("emojiModifiersOnlyAttachToBases", SourceInteractionBoundariesCoverageTest.emojiModifiersOnlyAttachToBases);
        run("zwjChainsJoinOnlyExtendedPictographic", SourceInteractionBoundariesCoverageTest.zwjChainsJoinOnlyExtendedPictographic);
        run("unpairedSurrogatesFallBackToSingleUnits", SourceInteractionBoundariesCoverageTest.unpairedSurrogatesFallBackToSingleUnits);
        run("codePointAtCompatCoversEverySurrogateCase", SourceInteractionBoundariesCoverageTest.codePointAtCompatCoversEverySurrogateCase);
        run("rangeBoundariesRespectTheRequestedWindow", SourceInteractionBoundariesCoverageTest.rangeBoundariesRespectTheRequestedWindow);
        run("coercionHonoursEveryBiasAndEdgeCase", SourceInteractionBoundariesCoverageTest.coercionHonoursEveryBiasAndEdgeCase);
        TestTraceRecorder.flushClass("SourceInteractionBoundariesCoverageTest");
        run("chineseLanguageContextUsesPinnedMacrolanguageRegistry", EastAsianSpacingTest.chineseLanguageContextUsesPinnedMacrolanguageRegistry);
        run("usesPinnedUnicodeDraftDataAcrossScripts", EastAsianSpacingTest.usesPinnedUnicodeDraftDataAcrossScripts);
        run("resolvesConditionalValuesFromChineseLanguageContext", EastAsianSpacingTest.resolvesConditionalValuesFromChineseLanguageContext);
        run("enclosingMarkMakesTheWholeGraphemeClusterOther", EastAsianSpacingTest.enclosingMarkMakesTheWholeGraphemeClusterOther);
        run("resolvesTheActualSourceUnitAtEachShapingClusterEdge", EastAsianSpacingTest.resolvesTheActualSourceUnitAtEachShapingClusterEdge);
        TestTraceRecorder.flushClass("EastAsianSpacingTest");
        run("testUnicodeWordCharacter", EastAsianSpacingCoverageTest.testUnicodeWordCharacter);
        run("testUnicodeScriptEvidence", EastAsianSpacingCoverageTest.testUnicodeScriptEvidence);
        run("testEastAsianSpacingDataAndValues", EastAsianSpacingCoverageTest.testEastAsianSpacingDataAndValues);
        run("testEastAsianSpacingEdgesModel", EastAsianSpacingCoverageTest.testEastAsianSpacingEdgesModel);
        run("testUnicodeEastAsianSpacing", EastAsianSpacingCoverageTest.testUnicodeEastAsianSpacing);
        TestTraceRecorder.flushClass("EastAsianSpacingCoverageTest");
        run("lookupCoversEveryGeneratedValueAndBothMissDirections", EastAsianSpacingLookupCoverageTest.lookupCoversEveryGeneratedValueAndBothMissDirections);
        TestTraceRecorder.flushClass("EastAsianSpacingLookupCoverageTest");
        run("numbersAreMembersAcrossScriptsAndNonScalarsAreRejected", UnicodeNumberTest.numbersAreMembersAcrossScriptsAndNonScalarsAreRejected);
        TestTraceRecorder.flushClass("UnicodeNumberTest");
        run("commonAndInheritedScalarsDoNotVote", UnicodeScriptEvidenceTest.commonAndInheritedScalarsDoNotVote);
        run("eastAsianScriptsAreDistinctFromOtherStrongScripts", UnicodeScriptEvidenceTest.eastAsianScriptsAreDistinctFromOtherStrongScripts);
        TestTraceRecorder.flushClass("UnicodeScriptEvidenceTest");
        run("lettersAndNumbersAreWordCharactersAcrossScripts", UnicodeWordCharacterTest.lettersAndNumbersAreWordCharactersAcrossScripts);
        TestTraceRecorder.flushClass("UnicodeWordCharacterTest");
        run("testTiqianTextContentAndLinkAddressDisplay", TextModelCoverageTest.testTiqianTextContentAndLinkAddressDisplay);
        run("testSpansAndInlineBox", TextModelCoverageTest.testSpansAndInlineBox);
        run("testInlineObjectPreferredStretchAndAdjustment", TextModelCoverageTest.testInlineObjectPreferredStretchAndAdjustment);
        run("testTextStyleAndDecorations", TextModelCoverageTest.testTextStyleAndDecorations);
        run("testRichTextSpansAndPatterns", TextModelCoverageTest.testRichTextSpansAndPatterns);
        run("testRubyAndParagraphModels", TextModelCoverageTest.testRubyAndParagraphModels);
        TestTraceRecorder.flushClass("TextModelCoverageTest");

        if (failures > 0) {
            Process.exit(1);
        }
        Console.log("all CoreUnitsGeometryTest checks passed");
    }
}
