// Generated by the reflaxe TypeScript target. Do not edit.

import { Hyphenator } from "./Hyphenator.ts";
import { SortedMapTable } from "../../../runtime.ts";

export class LiangHyphenator implements Hyphenator {
  private readonly patterns: SortedMapTable<string, number[]>;
  private readonly exceptions: SortedMapTable<string, number[]>;
  private readonly leftMin: number;
  private readonly rightMin: number;

  constructor(patterns: SortedMapTable<string, number[]>, exceptions?: SortedMapTable<string, number[]> | null, leftMin: number | null = null, rightMin: number | null = null) {
    this.patterns = patterns;
    this.exceptions = exceptions;
    this.leftMin = leftMin ?? 2;
    this.rightMin = rightMin ?? 3;
  }

  public hyphenate(word: string): readonly number[] {
    if (word.length < this.leftMin + this.rightMin) {
      return [];
    }
    const lower = word.toLowerCase();
    const explicit = this.exceptions.get(lower);
    if (explicit !== null) {
      const out: number[] = [];
      for (let qIdx = 0, count = explicit.length; qIdx < count; qIdx += 1) {
        const v = explicit[qIdx]!;
        if (v >= this.leftMin && v <= word.length - this.rightMin) {
          out.push(v);
        }
      }
      return out;
    }
    const work = `.${lower}.`;
    const _g2: number[] = [];
    for (let _ = 0, count2 = work.length + 1; _ < count2; _ += 1) {
      _g2.push(0);
    }
    const levels = _g2;
    let i = 0;
    while (i < work.length) {
      let key = "";
      let j = i + 1;
      while (j <= work.length) {
        key += work.charAt(j - 1);
        const pattern = this.patterns.get(key);
        if (pattern !== null) {
          let k = 0;
          while (k < pattern.length) {
            if (pattern[k]! > levels[i + k]!) {
              levels[i + k] = pattern[k]!;
            }
            k++;
          }
        }
        j++;
      }
      i++;
    }
    const result: number[] = [];
    let m = 0;
    while (m < word.length - 1) {
      const offset = m + 1;
      if (offset >= this.leftMin && offset <= word.length - this.rightMin && levels[m + 2]! % 2 === 1) {
        result.push(offset);
      }
      m++;
    }
    return result;
  }
}
