// Generated by the reflaxe TypeScript target. Do not edit.

import { ParsedTexHyphenation } from "./ParsedTexHyphenation.ts";
import { SortedTable } from "../../../runtime.ts";

export class ParseTexHyphenationPatterns {
  private static block(text: string, name: string): string {
    const start = text.indexOf(name);
    if (start < 0) {
      return "";
    }
    const open = text.indexOf("{", start);
    if (open < 0) {
      return "";
    }
    const close = text.indexOf("}", open + 1);
    if (close < 0) {
      return "";
    }
    return text.substring(open + 1, close);
  }

  private static tokens(text: string): string[] {
    const out: string[] = [];
    let token = "";
    let i = 0;
    while (i < text.length) {
      const c = text.charAt(i);
      const sep = c === " " || c === "\t" || c === "\n" || c === "\r";
      if (sep) {
        if (token.length > 0) {
          out.push(token);
          token = "";
        }
      } else {
        token += c;
      }
      i++;
    }
    if (token.length > 0) {
      out.push(token);
    }
    return out;
  }

  public static parse(tex: string): ParsedTexHyphenation {
    let noComments = "";
    const sourceLines = tex.split("\n");
    let li = 0;
    while (li < sourceLines.length) {
      const line = sourceLines[li]!;
      const p = line.indexOf("%");
      noComments += (p < 0 ? line : line.substring(0, p)) + "\n";
      li++;
    }
    const pb = SortedTable.mapBuilder<string, number[]>(SortedTable.compareStrings);
    const eb = SortedTable.mapBuilder<string, number[]>(SortedTable.compareStrings);
    const patternTokens = ParseTexHyphenationPatterns.tokens(ParseTexHyphenationPatterns.block(noComments, "\\patterns"));
    let ti = 0;
    while (ti < patternTokens.length) {
      const token = patternTokens[ti]!;
      let key_b = "";
      const levels = [0];
      let i = 0;
      while (i < token.length) {
        const code = (Number.isNaN(token.charCodeAt(i)) ? null : token.charCodeAt(i))!;
        if (code >= 48 && code <= 57) {
          levels[levels.length - 1] = code - 48;
        } else {
          {
            const x = token.charAt(i);
            key_b += x;
          }
          levels.push(0);
        }
        i++;
      }
      pb.put(key_b, levels);
      ti++;
    }
    const hyphenationTokens = ParseTexHyphenationPatterns.tokens(ParseTexHyphenationPatterns.block(noComments, "\\hyphenation"));
    let ei = 0;
    while (ei < hyphenationTokens.length) {
      const token2 = hyphenationTokens[ei]!;
      let key_b2 = "";
      const offsets: number[] = [];
      let pos = 0;
      let i2 = 0;
      while (i2 < token2.length) {
        if (token2.charAt(i2) === "-") {
          offsets.push(pos);
        } else {
          {
            const x2 = token2.charAt(i2);
            key_b2 += x2;
          }
          pos++;
        }
        i2++;
      }
      eb.put(key_b2.toLowerCase(), offsets);
      ei++;
    }
    return new ParsedTexHyphenation(pb.build(), eb.build());
  }
}
