// Generated by the reflaxe TypeScript target. Do not edit.

import { TextRangeError } from "./../core/TextRangeError.ts";
import { TiqianIllegalArgumentException } from "./../core/TiqianIllegalArgumentException.ts";
import { UnicodePunctuationLineBreakData } from "./UnicodePunctuationLineBreakData.ts";

export class UnicodePunctuationLineBreak {
  public static classOf(codePoint: number): UnicodePunctuationLineBreakClass {
    if (codePoint < 0 || codePoint > 1114111) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    if (codePoint >= 55296 && codePoint <= 57343) {
      throw new TiqianIllegalArgumentException(({ kind: "Message", text: `Surrogate is not a Unicode scalar value: ${codePoint}` } as TextRangeError));
    }
    const kind = UnicodePunctuationLineBreakData.lookup(codePoint);
    if (kind === 0) {
      return UnicodePunctuationLineBreakClass.BreakAfter;
    }
    if (kind === 1) {
      return UnicodePunctuationLineBreakClass.BreakBoth;
    }
    if (kind === 2) {
      return UnicodePunctuationLineBreakClass.ClosePunctuation;
    }
    if (kind === 3) {
      return UnicodePunctuationLineBreakClass.CloseParenthesis;
    }
    if (kind === 4) {
      return UnicodePunctuationLineBreakClass.Exclamation;
    }
    if (kind === 5) {
      return UnicodePunctuationLineBreakClass.HyphenHH;
    }
    if (kind === 6) {
      return UnicodePunctuationLineBreakClass.Hyphen;
    }
    if (kind === 7) {
      return UnicodePunctuationLineBreakClass.Inseparable;
    }
    if (kind === 8) {
      return UnicodePunctuationLineBreakClass.InfixNumericSeparator;
    }
    if (kind === 9) {
      return UnicodePunctuationLineBreakClass.Nonstarter;
    }
    if (kind === 10) {
      return UnicodePunctuationLineBreakClass.OpenPunctuation;
    }
    if (kind === 11) {
      return UnicodePunctuationLineBreakClass.Quotation;
    }
    if (kind === 12) {
      return UnicodePunctuationLineBreakClass.SymbolsAllowingBreakAfter;
    }
    return UnicodePunctuationLineBreakClass.Other;
  }
}

export interface BreakAfter {
  readonly kind: "BreakAfter"
}

export interface BreakBoth {
  readonly kind: "BreakBoth"
}

export interface ClosePunctuation {
  readonly kind: "ClosePunctuation"
}

export interface CloseParenthesis {
  readonly kind: "CloseParenthesis"
}

export interface Exclamation {
  readonly kind: "Exclamation"
}

export interface HyphenHH {
  readonly kind: "HyphenHH"
}

export interface Hyphen {
  readonly kind: "Hyphen"
}

export interface Inseparable {
  readonly kind: "Inseparable"
}

export interface InfixNumericSeparator {
  readonly kind: "InfixNumericSeparator"
}

export interface Nonstarter {
  readonly kind: "Nonstarter"
}

export interface OpenPunctuation {
  readonly kind: "OpenPunctuation"
}

export interface Quotation {
  readonly kind: "Quotation"
}

export interface SymbolsAllowingBreakAfter {
  readonly kind: "SymbolsAllowingBreakAfter"
}

export interface Other {
  readonly kind: "Other"
}

export type UnicodePunctuationLineBreakClass =
  | BreakAfter
  | BreakBoth
  | ClosePunctuation
  | CloseParenthesis
  | Exclamation
  | HyphenHH
  | Hyphen
  | Inseparable
  | InfixNumericSeparator
  | Nonstarter
  | OpenPunctuation
  | Quotation
  | SymbolsAllowingBreakAfter
  | Other;

export const UnicodePunctuationLineBreakClass = Object.freeze({
  BreakAfter: Object.freeze({ kind: "BreakAfter" } as BreakAfter),
  BreakBoth: Object.freeze({ kind: "BreakBoth" } as BreakBoth),
  ClosePunctuation: Object.freeze({ kind: "ClosePunctuation" } as ClosePunctuation),
  CloseParenthesis: Object.freeze({ kind: "CloseParenthesis" } as CloseParenthesis),
  Exclamation: Object.freeze({ kind: "Exclamation" } as Exclamation),
  HyphenHH: Object.freeze({ kind: "HyphenHH" } as HyphenHH),
  Hyphen: Object.freeze({ kind: "Hyphen" } as Hyphen),
  Inseparable: Object.freeze({ kind: "Inseparable" } as Inseparable),
  InfixNumericSeparator: Object.freeze({ kind: "InfixNumericSeparator" } as InfixNumericSeparator),
  Nonstarter: Object.freeze({ kind: "Nonstarter" } as Nonstarter),
  OpenPunctuation: Object.freeze({ kind: "OpenPunctuation" } as OpenPunctuation),
  Quotation: Object.freeze({ kind: "Quotation" } as Quotation),
  SymbolsAllowingBreakAfter: Object.freeze({ kind: "SymbolsAllowingBreakAfter" } as SymbolsAllowingBreakAfter),
  Other: Object.freeze({ kind: "Other" } as Other)
});

export function compareUnicodePunctuationLineBreakClass(a: UnicodePunctuationLineBreakClass, b: UnicodePunctuationLineBreakClass): number {
  if (a === b) return 0;
  if (a.kind === "BreakAfter") return 0 - (b.kind === "BreakAfter" ? 0 : 0);
  if (a.kind === "BreakBoth") return 1 - (b.kind === "BreakBoth" ? 1 : 0);
  if (a.kind === "ClosePunctuation") return 2 - (b.kind === "ClosePunctuation" ? 2 : 0);
  if (a.kind === "CloseParenthesis") return 3 - (b.kind === "CloseParenthesis" ? 3 : 0);
  if (a.kind === "Exclamation") return 4 - (b.kind === "Exclamation" ? 4 : 0);
  if (a.kind === "HyphenHH") return 5 - (b.kind === "HyphenHH" ? 5 : 0);
  if (a.kind === "Hyphen") return 6 - (b.kind === "Hyphen" ? 6 : 0);
  if (a.kind === "Inseparable") return 7 - (b.kind === "Inseparable" ? 7 : 0);
  if (a.kind === "InfixNumericSeparator") return 8 - (b.kind === "InfixNumericSeparator" ? 8 : 0);
  if (a.kind === "Nonstarter") return 9 - (b.kind === "Nonstarter" ? 9 : 0);
  if (a.kind === "OpenPunctuation") return 10 - (b.kind === "OpenPunctuation" ? 10 : 0);
  if (a.kind === "Quotation") return 11 - (b.kind === "Quotation" ? 11 : 0);
  if (a.kind === "SymbolsAllowingBreakAfter") return 12 - (b.kind === "SymbolsAllowingBreakAfter" ? 12 : 0);
  if (a.kind === "Other") return 13 - (b.kind === "Other" ? 13 : 0);
  return 0;
}
